/**
 * Generated by OCaml5.Fuzz (spike P5, round four). Program `p400217`, seed 400217, 8 operations.
 *
 * Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`.
 */
import { Context, Effect } from "effect"
import type { Fiber, Option, Scope } from "effect"

/** Service `Fibers`: one method per operation of the Lean family, plus the three rows
 * `fiber-fixture.ts` does not declare and rc.112 does. */
export class Fibers extends Context.Service<Fibers, {
  readonly fork: (body: number) => Effect.Effect<Fiber.Fiber<number, number>>
  readonly forkDetach: (body: number) => Effect.Effect<Fiber.Fiber<number, number>>
  readonly join: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<number, number>
  readonly awaitValue: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<Option.Option<number>>
  readonly awaitError: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<Option.Option<number>>
  readonly interrupt: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<void>
  readonly started: Effect.Effect<ReadonlyArray<number>>
  readonly cleanups: Effect.Effect<ReadonlyArray<number>>
  readonly yieldNow: (priority: number) => Effect.Effect<void>
  readonly interruptAll: (fibers: ReadonlyArray<Fiber.Fiber<number, number>>) => Effect.Effect<void>
  readonly awaitAll: (fibers: ReadonlyArray<Fiber.Fiber<number, number>>) => Effect.Effect<void>
}>()("Fibers") {}

export const FibersRows = { "fork": { params: 1, answer: "Fiber.Fiber<number, number>" }, "forkDetach": { params: 1, answer: "Fiber.Fiber<number, number>" }, "join": { params: 1, answer: "number" }, "awaitValue": { params: 1, answer: "Option.Option<number>" }, "awaitError": { params: 1, answer: "Option.Option<number>" }, "interrupt": { params: 1, answer: "void" }, "started": { params: 0, answer: "ReadonlyArray<number>" }, "cleanups": { params: 0, answer: "ReadonlyArray<number>" }, "yieldNow": { params: 1, answer: "void" }, "interruptAll": { params: 1, answer: "void" }, "awaitAll": { params: 1, answer: "void" } }

/** Service `Scopes` (`harness/trace/scope-fixture.ts`). */
export class Scopes extends Context.Service<Scopes, {
  readonly make: Effect.Effect<Scope.Closeable>
  readonly addFinalizer: (scope: Scope.Closeable, key: number) => Effect.Effect<boolean>
  readonly remove: (scope: Scope.Closeable, key: number) => Effect.Effect<void>
  readonly close: (scope: Scope.Closeable) => Effect.Effect<ReadonlyArray<number>>
}>()("Scopes") {}

export const ScopesRows = { "make": { params: 0, answer: "Scope.Closeable" }, "addFinalizer": { params: 2, answer: "boolean" }, "remove": { params: 2, answer: "void" }, "close": { params: 1, answer: "ReadonlyArray<number>" } }

/** Lowered from `p400217` by OCaml5.Fuzz. */
export const corpus_p400217 = (n: number) =>
  Effect.gen(function* () {
    const fibers = yield* Fibers
    const scopes = yield* Scopes
    void n
    const v0 = yield* fibers.fork(1)
    const v1 = yield* fibers.started
    const v2 = yield* fibers.join(v0)
    const v3 = yield* fibers.fork(0)
    const v4 = yield* fibers.started
    const v5 = yield* scopes.make
    const v6 = yield* fibers.forkDetach(3)
    const v7 = yield* fibers.join(v3)
    return v7
  })
