(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400068`, seed 400068, 9 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400068 () =
  let v0 = Fibers_fixture.fork 4 in
  let _v1 = Fibers_fixture.await_value v0 in
  let _v2 = Fibers_fixture.join v0 in
  ignore (Fibers_fixture.interrupt v0);
  let _v3 = Fibers_fixture.started () in
  let _v4 = Store_fixtures.ref_make 5 in
  let _v5 = Fibers_fixture.await_error v0 in
  let _v6 = Fibers_fixture.started () in
  let v7 = Fibers_fixture.cleanups () in
  v7

let programs : (string * (unit -> value)) list = [ ("p400068", corpus_p400068) ]
