(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400103`, seed 400103, 38 operations.
   Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400103 () =
  let v0 = Fibers_fixture.fork_detach 1 in
  let _v1 = Fibers_fixture.started () in
  let _v2 = Fibers_fixture.started () in
  let _v3 = Fibers_fixture.cleanups () in
  let v4 = Store_fixtures.ref_make 9 in
  let _v5 = Fibers_fixture.started () in
  let _v6 = Store_fixtures.ref_get_and_set v4 1 in
  ignore (Fibers_fixture.interrupt v0);
  let v7 = Fibers_fixture.fork 0 in
  let _v8 = Fibers_fixture.cleanups () in
  ignore (Store_fixtures.ref_set v4 6);
  let _v9 = Fibers_fixture.started () in
  let _v10 = Store_fixtures.ref_get_and_set v4 7 in
  let _v11 = Fibers_fixture.join v7 in
  let v12 = Fibers_fixture.fork 2 in
  let v13 = Fibers_fixture.fork 4 in
  ignore (Store_fixtures.ref_update v4 7);
  let v14 = Store_fixtures.layer_build 0 in
  let _v15 = Fibers_fixture.cleanups () in
  let v16 = Fibers_fixture.fork 1 in
  ignore (Store_fixtures.ref_update v4 4);
  let v17 = Store_fixtures.layer_build 3 in
  ignore (Fibers_fixture.interrupt v13);
  let _v18 = Fibers_fixture.await_value v0 in
  ignore (Fibers_fixture.interrupt v13);
  let _v19 = Fibers_fixture.started () in
  let v20 = Fibers_fixture.fork 4 in
  let _v21 = Fibers_fixture.cleanups () in
  let _v22 = Store_fixtures.ref_make 4 in
  let _v23 = Fibers_fixture.cleanups () in
  let _v24 = Fibers_fixture.started () in
  let _v25 = Fibers_fixture.join v12 in
  let _v26 = Store_fixtures.layer_scope_of v14 in
  ignore (Extra_fixture.yield ());
  let _v27 = Store_fixtures.layer_scope_of v17 in
  let _v28 = Fibers_fixture.join v13 in
  let _v29 = Fibers_fixture.await_value v20 in
  let v30 = Fibers_fixture.join v16 in
  v30

let programs : (string * (unit -> value)) list = [ ("p400103", corpus_p400103) ]
