-- GENERATED by tools/Effect4Gen/Authoring.lean; do not edit
-- GENERATED by tools/Effect4Gen/Authoring.lean from tools/Effect4Gen/binders.json and the Lean environment. Do not edit.
-- Regenerate (tools/Effect4Gen/Driver.lean runs this for every group; --verify refuses a diff):
--   lake env lean -M 4096 --run tools/Effect4Gen/Authoring.lean --group Binders --imports Effect4.Program.Refs --out src/Effect4/Program/Binders.lean --append tools/Effect4Gen/guards/binders.lean -- Effect4.Program.Eff
-- Acceptance guards appended verbatim from: tools/Effect4Gen/guards/binders.lean
import Effect4.Program.Refs

set_option autoImplicit false

namespace Effect4.Program

namespace Node

variable {Op : Type}

/-- Values bound at child `i` beyond the ambient scope: the one binder table
(`tools/Effect4Gen/binders.json`), which `effTy` follows with the types. -/
def binders : Node Op → Nat → Nat
  | .eff (.bind _ _), 1 => 1
  | .eff (.catchCause _ _), 1 => 1
  | .eff (.catchIf _ _ _), 1 => 1
  | .eff (.select _ (.option) _ _), 1 => 1
  | .eff (.select _ (.tag _) _ _), 0 => 1
  | .eff (.select _ (.tag _) _ _), 1 => 1
  | .eff (.matchCause _ _ _), 1 => 1
  | .eff (.matchCause _ _ _), 2 => 1
  | .eff (.onExit _ _), 1 => 1
  | .eff (.whileLoop _ _ _ _), 0 => 1
  | .eff (.iterate _ _ _ _ _ _), 0 => 1
  | .eff (.acquireRelease _ _), 1 => 2
  | .stmts (.cons (.bindYield _) _), 1 => 1
  | _, _ => 0

/-- Children elaborated and typed in the empty scope: a layer's body. -/
def closedChild : Node Op → Nat → Bool
  | .layer (.effect _ _), 0 => true
  | .layer (.effectDiscard _), 0 => true
  | _, _ => false

/-- The level of child `i` of a node at level `n`. -/
def childLevel (n : Nat) (node : Node Op) (i : Nat) : Nat :=
  if node.closedChild i then 0 else n + node.binders i

end Node

/-! ## The authoring profile (DI-84): heads with no authoring lift -/

/-- The reader's canonical forms for generator code and the retiring invocation forms. -/
def readerOnlyHeads : List String := ["gen", "yieldError"]

/-- The fiber actions the printer refuses as internal. -/
def machineOnlyHeads : List String := ["interruptScoped", "awaitAllFailFast", "snapshotChildren", "awaitNewChildren", "setContext"]


/-! ## Receipts -/

#print axioms Effect4.Program.Node.binders
#print axioms Effect4.Program.Node.closedChild
#print axioms Effect4.Program.Node.childLevel

end Effect4.Program

/-! ## Acceptance guards for the generated binder table

Appended verbatim by `--append tools/Effect4Gen/guards/binders.lean` into
`src/Effect4/Program/Binders.lean`. The rows are `tools/Effect4Gen/binders.json`'s; these
pin the projection at one constructor of each shape so a regenerated table that dropped a
row fails here before any consumer notices. -/

namespace Effect4.Program.BindersGuards

open Effect4.Program

private def e0 : Eff Unit := .succeed (.lit .unit)

#guard Node.binders (.eff (.bind e0 e0)) 0 = 0
#guard Node.binders (.eff (.bind e0 e0)) 1 = 1
#guard Node.binders (.eff (.matchCause e0 e0 e0)) 2 = 1
#guard Node.binders (.eff (.acquireRelease e0 e0)) 1 = 2
#guard Node.binders (.eff (.whileLoop (.lit .unit) (.lit .unit) (.lit .unit) e0)) 0 = 1
#guard Node.binders (.eff (.iterate .nat (.lit .unit) (.lit .unit) (.lit .unit) (.lit .unit) e0)) 0 = 1
#guard Node.binders (.eff (.suspend e0)) 0 = 0
-- `select` binds by its decision: nothing, the some-value, the payload and the rest
#guard Node.binders (.eff (.select (.lit .unit) .bool e0 e0)) 1 = 0
#guard Node.binders (.eff (.select (.lit .unit) .option e0 e0)) 0 = 0
#guard Node.binders (.eff (.select (.lit .unit) .option e0 e0)) 1 = 1
#guard Node.binders (.eff (.select (.lit .unit) (.tag "A") e0 e0)) 0 = 1
#guard Node.binders (.eff (.select (.lit .unit) (.tag "A") e0 e0)) 1 = 1
#guard Node.binders (.stmts (.cons (.bindYield e0) .nil)) 1 = 1
#guard Node.binders (.stmts (.cons (.yieldDiscard e0) .nil)) 1 = 0
#guard Node.closedChild (.layer (.effectDiscard e0)) 0 = true
#guard Node.closedChild (.eff (.bind e0 e0)) 1 = false
#guard Node.childLevel 3 (.eff (.bind e0 e0)) 1 = 4
#guard Node.childLevel 3 (.layer (.effectDiscard e0)) 0 = 0
#guard Node.childLevel 3 (.eff (.suspend e0)) 0 = 3
#guard readerOnlyHeads.length = 2
#guard machineOnlyHeads.length = 5

end Effect4.Program.BindersGuards

