-- GENERATED by tools/Effect4Gen/Authoring.lean; do not edit
-- GENERATED by tools/Effect4Gen/Authoring.lean from tools/Effect4Gen/binders.json and the Lean environment. Do not edit.
-- Regenerate (tools/Effect4Gen/Driver.lean runs this for every group; --verify refuses a diff):
--   lake env lean -M 4096 --run tools/Effect4Gen/Authoring.lean --group NodeLenses --imports Effect4.Program.Node --out src/Effect4/Program/NodeLenses.lean --append tools/Effect4Gen/guards/nodelenses.lean -- Effect4.Program.Eff
-- Acceptance guards appended verbatim from: tools/Effect4Gen/guards/nodelenses.lean
import Effect4.Program.Node

set_option autoImplicit false

namespace Effect4.Program

namespace Node

variable {Op : Type}

/-- The child at an index: the node-typed arguments of a constructor, in declaration order.
Terms are not nodes: only programs, statements, actions, layers and the two spines are
addressed. -/
def child : Node Op → Nat → Option (Node Op)
  | eff (.suspend a0), 0 => some (eff a0)
  | eff (.bind a0 _), 0 => some (eff a0)
  | eff (.bind _ a1), 1 => some (eff a1)
  | eff (.gen a0), 0 => some (stmts a0)
  | eff (.catchCause a0 _), 0 => some (eff a0)
  | eff (.catchCause _ a1), 1 => some (eff a1)
  | eff (.matchCause a0 _ _), 0 => some (eff a0)
  | eff (.matchCause _ a1 _), 1 => some (eff a1)
  | eff (.matchCause _ _ a2), 2 => some (eff a2)
  | eff (.onExit a0 _), 0 => some (eff a0)
  | eff (.onExit _ a1), 1 => some (eff a1)
  | eff (.exit a0), 0 => some (eff a0)
  | eff (.uninterruptible a0), 0 => some (eff a0)
  | eff (.interruptible a0), 0 => some (eff a0)
  | eff (.branch _ a1 _), 0 => some (eff a1)
  | eff (.branch _ _ a2), 1 => some (eff a2)
  | eff (.whileLoop _ _ _ a3), 0 => some (eff a3)
  | eff (.withFiber a0), 0 => some (action a0)
  | eff (.scoped a0), 0 => some (eff a0)
  | eff (.acquireRelease a0 _), 0 => some (eff a0)
  | eff (.acquireRelease _ a1), 1 => some (eff a1)
  | eff (.provideLayer a0 _ _), 0 => some (layer a0)
  | eff (.provideLayer _ _ a2), 1 => some (eff a2)
  | eff (.provideService _ _ a2), 0 => some (eff a2)
  | eff (.catchIf _ a1 _), 0 => some (eff a1)
  | eff (.catchIf _ _ a2), 1 => some (eff a2)
  | action (.fork a0 _), 0 => some (eff a0)
  | action (.forkIn a0 _ _), 0 => some (eff a0)
  | action (.forkScoped a0 _), 0 => some (eff a0)
  | action (.raceAll a0), 0 => some (effs a0)
  | layer (.effect _ a1), 0 => some (eff a1)
  | layer (.effectDiscard a0), 0 => some (eff a0)
  | layer (.provide a0 _), 0 => some (layer a0)
  | layer (.provide _ a1), 1 => some (layer a1)
  | layer (.provideMerge a0 _), 0 => some (layer a0)
  | layer (.provideMerge _ a1), 1 => some (layer a1)
  | layer (.merge a0 _), 0 => some (layer a0)
  | layer (.merge _ a1), 1 => some (layer a1)
  | layer (.fresh a0), 0 => some (layer a0)
  | layer (.orDie a0), 0 => some (layer a0)
  | layer (.mergeAll a0), 0 => some (layers a0)
  | stmts (.cons a0 _), 0 => some (stmt a0)
  | stmts (.cons _ a1), 1 => some (stmts a1)
  | stmt (.bindYield a0), 0 => some (eff a0)
  | stmt (.yieldDiscard a0), 0 => some (eff a0)
  | stmt (.ifElse _ a1 _), 0 => some (stmts a1)
  | stmt (.ifElse _ _ a2), 1 => some (stmts a2)
  | stmt (.whileTrue a0), 0 => some (stmts a0)
  | effs (.cons a0 _), 0 => some (eff a0)
  | effs (.cons _ a1), 1 => some (effs a1)
  | layers (.cons a0 _), 0 => some (layer a0)
  | layers (.cons _ a1), 1 => some (layers a1)
  | _, _ => none

/-- The node with the child at an index replaced by one of the same sort; `none` where
`child` is `none` or the sorts differ. -/
def setChild : Node Op → Nat → Node Op → Option (Node Op)
  | eff (.suspend _), 0, eff x => some (eff (.suspend x))
  | eff (.bind _ a1), 0, eff x => some (eff (.bind x a1))
  | eff (.bind a0 _), 1, eff x => some (eff (.bind a0 x))
  | eff (.gen _), 0, stmts x => some (eff (.gen x))
  | eff (.catchCause _ a1), 0, eff x => some (eff (.catchCause x a1))
  | eff (.catchCause a0 _), 1, eff x => some (eff (.catchCause a0 x))
  | eff (.matchCause _ a1 a2), 0, eff x => some (eff (.matchCause x a1 a2))
  | eff (.matchCause a0 _ a2), 1, eff x => some (eff (.matchCause a0 x a2))
  | eff (.matchCause a0 a1 _), 2, eff x => some (eff (.matchCause a0 a1 x))
  | eff (.onExit _ a1), 0, eff x => some (eff (.onExit x a1))
  | eff (.onExit a0 _), 1, eff x => some (eff (.onExit a0 x))
  | eff (.exit _), 0, eff x => some (eff (.exit x))
  | eff (.uninterruptible _), 0, eff x => some (eff (.uninterruptible x))
  | eff (.interruptible _), 0, eff x => some (eff (.interruptible x))
  | eff (.branch a0 _ a2), 0, eff x => some (eff (.branch a0 x a2))
  | eff (.branch a0 a1 _), 1, eff x => some (eff (.branch a0 a1 x))
  | eff (.whileLoop a0 a1 a2 _), 0, eff x => some (eff (.whileLoop a0 a1 a2 x))
  | eff (.withFiber _), 0, action x => some (eff (.withFiber x))
  | eff (.scoped _), 0, eff x => some (eff (.scoped x))
  | eff (.acquireRelease _ a1), 0, eff x => some (eff (.acquireRelease x a1))
  | eff (.acquireRelease a0 _), 1, eff x => some (eff (.acquireRelease a0 x))
  | eff (.provideLayer _ a1 a2), 0, layer x => some (eff (.provideLayer x a1 a2))
  | eff (.provideLayer a0 a1 _), 1, eff x => some (eff (.provideLayer a0 a1 x))
  | eff (.provideService a0 a1 _), 0, eff x => some (eff (.provideService a0 a1 x))
  | eff (.catchIf a0 _ a2), 0, eff x => some (eff (.catchIf a0 x a2))
  | eff (.catchIf a0 a1 _), 1, eff x => some (eff (.catchIf a0 a1 x))
  | action (.fork _ a1), 0, eff x => some (action (.fork x a1))
  | action (.forkIn _ a1 a2), 0, eff x => some (action (.forkIn x a1 a2))
  | action (.forkScoped _ a1), 0, eff x => some (action (.forkScoped x a1))
  | action (.raceAll _), 0, effs x => some (action (.raceAll x))
  | layer (.effect a0 _), 0, eff x => some (layer (.effect a0 x))
  | layer (.effectDiscard _), 0, eff x => some (layer (.effectDiscard x))
  | layer (.provide _ a1), 0, layer x => some (layer (.provide x a1))
  | layer (.provide a0 _), 1, layer x => some (layer (.provide a0 x))
  | layer (.provideMerge _ a1), 0, layer x => some (layer (.provideMerge x a1))
  | layer (.provideMerge a0 _), 1, layer x => some (layer (.provideMerge a0 x))
  | layer (.merge _ a1), 0, layer x => some (layer (.merge x a1))
  | layer (.merge a0 _), 1, layer x => some (layer (.merge a0 x))
  | layer (.fresh _), 0, layer x => some (layer (.fresh x))
  | layer (.orDie _), 0, layer x => some (layer (.orDie x))
  | layer (.mergeAll _), 0, layers x => some (layer (.mergeAll x))
  | stmts (.cons _ a1), 0, stmt x => some (stmts (.cons x a1))
  | stmts (.cons a0 _), 1, stmts x => some (stmts (.cons a0 x))
  | stmt (.bindYield _), 0, eff x => some (stmt (.bindYield x))
  | stmt (.yieldDiscard _), 0, eff x => some (stmt (.yieldDiscard x))
  | stmt (.ifElse a0 _ a2), 0, stmts x => some (stmt (.ifElse a0 x a2))
  | stmt (.ifElse a0 a1 _), 1, stmts x => some (stmt (.ifElse a0 a1 x))
  | stmt (.whileTrue _), 0, stmts x => some (stmt (.whileTrue x))
  | effs (.cons _ a1), 0, eff x => some (effs (.cons x a1))
  | effs (.cons a0 _), 1, effs x => some (effs (.cons a0 x))
  | layers (.cons _ a1), 0, layer x => some (layers (.cons x a1))
  | layers (.cons a0 _), 1, layers x => some (layers (.cons a0 x))
  | _, _, _ => none

end Node

/-! ## Receipts -/

#print axioms Effect4.Program.Node.child
#print axioms Effect4.Program.Node.setChild

end Effect4.Program

/-! ## Acceptance guards for the generated child lenses

Appended verbatim by `--append tools/Effect4Gen/guards/nodelenses.lean` into
`src/Effect4/Program/NodeLenses.lean`. One constructor of each shape: a program child, a
layer child, a spine, a statement, and the refusals (no such child, the wrong sort). -/

namespace Effect4.Program.NodeLensesGuards

open Effect4.Program

private def e0 : Eff Unit := .succeed (.lit .unit)
private def e1 : Eff Unit := .succeed (.lit (.nat 1))

#guard Node.child (.eff (.bind e0 e1)) 0 = some (.eff e0)
#guard Node.child (.eff (.bind e0 e1)) 1 = some (.eff e1)
#guard Node.child (.eff (.bind e0 e1)) 2 = none
#guard Node.child (.eff e0) 0 = none
#guard Node.child (.eff (.provideLayer (.ref [3]) false e0)) 0 = some (.layer (.ref [3]))
#guard Node.child (.eff (.withFiber (.raceAll (.cons e0 .nil)))) 0 = some (.action (.raceAll (.cons e0 .nil)))
#guard Node.child (.effs (.cons e0 (.cons e1 .nil))) 1 = some (.effs (.cons e1 .nil))
#guard Node.child (.stmts (.cons (.bindYield e0) .nil)) 0 = some (.stmt (.bindYield e0))
#guard Node.setChild (.eff (.bind e0 e1)) 0 (.eff e1) = some (.eff (.bind e1 e1))
#guard Node.setChild (.eff (.bind e0 e1)) 0 (.layer (.ref [])) = none
#guard Node.setChild ((.layer (.merge (.ref [0]) (.ref [1]))) : Node Unit) 1 (.layer (.ref [2]))
  = some (.layer (.merge (.ref [0]) (.ref [2])))
#guard Node.setChild (.eff e0) 0 (.eff e1) = none

end Effect4.Program.NodeLensesGuards

