(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400079`, seed 400079, 14 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400079 () =
  let v0 = Fibers_fixture.fork 1 in
  let v1 = Store_fixtures.layer_build 0 in
  let _v2 = Store_fixtures.layer_scope_of v1 in
  let _v3 = Store_fixtures.ref_make 1 in
  ignore (Extra_fixture.yield ());
  let _v4 = Extra_fixture.await_all [ v0 ] in
  let _v5 = Extra_fixture.await_all [ v0 ] in
  let _v6 = Fibers_fixture.await_value v0 in
  let v7 = Fibers_fixture.fork 1 in
  let _v8 = Fibers_fixture.fork 0 in
  let _v9 = Store_fixtures.layer_provide_count 0 in
  let _v10 = Store_fixtures.ref_make 4 in
  let _v11 = Store_fixtures.def_make () in
  let v12 = Fibers_fixture.join v7 in
  v12

let programs : (string * (unit -> value)) list = [ ("p400079", corpus_p400079) ]
