import TypeScript
import Effect4.Codegen.Types

/-!
Contract packet: `Test/contracts/typescript-target-expr.contract.md`

This battery freezes the retained Foldlab syntax surface and representative
fixed-layout bytes. It makes no target-typing or simulation claim.
-/

open TypeScript

namespace Test.Codegen.ExprContract

#synth Inhabited Expr

#guard Render.quoted house0 "quote\" slash\\ line\nreturn\rtab\t café" =
  "\"quote\\\" slash\\\\ line\\nreturn\\rtab\\t café\""

#guard Render.expr house0 0 (.float64Bits 0x3ff0000000000000) =
  "new DataView(Uint8Array.of(63, 240, 0, 0, 0, 0, 0, 0).buffer).getFloat64(0, false)"

#guard Render.expr house0 0 (.objectQuoted [("not an identifier", .str "value")]) =
  "{ \"not an identifier\": \"value\" }"

#guard Render.expr house0 0 (.objectQuotedML [("not an identifier", .str "value")]) =
  "{\n  \"not an identifier\": \"value\",\n}"

#guard Render.expr house0 0 (.objectFromEntries [("__proto__", .str "value")]) =
  "Object.fromEntries([[\"__proto__\", \"value\"]])"

private def longValue : String :=
  "this field deliberately exceeds any conventional formatter width"

#guard Render.expr house0 0 (.object [("value", .str longValue)]) =
  "{ value: \"this field deliberately exceeds any conventional formatter width\" }"

#guard Render.expr house0 0 (.objectML [("value", .str longValue)]) =
  "{\n  value: \"this field deliberately exceeds any conventional formatter width\",\n}"

#guard Render.expr house0 0
    (.arr [.objectML [("answer", .int 42)]]) =
  "[\n  {\n    answer: 42,\n  },\n]"

private def sampleModule : Module :=
  { header := ["Generated by Effect4.", "", "Do not edit."]
    imports :=
      [ .all "Effect" "effect/Effect"
      , .types ["Store"] "./Store.js" ]
    decls :=
      [ .const
          { doc := ["A stable literal."]
            name := "answer"
            value := .int 42
            type := some (.name ["number"] []) }
      , .prog
          { doc := ["Read the retained value."]
            name := "read"
            paramName := "store"
            paramType := .name ["Store"] []
            stmts := [.ret (.ident "store")] }
      , .raw "type Local = string" ] }

#guard Render.module house0 sampleModule =
  "/**\n * Generated by Effect4.\n *\n * Do not edit.\n */\nimport * as Effect from \"effect/Effect\"\nimport type { Store } from \"./Store.js\"\n\n/** A stable literal. */\nexport const answer: number = 42\n\n/** Read the retained value. */\nexport const read = (store: Store) =>\n  Effect.gen(function* () {\n    return store\n  })\n\ntype Local = string\n"

-- Existing canonical spellings keep their bytes. String literal types now
-- escape their contents using the target renderer instead of raw concatenation.
#guard ([.never, .unit, .nat, .int, .bool, .string,
    .union .nat .string, .list (.union .nat .string),
    .prod (.option .nat) (.exitOf .nat .string),
    .fiberOf (.list .nat) (.causeOf .string), .except .string .nat,
    .handle "Ref.Ref<number>", .handle "Context.Context<unknown>"] :
    List Effect4.Program.Ty).all fun sourceType =>
  match Effect4.Codegen.Types.ofTy sourceType with
  | some targetType => Render.type house0 targetType == sourceType.render
  | none => false
#guard (Effect4.Codegen.Types.ofTy (.lit "quote\" slash\\ line\nλ")).map
    (Render.type house0) = some "\"quote\\\" slash\\\\ line\\nλ\""

#guard Effect4.Codegen.Types.parseLegacy "Box<readonly [number, 'tag']> | never" ==
  some (.union [.name ["Box"] [.tuple [.name ["number"] [], .literal "tag"] true],
    .name ["never"] []])
#guard Effect4.Codegen.Types.parseLegacy "'\\uD83D\\uDE42'" == some (.literal "🙂")

-- Projected and parsed unions are canonical in the target: members that collapse to one
-- spelling collapse to one member, so a declared `number` compares equal to the projection
-- of `nat | int` (breaker finding B19).
#guard Effect4.Codegen.Types.ofTy (.union .nat .int) == some (.name ["number"] [])
#guard (Effect4.Codegen.Types.ofTy (.union (.union .nat .int) .string)).map (Render.type house0)
  = some "number | string"
#guard Effect4.Codegen.Types.parseLegacy "A | A" == some (.name ["A"] [])
#guard Effect4.Codegen.Types.parseLegacy "A | (B | A)" == some (.union [.name ["A"] [], .name ["B"] []])
#guard ["", "A<>", "number<string>", "void.X", "default", "true", "A.1",
    "'\\uD800'", "number); injected("].all
  (fun text => (Effect4.Codegen.Types.parseLegacy text).isNone)

end Test.Codegen.ExprContract
