import Effect4.Codegen.Schema
import Effect4.Laws.Schema.Codec

/-! Representative raw Schema and containing-data generation receipts. -/

open TypeScript

namespace Test.Codegen.SchemaGenerationContract

open Effect4

private def person : Representation :=
  Schema.struct
    [ Schema.property "name"
        ((Schema.withCheck Schema.string Schema.Check.trimmed).getD Schema.string)
    , Schema.property "active" Schema.boolean ]

private def personDocument : Document := Schema.document person

private def prototypeReferenceDocument : Document :=
  Schema.document Schema.string
    [{ key := "__proto__", representation := Schema.string }]

private def duplicatePrototypeReferenceDocument : Document :=
  Schema.document Schema.string
    [ { key := "__proto__", representation := Schema.string }
    , { key := "x", representation := Schema.string }
    , { key := "x", representation := Schema.boolean } ]

#check (@Codegen.Schema.json : Json → TypeScript.Expr)
#check (@Codegen.Schema.reifyJson? :
  TypeScript.Expr → Option Json)
#check (@Codegen.Schema.reifyJson?_json :
  ∀ value, Codegen.Schema.reifyJson?
    (Codegen.Schema.json value) = some value)
#check (@Codegen.Schema.json_injective :
  Function.Injective Codegen.Schema.json)
#check (@Codegen.Schema.representation :
  Representation → TypeScript.Expr)
#check (@Codegen.Schema.documentExpr :
  Document → TypeScript.Expr)
#check (@Codegen.Schema.moduleSyntax :
  String → Document → List (String × Json) → TypeScript.Module)
#check (@Codegen.Schema.module? :
  String → Document → List (String × Json) → Option TypeScript.Module)
#check (@Codegen.Schema.source? :
  String → Document → List (String × Json) →
    TypeScript.Style → Option String)
#check (@Codegen.Schema.generate? :
  String → Document → List (String × Json) →
    TypeScript.Style → Option String)

#guard TypeScript.Render.expr TypeScript.house0 0
    (Codegen.Schema.json (.number Float64.negZero)) =
  "new DataView(Uint8Array.of(128, 0, 0, 0, 0, 0, 0, 0).buffer).getFloat64(0, false)"

#guard Codegen.Schema.jsonSource
    (.obj [("__proto__", .str "data")]) =
  "Object.fromEntries([[\"__proto__\", \"data\"]])"

#guard Codegen.Schema.reifyJson?
    (Codegen.Schema.json
      (.obj [("x", .number Float64.negZero), ("x", .number Float64.nan)])) =
  some (.obj [("x", .number Float64.negZero), ("x", .number Float64.nan)])

#guard Codegen.Schema.reifyJson? (.ident "arbitraryCode") = none

#guard Codegen.Schema.documentSource prototypeReferenceDocument =
  "{\n" ++
  "  \"representation\": { \"_tag\": \"String\", \"checks\": [] },\n" ++
  "  \"references\": Object.fromEntries([[\"__proto__\", " ++
    "{ \"_tag\": \"String\", \"checks\": [] }]]),\n" ++
  "}"

#guard Codegen.Schema.documentReady prototypeReferenceDocument
#guard !Codegen.Schema.documentReady duplicatePrototypeReferenceDocument

#guard Codegen.Schema.generationReady "PersonSchema" personDocument
  [("ada", .obj [("name", .str "Ada"), ("active", .bool true)])]

#guard !Codegen.Schema.generationReady "not a name" personDocument []

#guard !Codegen.Schema.generationReady "PersonSchema" personDocument
  [("PersonSchema", .null)]

#guard !Codegen.Schema.generationReady "PersonSchema" personDocument
  [("duplicateKeys", .obj [("x", .str "first"), ("x", .str "second")])]

#guard !Codegen.Schema.generationReady "PersonSchema" personDocument
  [("duplicateProtoKeys",
    .obj [("__proto__", .str "data"), ("x", .str "first"), ("x", .str "second")])]

#guard Codegen.Schema.source? "PersonSchema" personDocument
    [("ada", .obj [("name", .str "Ada"), ("active", .bool true)])] = some (
  "/**\n * Generated by Effect4 Schema.\n *\n * Do not edit.\n */\n" ++
  "import * as Schema from \"effect/Schema\"\n" ++
  "import * as SchemaRepresentation from \"effect/SchemaRepresentation\"\n\n" ++
  "/** Raw Effect Schema document. */\n" ++
  "export const PersonSchemaJson: Schema.Json = {\n" ++
  "  \"representation\": {\n" ++
  "    \"_tag\": \"Objects\",\n" ++
  "    \"checks\": [],\n" ++
  "    \"propertySignatures\": [\n" ++
  "      {\n" ++
  "        \"name\": { \"type\": \"string\", \"value\": \"name\" },\n" ++
  "        \"type\": {\n" ++
  "          \"_tag\": \"String\",\n" ++
  "          \"checks\": [\n" ++
  "            {\n" ++
  "              \"_tag\": \"Filter\",\n" ++
  "              \"representation\": { \"id\": \"effect/schema/isTrimmed\", \"payload\": null },\n" ++
  "              \"aborted\": false,\n" ++
  "            },\n" ++
  "          ],\n" ++
  "        },\n" ++
  "        \"isOptional\": false,\n" ++
  "        \"isMutable\": false,\n" ++
  "      },\n" ++
  "      {\n" ++
  "        \"name\": { \"type\": \"string\", \"value\": \"active\" },\n" ++
  "        \"type\": { \"_tag\": \"Boolean\", \"checks\": [] },\n" ++
  "        \"isOptional\": false,\n" ++
  "        \"isMutable\": false,\n" ++
  "      },\n" ++
  "    ],\n" ++
  "    \"indexSignatures\": [],\n" ++
  "  },\n" ++
  "  \"references\": {},\n" ++
  "}\n\n" ++
  "/** Effect Schema document decoded from the generated raw value. */\n" ++
  "export const PersonSchema: SchemaRepresentation.Document = " ++
  "SchemaRepresentation.fromJson(PersonSchemaJson)\n\n" ++
  "/** Data associated with the generated schema. */\n" ++
  "export const ada: Schema.Json = { \"name\": \"Ada\", \"active\": true }\n")

#guard Codegen.Schema.generate? "PersonSchema" personDocument
    [("ada", .obj [("name", .str "Ada"), ("active", .bool true)])] =
  Codegen.Schema.source? "PersonSchema" personDocument
    [("ada", .obj [("name", .str "Ada"), ("active", .bool true)])]

/-! ## S-3: the checked JSON boundary, owner amendment 2026-09-11 -/

open Effect4.Program

private def codecCause : Machine.CauseV :=
  ⟨[.fail (.text "bad") .empty, .die (.user 7) .empty,
    .interrupt none .empty, .interrupt (some ⟨9⟩) .empty]⟩

private def codecCauseJson : Json := .arr
  [ .obj [("_tag", .str "Fail"), ("error", .str "bad")]
  , .obj [("_tag", .str "Die"), ("defect", .obj [("user", Arch.Json.ofNat 7)])]
  , .obj [("_tag", .str "Interrupt"), ("fiberId", .null)]
  , .obj [("_tag", .str "Interrupt"), ("fiberId", Arch.Json.ofNat 9)] ]

/-- Representative boundary cases, also exported to the pinned host schema check.
The expected JSON is independent of the codec implementation. -/
def codecCases : List (String × Ty × Store.Val × Json) :=
  [ ("unit", .unit, .unit, .null)
  , ("bool", .bool, .bool true, .bool true)
  , ("nat", .nat, .nat 42, Arch.Json.ofNat 42)
  , ("string", .string, .str "λ🙂", .str "λ🙂")
  , ("literal", .lit "User", .str "User", .str "User")
  , ("pair", .prod .nat .string, .list [.nat 3, .str "x"], .arr [Arch.Json.ofNat 3, .str "x"])
  , ("list", .list .bool, .list [.bool true, .bool false], .arr [.bool true, .bool false])
  , ("none", .option .nat, .none, .obj [("_tag", .str "None")])
  , ("some", .option .nat, .some (.nat 7),
      .obj [("_tag", .str "Some"), ("value", Arch.Json.ofNat 7)])
  , ("resultFailure", Ty.result .bool .string, .ctor 0 [.str "bad"],
      .obj [("_tag", .str "Failure"), ("failure", .str "bad")])
  , ("resultSuccess", Ty.result .bool .string, .ctor 1 [.bool true],
      .obj [("_tag", .str "Success"), ("success", .bool true)])
  , ("exitSuccess", .exitOf .bool .string, .ctor 0 [.bool true],
      .obj [("_tag", .str "Success"), ("value", .bool true)])
  , ("exitFailure", .exitOf .bool .string, Machine.Val.exitErr codecCause,
      .obj [("_tag", .str "Failure"), ("cause", codecCauseJson)])
  , ("cause", .causeOf .string, Machine.Val.exitErr codecCause, codecCauseJson)
  , ("emptyCause", .causeOf .never, Machine.Val.exitErr ⟨[]⟩, .arr [])
  , ("union", .union .string .nat, .nat 4, Arch.Json.ofNat 4)
  , ("nested", .list (.option (Ty.result .bool .string)),
      .list [.some (.ctor 1 [.bool true]), .none],
      .arr [.obj [("_tag", .str "Some"), ("value",
        .obj [("_tag", .str "Success"), ("success", .bool true)])],
        .obj [("_tag", .str "None")]]) ]

#guard codecCases.all fun (_, t, v, j) =>
  Ty.encode t v == some j && Ty.decode t j == some v && Ty.isCodecValue t v

-- The number boundary accepts exactly representable large integers, refusing rounding.
#guard Ty.encode .nat (.nat (2 ^ 53)) = some (Arch.Json.ofNat (2 ^ 53))
#guard Ty.encode .nat (.nat (2 ^ 53 + 1)) = none
#guard Ty.encode .nat (.nat (2 ^ 53 + 2)) = some (Arch.Json.ofNat (2 ^ 53 + 2))
#guard Ty.decode .nat (.number Float64.negZero) = none
#guard Ty.decode .nat (.number Float64.nan) = none
#guard Ty.decode .nat (.number Float64.posInfinity) = none
#guard Ty.decode .nat (.number ⟨0x3FF8000000000000⟩) = none -- 1.5

-- The checked decoder enforces original literals and rejects malformed object fields.
#guard Ty.decode (.lit "yes") (.str "no") = none
#guard Ty.encode (.list .nat) (.list [.str "no"]) = none
#guard Ty.decode (.prod .nat .bool) (.arr [Arch.Json.ofNat 1]) = none
#guard Ty.decode (.option .nat) (.obj [("value", Arch.Json.ofNat 7), ("_tag", .str "Some")]) =
  some (.some (.nat 7))
#guard Ty.decode (.option .nat) (.obj [("_tag", .str "Some"), ("_tag", .str "None")]) = none
#guard Ty.decode (.option .nat) (.obj [("_tag", .str "None"), ("extra", .bool true)]) = none
#guard Ty.decode (Ty.result .bool .string) (.obj [("_tag", .str "Success"), ("value", .bool true)]) = none
#guard Ty.decode (.causeOf .string) (.obj [("reasons", .arr [])]) = none
#guard Ty.decode (.causeOf .never)
  (.arr [.obj [("_tag", .str "Fail"), ("error", .str "bad")]]) = none

-- Opaque runtime handles and the distinct snapshot representation stay outside JSON.
#guard Ty.encode .int (.nat 1) = none
#guard Ty.decode .never .null = none
#guard Ty.encode (.fiberOf .nat .never) (Machine.Val.fiber ⟨0⟩) = none
#guard Ty.encode (Ty.handle "Ref.Ref<unknown>") (Machine.Val.cell ⟨0⟩) = none
#guard Ty.encode (.list .bool) (Machine.Val.fibers []) = none
#guard Ty.encode (.list .bool) (.list []) = some (.arr [])

-- Cause annotations are omitted by the host JSON schema; exact admission refuses loss.
#guard Ty.encode (.causeOf .never) (Machine.Val.exitErr
  ⟨[.die .badName ⟨[("note", ())], by decide⟩]⟩) = none

-- Both an empty list and an empty cause encode as []; the later interpretation refuses.
#guard Ty.encode (.union (.list .bool) (.causeOf .never)) (Machine.Val.exitErr ⟨[]⟩) = none
#guard Ty.encode (.union (.causeOf .never) (.list .bool)) (Machine.Val.exitErr ⟨[]⟩) = some (.arr [])

-- Conservative compatibility admits literal widening without erasing union selectors.
example : Schema.Codec.Compatible (.prod (.lit "User") (.option (.lit "ok")))
    (.prod .string (.option .string)) := rfl
example (v : Store.Val) (hv : Program.Val.hasTy v (.lit "User") = true) :
    Ty.encode .string v = Ty.encode (.lit "User") v :=
  Schema.encode_sub (by simp [Ty.sub]) hv rfl

#check Schema.encode_of_hasTy
#check Schema.decode_encode
#check Schema.hasTy_decode
#check Schema.encode_sub

end Test.Codegen.SchemaGenerationContract
