import Effect4.Codegen.Schema

/-! Representative raw Schema and containing-data generation receipts. -/

open TypeScript

namespace Test.Codegen.SchemaGenerationContract

open Effect4

private def person : Representation :=
  Schema.struct
    [ Schema.property "name"
        ((Schema.withCheck Schema.string Schema.Check.trimmed).getD Schema.string)
    , Schema.property "active" Schema.boolean ]

private def personDocument : Document := Schema.document person

private def prototypeReferenceDocument : Document :=
  Schema.document Schema.string
    [{ key := "__proto__", representation := Schema.string }]

private def duplicatePrototypeReferenceDocument : Document :=
  Schema.document Schema.string
    [ { key := "__proto__", representation := Schema.string }
    , { key := "x", representation := Schema.string }
    , { key := "x", representation := Schema.boolean } ]

#check (@Codegen.Schema.json : Json → TypeScript.Expr)
#check (@Codegen.Schema.reifyJson? :
  TypeScript.Expr → Option Json)
#check (@Codegen.Schema.reifyJson?_json :
  ∀ value, Codegen.Schema.reifyJson?
    (Codegen.Schema.json value) = some value)
#check (@Codegen.Schema.json_injective :
  Function.Injective Codegen.Schema.json)
#check (@Codegen.Schema.representation :
  Representation → TypeScript.Expr)
#check (@Codegen.Schema.documentExpr :
  Document → TypeScript.Expr)
#check (@Codegen.Schema.moduleSyntax :
  String → Document → List (String × Json) → TypeScript.Module)
#check (@Codegen.Schema.module? :
  String → Document → List (String × Json) → Option TypeScript.Module)
#check (@Codegen.Schema.source? :
  String → Document → List (String × Json) →
    TypeScript.Style → Option String)
#check (@Codegen.Schema.generate? :
  String → Document → List (String × Json) →
    TypeScript.Style → Option String)

#guard TypeScript.Render.expr TypeScript.house0 0
    (Codegen.Schema.json (.number Float64.negZero)) =
  "new DataView(Uint8Array.of(128, 0, 0, 0, 0, 0, 0, 0).buffer).getFloat64(0, false)"

#guard Codegen.Schema.jsonSource
    (.obj [("__proto__", .str "data")]) =
  "Object.fromEntries([[\"__proto__\", \"data\"]])"

#guard Codegen.Schema.reifyJson?
    (Codegen.Schema.json
      (.obj [("x", .number Float64.negZero), ("x", .number Float64.nan)])) =
  some (.obj [("x", .number Float64.negZero), ("x", .number Float64.nan)])

#guard Codegen.Schema.reifyJson? (.ident "arbitraryCode") = none

#guard Codegen.Schema.documentSource prototypeReferenceDocument =
  "{\n" ++
  "  \"representation\": { \"_tag\": \"String\", \"checks\": [] },\n" ++
  "  \"references\": Object.fromEntries([[\"__proto__\", " ++
    "{ \"_tag\": \"String\", \"checks\": [] }]]),\n" ++
  "}"

#guard Codegen.Schema.documentReady prototypeReferenceDocument
#guard !Codegen.Schema.documentReady duplicatePrototypeReferenceDocument

#guard Codegen.Schema.generationReady "PersonSchema" personDocument
  [("ada", .obj [("name", .str "Ada"), ("active", .bool true)])]

#guard !Codegen.Schema.generationReady "not a name" personDocument []

#guard !Codegen.Schema.generationReady "PersonSchema" personDocument
  [("PersonSchema", .null)]

#guard !Codegen.Schema.generationReady "PersonSchema" personDocument
  [("duplicateKeys", .obj [("x", .str "first"), ("x", .str "second")])]

#guard !Codegen.Schema.generationReady "PersonSchema" personDocument
  [("duplicateProtoKeys",
    .obj [("__proto__", .str "data"), ("x", .str "first"), ("x", .str "second")])]

#guard Codegen.Schema.source? "PersonSchema" personDocument
    [("ada", .obj [("name", .str "Ada"), ("active", .bool true)])] = some (
  "/**\n * Generated by Effect4 Schema.\n *\n * Do not edit.\n */\n" ++
  "import * as Schema from \"effect/Schema\"\n" ++
  "import * as SchemaRepresentation from \"effect/SchemaRepresentation\"\n\n" ++
  "/** Raw Effect Schema document. */\n" ++
  "export const PersonSchemaJson: Schema.Json = {\n" ++
  "  \"representation\": {\n" ++
  "    \"_tag\": \"Objects\",\n" ++
  "    \"checks\": [],\n" ++
  "    \"propertySignatures\": [\n" ++
  "      {\n" ++
  "        \"name\": { \"type\": \"string\", \"value\": \"name\" },\n" ++
  "        \"type\": {\n" ++
  "          \"_tag\": \"String\",\n" ++
  "          \"checks\": [\n" ++
  "            {\n" ++
  "              \"_tag\": \"Filter\",\n" ++
  "              \"representation\": { \"id\": \"effect/schema/isTrimmed\", \"payload\": null },\n" ++
  "              \"aborted\": false,\n" ++
  "            },\n" ++
  "          ],\n" ++
  "        },\n" ++
  "        \"isOptional\": false,\n" ++
  "        \"isMutable\": false,\n" ++
  "      },\n" ++
  "      {\n" ++
  "        \"name\": { \"type\": \"string\", \"value\": \"active\" },\n" ++
  "        \"type\": { \"_tag\": \"Boolean\", \"checks\": [] },\n" ++
  "        \"isOptional\": false,\n" ++
  "        \"isMutable\": false,\n" ++
  "      },\n" ++
  "    ],\n" ++
  "    \"indexSignatures\": [],\n" ++
  "  },\n" ++
  "  \"references\": {},\n" ++
  "}\n\n" ++
  "/** Effect Schema document decoded from the generated raw value. */\n" ++
  "export const PersonSchema: SchemaRepresentation.Document = " ++
  "SchemaRepresentation.fromJson(PersonSchemaJson)\n\n" ++
  "/** Data associated with the generated schema. */\n" ++
  "export const ada: Schema.Json = { \"name\": \"Ada\", \"active\": true }\n")

#guard Codegen.Schema.generate? "PersonSchema" personDocument
    [("ada", .obj [("name", .str "Ada"), ("active", .bool true)])] =
  Codegen.Schema.source? "PersonSchema" personDocument
    [("ada", .obj [("name", .str "Ada"), ("active", .bool true)])]

end Test.Codegen.SchemaGenerationContract
