/**
 * Generated by OCaml5.Fuzz (spike P5, round four). Program `p400078`, seed 400078, 7 operations.
 *
 * Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`.
 */
import { Context, Effect } from "effect"
import type { Fiber, Option, Ref } from "effect"

/** Service `Fibers`: one method per operation of the Lean family, plus the three rows
 * `fiber-fixture.ts` does not declare and rc.112 does. */
export class Fibers extends Context.Service<Fibers, {
  readonly fork: (body: number) => Effect.Effect<Fiber.Fiber<number, number>>
  readonly forkDetach: (body: number) => Effect.Effect<Fiber.Fiber<number, number>>
  readonly join: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<number, number>
  readonly awaitValue: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<Option.Option<number>>
  readonly awaitError: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<Option.Option<number>>
  readonly interrupt: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<void>
  readonly started: Effect.Effect<ReadonlyArray<number>>
  readonly cleanups: Effect.Effect<ReadonlyArray<number>>
  readonly yieldNow: (priority: number) => Effect.Effect<void>
  readonly interruptAll: (fibers: ReadonlyArray<Fiber.Fiber<number, number>>) => Effect.Effect<void>
  readonly awaitAll: (fibers: ReadonlyArray<Fiber.Fiber<number, number>>) => Effect.Effect<void>
}>()("Fibers") {}

export const FibersRows = { "fork": { params: 1, answer: "Fiber.Fiber<number, number>" }, "forkDetach": { params: 1, answer: "Fiber.Fiber<number, number>" }, "join": { params: 1, answer: "number" }, "awaitValue": { params: 1, answer: "Option.Option<number>" }, "awaitError": { params: 1, answer: "Option.Option<number>" }, "interrupt": { params: 1, answer: "void" }, "started": { params: 0, answer: "ReadonlyArray<number>" }, "cleanups": { params: 0, answer: "ReadonlyArray<number>" }, "yieldNow": { params: 1, answer: "void" }, "interruptAll": { params: 1, answer: "void" }, "awaitAll": { params: 1, answer: "void" } }

/** Service `Refs` (`harness/trace/ref-fixture.ts`). */
export class Refs extends Context.Service<Refs, {
  readonly make: (initial: number) => Effect.Effect<Ref.Ref<number>>
  readonly get: (ref: Ref.Ref<number>) => Effect.Effect<number>
  readonly set: (ref: Ref.Ref<number>, value: number) => Effect.Effect<void>
  readonly update: (ref: Ref.Ref<number>, amount: number) => Effect.Effect<void>
  readonly modify: (ref: Ref.Ref<number>, amount: number) => Effect.Effect<number>
  readonly getAndSet: (ref: Ref.Ref<number>, value: number) => Effect.Effect<number>
}>()("Refs") {}

export const RefsRows = { "make": { params: 1, answer: "Ref.Ref<number>" }, "get": { params: 1, answer: "number" }, "set": { params: 2, answer: "void" }, "update": { params: 2, answer: "void" }, "modify": { params: 2, answer: "number" }, "getAndSet": { params: 2, answer: "number" } }

/** Lowered from `p400078` by OCaml5.Fuzz. */
export const corpus_p400078 = (n: number) =>
  Effect.gen(function* () {
    const fibers = yield* Fibers
    const refs = yield* Refs
    void n
    const v0 = yield* fibers.fork(0)
    const v1 = yield* fibers.cleanups
    const v2 = yield* refs.make(3)
    yield* fibers.yieldNow(0)
    const v3 = yield* fibers.cleanups
    const v4 = yield* fibers.fork(0)
    const v5 = yield* fibers.cleanups
    return v5
  })
