#!/usr/bin/env bash
# Generate fixture.ts from Lean, byte-compare it with the committed fixture,
# then run the host harness (tsc.original, effect-tsgo strict, node run).
#
# ## Stamp (rule 9)
#
# What it reads: `Generate.lean` and the Lake trace of `Effect4.Meta.Derive`,
# the one module it imports, which stands for the whole olean closure beneath
# it; the three committed files the runner stages -- `fixture.ts`, `atoms.ts`,
# `tail.ts` -- and `tsconfig.json`, which names them; the effect4-tools runner;
# and the pinned installation's identity. This harness carries no `host-pin.json`
# of its own, so the profile it runs under is whatever `check.mjs` asserts
# against `EFFECT4_EFFECT_NODE_MODULES`; the key names those three package
# manifests by absolute path, and the trace harness's pin file, which is where
# the rc.112 tree digest is written down.
#
# `--update` rewrites the committed fixture from Lean, so it is never stamped.
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "$here/../.." && pwd)"
. "$repo/scripts/lib/portable.sh"
. "$repo/scripts/lib/stamp.sh"
tools="${EFFECT4_TOOLS:-$repo/../effect4-tools}"
update=0; stamped=1
for argument in "$@"; do
  case "$argument" in
    --update) update=1; stamped=0 ;;
    --force) export EFFECT4_FORCE=1 ;;
    *) echo "unknown argument $argument" >&2; exit 2 ;;
  esac
done
cd "$repo"
lake build Effect4 >/dev/null
if [ "$stamped" -eq 1 ]; then
  inputs=(
    "$here/check.sh"
    "$here/Generate.lean"
    "$here/fixture.ts" "$here/atoms.ts" "$here/tail.ts" "$here/tsconfig.json"
    "$repo/scripts/lib/portable.sh"
    "$repo/scripts/lib/stamp.sh"
    "$repo/lakefile.toml"
    "$repo/lake-manifest.json"
    "$repo/lean-toolchain"
  )
  while IFS= read -r input; do inputs+=("$input"); done < <(
    stamp_lean_traces "$here/Generate.lean"
    stamp_tools_inputs check.mjs copy.mjs
    stamp_host_inputs
  )
  key="$(stamp_key "${inputs[@]}")"
  if stamp_hit effect-v4-family "$key"; then
    stamp_report effect-v4-family "$key"
    exit 0
  fi
fi
generated="$(mktemp)"; trap 'rm -f "$generated"' EXIT
lean_run "$here/Generate.lean" > "$generated"
if [ "$update" -eq 1 ]; then cp "$generated" "$here/fixture.ts"; fi
cmp -s "$generated" "$here/fixture.ts" || { echo "FAIL fixture.ts drifted from Lean generation" >&2; diff "$generated" "$here/fixture.ts" | head -20 >&2; exit 1; }
echo "PASS fixture.ts regenerated byte-identically"
node "$tools/packages/harness/check.mjs" "$here"
if [ "$stamped" -eq 1 ]; then
  stamp_write effect-v4-family "$key" \
    "fixture.ts regenerates byte-identically; tsc, tsgo and the node run of tail.ts all pass"
fi
