#!/usr/bin/env bash
# Generate fixture.ts from Lean, byte-compare it with the committed fixture,
# then run the host harness (tsc.original, effect-tsgo strict, node run).
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "$here/../.." && pwd)"
tools="${EFFECT4_TOOLS:-$repo/../effect4-tools}"
cd "$repo"
lake build Effect4 >/dev/null
generated="$(mktemp)"; trap 'rm -f "$generated"' EXIT
lake env lean --run "$here/Generate.lean" | grep -v "^warning: manifest out of date" > "$generated"
if [ "${1:-}" = "--update" ]; then cp "$generated" "$here/fixture.ts"; fi
cmp -s "$generated" "$here/fixture.ts" || { echo "FAIL fixture.ts drifted from Lean generation" >&2; diff "$generated" "$here/fixture.ts" | head -20 >&2; exit 1; }
echo "PASS fixture.ts regenerated byte-identically"
node "$tools/packages/harness/check.mjs" "$here"
