(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400212`, seed 400212, 9 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400212 () =
  let v0 = Fibers_fixture.fork 0 in
  let _v1 = Store_fixtures.layer_build 0 in
  let _v2 = Extra_fixture.await_all [ v0 ] in
  let _v3 = Fibers_fixture.await_error v0 in
  let v4 = Store_fixtures.ref_make 8 in
  let _v5 = Store_fixtures.ref_make 1 in
  ignore (Store_fixtures.ref_set v4 5);
  let _v6 = Fibers_fixture.started () in
  let v7 = Fibers_fixture.started () in
  v7

let programs : (string * (unit -> value)) list = [ ("p400212", corpus_p400212) ]
