import Effect4.Laws
import Test.Api.FrontierContract
import Test.Data.OpticContract
import Test.Schema.AnnotationDataPlaneContract
import Test.Schema.DataBridge
import Test.Schema.AuthoringContract
import Test.Schema.DialectContract
import Test.Counterexamples.Codegen.TypeScriptRender
import Test.Schema.RepresentationContract
import Test.Schema.SubAlphabetContract
import Test.Schema.PayloadContract
import Test.Schema.Modeled
import Test.Schema.Identity
import Test.Program.StepLanguage
import Test.Program.StepConstruction
import Test.Program.StepConstructors
import Test.Program.StepFolds
import Test.Program.StepInputs
import Test.Program.StepLists
import Test.Program.StepTuples
import Test.Program.SemaphoreData
import Test.Program.PoolData
import Test.Program.QueueData
import Test.Program.LatchSteps
import Test.Program.LatchRegistration
import Test.Data.RowContract
import Test.Machine.Environment.ContextKeyContract
import Test.Codegen.ExprContract
import Test.Codegen.DataTypes
import Test.Codegen.DataCodec
import Test.Codegen.Metadata
import Test.Codegen.Record
import Test.Codegen.RecordTerms
import Test.Codegen.TermRows
import Test.Codegen.TypeReader
import Test.Codegen.RecordEmission
import Test.Codegen.PayloadClasses
import Test.Codegen.RecordTag
import Test.Codegen.Tuple
import Test.Codegen.SchemaGenerationContract
import Test.Codegen.SchemaGenerationCoverage
import Test.Machine.Semantics.CauseExitContract
import Test.Counterexamples.Machine.Semantics.CauseExit
import Test.Counterexamples.Machine.Semantics.ActionAtRaceAllPremise
import Test.Counterexamples.Machine.Semantics.InterruptDelivery
import Test.Counterexamples.Machine.Semantics.StrongExitDefect
import Test.Counterexamples.Machine.Semantics.InterruptEscape
import Test.Counterexamples.Machine.Semantics.InterruptCarrier
import Test.Counterexamples.Machine.Semantics.AsyncHookContract
import Test.Counterexamples.Machine.Semantics.TrivialPosts
import Test.Counterexamples.Machine.Semantics.M6Capstone
import Test.Counterexamples.Machine.Semantics.StaleCode
import Test.Counterexamples.Machine.Semantics.AwaitLoad
import Test.Counterexamples.Machine.Semantics.RawOrderLoad
import Test.Counterexamples.Machine.Semantics.ScopePresence
import Test.Program.TypedSplit
import Test.Counterexamples.Machine.Semantics.LayerValue
import Test.Counterexamples.Machine.Semantics.ValueMembership
import Test.Counterexamples.Machine.Semantics.FitsOrder
import Test.Program.TermFits
import Test.Program.SignatureControls
import Test.Program.SketchControls
import Test.Program.DefinitionsControls
import Test.Program.ReplaceControls
import Test.Program.TypedProgRows
import Test.Program.AdmissionColumns
import Test.Program.FormationContract
import Test.Program.FormationClosed
import Test.Program.FoldContract
import Test.Program.MaskContract
import Test.Program.MaskEngine
import Test.Program.MaskClaims
import Test.Program.QueueMask
import Test.Program.FoldHygiene
import Test.Program.Ascribe
import Test.Program.RecordValues
import Test.Program.MapValues
import Test.Program.MapTyping
import Test.Program.MapHandles
import Test.Program.RecordOperations
import Test.Program.UnionRule
import Test.Program.Order
import Test.Program.Eliminators
import Test.Program.FoldFamilySelection
import Test.Program.RecordRefusals
import Test.Program.RecordTerms
import Test.Program.RecordTag
import Test.Program.AuthoringRecords
import Test.Program.TupleTerms
import Test.Program.TupleRefusals
import Test.Program.TupleTyping
import Test.Program.TupleMembership
import Test.Program.TupleHandles
import Test.Program.AuthoringTuples
import Test.Program.TypedWorldValidity
import Test.Program.ProtocolCertificates
import Test.Program.ProtocolLaws
import Test.Program.TypedProgBindRed
import Test.Program.SignatureSum
import Test.Program.TypedResidual
import Test.Program.TypedControl
import Test.Program.H2PartOne
import Test.Program.TypedDenotation
import Test.Program.LayerDenotation
import Test.Program.LayerRefs
import Test.Program.ReferenceExpansion
import Test.Program.TyTables
import Test.Program.TyWave
import Test.Program.GuardFoldLift
import Test.Program.ParkHandshake
import Test.Program.ExitConnector
import Test.Program.TypedCorpus
import Test.Program.AdmissionCensus
import Test.Program.LoadedAdmission
import Test.Program.TypedStack
import Test.Program.FramesNotKripke
import Test.Program.TimerColumn
import Test.Program.MemoTable
import Test.Program.WaiterColumn
import Test.Program.RegistrationColumn
import Test.Program.EnrollmentBound
import Test.Program.ScopeExitCallback
import Test.Program.RegistrationYield
import Test.Program.LaunchEntrant
import Test.Program.HostWalk
import Test.Program.LoopProtocols
import Test.Program.AnswerSchema
import Test.Program.ProtocolPosts
import Test.Program.RawHandleTerms
import Test.Program.CompletionDueControls
import Test.Program.ReadOnlyStoreClauses
import Test.Program.CapabilityMembership
import Test.Audit.AnswerGate
import Test.Machine.Runtime.RepresentationFoundations
import Test.Machine.Runtime.ScopeContract
import Test.Machine.Runtime.ScopeMachineContract
import Test.Machine.Runtime.ScopeRestorationContract
import Test.Counterexamples.Machine.Runtime.ScopeRestorationBoundary
import Test.Counterexamples.Machine.Runtime.Scope
import Test.Machine.Runtime.FramesContract
import Test.Counterexamples.Machine.Runtime.Frames
import Test.Machine.Runtime.LiveStackContract
import Test.Counterexamples.Machine.Runtime.LiveStack
import Test.Counterexamples.Machine.Runtime.HostHandleForgery
import Test.Counterexamples.Machine.Runtime.HostReservedDefect
import Test.Counterexamples.Machine.Runtime.LayerEnvironment
import Test.Counterexamples.Program.AdmissionUnserved
import Test.Machine.Runtime.StoresLawsContract
import Test.Machine.Runtime.CompletionDataContract
import Test.Machine.Runtime.ApproximationContract
import Test.Machine.Runtime.TapeAction
import Test.Machine.Runtime.BehaviourContract
import Test.Machine.Runtime.CompletionContract
import Test.Machine.Runtime.HandlesContract
import Test.Machine.Runtime.SchedulerCoreContract
import Test.Machine.Runtime.SchedulingContract
import Test.Store.Templates
import Test.Store.StoreContract
import Test.Store.NodeContract
import Test.Store.WordContract
import Test.Store.TraitContract
import Test.Store.ProbeContract
import Test.Store.DerivedCheck
import Test.Codegen.PrintContract
import Test.Codegen.PrintTyped
import Test.Codegen.DefinitionsPrint
import Test.Codegen.ReadContract
import Test.Codegen.SourceBindingsContract
import Test.Ingest.TaxonomyContract
import Test.Codegen.FormsContract
import Test.Codegen.TemplateContract
import Test.Codegen.TemplatesContract
import Test.Program.Gen
import Test.Program.CompileContract
import Test.Program.TypedContract
import Test.Program.WeakenContract
import Test.Program.AuthoringContract
import Test.Program.AuthoringDeclare
import Test.Program.AuthorContract
import Test.Program.AuthoringScope
import Test.Program.LoopSugarContract
import Test.Program.FragmentCensusContract
import Test.Program.DenoteContract
import Test.Program.DenoteBContract
import Test.Program.IterLimit
import Test.Program.StoreComodel
import Test.Program.MeaningSoundContract
import Test.Program.LoopSoundContract
import Test.Program.LoopAgreementContract
import Test.Program.AgreementContract
import Test.Program.MeaningEqContract
import Test.Program.QueueContract
import Test.Program.QueueCapacity
import Test.Program.QueueProfile
import Test.Program.QueueSteps
import Test.Program.QueueScenarios
import Test.Program.QueueDefs
import Test.Program.AuthoringDefs
import Test.Program.AuthoringModule
import Test.Program.ModuleDefinitions
import Test.Program.QueueOps
import Test.Program.QueueTraces
import Test.Program.QueueInvariant
import Test.Program.QueueAgreement
import Test.Program.QueueRelation
import Test.Program.QueueWorkload
import Test.Program.QueueEngine
import Test.Program.QueueFaces
import Test.Program.QueueTyping
import Test.Program.SemaphoreContract
import Test.Program.SemaphoreSteps
import Test.Program.SemaphoreScenarios
import Test.Program.SemaphoreAgreement
import Test.Program.SemaphoreRelation
import Test.Program.SemaphoreEngine
import Test.Program.SemaphoreWrapper
import Test.Program.SemaphoreOps
import Test.Program.SemaphoreTraces
import Test.Program.SemaphoreFaces
import Test.Program.PoolScenarios
import Test.Program.PoolContract
import Test.Program.PoolSteps
import Test.Program.PoolAgreement
import Test.Program.PoolRelation
import Test.Program.PoolEngine
import Test.Program.PoolPublic
import Test.Program.PoolOps
import Test.Program.PoolTraces
import Test.Program.PoolFaces
import Test.Program.ProgressContract
import Test.Program.InvocationContract
import Test.Program.HostSpecContract
import Test.Program.HostBoundaryContract
import Test.Api.HostSessionContract
import Test.Api.RunnerContract
import Test.Api.SessionMeaning
import Test.Api.TypedReplies
import Test.Api.RunnerFinality
import Test.Api.KeyedHostContract
import Test.Run.RunContract
import Test.Program.SchedContract
import Test.Program.DenoteRContract
import Test.Program.ScopeMarkers
import Test.Program.RuntimeRContract
import Test.Program.RuntimeRShapesContract
import Test.Program.SimulationContract
import Test.Program.DenoteRowsContract
import Test.Program.TableReference
import Test.Program.ProvisionContract
import Test.Program.ProvideRows
import Test.Program.ConfigContract
import Test.Api.ApiContract
import Test.Api.RecordAuthoring
import Test.Api.MapAuthoring
import Test.Api.TupleAuthoring
import Test.Api.TestClockContract
import Test.Program.ScopedTypingContract
import Test.Program.NativeAtomContract
import Test.Program.AtomTable
import Test.Program.AtomRulesRed
import Test.Program.CheckerRulesRed
import Test.Program.TypedStateRulesRed
import Test.Program.ErrorQueriesContract
import Test.Program.CatchIfContract
import Test.Audit.RuntimeCoverage
import Test.Audit.ClockLowering
import Test.Audit.LetReturn
import Test.Audit.AxiomGate
import Test.Audit.PositionAnalysis
import Test.Audit.TypedStateDecl
import Test.Audit.FrameRules
import Test.Audit.ProofGraph
import Test.Audit.ProofGraphPlan
import Test.Audit.Explain
import Test.Audit.Exposure
import Test.Audit.ScenarioGate
import Test.Audit.ProofStyle
import Test.Machine.StoreKernelBank
import Test.Machine.MaskDiscipline
import Test.Machine.MaskRuns
import Test.Machine.MaskBracket
import Test.Counterexamples.Machine.Runtime.ArmedFrontier
import Test.Audit.Obligations
import Test.Audit.SemanticsCensus
import Test.Program.TypeAlgebraContract
import Test.Program.TyViewContract
import Test.Program.ValueModelContract
import Test.Program.TypingCheckContract
import Test.Program.LinkedRowsContract
import Test.Program.LayerSharingContract
import Test.Program.BlameContract
import Test.Program.FocusControls
import Test.Program.TableControls
import Test.Program.PartsControls
import Test.Program.SpliceControls
import Test.Program.EditControls
import Test.Program.SessionToolControls
import Test.Program.JsonFormControls
import Test.Program.CallInstance
import Test.Program.QueryControls
import Test.Program.BoundsControls
import Test.Program.DecisionContract
import Test.Machine.Runtime.ArenaContract
import Test.Dogfood.P1HttpCache
import Test.Dogfood.P2HandlerLayers
import Test.Dogfood.P3WorkerQueue
import Test.Dogfood.P4RateLimiter
import Test.Dogfood.P5LedgerService
import Test.Dogfood.Scenario
import Test.Dogfood.Scenario.Workers
import Test.Dogfood.Scenario.QueueWorkers
import Test.Dogfood.Scenario.Routing
import Test.Dogfood.Scenario.Atomic
import Test.Dogfood.Scenario.Timeout
import Test.Dogfood.Scenario.Tape
import Test.Dogfood.Scenario.Lowered
import Test.Dogfood.Scenario.Gate
import Test.Dogfood.Scenario.Faces
import Test.Dogfood.Scenario.Todo
import Test.Dogfood.Scenario.TodoPaged
import Test.Program.ScopedOpContract
import Test.Program.SliceLattice
import Test.Program.StepCallback
import Test.Program.RefModel
import Test.Program.RefAgreement
import Test.Program.RefPrograms
import Test.Program.RefFaces
import Test.Program.PartitionedSemaphorePrograms
import Test.Program.PartitionedSemaphoreFaces
import Test.Program.PartitionedSemaphoreBookkeeping
import Test.Program.StreamArray
import Test.Program.SynchronizedRef
import Test.Program.PubSubSingle

/-!
# Effect4 test battery

The default Lake build imports every admitted contract and attack through this
root. A test file not reachable here is not a
passing gate. The batteries of the Flow route live on branch
`archive/flow-route` (`docs/research/2026-09-04-prod-cleanup-inventory.md`).
-/

#effect4_axiom_gate
-- The import gate of decisions row 332: the acceptance programs import entry modules, a composed
-- module's own files and the batteries' support only (`tools/Tools/Exposure.lean`).
#exposure_gate
