import Effect4.Laws
import Test.Api.FrontierContract
import Test.Data.OpticContract
import Test.Schema.AnnotationDataPlaneContract
import Test.Schema.EffectfulFieldContract
import Test.Schema.EffectfulFieldPropertiesContract
import Test.Schema.AuthoringContract
import Test.Counterexamples.Codegen.TypeScriptRender
import Test.Counterexamples.Schema.CensusCoverage
import Test.Counterexamples.Schema.KindAlphabetSeparation
import Test.Counterexamples.Schema.NoLocalSymbolPropertyKey
import Test.Counterexamples.Schema.NoNullLiteralKind
import Test.Counterexamples.Schema.SemanticTagSeparation
import Test.Counterexamples.Schema.WireSpellingDrift
import Test.Counterexamples.Schema.AnnotationDataPlane
import Test.Counterexamples.Schema.EffectfulField
import Test.Counterexamples.Schema.EffectfulFieldProperties
import Test.Counterexamples.Schema.RecursiveElimination
import Test.Counterexamples.Schema.Codec
import Test.Schema.RepresentationContract
import Test.Schema.RepresentationFoldContract
import Test.Schema.SubAlphabetContract
import Test.Schema.PayloadContract
import Test.Data.RowContract
import Test.Machine.Environment.ContextKeyContract
import Test.Codegen.ExprContract
import Test.Codegen.SchemaGenerationContract
import Test.Codegen.SchemaGenerationCoverage
import Test.Codegen.EffectfulFieldContract
import Test.Counterexamples.Codegen.EffectfulField
import Test.Machine.Semantics.CauseExitContract
import Test.Counterexamples.Machine.Semantics.CauseExit
import Test.Machine.Runtime.ScopeContract
import Test.Machine.Runtime.ScopeMachineContract
import Test.Machine.Runtime.ScopeRestorationContract
import Test.Counterexamples.Machine.Runtime.ScopeRestorationBoundary
import Test.Counterexamples.Machine.Runtime.Scope
import Test.Machine.Runtime.FramesContract
import Test.Counterexamples.Machine.Runtime.Frames
import Test.Machine.Runtime.LiveStackContract
import Test.Counterexamples.Machine.Runtime.LiveStack
import Test.Machine.Runtime.StoresLawsContract
import Test.Machine.Runtime.ApproximationContract
import Test.Machine.Runtime.BehaviourContract
import Test.Machine.Runtime.CompletionContract
import Test.Machine.Runtime.HandlesContract
import Test.Machine.Runtime.SchedulerCoreContract
import Test.Machine.Runtime.SchedulingContract
import Test.Store.Templates
import Test.Store.StoreContract
import Test.Store.NodeContract
import Test.Store.WordContract
import Test.Store.TraitContract
import Test.Store.ProbeContract
import Test.Store.DerivedCheck
import Test.Codegen.PrintContract
import Test.Codegen.ReadContract
import Test.Codegen.SourceBindingsContract
import Test.Ingest.TaxonomyContract
import Test.Codegen.FormsContract
import Test.Program.Gen
import Test.Program.CompileContract
import Test.Program.TypedContract
import Test.Program.WeakenContract
import Test.Program.AuthoringContract
import Test.Program.LoopSugarContract
import Test.Program.DenoteContract
import Test.Program.DenoteBContract
import Test.Program.MeaningSoundContract
import Test.Program.LoopSoundContract
import Test.Program.LoopAgreementContract
import Test.Program.AgreementContract
import Test.Program.ProgressContract
import Test.Program.InvocationContract
import Test.Program.HostSpecContract
import Test.Program.HostBoundaryContract
import Test.Api.HostSessionContract
import Test.Api.RunnerContract
import Test.Api.KeyedHostContract
import Test.Program.SchedContract
import Test.Program.DenoteRContract
import Test.Program.RuntimeRContract
import Test.Program.RuntimeRShapesContract
import Test.Program.SimulationContract
import Test.Program.ProvisionContract
import Test.Program.ConfigContract
import Test.Api.ApiContract
import Test.Api.TestClockContract
import Test.Program.ScopedTypingContract
import Test.Program.NativeAtomContract
import Test.Program.ErrorQueriesContract
import Test.Program.CatchIfContract
import Test.Machine.Fuzz
import Test.Audit.RuntimeCoverage
import Test.Audit.AxiomGate
import Test.Program.TypeAlgebraContract
import Test.Program.ValueModelContract
import Test.Program.TypingCheckContract
import Test.Program.LinkedRowsContract
import Test.Program.LayerSharingContract
import Test.Program.BlameContract
import Test.Program.DecisionContract

/-!
# Effect4 test battery

The default Lake build imports every admitted contract and attack through this
root. A test file not reachable here is not a
passing gate. The batteries of the Flow route live on branch
`archive/flow-route` (`docs/research/2026-09-04-prod-cleanup-inventory.md`).
-/

#effect4_axiom_gate
