(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400192`, seed 400192, 13 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400192 () =
  let v0 = Fibers_fixture.fork 4 in
  let v1 = Store_fixtures.def_make () in
  let _v2 = Store_fixtures.def_await_value v1 in
  let _v3 = Fibers_fixture.cleanups () in
  let _v4 = Store_fixtures.def_fail v1 9 in
  let _v5 = Fibers_fixture.started () in
  let _v6 = Fibers_fixture.join v0 in
  let _v7 = Extra_fixture.await_all [ v0 ] in
  let v8 = Fibers_fixture.fork 2 in
  let _v9 = Fibers_fixture.started () in
  let _v10 = Extra_fixture.interrupt_all [ v0; v8 ] in
  let _v11 = Store_fixtures.def_make () in
  let v12 = Fibers_fixture.await_value v8 in
  v12

let programs : (string * (unit -> value)) list = [ ("p400192", corpus_p400192) ]
