import Effect4.Laws.Api.TraceOrigin

#print axioms Effect4.Api.TraceFacts.Agreement.noFork_nil
#print axioms Effect4.Api.TraceFacts.Agreement.noFork_append
#print axioms Effect4.Api.TraceFacts.Agreement.forkedOf_frame_map
#print axioms Effect4.Api.TraceFacts.Agreement.noFork_frame_map
#print axioms Effect4.Api.TraceFacts.Agreement.ok_update_iff
#print axioms Effect4.Api.TraceFacts.Agreement.ok_emit_iff
#print axioms Effect4.Api.TraceFacts.Agreement.ok_modify_iff
#print axioms Effect4.Api.TraceFacts.Agreement.ok_updateRace_iff
#print axioms Effect4.Api.TraceFacts.Agreement.ok_arm_iff
#print axioms Effect4.Api.TraceFacts.Agreement.ok_disarm_iff
#print axioms Effect4.Api.TraceFacts.Agreement.ok_halt_iff
#print axioms Effect4.Api.TraceFacts.Agreement.ok_state_iff
#print axioms Effect4.Api.TraceFacts.Agreement.ok_token_iff
#print axioms Effect4.Api.TraceFacts.Agreement.ok_state_token_iff
#print axioms Effect4.Api.TraceFacts.Agreement.ok_middleware_iff
#print axioms Effect4.Api.TraceFacts.Agreement.ok_fibers_iff
#print axioms Effect4.Api.TraceFacts.Agreement.update_keeps
#print axioms Effect4.Api.TraceFacts.Agreement.emit_keeps
#print axioms Effect4.Api.TraceFacts.Agreement.update_ok
#print axioms Effect4.Api.TraceFacts.Agreement.emit_ok
#print axioms Effect4.Api.TraceFacts.Agreement.updateRace_ok
#print axioms Effect4.Api.TraceFacts.Agreement.halt_ok
#print axioms Effect4.Api.TraceFacts.Agreement.arm_ok
#print axioms Effect4.Api.TraceFacts.Agreement.disarm_ok
#print axioms Effect4.Api.TraceFacts.Agreement.state_ok
#print axioms Effect4.Api.TraceFacts.Agreement.middleware_ok
#print axioms Effect4.Api.TraceFacts.Agreement.modify_ok
#print axioms Effect4.Api.TraceFacts.Agreement.mapFibers_ok
#print axioms Effect4.Api.TraceFacts.Agreement.appendRoot_ok
#print axioms Effect4.Api.TraceFacts.Agreement.postTask_ok
#print axioms Effect4.Api.TraceFacts.Agreement.start_ok
#print axioms Effect4.Api.TraceFacts.Agreement.drainOwed_ok
#print axioms Effect4.Api.TraceFacts.Agreement.spawn_forked_site
#print axioms Effect4.Api.TraceFacts.Agreement.spawn_iff
#print axioms Effect4.Api.TraceFacts.Agreement.spawn_keeps
#print axioms Effect4.Api.TraceFacts.Agreement.spawn_ok
#print axioms Effect4.Api.TraceFacts.Agreement.launchEntrant_ok
#print axioms Effect4.Api.TraceFacts.Agreement.forkFinalizers_ok
#print axioms Effect4.Api.TraceFacts.Agreement.settle_ok
#print axioms Effect4.Api.TraceFacts.Agreement.interruptEdit_ok
#print axioms Effect4.Api.TraceFacts.Agreement.agrees_updates
#print axioms Effect4.Api.TraceFacts.Agreement.agrees_edits
#print axioms Effect4.Api.TraceFacts.Agreement.edits
#print axioms Effect4.Api.TraceFacts.Agreement.Native.countdown_ok
#print axioms Effect4.Api.TraceFacts.Agreement.Native.countdown_result_ok
#print axioms Effect4.Api.TraceFacts.Agreement.Native.linkScope_ok
#print axioms Effect4.Api.TraceFacts.Agreement.Native.interruptEach_ok
#print axioms Effect4.Api.TraceFacts.Agreement.Native.interruptEach_result_ok
#print axioms Effect4.Api.TraceFacts.Agreement.Native.beginRace_ok
#print axioms Effect4.Api.TraceFacts.Agreement.Native.registerRace_ok
#print axioms Effect4.Api.TraceFacts.Agreement.Native.stepFrame_ok
#print axioms Effect4.Api.TraceFacts.Agreement.Native.finalizerOr_ok
#print axioms Effect4.Api.TraceFacts.Agreement.Native.withFiber_ok
#print axioms Effect4.Api.TraceFacts.Agreement.Native.evaluatePrim_ok
#print axioms Effect4.Api.TraceFacts.Agreement.Native.enterScoped_ok
#print axioms Effect4.Api.TraceFacts.Agreement.Native.exitScoped_ok
#print axioms Effect4.Api.TraceFacts.Agreement.Native.evaluateNative_ok
#print axioms Effect4.Api.TraceFacts.Agreement.Native.iteration_ok
#print axioms Effect4.Api.TraceFacts.Agreement.Native.exitFiber_ok
#print axioms Effect4.Api.TraceFacts.Agreement.Native.fireObserver_ok
#print axioms Effect4.Api.TraceFacts.Agreement.Native.driveStep_ok
#print axioms Effect4.Api.TraceFacts.Agreement.Native.steppedBy_ok
#print axioms Effect4.Api.TraceFacts.Agreement.Native.drive_ok
#print axioms Effect4.Api.TraceFacts.Agreement.Native.runFork_ok
#print axioms Effect4.Api.TraceFacts.Agreement.Native.runCallback_ok
#print axioms Effect4.Api.TraceFacts.Agreement.Native.load_agrees
#print axioms Effect4.Api.TraceFacts.Agreement.Native.reachable_agrees_of
#print axioms Effect4.Api.TraceFacts.Agreement.Native.step_agrees
#print axioms Effect4.Api.TraceFacts.Agreement.Native.reachable_agrees
#print axioms Effect4.Api.TraceFacts.Agreement.emit_with_bank
#print axioms Effect4.Api.TraceFacts.M1Trace.step_agrees
#print axioms Effect4.Api.TraceFacts.M1Trace.reachable_agrees
