/**
 * Generated by OCaml5.Fuzz (spike P5, round four). Program `p400127`, seed 400127, 26 operations.
 *
 * Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`.
 */
import { Context, Effect } from "effect"
import type { Deferred, Fiber, Option, Ref, Result, Scope } from "effect"

/** Service `Fibers`: one method per operation of the Lean family, plus the three rows
 * `fiber-fixture.ts` does not declare and rc.112 does. */
export class Fibers extends Context.Service<Fibers, {
  readonly fork: (body: number) => Effect.Effect<Fiber.Fiber<number, number>>
  readonly forkDetach: (body: number) => Effect.Effect<Fiber.Fiber<number, number>>
  readonly join: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<number, number>
  readonly awaitValue: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<Option.Option<number>>
  readonly awaitError: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<Option.Option<number>>
  readonly interrupt: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<void>
  readonly started: Effect.Effect<ReadonlyArray<number>>
  readonly cleanups: Effect.Effect<ReadonlyArray<number>>
  readonly yieldNow: (priority: number) => Effect.Effect<void>
  readonly interruptAll: (fibers: ReadonlyArray<Fiber.Fiber<number, number>>) => Effect.Effect<void>
  readonly awaitAll: (fibers: ReadonlyArray<Fiber.Fiber<number, number>>) => Effect.Effect<void>
}>()("Fibers") {}

export const FibersRows = { "fork": { params: 1, answer: "Fiber.Fiber<number, number>" }, "forkDetach": { params: 1, answer: "Fiber.Fiber<number, number>" }, "join": { params: 1, answer: "number" }, "awaitValue": { params: 1, answer: "Option.Option<number>" }, "awaitError": { params: 1, answer: "Option.Option<number>" }, "interrupt": { params: 1, answer: "void" }, "started": { params: 0, answer: "ReadonlyArray<number>" }, "cleanups": { params: 0, answer: "ReadonlyArray<number>" }, "yieldNow": { params: 1, answer: "void" }, "interruptAll": { params: 1, answer: "void" }, "awaitAll": { params: 1, answer: "void" } }

/** Service `Deferreds` (`harness/trace/deferred-fixture.ts`). */
export class Deferreds extends Context.Service<Deferreds, {
  readonly make: Effect.Effect<Deferred.Deferred<number, number>>
  readonly succeed: (cell: Deferred.Deferred<number, number>, value: number) => Effect.Effect<boolean>
  readonly fail: (cell: Deferred.Deferred<number, number>, error: number) => Effect.Effect<boolean>
  readonly isDone: (cell: Deferred.Deferred<number, number>) => Effect.Effect<boolean>
  readonly poll: (cell: Deferred.Deferred<number, number>) => Effect.Effect<Option.Option<Result.Result<number, number>>>
  readonly awaitValue: (cell: Deferred.Deferred<number, number>) => Effect.Effect<number, number>
  readonly awaitError: (cell: Deferred.Deferred<number, number>) => Effect.Effect<number, number>
}>()("Deferreds") {}

export const DeferredsRows = { "make": { params: 0, answer: "Deferred.Deferred<number, number>" }, "succeed": { params: 2, answer: "boolean" }, "fail": { params: 2, answer: "boolean" }, "isDone": { params: 1, answer: "boolean" }, "poll": { params: 1, answer: "Option.Option<Result.Result<number, number>>" }, "awaitValue": { params: 1, answer: "number" }, "awaitError": { params: 1, answer: "number" } }

/** Service `Layers` (`harness/trace/layer-fixture.ts`). */
export class Layers extends Context.Service<Layers, {
  readonly build: (layer: number) => Effect.Effect<Ref.Ref<number>>
  readonly provideCount: (layer: number) => Effect.Effect<number>
  readonly scopeOf: (service: Ref.Ref<number>) => Effect.Effect<Scope.Closeable>
  readonly close: Effect.Effect<ReadonlyArray<Ref.Ref<number>>>
}>()("Layers") {}

export const LayersRows = { "build": { params: 1, answer: "Ref.Ref<number>" }, "provideCount": { params: 1, answer: "number" }, "scopeOf": { params: 1, answer: "Scope.Closeable" }, "close": { params: 0, answer: "ReadonlyArray<Ref.Ref<number>>" } }

/** Lowered from `p400127` by OCaml5.Fuzz. */
export const corpus_p400127 = (n: number) =>
  Effect.gen(function* () {
    const fibers = yield* Fibers
    const deferreds = yield* Deferreds
    const layers = yield* Layers
    void n
    const v0 = yield* fibers.fork(0)
    const v1 = yield* fibers.started
    const v2 = yield* fibers.awaitAll([v0])
    const v3 = yield* fibers.cleanups
    const v4 = yield* fibers.started
    const v5 = yield* fibers.join(v0)
    const v6 = yield* fibers.cleanups
    const v7 = yield* fibers.started
    const v8 = yield* fibers.awaitAll([v0])
    const v9 = yield* deferreds.make
    const v10 = yield* deferreds.make
    const v11 = yield* fibers.cleanups
    const v12 = yield* fibers.cleanups
    const v13 = yield* fibers.fork(1)
    const v14 = yield* deferreds.poll(v9)
    const v15 = yield* fibers.interruptAll([v0, v13])
    const v16 = yield* fibers.join(v13)
    const v17 = yield* fibers.fork(4)
    const v18 = yield* layers.build(1)
    const v19 = yield* deferreds.fail(v10, 10)
    yield* fibers.interrupt(v0)
    const v20 = yield* deferreds.poll(v10)
    const v21 = yield* fibers.join(v13)
    const v22 = yield* deferreds.awaitValue(v10)
    const v23 = yield* fibers.join(v13)
    const v24 = yield* fibers.cleanups
    return v24
  })
