/-
Contract: the projection guard on every generated `Canonical` instance
(`docs/research/2026-09-04-cas-trait-plan.md` §4, `tools/Effect4Gen/Check.lean`).

Frozen: every `shapeDoc` in a generated file still projects an inductive that is actually in
the environment — the same case names in the same order, the same field names in the same
order inside each case, and a `toVal` clause writing each constructor's declaration position.
A reordered constructor upstream, a renamed field, a dropped case or a hand edit inside a
generated file is a build failure here rather than a silent change of every address in the
store.

Why the check runs in an elaborator rather than only in `scripts/generate-derived.ps1 -Check`:
the script is a step somebody has to remember, and the plan asks for the guard to be part of
the build. `Effect4Check.checkFile` is a `MetaM` action over the ambient environment, so
importing exactly the modules the generated files elaborate in and running it once per file is
the whole of it — no second environment, no subprocess. The tool's own `main`
(`tools/Effect4Gen/Check.lean:225`) is deliberately *not* used: it calls `importModules` to
build an environment of its own and ends in `IO.Process.exit`, neither of which belongs inside
a compiler that is already holding this one.

`Effect4Gen` is a tool library, not an audited one (`lakefile.toml`, the `Effect4Gen` hunk;
`Test/Audit/AxiomGate.lean:369-371` audits `Effect4`, `Test` and `Fixtures` only), so importing
it here subjects none of its declarations to the ceiling and adds no trust. What it does add is
a build edge: `TestStore` now needs `Effect4Gen.Check` compiled.

The paths are relative to the repository root, which is the working directory `lake` gives
every `lean` it runs. Measured 2026-09-05 (lane B, `workshop/Cas/NOTES-B.md`): five files,
forty-one shapes, twelve seconds and 877 MB in a `lake env lean -M 3072` probe.

`src/Effect4/Evidence/Char/Derived.lean` joined the list at the landing's gate (2026-09-05),
once its manifest row was in `scripts/generate-derived.ps1` and the generator's n-ary sum
reader let `Evidence` be generated with the rest of the room.
-/

import Effect4Gen.Check
import Effect4.Store.Derived.Json
import Effect4.Store.Derived.Schema
import Effect4.Program.Derived
import Effect4.Store.PinDerived
import Effect4.Evidence.StdLib.Derived
import Effect4.Evidence.Char.Derived

namespace Test.Store.DerivedCheck

/-- The generated files, in the order the generator emits them: the two store groups, the
program group, the pin group, and the census group. Each is regenerated by
`scripts/generate-derived.ps1`, whose manifest is the authority on the arguments. -/
def derivedFiles : List String :=
  [ "src/Effect4/Store/Derived/Json.lean"
  , "src/Effect4/Store/Derived/Schema.lean"
  , "src/Effect4/Program/Derived.lean"
  , "src/Effect4/Store/PinDerived.lean"
  , "src/Effect4/Evidence/StdLib/Derived.lean"
  , "src/Effect4/Evidence/Char/Derived.lean" ]

open Lean Meta in
#eval show MetaM Unit from do
  let mut refused := false
  for path in derivedFiles do
    if ← Effect4Check.checkFile path then refused := true
  if refused then
    throwError "the projection guard refused a generated file; regenerate it with \
      scripts/generate-derived.ps1 rather than editing it"

/-! ## Axiom receipts -/

#print axioms derivedFiles

end Test.Store.DerivedCheck
