/**
 * Generated by OCaml5.Fuzz (spike P5, round four). Program `p400103`, seed 400103, 38 operations.
 *
 * Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`.
 */
import { Context, Effect } from "effect"
import type { Fiber, Option, Ref, Scope } from "effect"

/** Service `Fibers`: one method per operation of the Lean family, plus the three rows
 * `fiber-fixture.ts` does not declare and rc.112 does. */
export class Fibers extends Context.Service<Fibers, {
  readonly fork: (body: number) => Effect.Effect<Fiber.Fiber<number, number>>
  readonly forkDetach: (body: number) => Effect.Effect<Fiber.Fiber<number, number>>
  readonly join: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<number, number>
  readonly awaitValue: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<Option.Option<number>>
  readonly awaitError: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<Option.Option<number>>
  readonly interrupt: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<void>
  readonly started: Effect.Effect<ReadonlyArray<number>>
  readonly cleanups: Effect.Effect<ReadonlyArray<number>>
  readonly yieldNow: (priority: number) => Effect.Effect<void>
  readonly interruptAll: (fibers: ReadonlyArray<Fiber.Fiber<number, number>>) => Effect.Effect<void>
  readonly awaitAll: (fibers: ReadonlyArray<Fiber.Fiber<number, number>>) => Effect.Effect<void>
}>()("Fibers") {}

export const FibersRows = { "fork": { params: 1, answer: "Fiber.Fiber<number, number>" }, "forkDetach": { params: 1, answer: "Fiber.Fiber<number, number>" }, "join": { params: 1, answer: "number" }, "awaitValue": { params: 1, answer: "Option.Option<number>" }, "awaitError": { params: 1, answer: "Option.Option<number>" }, "interrupt": { params: 1, answer: "void" }, "started": { params: 0, answer: "ReadonlyArray<number>" }, "cleanups": { params: 0, answer: "ReadonlyArray<number>" }, "yieldNow": { params: 1, answer: "void" }, "interruptAll": { params: 1, answer: "void" }, "awaitAll": { params: 1, answer: "void" } }

/** Service `Refs` (`harness/trace/ref-fixture.ts`). */
export class Refs extends Context.Service<Refs, {
  readonly make: (initial: number) => Effect.Effect<Ref.Ref<number>>
  readonly get: (ref: Ref.Ref<number>) => Effect.Effect<number>
  readonly set: (ref: Ref.Ref<number>, value: number) => Effect.Effect<void>
  readonly update: (ref: Ref.Ref<number>, amount: number) => Effect.Effect<void>
  readonly modify: (ref: Ref.Ref<number>, amount: number) => Effect.Effect<number>
  readonly getAndSet: (ref: Ref.Ref<number>, value: number) => Effect.Effect<number>
}>()("Refs") {}

export const RefsRows = { "make": { params: 1, answer: "Ref.Ref<number>" }, "get": { params: 1, answer: "number" }, "set": { params: 2, answer: "void" }, "update": { params: 2, answer: "void" }, "modify": { params: 2, answer: "number" }, "getAndSet": { params: 2, answer: "number" } }

/** Service `Layers` (`harness/trace/layer-fixture.ts`). */
export class Layers extends Context.Service<Layers, {
  readonly build: (layer: number) => Effect.Effect<Ref.Ref<number>>
  readonly provideCount: (layer: number) => Effect.Effect<number>
  readonly scopeOf: (service: Ref.Ref<number>) => Effect.Effect<Scope.Closeable>
  readonly close: Effect.Effect<ReadonlyArray<Ref.Ref<number>>>
}>()("Layers") {}

export const LayersRows = { "build": { params: 1, answer: "Ref.Ref<number>" }, "provideCount": { params: 1, answer: "number" }, "scopeOf": { params: 1, answer: "Scope.Closeable" }, "close": { params: 0, answer: "ReadonlyArray<Ref.Ref<number>>" } }

/** Lowered from `p400103` by OCaml5.Fuzz. */
export const corpus_p400103 = (n: number) =>
  Effect.gen(function* () {
    const fibers = yield* Fibers
    const refs = yield* Refs
    const layers = yield* Layers
    void n
    const v0 = yield* fibers.forkDetach(1)
    const v1 = yield* fibers.started
    const v2 = yield* fibers.started
    const v3 = yield* fibers.cleanups
    const v4 = yield* refs.make(9)
    const v5 = yield* fibers.started
    const v6 = yield* refs.getAndSet(v4, 1)
    yield* fibers.interrupt(v0)
    const v7 = yield* fibers.fork(0)
    const v8 = yield* fibers.cleanups
    yield* refs.set(v4, 6)
    const v9 = yield* fibers.started
    const v10 = yield* refs.getAndSet(v4, 7)
    const v11 = yield* fibers.join(v7)
    const v12 = yield* fibers.fork(2)
    const v13 = yield* fibers.fork(4)
    yield* refs.update(v4, 7)
    const v14 = yield* layers.build(0)
    const v15 = yield* fibers.cleanups
    const v16 = yield* fibers.fork(1)
    yield* refs.update(v4, 4)
    const v17 = yield* layers.build(3)
    yield* fibers.interrupt(v13)
    const v18 = yield* fibers.awaitValue(v0)
    yield* fibers.interrupt(v13)
    const v19 = yield* fibers.started
    const v20 = yield* fibers.fork(4)
    const v21 = yield* fibers.cleanups
    const v22 = yield* refs.make(4)
    const v23 = yield* fibers.cleanups
    const v24 = yield* fibers.started
    const v25 = yield* fibers.join(v12)
    const v26 = yield* layers.scopeOf(v14)
    yield* fibers.yieldNow(0)
    const v27 = yield* layers.scopeOf(v17)
    const v28 = yield* fibers.join(v13)
    const v29 = yield* fibers.awaitValue(v20)
    const v30 = yield* fibers.join(v16)
    return v30
  })
