-- GENERATED by tools/Effect4Gen/View.lean; do not edit
-- GENERATED by tools/Effect4Gen/View.lean from the Lean environment and
-- tools/Effect4Gen/variances.json (rc.112's own declarations). Do not edit.
-- Regenerate (tools/Effect4Gen/Driver.lean runs this for every group; --verify refuses a diff):
--   lake env lean -M 4096 --run tools/Effect4Gen/View.lean --group TyView --imports Effect4.Program.Folds.Ty,Effect4.Laws.Auto.RuleSets --out src/Effect4/Laws/Program/TyView.lean --append tools/Effect4Gen/guards/tyview.lean Effect4.Program.Ty
-- Acceptance guards appended verbatim from: tools/Effect4Gen/guards/tyview.lean
import Effect4.Program.Folds.Ty
import Effect4.Laws.Auto.RuleSets

set_option autoImplicit false

namespace Effect4.Program

namespace Ty

/-- How a relation reads a recursive argument: as rc.112 declares the parameter
(`Fiber<out A, out E>` covariant, `Ref<in out A>` invariant; decisions row 55). -/
inductive Variance where
  | co
  | contra
  | inv
deriving DecidableEq, Repr

/-- A Boolean relation lifted through a variance. -/
def Variance.holds (r : Ty → Ty → Bool) : Variance → Ty → Ty → Bool
  | .co,     x, y => r x y
  | .contra, x, y => r y x
  | .inv,    x, y => r x y && r y x

/-- The immediate `Ty` children of a type, each with the variance the order reads it at.
Not one row of this is declared here: every variance comes from
`tools/Effect4Gen/variances.json`, which `tools/Tools/Variances.lean` reads off the
vendored rc.112 sources. -/
def args : Ty → List (Variance × Ty)
  | .never => []
  | .unit => []
  | .nat => []
  | .int => []
  | .string => []
  | .bool => []
  | .handle _ => []
  | .option inner => [(.co, inner)]  -- vendor/effect-4.0.0-rc.112/src/Option.ts:55
  | .list inner => [(.co, inner)]  -- ReadonlyArray<A>
  | .prod left right => [(.co, left), (.co, right)]  -- readonly [A, B]
  | .except error value => [(.co, error), (.co, value)]  -- Result.Result<A, E>
  | .exitOf value error => [(.co, value), (.co, error)]  -- vendor/effect-4.0.0-rc.112/src/Exit.ts:59
  | .causeOf error => [(.co, error)]  -- vendor/effect-4.0.0-rc.112/src/Cause.ts:75
  | .fiberOf value error => [(.co, value), (.co, error)]  -- vendor/effect-4.0.0-rc.112/src/Fiber.ts:70
  | .union left right => [(.co, left), (.co, right)]  -- A | B
  | .lit _ => []
  | .refOf value => [(.inv, value)]  -- vendor/effect-4.0.0-rc.112/src/Ref.ts:59
  | .deferredOf value error => [(.inv, value), (.inv, error)]  -- vendor/effect-4.0.0-rc.112/src/Deferred.ts:58
  | .var _ => []
  | .unknown => []

/-- Same constructor and equal non-recursive payload. -/
def sameHead : Ty → Ty → Bool
  | .never, .never => true
  | .unit, .unit => true
  | .nat, .nat => true
  | .int, .int => true
  | .string, .string => true
  | .bool, .bool => true
  | .handle target1, .handle target2 => decide (target1 = target2)
  | .option _, .option _ => true
  | .list _, .list _ => true
  | .prod _ _, .prod _ _ => true
  | .except _ _, .except _ _ => true
  | .exitOf _ _, .exitOf _ _ => true
  | .causeOf _, .causeOf _ => true
  | .fiberOf _ _, .fiberOf _ _ => true
  | .lit value1, .lit value2 => decide (value1 = value2)
  | .refOf _, .refOf _ => true
  | .deferredOf _ _, .deferredOf _ _ => true
  | .var index1, .var index2 => decide (index1 = index2)
  | .unknown, .unknown => true
  -- `union` is deliberately absent: the order distributes a union on the left and chooses on the right (`sub_union_left`/`sub_union_right`), so it is row structure and not a head
  | _, _ => false

/-- The literal rule: one of the order's rules between members that is not a congruence
(`sub_lit_string`). -/
def litRule : Ty → Ty → Bool
  | .lit _, .string => true
  | _, _            => false

/-- The top (decisions row 46), the other one (`sub_unknown`). -/
def topRule : Ty → Ty → Bool
  | _, .unknown => true
  | _, _        => false

/-- The variance-wise comparison of corresponding arguments. -/
def argsBelow (r : Ty → Ty → Bool) (a b : Ty) : Bool :=
  (a.args.zip b.args).all fun p => p.1.1.holds r p.1.2 p.2.2

/-! ### The variance probes

One pair per position per head: a covariant position admits `lit "a"` below `string`
and not the reverse, a contravariant one the reverse, an invariant one neither. Then one
crossing probe per head of arity two or more: distinct atoms at every position, which
answers `false` when the arms are positional and `true` when two are compared out of
order. A variance row that does not match `sub`'s arm makes this file red, which makes
`python3 scripts/generate.py --only derived` fail. -/

#guard Ty.sub (.option (.lit "a")) (.option .string)
#guard !Ty.sub (.option .string) (.option (.lit "a"))

#guard Ty.sub (.list (.lit "a")) (.list .string)
#guard !Ty.sub (.list .string) (.list (.lit "a"))

#guard Ty.sub (.prod (.lit "a") .nat) (.prod .string .nat)
#guard !Ty.sub (.prod .string .nat) (.prod (.lit "a") .nat)
#guard Ty.sub (.prod .nat (.lit "a")) (.prod .nat .string)
#guard !Ty.sub (.prod .nat .string) (.prod .nat (.lit "a"))
#guard !Ty.sub (.prod .nat .bool) (.prod .bool .unit)

#guard Ty.sub (.except (.lit "a") .nat) (.except .string .nat)
#guard !Ty.sub (.except .string .nat) (.except (.lit "a") .nat)
#guard Ty.sub (.except .nat (.lit "a")) (.except .nat .string)
#guard !Ty.sub (.except .nat .string) (.except .nat (.lit "a"))
#guard !Ty.sub (.except .nat .bool) (.except .bool .unit)

#guard Ty.sub (.exitOf (.lit "a") .nat) (.exitOf .string .nat)
#guard !Ty.sub (.exitOf .string .nat) (.exitOf (.lit "a") .nat)
#guard Ty.sub (.exitOf .nat (.lit "a")) (.exitOf .nat .string)
#guard !Ty.sub (.exitOf .nat .string) (.exitOf .nat (.lit "a"))
#guard !Ty.sub (.exitOf .nat .bool) (.exitOf .bool .unit)

#guard Ty.sub (.causeOf (.lit "a")) (.causeOf .string)
#guard !Ty.sub (.causeOf .string) (.causeOf (.lit "a"))

#guard Ty.sub (.fiberOf (.lit "a") .nat) (.fiberOf .string .nat)
#guard !Ty.sub (.fiberOf .string .nat) (.fiberOf (.lit "a") .nat)
#guard Ty.sub (.fiberOf .nat (.lit "a")) (.fiberOf .nat .string)
#guard !Ty.sub (.fiberOf .nat .string) (.fiberOf .nat (.lit "a"))
#guard !Ty.sub (.fiberOf .nat .bool) (.fiberOf .bool .unit)

#guard !Ty.sub (.refOf (.lit "a")) (.refOf .string)
#guard !Ty.sub (.refOf .string) (.refOf (.lit "a"))

#guard !Ty.sub (.deferredOf (.lit "a") .nat) (.deferredOf .string .nat)
#guard !Ty.sub (.deferredOf .string .nat) (.deferredOf (.lit "a") .nat)
#guard !Ty.sub (.deferredOf .nat (.lit "a")) (.deferredOf .nat .string)
#guard !Ty.sub (.deferredOf .nat .string) (.deferredOf .nat (.lit "a"))
#guard !Ty.sub (.deferredOf .nat .bool) (.deferredOf .bool .unit)

/-- `union` is the one head `sameHead` refuses, so reflexivity is stated at a member; an
`isMember` hypothesis is exactly what every caller of the view has: the one goal the
normalisation leaves is that head, and `isMember` is `false` there. -/
theorem sameHead_refl (t : Ty) (h : isMember t = true) : sameHead t t = true := by
  cases t <;> simp only [sameHead, decide_eq_true_eq]
  exact h

theorem sameHead_symm {a b : Ty} (h : sameHead a b = true) : sameHead b a = true := by
  cases a <;> cases b <;> aesop (add norm simp [sameHead])

/-- `fun_cases` on `sameHead` itself, so the split is its own arm list and not the square of
the alphabet: one case per arm, then one `cases c` inside each. -/
theorem sameHead_trans {a b c : Ty} (hab : sameHead a b = true)
    (hbc : sameHead b c = true) : sameHead a c = true := by
  fun_cases Ty.sameHead a b <;> cases c <;> aesop (add norm simp [sameHead])

/-- The variance-wise comparison of a node with itself, from `sub_refl`. -/
theorem argsBelow_refl (t : Ty) : argsBelow sub t t = true := by
  cases t <;>
    simp only [argsBelow, args, Variance.holds, List.zip, List.zipWith, List.all_cons,
      List.all_nil, Bool.and_true, sub_refl]

/-- Corresponding arguments correspond: same length, same variances. -/
theorem args_congr {a b : Ty} (h : sameHead a b = true) :
    a.args.length = b.args.length ∧ a.args.map Prod.fst = b.args.map Prod.fst := by
  cases a <;> cases b <;> aesop (add norm simp [sameHead, args])

/-- A node is its head and its children. -/
theorem eq_of_sameHead {a b : Ty} (h : sameHead a b = true)
    (hx : a.args.map Prod.snd = b.args.map Prod.snd) : a = b := by
  cases a <;> cases b <;> aesop (add norm simp [sameHead, args, Ty.handle.injEq, Ty.option.injEq, Ty.list.injEq, Ty.prod.injEq, Ty.except.injEq, Ty.exitOf.injEq, Ty.causeOf.injEq, Ty.fiberOf.injEq, Ty.union.injEq, Ty.lit.injEq, Ty.refOf.injEq, Ty.deferredOf.injEq, Ty.var.injEq])

/-- Composition at each variance, once, for every relational law that needs it. -/
theorem Variance.holds_trans {r : Ty → Ty → Bool} (v : Variance)
    (htrans : ∀ x y z, r x y = true → r y z = true → r x z = true) {x y z : Ty}
    (h : v.holds r x y = true) (h' : v.holds r y z = true) : v.holds r x z = true := by
  cases v <;> aesop (add norm simp [Variance.holds])

/-- And at each variance, a two-sided comparison gives the relation both ways. -/
theorem Variance.holds_antisymm {r : Ty → Ty → Bool} (v : Variance) {x y : Ty}
    (h : v.holds r x y = true) (h' : v.holds r y x = true) :
    r x y = true ∧ r y x = true := by
  cases v <;> aesop (add norm simp [Variance.holds])

/-! ### The congruence arms, one lemma each

A1 of the tooling plan's assumption table asked whether ONE generated proof closes over
the whole square of constructors. It does — `fun_cases Ty.sub a b` plus one `aesop` — but
that proof reaches `Classical.choice` through aesop's search, and this file is audited
source whose ceiling is `[propext, Quot.sound]`. So the plan's designed fallback is what
lands: one lemma per congruence arm, and a dispatcher over `fun_cases` that names no
constructor of its own. Each lemma is the idiom of `Ty.lean`'s `sub_*_of_ne`, with the
reflexive case folded in so no caller carries an inequality. -/

theorem sub_args_option (x0 y0 : Ty) :
    sub (.option x0) (.option y0) = argsBelow sub (.option x0) (.option y0) := by
  by_cases h : Ty.option x0 = Ty.option y0
  · rw [h, sub_refl, argsBelow_refl]
  · conv => lhs; unfold sub
    simp only [h, ↓reduceIte, argsBelow, args, Variance.holds, List.zip, List.zipWith,
      List.all_cons, List.all_nil, Bool.and_true]

theorem sub_args_list (x0 y0 : Ty) :
    sub (.list x0) (.list y0) = argsBelow sub (.list x0) (.list y0) := by
  by_cases h : Ty.list x0 = Ty.list y0
  · rw [h, sub_refl, argsBelow_refl]
  · conv => lhs; unfold sub
    simp only [h, ↓reduceIte, argsBelow, args, Variance.holds, List.zip, List.zipWith,
      List.all_cons, List.all_nil, Bool.and_true]

theorem sub_args_prod (x0 x1 y0 y1 : Ty) :
    sub (.prod x0 x1) (.prod y0 y1) = argsBelow sub (.prod x0 x1) (.prod y0 y1) := by
  by_cases h : Ty.prod x0 x1 = Ty.prod y0 y1
  · rw [h, sub_refl, argsBelow_refl]
  · conv => lhs; unfold sub
    simp only [h, ↓reduceIte, argsBelow, args, Variance.holds, List.zip, List.zipWith,
      List.all_cons, List.all_nil, Bool.and_true]

theorem sub_args_except (x0 x1 y0 y1 : Ty) :
    sub (.except x0 x1) (.except y0 y1) = argsBelow sub (.except x0 x1) (.except y0 y1) := by
  by_cases h : Ty.except x0 x1 = Ty.except y0 y1
  · rw [h, sub_refl, argsBelow_refl]
  · conv => lhs; unfold sub
    simp only [h, ↓reduceIte, argsBelow, args, Variance.holds, List.zip, List.zipWith,
      List.all_cons, List.all_nil, Bool.and_true]

theorem sub_args_exitOf (x0 x1 y0 y1 : Ty) :
    sub (.exitOf x0 x1) (.exitOf y0 y1) = argsBelow sub (.exitOf x0 x1) (.exitOf y0 y1) := by
  by_cases h : Ty.exitOf x0 x1 = Ty.exitOf y0 y1
  · rw [h, sub_refl, argsBelow_refl]
  · conv => lhs; unfold sub
    simp only [h, ↓reduceIte, argsBelow, args, Variance.holds, List.zip, List.zipWith,
      List.all_cons, List.all_nil, Bool.and_true]

theorem sub_args_causeOf (x0 y0 : Ty) :
    sub (.causeOf x0) (.causeOf y0) = argsBelow sub (.causeOf x0) (.causeOf y0) := by
  by_cases h : Ty.causeOf x0 = Ty.causeOf y0
  · rw [h, sub_refl, argsBelow_refl]
  · conv => lhs; unfold sub
    simp only [h, ↓reduceIte, argsBelow, args, Variance.holds, List.zip, List.zipWith,
      List.all_cons, List.all_nil, Bool.and_true]

theorem sub_args_fiberOf (x0 x1 y0 y1 : Ty) :
    sub (.fiberOf x0 x1) (.fiberOf y0 y1) = argsBelow sub (.fiberOf x0 x1) (.fiberOf y0 y1) := by
  by_cases h : Ty.fiberOf x0 x1 = Ty.fiberOf y0 y1
  · rw [h, sub_refl, argsBelow_refl]
  · conv => lhs; unfold sub
    simp only [h, ↓reduceIte, argsBelow, args, Variance.holds, List.zip, List.zipWith,
      List.all_cons, List.all_nil, Bool.and_true]

theorem sub_args_refOf (x0 y0 : Ty) :
    sub (.refOf x0) (.refOf y0) = argsBelow sub (.refOf x0) (.refOf y0) := by
  by_cases h : Ty.refOf x0 = Ty.refOf y0
  · rw [h, sub_refl, argsBelow_refl]
  · conv => lhs; unfold sub
    simp only [h, ↓reduceIte, argsBelow, args, Variance.holds, List.zip, List.zipWith,
      List.all_cons, List.all_nil, Bool.and_true]

theorem sub_args_deferredOf (x0 x1 y0 y1 : Ty) :
    sub (.deferredOf x0 x1) (.deferredOf y0 y1) = argsBelow sub (.deferredOf x0 x1) (.deferredOf y0 y1) := by
  by_cases h : Ty.deferredOf x0 x1 = Ty.deferredOf y0 y1
  · rw [h, sub_refl, argsBelow_refl]
  · conv => lhs; unfold sub
    simp only [h, ↓reduceIte, argsBelow, args, Variance.holds, List.zip, List.zipWith,
      List.all_cons, List.all_nil, Bool.and_true, Bool.and_assoc]

/-- Different heads: the order answers `false`. `fun_cases Ty.sub` makes the catch-all —
the one case a square-of-constructors proof cannot discharge without search — into `rfl`,
because the arm it takes IS `false`. -/
theorem sub_eq_false_of_not_sameHead (a b : Ty) (ha : isMember a = true)
    (hb : isMember b = true) (hlit : litRule a b = false) (htop : topRule a b = false)
    (hh : sameHead a b = false) : sub a b = false := by
  fun_cases Ty.sub a b
  case case1 => rw [sameHead_refl _ ha] at hh; exact Bool.noConfusion hh
  case case2 => exact Bool.noConfusion ha
  case case3 => exact Bool.noConfusion ha
  case case4 => exact Bool.noConfusion hb
  case case5 => exact Bool.noConfusion htop
  case case6 => exact Bool.noConfusion hlit
  case case16 => rfl
  -- the congruence arms: `sameHead` answers `true` at a matching head, so `hh` is absurd
  all_goals simp only [sameHead, Bool.true_eq_false] at hh

/-- Same head: the order IS the variance-wise comparison. `fun_cases Ty.sameHead` splits on
the head test's own arms, so there is one case per constructor and no square. -/
theorem sub_eq_argsBelow_of_sameHead (a b : Ty) (hh : sameHead a b = true) :
    sub a b = argsBelow sub a b := by
  revert hh
  fun_cases Ty.sameHead a b
  case case1 => intro _; rw [sub_refl, argsBelow_refl]
  case case2 => intro _; rw [sub_refl, argsBelow_refl]
  case case3 => intro _; rw [sub_refl, argsBelow_refl]
  case case4 => intro _; rw [sub_refl, argsBelow_refl]
  case case5 => intro _; rw [sub_refl, argsBelow_refl]
  case case6 => intro _; rw [sub_refl, argsBelow_refl]
  case case7 =>
    intro hh
    have hp := of_decide_eq_true hh
    subst hp
    rw [sub_refl, argsBelow_refl]
  case case8 => intro _; exact sub_args_option _ _
  case case9 => intro _; exact sub_args_list _ _
  case case10 => intro _; exact sub_args_prod _ _ _ _
  case case11 => intro _; exact sub_args_except _ _ _ _
  case case12 => intro _; exact sub_args_exitOf _ _ _ _
  case case13 => intro _; exact sub_args_causeOf _ _
  case case14 => intro _; exact sub_args_fiberOf _ _ _ _
  case case15 =>
    intro hh
    have hp := of_decide_eq_true hh
    subst hp
    rw [sub_refl, argsBelow_refl]
  case case16 => intro _; exact sub_args_refOf _ _
  case case17 => intro _; exact sub_args_deferredOf _ _ _ _
  case case18 =>
    intro hh
    have hp := of_decide_eq_true hh
    subst hp
    rw [sub_refl, argsBelow_refl]
  case case19 => intro _; rw [sub_refl, argsBelow_refl]
  case case20 => intro hh; exact Bool.noConfusion hh

/-- **`sub` between union members is the variance-wise comparison of corresponding
arguments.** Everything a relational proof needs to know about `Ty`'s constructors, in one
statement: the exceptional rules are excluded by the four hypotheses, and the congruence
arms are the right-hand side. The two directions above are the proof, and neither names a
constructor: a new one adds an arm lemma and a `case`, both generated. -/
theorem sub_eq_args (a b : Ty) (ha : isMember a = true) (hb : isMember b = true)
    (hlit : litRule a b = false) (htop : topRule a b = false) :
    sub a b = (sameHead a b && argsBelow sub a b) := by
  cases hh : sameHead a b
  · rw [Bool.false_and]
    exact sub_eq_false_of_not_sameHead a b ha hb hlit htop hh
  · rw [Bool.true_and]
    exact sub_eq_argsBelow_of_sameHead a b hh

/-- A child is smaller: the termination measure of every relational law. One arm per
constructor, so the script names no shape it was not given. -/
theorem sizeOf_args {t : Ty} {v : Variance} {x : Ty} (h : (v, x) ∈ t.args) :
    sizeOf x < sizeOf t := by
  cases t
  case never => simp only [args, List.not_mem_nil] at h
  case unit => simp only [args, List.not_mem_nil] at h
  case nat => simp only [args, List.not_mem_nil] at h
  case int => simp only [args, List.not_mem_nil] at h
  case string => simp only [args, List.not_mem_nil] at h
  case bool => simp only [args, List.not_mem_nil] at h
  case handle target => simp only [args, List.not_mem_nil] at h
  case option inner =>
    simp only [args, List.mem_cons, List.not_mem_nil, or_false, Prod.mk.injEq] at h
    rcases h with ⟨-, rfl⟩; simp only [Ty.option.sizeOf_spec]; omega
  case list inner =>
    simp only [args, List.mem_cons, List.not_mem_nil, or_false, Prod.mk.injEq] at h
    rcases h with ⟨-, rfl⟩; simp only [Ty.list.sizeOf_spec]; omega
  case prod left right =>
    simp only [args, List.mem_cons, List.not_mem_nil, or_false, Prod.mk.injEq] at h
    rcases h with ⟨-, rfl⟩ | ⟨-, rfl⟩ <;> simp only [Ty.prod.sizeOf_spec] <;> omega
  case except error value =>
    simp only [args, List.mem_cons, List.not_mem_nil, or_false, Prod.mk.injEq] at h
    rcases h with ⟨-, rfl⟩ | ⟨-, rfl⟩ <;> simp only [Ty.except.sizeOf_spec] <;> omega
  case exitOf value error =>
    simp only [args, List.mem_cons, List.not_mem_nil, or_false, Prod.mk.injEq] at h
    rcases h with ⟨-, rfl⟩ | ⟨-, rfl⟩ <;> simp only [Ty.exitOf.sizeOf_spec] <;> omega
  case causeOf error =>
    simp only [args, List.mem_cons, List.not_mem_nil, or_false, Prod.mk.injEq] at h
    rcases h with ⟨-, rfl⟩; simp only [Ty.causeOf.sizeOf_spec]; omega
  case fiberOf value error =>
    simp only [args, List.mem_cons, List.not_mem_nil, or_false, Prod.mk.injEq] at h
    rcases h with ⟨-, rfl⟩ | ⟨-, rfl⟩ <;> simp only [Ty.fiberOf.sizeOf_spec] <;> omega
  case union left right =>
    simp only [args, List.mem_cons, List.not_mem_nil, or_false, Prod.mk.injEq] at h
    rcases h with ⟨-, rfl⟩ | ⟨-, rfl⟩ <;> simp only [Ty.union.sizeOf_spec] <;> omega
  case lit value => simp only [args, List.not_mem_nil] at h
  case refOf value =>
    simp only [args, List.mem_cons, List.not_mem_nil, or_false, Prod.mk.injEq] at h
    rcases h with ⟨-, rfl⟩; simp only [Ty.refOf.sizeOf_spec]; omega
  case deferredOf value error =>
    simp only [args, List.mem_cons, List.not_mem_nil, or_false, Prod.mk.injEq] at h
    rcases h with ⟨-, rfl⟩ | ⟨-, rfl⟩ <;> simp only [Ty.deferredOf.sizeOf_spec] <;> omega
  case var index => simp only [args, List.not_mem_nil] at h
  case unknown => simp only [args, List.not_mem_nil] at h

/-! ### The order's two generic steps -/

/-- Composition at each variance under a measure: the composed pair is read at the same
triple, whichever way round the variance turns it, so one bound serves every arm. -/
theorem Variance.holds_trans_of {r : Ty → Ty → Bool} (v : Variance) {x y z : Ty} {m : Nat}
    (hm : sizeOf x + sizeOf y + sizeOf z < m)
    (htrans : ∀ p q s, sizeOf p + sizeOf q + sizeOf s < m →
      r p q = true → r q s = true → r p s = true)
    (h : v.holds r x y = true) (h' : v.holds r y z = true) : v.holds r x z = true := by
  cases v
  case co => exact htrans x y z hm h h'
  case contra => exact htrans z y x (by omega) h' h
  case inv =>
    simp only [Variance.holds, Bool.and_eq_true_iff] at h h' ⊢
    exact ⟨htrans x y z hm h.1 h'.1, htrans z y x (by omega) h'.2 h.2⟩

/-- The list step of `argsBelow_trans`: corresponding positions compose, position by
position, with the variance carried by the first list (the second and third agree with it). -/
private theorem zipAll_trans {r : Ty → Ty → Bool} :
    ∀ (xs ys zs : List (Variance × Ty)),
      xs.map Prod.fst = ys.map Prod.fst → ys.map Prod.fst = zs.map Prod.fst →
      (∀ x ∈ xs, ∀ y ∈ ys, ∀ z ∈ zs, ∀ v : Variance,
        v.holds r x.2 y.2 = true → v.holds r y.2 z.2 = true → v.holds r x.2 z.2 = true) →
      (xs.zip ys).all (fun p => p.1.1.holds r p.1.2 p.2.2) = true →
      (ys.zip zs).all (fun p => p.1.1.holds r p.1.2 p.2.2) = true →
      (xs.zip zs).all (fun p => p.1.1.holds r p.1.2 p.2.2) = true
  | [], _, _, _, _, _, _, _ => rfl
  | _ :: _, [], _, h1, _, _, _, _ => by
    simp only [List.map_cons, List.map_nil] at h1
    exact absurd h1 (List.cons_ne_nil _ _)
  | _ :: _, _ :: _, [], _, h2, _, _, _ => by
    simp only [List.map_cons, List.map_nil] at h2
    exact absurd h2 (List.cons_ne_nil _ _)
  | x :: xs, y :: ys, z :: zs, h1, h2, hstep, hxy, hyz => by
    simp only [List.map_cons, List.cons.injEq] at h1 h2
    simp only [List.zip_cons_cons, List.all_cons, Bool.and_eq_true_iff] at hxy hyz ⊢
    refine ⟨?_, ?_⟩
    · refine hstep x List.mem_cons_self y List.mem_cons_self z List.mem_cons_self x.1 hxy.1 ?_
      rw [h1.1]
      exact hyz.1
    · exact zipAll_trans xs ys zs h1.2 h2.2
        (fun a ha b hb c hc => hstep a (List.mem_cons_of_mem _ ha) b (List.mem_cons_of_mem _ hb)
          c (List.mem_cons_of_mem _ hc))
        hxy.2 hyz.2

/-- **The order's transitive step, once.** At a common head the variance-wise comparison
composes, given transitivity at every strictly smaller triple — which is exactly the
induction hypothesis a proof by the triple measure has. No constructor is named. -/
theorem argsBelow_trans {r : Ty → Ty → Bool} {a b c : Ty}
    (hab : sameHead a b = true) (hbc : sameHead b c = true)
    (htrans : ∀ x y z, sizeOf x + sizeOf y + sizeOf z < sizeOf a + sizeOf b + sizeOf c →
      r x y = true → r y z = true → r x z = true)
    (h1 : argsBelow r a b = true) (h2 : argsBelow r b c = true) :
    argsBelow r a c = true := by
  refine zipAll_trans a.args b.args c.args (args_congr hab).2 (args_congr hbc).2 ?_ h1 h2
  intro x hx y hy z hz v
  refine Variance.holds_trans_of v ?_ htrans
  have hxa : sizeOf x.2 < sizeOf a := sizeOf_args hx
  have hyb : sizeOf y.2 < sizeOf b := sizeOf_args hy
  have hzc : sizeOf z.2 < sizeOf c := sizeOf_args hz
  omega

/-- The list step of `argsBelow_antisymm`. -/
private theorem zipAll_antisymm {r : Ty → Ty → Bool} :
    ∀ (xs ys : List (Variance × Ty)),
      xs.map Prod.fst = ys.map Prod.fst →
      (∀ x ∈ xs, ∀ y ∈ ys, r x.2 y.2 = true → r y.2 x.2 = true → x.2 = y.2) →
      (xs.zip ys).all (fun p => p.1.1.holds r p.1.2 p.2.2) = true →
      (ys.zip xs).all (fun p => p.1.1.holds r p.1.2 p.2.2) = true →
      xs.map Prod.snd = ys.map Prod.snd
  | [], [], _, _, _, _ => rfl
  | _ :: _, [], h, _, _, _ => by
    simp only [List.map_cons, List.map_nil] at h
    exact absurd h (List.cons_ne_nil _ _)
  | [], _ :: _, h, _, _, _ => by
    simp only [List.map_cons, List.map_nil] at h
    exact absurd h.symm (List.cons_ne_nil _ _)
  | x :: xs, y :: ys, h, hstep, hxy, hyx => by
    simp only [List.map_cons, List.cons.injEq] at h
    simp only [List.zip_cons_cons, List.all_cons, Bool.and_eq_true_iff] at hxy hyx
    simp only [List.map_cons, List.cons.injEq]
    refine ⟨?_, zipAll_antisymm xs ys h.2
      (fun a ha b hb => hstep a (List.mem_cons_of_mem _ ha) b (List.mem_cons_of_mem _ hb))
      hxy.2 hyx.2⟩
    have hback : x.1.holds r y.2 x.2 = true := by rw [h.1]; exact hyx.1
    obtain ⟨hf, hb⟩ := Variance.holds_antisymm x.1 hxy.1 hback
    exact hstep x List.mem_cons_self y List.mem_cons_self hf hb

/-- A child of the node, read through `args.map Prod.snd`: the shape every consumer of
the two steps below has, and the one `sizeOf_args` is applied at. -/
theorem sizeOf_args_mem {t x : Ty} (h : x ∈ t.args.map Prod.snd) : sizeOf x < sizeOf t := by
  obtain ⟨p, hp, rfl⟩ := List.mem_map.mp h
  exact sizeOf_args hp

/-- **The order's antisymmetric step, once.** At a common head, two-sided comparison makes
the children agree; `eq_of_sameHead` then makes the nodes agree.

Its element step is stated over MEMBERSHIP where `argsBelow_trans`'s is stated over the
measure, and the difference is not a slip. Transitivity composes, and at a contravariant
or invariant position it composes the triple the other way round, so no membership
hypothesis it could be given covers both directions while a symmetric measure does.
Antisymmetry does not compose: its element step is a predicate at one pair, and a caller
that carries a side condition on the children (normality, closedness) needs the
membership to discharge it. Each is the weakest hypothesis that does its own job, and
membership gives the measure back through `sizeOf_args_mem`. -/
theorem argsBelow_antisymm {r : Ty → Ty → Bool} {a b : Ty} (hab : sameHead a b = true)
    (heq : ∀ x ∈ a.args.map Prod.snd, ∀ y ∈ b.args.map Prod.snd,
      r x y = true → r y x = true → x = y)
    (h1 : argsBelow r a b = true) (h2 : argsBelow r b a = true) : a = b := by
  refine eq_of_sameHead hab (zipAll_antisymm a.args b.args (args_congr hab).2 ?_ h1 h2)
  intro x hx y hy hxy hyx
  exact heq x.2 (List.mem_map_of_mem hx) y.2 (List.mem_map_of_mem hy) hxy hyx

/-! ### The two rules beside the congruences, as inversions -/

/-- The top is the only right-hand side the top rule fires at. -/
theorem topRule_eq_false {a b : Ty} (h : b ≠ .unknown) : topRule a b = false := by
  cases b
  case unknown => exact absurd rfl h
  all_goals rfl

/-- The literal rule fires only into `string`. -/
theorem litRule_eq_false {a b : Ty} (h : b ≠ .string) : litRule a b = false := by
  cases b
  case string => exact absurd rfl h
  all_goals cases a <;> rfl

/-- At a head with no children, `sameHead` IS equality: a node is its head and its children,
and there are none. -/
theorem eq_of_sameHead_nil {a b : Ty} (h : sameHead a b = true) (hx : a.args = []) : a = b := by
  have hlen := (args_congr h).1
  rw [hx, List.length_nil] at hlen
  have hb : b.args = [] := List.eq_nil_of_length_eq_zero hlen.symm
  exact eq_of_sameHead h (by rw [hx, hb])

/-- The literal rule fires at exactly one pair of shapes. -/
theorem litRule_eq_true {a b : Ty} (h : litRule a b = true) :
    ∃ s, a = .lit s ∧ b = .string := by
  cases a
  case lit s =>
    cases b
    case string => exact ⟨s, rfl, rfl⟩
    all_goals exact Bool.noConfusion h
  all_goals exact Bool.noConfusion h

/-- …so it does not fire whenever either side is known not to be that shape. -/
theorem litRule_eq_false_of_head {a b : Ty} (h : ¬ ∃ s, a = .lit s ∧ b = .string) :
    litRule a b = false := by
  cases hl : litRule a b
  · rfl
  · exact absurd (litRule_eq_true hl) h

end Ty

/-- A value-admission carrier: a predicate on a value and an allocation table.
`Val.hasTy` at a fixed type is one (`Folds/Ty.lean`'s `fold_of`). -/
abbrev Adm := Effect4.Machine.Val → List String → Bool

/-- The pointwise order: `p` admits no more than `q`. -/
def Adm.le (p q : Adm) : Prop := ∀ v al, p v al = true → q v al = true

theorem Adm.le_refl (p : Adm) : Adm.le p p := fun _ _ h => h

theorem Adm.le_trans {p q r : Adm} (h : Adm.le p q) (h' : Adm.le q r) : Adm.le p r :=
  fun v al hv => h' v al (h v al hv)

/-- The algebra's carrier as `fold_of` builds it: the node rebuilt beside its result
(a paramorphism, `FoldOf.lean`). -/
abbrev AdmCarrier : TyFam → Type := fun fam => TyFam.rec (Ty × Adm) fam

/-- **One field per constructor**: what an admission algebra must satisfy for its fold to
respect `sub`. The empty union admits nothing and the top admits everything; a union is
the disjunction of its members; the literal rule is an inclusion; a covariant argument is
monotone, a contravariant one antitone, and an invariant one is IGNORED — which is
decisions row 44 (a handle is coarse by kind; the world's tables type what it holds)
stated as a law. A new constructor adds a field here and one line to each instance, at a
place the compiler names. -/
structure AdmitsSub (alg : TyAlgebra AdmCarrier) : Prop where
  /-- the empty union admits nothing -/
  never : ∀ v al, (alg.ty_never).2 v al = false
  /-- a union is the disjunction of its members -/
  union : ∀ p q v al, (alg.ty_union p q).2 v al = ((p.2 v al) || (q.2 v al))
  /-- the top admits everything (decisions row 46) -/
  top : ∀ v al, (alg.ty_unknown).2 v al = true
  /-- the literal rule -/
  lit_string : ∀ s, Adm.le (alg.ty_lit s).2 (alg.ty_string).2
  /-- a template parameter has no inhabitant -/
  var : ∀ i v al, (alg.ty_var i).2 v al = false
  /-- argument 0 co (vendor/effect-4.0.0-rc.112/src/Option.ts:55) -/
  option : ∀ p0 q0, Adm.le (p0).2 (q0).2 → Adm.le (alg.ty_option p0).2 (alg.ty_option q0).2
  /-- argument 0 co (ReadonlyArray<A>) -/
  list : ∀ p0 q0, Adm.le (p0).2 (q0).2 → Adm.le (alg.ty_list p0).2 (alg.ty_list q0).2
  /-- argument 0 co, argument 1 co (readonly [A, B]) -/
  prod : ∀ p0 p1 q0 q1, Adm.le (p0).2 (q0).2 → Adm.le (p1).2 (q1).2 → Adm.le (alg.ty_prod p0 p1).2 (alg.ty_prod q0 q1).2
  /-- argument 0 co, argument 1 co (Result.Result<A, E>) -/
  except : ∀ p0 p1 q0 q1, Adm.le (p0).2 (q0).2 → Adm.le (p1).2 (q1).2 → Adm.le (alg.ty_except p0 p1).2 (alg.ty_except q0 q1).2
  /-- argument 0 co, argument 1 co (vendor/effect-4.0.0-rc.112/src/Exit.ts:59) -/
  exitOf : ∀ p0 p1 q0 q1, Adm.le (p0).2 (q0).2 → Adm.le (p1).2 (q1).2 → Adm.le (alg.ty_exitOf p0 p1).2 (alg.ty_exitOf q0 q1).2
  /-- argument 0 co (vendor/effect-4.0.0-rc.112/src/Cause.ts:75) -/
  causeOf : ∀ p0 q0, Adm.le (p0).2 (q0).2 → Adm.le (alg.ty_causeOf p0).2 (alg.ty_causeOf q0).2
  /-- argument 0 co, argument 1 co (vendor/effect-4.0.0-rc.112/src/Fiber.ts:70) -/
  fiberOf : ∀ p0 p1 q0 q1, Adm.le (p0).2 (q0).2 → Adm.le (p1).2 (q1).2 → Adm.le (alg.ty_fiberOf p0 p1).2 (alg.ty_fiberOf q0 q1).2
  /-- argument 0 inv (vendor/effect-4.0.0-rc.112/src/Ref.ts:59) -/
  refOf : ∀ p0 q0, (alg.ty_refOf p0).2 = (alg.ty_refOf q0).2
  /-- argument 0 inv, argument 1 inv (vendor/effect-4.0.0-rc.112/src/Deferred.ts:58) -/
  deferredOf : ∀ p0 p1 q0 q1, (alg.ty_deferredOf p0 p1).2 = (alg.ty_deferredOf q0 q1).2

end Effect4.Program

/-! ## Acceptance guards for the generated relational view of `Ty`

Appended verbatim by `--append tools/Effect4Gen/guards/tyview.lean` into
`src/Effect4/Laws/Program/TyView.lean`.

The variance probes above are emitted per head from `tools/Effect4Gen/variances.json`; these
guards are the view's own contract, and they do not depend on which constructors exist:

1. `sub_eq_args` holds at named pairs that exercise each variance, so the law is exercised as a
   computation and not only as a theorem.
2. The four hypotheses are each necessary: dropping any one of them makes the two sides differ
   at a named counterexample (`never`, `union`, the literal rule, the top).
3. `sameHead` is an equivalence on members, and `union` is outside it.
4. `eq_of_sameHead` and `args_congr` at a pair the printer's corpus actually carries.
-/

namespace TyViewAcceptance

open Effect4.Program Effect4.Program.Ty

/-! ### 1. The law, computed -/

private def lhs (a b : Ty) : Bool := Ty.sub a b
private def rhs (a b : Ty) : Bool := Ty.sameHead a b && Ty.argsBelow Ty.sub a b

-- covariant: `option`, `list`, `causeOf`, and the two-argument covariant heads
#guard lhs (.option (.lit "a")) (.option .string) = rhs (.option (.lit "a")) (.option .string)
#guard lhs (.list .nat) (.list .string) = rhs (.list .nat) (.list .string)
#guard lhs (.fiberOf (.lit "a") .never) (.fiberOf .string .string)
  = rhs (.fiberOf (.lit "a") .never) (.fiberOf .string .string)
-- invariant: the cell and promise handles (decisions row 55)
#guard lhs (.refOf (.lit "a")) (.refOf .string) = rhs (.refOf (.lit "a")) (.refOf .string)
#guard lhs (.refOf .string) (.refOf .string) = rhs (.refOf .string) (.refOf .string)
#guard lhs (.deferredOf .nat .string) (.deferredOf .nat .string)
  = rhs (.deferredOf .nat .string) (.deferredOf .nat .string)
-- different heads, and different payloads at the same head
#guard lhs (.option .nat) (.list .nat) = rhs (.option .nat) (.list .nat)
#guard lhs (.handle "A") (.handle "B") = rhs (.handle "A") (.handle "B")
#guard lhs (.lit "a") (.lit "b") = rhs (.lit "a") (.lit "b")
#guard lhs (.var 0) (.var 1) = rhs (.var 0) (.var 1)

/-! ### 2. Each hypothesis is necessary

Every line below is a pair where the two sides of `sub_eq_args` DISAGREE, and the hypothesis
that excludes it. Without them the law would be false, so these are what the four arguments
are for. -/

-- `isMember a`: `never` is below everything, and has no head
#guard Ty.isMember .never = false
#guard lhs .never .nat != rhs .never .nat
-- `isMember b`: a union on the right is a choice, not a congruence
#guard Ty.isMember (.union .nat .string) = false
#guard lhs .nat (.union .nat .string) != rhs .nat (.union .nat .string)
-- `litRule`: a literal is below `string` with no head in common
#guard Ty.litRule (.lit "a") .string = true
#guard lhs (.lit "a") .string != rhs (.lit "a") .string
-- `topRule`: everything is below the top (decisions row 46)
#guard Ty.topRule .nat .unknown = true
#guard lhs .nat .unknown != rhs .nat .unknown

/-! ### 3. `sameHead` on members, and `union` outside it -/

#guard Ty.sameHead (.prod .nat .string) (.prod .string .nat)
#guard !Ty.sameHead (.union .nat .string) (.union .nat .string)
#guard !Ty.sameHead (.prod .nat .string) (.except .nat .string)
#guard Ty.sameHead (.handle "Scope.Scope") (.handle "Scope.Scope")

example (t : Ty) (h : Ty.isMember t = true) : Ty.sameHead t t = true := Ty.sameHead_refl t h
example {a b : Ty} (h : Ty.sameHead a b = true) : Ty.sameHead b a = true := Ty.sameHead_symm h
example {a b c : Ty} (h : Ty.sameHead a b = true) (h' : Ty.sameHead b c = true) :
    Ty.sameHead a c = true := Ty.sameHead_trans h h'

/-! ### 4. The node is its head and its children -/

example {a b : Ty} (h : Ty.sameHead a b = true)
    (hx : a.args.map Prod.snd = b.args.map Prod.snd) : a = b := Ty.eq_of_sameHead h hx
example {a b : Ty} (h : Ty.sameHead a b = true) :
    a.args.length = b.args.length ∧ a.args.map Prod.fst = b.args.map Prod.fst := Ty.args_congr h
example {t : Ty} {v : Ty.Variance} {x : Ty} (h : (v, x) ∈ t.args) : sizeOf x < sizeOf t :=
  Ty.sizeOf_args h

#guard (Ty.prod .nat .string).args.map Prod.snd = [.nat, .string]
#guard (Ty.refOf .nat).args = [(.inv, .nat)]
#guard (Ty.fiberOf .nat .string).args.map Prod.fst = [.co, .co]
#guard (Ty.unknown).args = []

end TyViewAcceptance

