-- GENERATED by src/OCaml5/Tools/Describe.lean from the Lean environment. Do not edit.
import OCaml5.Ml.Reflect

namespace OCaml5.Ml.Derived.Layer
open OCaml5.Ml

def layerId : StructDesc where
  leanName := "LayerId"
  site := "Layer.lean:51"
  subst := []
  leanParams := []
  fields :=
    [{ leanName := "index", leanTy := .nm "Nat" }]

def memoMapId : StructDesc where
  leanName := "MemoMapId"
  site := "Layer.lean:56"
  subst := []
  leanParams := []
  fields :=
    [{ leanName := "index", leanTy := .nm "Nat" }]

def serviceKey : StructDesc where
  leanName := "ServiceKey"
  site := "Key.lean:68"
  subst := []
  leanParams := []
  fields :=
    [{ leanName := "name", leanTy := .nm "ServiceName" },
     { leanName := "service", leanTy := .nm "ServiceTypeCode" }]

def defect : InductiveDesc where
  leanName := "Defect"
  site := "Context.lean:777"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "notImplemented", args := [] },
     { leanName := "asyncFiber", args := [] },
     { leanName := "badName", args := [] },
     { leanName := "serviceNotFound", args := [{ leanName := "key", leanTy := .nm "ServiceKey" }] },
     { leanName := "unknownLayer", args := [{ leanName := "index", leanTy := .nm "Nat" }] }]

def contextUpdate : InductiveDesc where
  leanName := "ContextUpdate"
  site := "Context.lean:1002"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "setTo", args := [{ leanName := "context", leanTy := .nm "Ctx" }] },
     { leanName := "provide", args := [{ leanName := "that", leanTy := .nm "Ctx" }] },
     { leanName := "provideService", args := [{ leanName := "key", leanTy := .nm "ServiceKey" }, { leanName := "value", leanTy := .nm "Val" }] }]

def combineMode : InductiveDesc where
  leanName := "CombineMode"
  site := "Layer.lean:66"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "provide", args := [] },
     { leanName := "provideMerge", args := [] }]

def construction : InductiveDesc where
  leanName := "Construction"
  site := "Layer.lean:73"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "succeedContext", args := [{ leanName := "services", leanTy := .lst (.app "Prod" [.nm "ServiceKey", .nm "Val"]) }] },
     { leanName := "failWith", args := [{ leanName := "error", leanTy := .nm "Err" }] },
     { leanName := "acquire", args := [{ leanName := "services", leanTy := .lst (.app "Prod" [.nm "ServiceKey", .nm "Val"]) }, { leanName := "release", leanTy := .nm "Nat" }] },
     { leanName := "fromService", args := [{ leanName := "input", leanTy := .nm "ServiceKey" }, { leanName := "output", leanTy := .nm "ServiceKey" }] }]

def layerDesc : InductiveDesc where
  leanName := "LayerDesc"
  site := "Layer.lean:88"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "atom", args := [{ leanName := "construction", leanTy := .nm "Construction" }] },
     { leanName := "memoized", args := [{ leanName := "construction", leanTy := .nm "Construction" }] },
     { leanName := "childScope", args := [{ leanName := "inner", leanTy := .nm "LayerId" }] },
     { leanName := "fresh", args := [{ leanName := "inner", leanTy := .nm "LayerId" }] },
     { leanName := "provideWith", args := [{ leanName := "self", leanTy := .nm "LayerId" }, { leanName := "that", leanTy := .nm "LayerId" }, { leanName := "mode", leanTy := .nm "CombineMode" }] },
     { leanName := "mergeAll", args := [{ leanName := "layers", leanTy := .lst (.nm "LayerId") }] }]

def finName : InductiveDesc where
  leanName := "FinName"
  site := "Layer.lean:112"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "closeChildScope", args := [{ leanName := "scope", leanTy := .nm "Nat" }] },
     { leanName := "detachFromParent", args := [{ leanName := "parent", leanTy := .nm "Nat" }, { leanName := "key", leanTy := .nm "Nat" }] },
     { leanName := "closeChildOnFailure", args := [{ leanName := "scope", leanTy := .nm "Nat" }] },
     { leanName := "memoEntry", args := [{ leanName := "layer", leanTy := .nm "LayerId" }, { leanName := "memoMap", leanTy := .nm "MemoMapId" }] },
     { leanName := "memoDone", args := [{ leanName := "layer", leanTy := .nm "LayerId" }, { leanName := "memoMap", leanTy := .nm "MemoMapId" }] },
     { leanName := "restoreContext", args := [{ leanName := "prev", leanTy := .nm "Ctx" }] },
     { leanName := "scopedExit", args := [{ leanName := "prev", leanTy := .nm "Ctx" }, { leanName := "scope", leanTy := .nm "Nat" }] },
     { leanName := "closeScopeWith", args := [{ leanName := "scope", leanTy := .nm "Nat" }] },
     { leanName := "release", args := [{ leanName := "label", leanTy := .nm "Nat" }, { leanName := "fails", leanTy := .nm "Bool" }] },
     { leanName := "releaseWith", args := [{ leanName := "label", leanTy := .nm "Nat" }, { leanName := "captured", leanTy := .nm "Ctx" }] },
     { leanName := "interruptFiber", args := [{ leanName := "fiber", leanTy := .nm "FiberId" }, { leanName := "skipSelf", leanTy := .nm "Bool" }] }]

def syncOp : InductiveDesc where
  leanName := "SyncOp"
  site := "Layer.lean:142"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "scopeMake", args := [{ leanName := "strategy", leanTy := .nm "FinalizerStrategy" }] },
     { leanName := "scopeFork", args := [{ leanName := "parent", leanTy := .nm "Nat" }, { leanName := "strategy", leanTy := .nm "FinalizerStrategy" }] },
     { leanName := "scopeAdd", args := [{ leanName := "scope", leanTy := .nm "Nat" }, { leanName := "finalizer", leanTy := .nm "FinName" }] },
     { leanName := "scopeRemove", args := [{ leanName := "scope", leanTy := .nm "Nat" }, { leanName := "key", leanTy := .nm "Nat" }] },
     { leanName := "memoFork", args := [{ leanName := "parent", leanTy := .opt (.nm "MemoMapId") }] },
     { leanName := "memoGet", args := [{ leanName := "layer", leanTy := .nm "LayerId" }, { leanName := "memoMap", leanTy := .nm "MemoMapId" }] },
     { leanName := "memoBuild", args := [{ leanName := "layer", leanTy := .nm "LayerId" }, { leanName := "memoMap", leanTy := .nm "MemoMapId" }] },
     { leanName := "memoComplete", args := [{ leanName := "layer", leanTy := .nm "LayerId" }, { leanName := "memoMap", leanTy := .nm "MemoMapId" }, { leanName := "exit", leanTy := .nm "ExitV" }] },
     { leanName := "memoRelease", args := [{ leanName := "layer", leanTy := .nm "LayerId" }, { leanName := "memoMap", leanTy := .nm "MemoMapId" }] },
     { leanName := "deferredAwaitCleanup", args := [{ leanName := "cell", leanTy := .nm "DeferredKey" }, { leanName := "waiter", leanTy := .nm "FiberId" }, { leanName := "token", leanTy := .nm "Nat" }] }]

def progName : InductiveDesc where
  leanName := "ProgName"
  site := "Layer.lean:172"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "value", args := [{ leanName := "v", leanTy := .nm "Val" }] },
     { leanName := "failCause", args := [{ leanName := "cause", leanTy := .nm "CauseV" }] },
     { leanName := "getContext", args := [] },
     { leanName := "service", args := [{ leanName := "key", leanTy := .nm "ServiceKey" }] },
     { leanName := "setContextTo", args := [{ leanName := "context", leanTy := .nm "Ctx" }, { leanName := "body", leanTy := .nm "ProgName" }] },
     { leanName := "provideContext", args := [{ leanName := "context", leanTy := .nm "Ctx" }, { leanName := "body", leanTy := .nm "ProgName" }] },
     { leanName := "provideService", args := [{ leanName := "key", leanTy := .nm "ServiceKey" }, { leanName := "value", leanTy := .nm "Val" }, { leanName := "body", leanTy := .nm "ProgName" }] },
     { leanName := "scoped", args := [{ leanName := "body", leanTy := .nm "ProgName" }] },
     { leanName := "acquireRelease", args := [{ leanName := "acquire", leanTy := .nm "ProgName" }, { leanName := "release", leanTy := .nm "Nat" }, { leanName := "interruptible", leanTy := .nm "Bool" }] },
     { leanName := "acquireMasked", args := [{ leanName := "acquire", leanTy := .nm "ProgName" }, { leanName := "release", leanTy := .nm "Nat" }, { leanName := "captured", leanTy := .nm "Ctx" }, { leanName := "interruptible", leanTy := .nm "Bool" }] },
     { leanName := "addFinalizer", args := [{ leanName := "label", leanTy := .nm "Nat" }] },
     { leanName := "seq", args := [{ leanName := "first", leanTy := .nm "ProgName" }, { leanName := "second", leanTy := .nm "ProgName" }] },
     { leanName := "never", args := [] },
     { leanName := "closeScope", args := [{ leanName := "scope", leanTy := .nm "Nat" }, { leanName := "exit", leanTy := .nm "ExitV" }] },
     { leanName := "build", args := [{ leanName := "layer", leanTy := .nm "LayerId" }] },
     { leanName := "buildWithScope", args := [{ leanName := "layer", leanTy := .nm "LayerId" }, { leanName := "scope", leanTy := .nm "Nat" }] },
     { leanName := "buildWithMemoMap", args := [{ leanName := "layer", leanTy := .nm "LayerId" }, { leanName := "memoMap", leanTy := .nm "MemoMapId" }, { leanName := "scope", leanTy := .nm "Nat" }] },
     { leanName := "layerBuild", args := [{ leanName := "layer", leanTy := .nm "LayerId" }, { leanName := "memoMap", leanTy := .nm "MemoMapId" }, { leanName := "scope", leanTy := .nm "Nat" }] },
     { leanName := "buildAdding", args := [{ leanName := "layer", leanTy := .nm "LayerId" }, { leanName := "memoMap", leanTy := .nm "MemoMapId" }, { leanName := "scope", leanTy := .nm "Nat" }] },
     { leanName := "buildThenNever", args := [{ leanName := "layer", leanTy := .nm "LayerId" }] },
     { leanName := "launch", args := [{ leanName := "layer", leanTy := .nm "LayerId" }] },
     { leanName := "provideLayer", args := [{ leanName := "layer", leanTy := .nm "LayerId" }, { leanName := "isLocal", leanTy := .nm "Bool" }, { leanName := "body", leanTy := .nm "ProgName" }] },
     { leanName := "scopedWithAlloc", args := [{ leanName := "layer", leanTy := .nm "LayerId" }, { leanName := "isLocal", leanTy := .nm "Bool" }, { leanName := "body", leanTy := .nm "ProgName" }] },
     { leanName := "memoLookup", args := [{ leanName := "layer", leanTy := .nm "LayerId" }, { leanName := "memoMap", leanTy := .nm "MemoMapId" }, { leanName := "scope", leanTy := .nm "Nat" }, { leanName := "construction", leanTy := .nm "Construction" }] },
     { leanName := "finalizerOf", args := [{ leanName := "fin", leanTy := .nm "FinName" }, { leanName := "exit", leanTy := .nm "ExitV" }] },
     { leanName := "memoReleaseOf", args := [{ leanName := "layer", leanTy := .nm "LayerId" }, { leanName := "memoMap", leanTy := .nm "MemoMapId" }, { leanName := "exit", leanTy := .nm "ExitV" }] },
     { leanName := "releaseOf", args := [{ leanName := "label", leanTy := .nm "Nat" }] }]

def name : InductiveDesc where
  leanName := "Name"
  site := "Layer.lean:231"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "restore", args := [{ leanName := "exit", leanTy := .nm "ExitV" }] },
     { leanName := "merge", args := [{ leanName := "exit", leanTy := .nm "ExitV" }] },
     { leanName := "seq", args := [{ leanName := "next", leanTy := .nm "ProgName" }] },
     { leanName := "constant", args := [{ leanName := "value", leanTy := .nm "Val" }] },
     { leanName := "registerAwait", args := [{ leanName := "cell", leanTy := .nm "DeferredKey" }] },
     { leanName := "cancelAwait", args := [{ leanName := "cell", leanTy := .nm "DeferredKey" }] },
     { leanName := "neverRegister", args := [] },
     { leanName := "abortController", args := [] },
     { leanName := "cancelPark", args := [] },
     { leanName := "cancelRace", args := [{ leanName := "race", leanTy := .nm "Nat" }] },
     { leanName := "withWaiter", args := [{ leanName := "base", leanTy := .nm "Name" }, { leanName := "waiter", leanTy := .nm "FiberId" }, { leanName := "token", leanTy := .nm "Nat" }] },
     { leanName := "reFail", args := [{ leanName := "cause", leanTy := .nm "CauseV" }] },
     { leanName := "finalizerName", args := [{ leanName := "fin", leanTy := .nm "FinName" }] },
     { leanName := "closeSeq", args := [{ leanName := "remaining", leanTy := .lst (.nm "FinName") }, { leanName := "exit", leanTy := .nm "ExitV" }, { leanName := "captured", leanTy := .lst (.app "Reason" [.nm "Err", .nm "Defect", .nm "FiberId", .nm "Ann"]) }] },
     { leanName := "closePar", args := [{ leanName := "remaining", leanTy := .lst (.nm "FinName") }, { leanName := "exit", leanTy := .nm "ExitV" }, { leanName := "forked", leanTy := .lst (.nm "FiberId") }, { leanName := "closerInterruptible", leanTy := .nm "Bool" }] },
     { leanName := "mergeAwaitedExits", args := [] },
     { leanName := "afterScopeAdd", args := [{ leanName := "fin", leanTy := .nm "FinName" }] },
     { leanName := "updateThen", args := [{ leanName := "update", leanTy := .nm "ContextUpdate" }, { leanName := "body", leanTy := .nm "ProgName" }] },
     { leanName := "bodyThen", args := [{ leanName := "body", leanTy := .nm "ProgName" }, { leanName := "prev", leanTy := .nm "Ctx" }] },
     { leanName := "scopedThen", args := [{ leanName := "body", leanTy := .nm "ProgName" }] },
     { leanName := "scopedInstall", args := [{ leanName := "body", leanTy := .nm "ProgName" }, { leanName := "prev", leanTy := .nm "Ctx" }] },
     { leanName := "scopedBody", args := [{ leanName := "body", leanTy := .nm "ProgName" }, { leanName := "prev", leanTy := .nm "Ctx" }, { leanName := "scope", leanTy := .nm "Nat" }] },
     { leanName := "thenClose", args := [{ leanName := "scope", leanTy := .nm "Nat" }, { leanName := "exit", leanTy := .nm "ExitV" }] },
     { leanName := "serviceLookup", args := [{ leanName := "key", leanTy := .nm "ServiceKey" }] },
     { leanName := "bindService", args := [{ leanName := "output", leanTy := .nm "ServiceKey" }] },
     { leanName := "acquireWith", args := [{ leanName := "acquire", leanTy := .nm "ProgName" }, { leanName := "release", leanTy := .nm "Nat" }, { leanName := "interruptible", leanTy := .nm "Bool" }] },
     { leanName := "acquireInScope", args := [{ leanName := "acquire", leanTy := .nm "ProgName" }, { leanName := "release", leanTy := .nm "Nat" }, { leanName := "captured", leanTy := .nm "Ctx" }, { leanName := "interruptible", leanTy := .nm "Bool" }] },
     { leanName := "registerRelease", args := [{ leanName := "scope", leanTy := .nm "Nat" }, { leanName := "release", leanTy := .nm "Nat" }, { leanName := "captured", leanTy := .nm "Ctx" }] },
     { leanName := "addFinalizerOn", args := [{ leanName := "label", leanTy := .nm "Nat" }] },
     { leanName := "addFinalizerCaptured", args := [{ leanName := "scope", leanTy := .nm "Nat" }, { leanName := "label", leanTy := .nm "Nat" }] },
     { leanName := "buildFromContext", args := [{ leanName := "layer", leanTy := .nm "LayerId" }] },
     { leanName := "buildWithScopeFromContext", args := [{ leanName := "layer", leanTy := .nm "LayerId" }, { leanName := "scope", leanTy := .nm "Nat" }] },
     { leanName := "withMemoMapThen", args := [{ leanName := "layer", leanTy := .nm "LayerId" }, { leanName := "scope", leanTy := .opt (.nm "Nat") }] },
     { leanName := "addCurrentMemoMap", args := [{ leanName := "memoMap", leanTy := .nm "MemoMapId" }] },
     { leanName := "memoize", args := [{ leanName := "layer", leanTy := .nm "LayerId" }, { leanName := "memoMap", leanTy := .nm "MemoMapId" }, { leanName := "scope", leanTy := .nm "Nat" }, { leanName := "construction", leanTy := .nm "Construction" }] },
     { leanName := "awaitPromise", args := [{ leanName := "cell", leanTy := .nm "DeferredKey" }] },
     { leanName := "buildIntoLayerScope", args := [{ leanName := "layer", leanTy := .nm "LayerId" }, { leanName := "memoMap", leanTy := .nm "MemoMapId" }, { leanName := "scope", leanTy := .nm "Nat" }, { leanName := "construction", leanTy := .nm "Construction" }] },
     { leanName := "thenBuildInto", args := [{ leanName := "layer", leanTy := .nm "LayerId" }, { leanName := "memoMap", leanTy := .nm "MemoMapId" }, { leanName := "construction", leanTy := .nm "Construction" }, { leanName := "layerScope", leanTy := .nm "Nat" }] },
     { leanName := "closeIfLast", args := [{ leanName := "exit", leanTy := .nm "ExitV" }] },
     { leanName := "fromBuildThen", args := [{ leanName := "desc", leanTy := .nm "LayerDesc" }, { leanName := "self", leanTy := .nm "LayerId" }, { leanName := "memoMap", leanTy := .nm "MemoMapId" }] },
     { leanName := "freshThen", args := [{ leanName := "inner", leanTy := .nm "LayerId" }, { leanName := "scope", leanTy := .nm "Nat" }] },
     { leanName := "provideThen", args := [{ leanName := "self", leanTy := .nm "LayerId" }, { leanName := "memoMap", leanTy := .nm "MemoMapId" }, { leanName := "scope", leanTy := .nm "Nat" }, { leanName := "mode", leanTy := .nm "CombineMode" }] },
     { leanName := "combineWith", args := [{ leanName := "mode", leanTy := .nm "CombineMode" }, { leanName := "thatContext", leanTy := .nm "Ctx" }] },
     { leanName := "mergeChildren", args := [{ leanName := "layers", leanTy := .lst (.nm "LayerId") }, { leanName := "memoMap", leanTy := .nm "MemoMapId" }] },
     { leanName := "mergeForkOne", args := [{ leanName := "layer", leanTy := .nm "LayerId" }, { leanName := "rest", leanTy := .lst (.nm "LayerId") }, { leanName := "memoMap", leanTy := .nm "MemoMapId" }, { leanName := "parent", leanTy := .nm "Nat" }, { leanName := "forked", leanTy := .lst (.nm "FiberId") }] },
     { leanName := "mergeForkNext", args := [{ leanName := "rest", leanTy := .lst (.nm "LayerId") }, { leanName := "memoMap", leanTy := .nm "MemoMapId" }, { leanName := "parent", leanTy := .nm "Nat" }, { leanName := "forked", leanTy := .lst (.nm "FiberId") }] },
     { leanName := "mergeContexts", args := [] },
     { leanName := "provideLayerWith", args := [{ leanName := "layer", leanTy := .nm "LayerId" }, { leanName := "isLocal", leanTy := .nm "Bool" }, { leanName := "body", leanTy := .nm "ProgName" }] },
     { leanName := "provideLayerBody", args := [{ leanName := "body", leanTy := .nm "ProgName" }] }]

def actionName : InductiveDesc where
  leanName := "ActionName"
  site := "Layer.lean:339"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "fork", args := [{ leanName := "program", leanTy := .nm "ProgName" }, { leanName := "options", leanTy := .nm "Supervision.ForkOptions" }] },
     { leanName := "forkScoped", args := [{ leanName := "program", leanTy := .nm "ProgName" }, { leanName := "options", leanTy := .nm "Supervision.ForkOptions" }, { leanName := "key", leanTy := .nm "Nat" }] },
     { leanName := "interrupt", args := [{ leanName := "target", leanTy := .nm "FiberId" }] },
     { leanName := "interruptScoped", args := [{ leanName := "target", leanTy := .nm "FiberId" }] },
     { leanName := "awaitAll", args := [{ leanName := "targets", leanTy := .lst (.nm "FiberId") }] },
     { leanName := "awaitAllFailFast", args := [{ leanName := "targets", leanTy := .lst (.nm "FiberId") }] },
     { leanName := "setContext", args := [{ leanName := "context", leanTy := .nm "Ctx" }] },
     { leanName := "getContext", args := [] },
     { leanName := "getId", args := [] },
     { leanName := "closeScope", args := [{ leanName := "scope", leanTy := .nm "Nat" }, { leanName := "exit", leanTy := .nm "ExitV" }] },
     { leanName := "setInterruptible", args := [{ leanName := "body", leanTy := .nm "ProgName" }, { leanName := "flag", leanTy := .nm "Bool" }] },
     { leanName := "refuse", args := [{ leanName := "cause", leanTy := .nm "CauseV" }] },
     { leanName := "dropObservers", args := [{ leanName := "token", leanTy := .nm "Nat" }] }]

def thunk : InductiveDesc where
  leanName := "Thunk"
  site := "Layer.lean:359"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "act", args := [{ leanName := "action", leanTy := .nm "ActionName" }] },
     { leanName := "op", args := [{ leanName := "operation", leanTy := .nm "SyncOp" }] },
     { leanName := "body", args := [{ leanName := "program", leanTy := .nm "ProgName" }] }]

def scopeState : InductiveDesc where
  leanName := "ScopeState"
  site := "Scope.lean:67"
  subst := []
  leanParams := ["κ", "φ", "β", "ε", "δ", "ι", "α"]
  ctors :=
    [{ leanName := "empty", args := [] },
     { leanName := "openEmpty", args := [] },
     { leanName := "openInline", args := [{ leanName := "key", leanTy := .nm "κ" }, { leanName := "finalizer", leanTy := .nm "φ" }] },
     { leanName := "openMap", args := [{ leanName := "entries", leanTy := .lst (.app "Prod" [.nm "κ", .nm "φ"]) }] },
     { leanName := "closed", args := [{ leanName := "exit", leanTy := .app "Exit" [.nm "β", .nm "ε", .nm "δ", .nm "ι", .nm "α"] }] }]

def scope : StructDesc where
  leanName := "Scope"
  site := "Scope.lean:84"
  subst := []
  leanParams := ["κ", "φ", "β", "ε", "δ", "ι", "α"]
  fields :=
    [{ leanName := "strategy", leanTy := .nm "FinalizerStrategy" },
     { leanName := "state", leanTy := .app "ScopeState" [.nm "κ", .nm "φ", .nm "β", .nm "ε", .nm "δ", .nm "ι", .nm "α"] }]

def scopeEntry : StructDesc where
  leanName := "ScopeEntry"
  site := "Layer.lean:444"
  subst := []
  leanParams := []
  fields :=
    [{ leanName := "key", leanTy := .nm "Nat" },
     { leanName := "scope", leanTy := .nm "ScopeV" }]

def scopeStore : StructDesc where
  leanName := "ScopeStore"
  site := "Layer.lean:449"
  subst := []
  leanParams := []
  fields :=
    [{ leanName := "entries", leanTy := .lst (.nm "ScopeEntry") }]

def memoEntry : StructDesc where
  leanName := "MemoEntry"
  site := "Layer.lean:491"
  subst := []
  leanParams := []
  fields :=
    [{ leanName := "observers", leanTy := .nm "Nat" },
     { leanName := "effect", leanTy := .nm "Program" },
     { leanName := "layerScope", leanTy := .nm "Nat" },
     { leanName := "deferred", leanTy := .nm "DeferredKey" },
     { leanName := "finalizer", leanTy := .nm "FinName" }]

def memoMap : StructDesc where
  leanName := "MemoMap"
  site := "Layer.lean:505"
  subst := []
  leanParams := []
  fields :=
    [{ leanName := "id", leanTy := .nm "MemoMapId" },
     { leanName := "parent", leanTy := .opt (.nm "MemoMapId") },
     { leanName := "entries", leanTy := .lst (.app "Prod" [.nm "LayerId", .nm "MemoEntry"]) }]

def st : StructDesc where
  leanName := "St"
  site := "Layer.lean:619"
  subst := []
  leanParams := []
  fields :=
    [{ leanName := "memo", leanTy := .nm "MemoWorld" },
     { leanName := "scopes", leanTy := .nm "ScopeStore" },
     { leanName := "deferreds", leanTy := .nm "DeferredStore" },
     { leanName := "nextName", leanTy := .nm "Nat" }]

end OCaml5.Ml.Derived.Layer
