-- GENERATED by src/OCaml5/Tools/Describe.lean from the Lean environment. Do not edit.
import OCaml5.Ml.Reflect

namespace OCaml5.Ml.Derived.Stores
open OCaml5.Ml

def refKey : StructDesc where
  leanName := "RefKey"
  site := "Stores.lean:54"
  subst := []
  leanParams := []
  fields :=
    [{ leanName := "index", leanTy := .nm "Nat" }]

def deferredKey : StructDesc where
  leanName := "DeferredKey"
  site := "Stores.lean:61"
  subst := []
  leanParams := []
  fields :=
    [{ leanName := "index", leanTy := .nm "Nat" }]

def err : InductiveDesc where
  leanName := "Err"
  site := "Stores.lean:72"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "boom", args := [] },
     { leanName := "tag", args := [{ leanName := "code", leanTy := .nm "Nat" }] }]

def defect : InductiveDesc where
  leanName := "Defect"
  site := "Stores.lean:78"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "notImplemented", args := [] },
     { leanName := "asyncFiber", args := [] },
     { leanName := "badName", args := [] },
     { leanName := "missingService", args := [] },
     { leanName := "user", args := [{ leanName := "payload", leanTy := .nm "Nat" }] }]

def fnName : InductiveDesc where
  leanName := "FnName"
  site := "Stores.lean:96"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "incr", args := [] },
     { leanName := "double", args := [] },
     { leanName := "zeroWhenPositive", args := [] },
     { leanName := "noChange", args := [] },
     { leanName := "takeAndBump", args := [] }]

def finName : InductiveDesc where
  leanName := "FinName"
  site := "Stores.lean:112"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "interruptFiber", args := [{ leanName := "fiber", leanTy := .nm "FiberId" }, { leanName := "skipSelf", leanTy := .nm "Bool" }] },
     { leanName := "closeChildScope", args := [{ leanName := "scope", leanTy := .nm "Nat" }] },
     { leanName := "detachFromParent", args := [{ leanName := "parent", leanTy := .nm "Nat" }, { leanName := "key", leanTy := .nm "Nat" }] },
     { leanName := "release", args := [{ leanName := "label", leanTy := .nm "Nat" }, { leanName := "fails", leanTy := .nm "Bool" }] },
     { leanName := "awaitNewChildren", args := [{ leanName := "snapshot", leanTy := .lst (.nm "FiberId") }] },
     { leanName := "parkThen", args := [{ leanName := "slot", leanTy := .nm "Nat" }] }]

def ctx : StructDesc where
  leanName := "Ctx"
  site := "Stores.lean:135"
  subst := []
  leanParams := []
  fields :=
    [{ leanName := "ambientScope", leanTy := .opt (.nm "Nat") },
     { leanName := "maxOpsBeforeYield", leanTy := .nm "Nat" },
     { leanName := "preventYield", leanTy := .nm "Bool" }]

def completion : InductiveDesc where
  leanName := "Completion"
  site := "Stores.lean:187"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "ofExit", args := [{ leanName := "exit", leanTy := .nm "ExitV" }] },
     { leanName := "ofRefGet", args := [{ leanName := "cell", leanTy := .nm "RefKey" }] }]

def syncOp : InductiveDesc where
  leanName := "SyncOp"
  site := "Stores.lean:199"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "refMake", args := [{ leanName := "initial", leanTy := .nm "Val" }] },
     { leanName := "refGet", args := [{ leanName := "cell", leanTy := .nm "RefKey" }] },
     { leanName := "refSet", args := [{ leanName := "cell", leanTy := .nm "RefKey" }, { leanName := "value", leanTy := .nm "Val" }] },
     { leanName := "refGetAndSet", args := [{ leanName := "cell", leanTy := .nm "RefKey" }, { leanName := "value", leanTy := .nm "Val" }] },
     { leanName := "refSetAndGet", args := [{ leanName := "cell", leanTy := .nm "RefKey" }, { leanName := "value", leanTy := .nm "Val" }] },
     { leanName := "refUpdate", args := [{ leanName := "cell", leanTy := .nm "RefKey" }, { leanName := "f", leanTy := .nm "FnName" }] },
     { leanName := "refGetAndUpdate", args := [{ leanName := "cell", leanTy := .nm "RefKey" }, { leanName := "f", leanTy := .nm "FnName" }] },
     { leanName := "refUpdateAndGet", args := [{ leanName := "cell", leanTy := .nm "RefKey" }, { leanName := "f", leanTy := .nm "FnName" }] },
     { leanName := "refUpdateSome", args := [{ leanName := "cell", leanTy := .nm "RefKey" }, { leanName := "pf", leanTy := .nm "FnName" }] },
     { leanName := "refGetAndUpdateSome", args := [{ leanName := "cell", leanTy := .nm "RefKey" }, { leanName := "pf", leanTy := .nm "FnName" }] },
     { leanName := "refUpdateSomeAndGet", args := [{ leanName := "cell", leanTy := .nm "RefKey" }, { leanName := "pf", leanTy := .nm "FnName" }] },
     { leanName := "refModify", args := [{ leanName := "cell", leanTy := .nm "RefKey" }, { leanName := "f", leanTy := .nm "FnName" }] },
     { leanName := "refModifySome", args := [{ leanName := "cell", leanTy := .nm "RefKey" }, { leanName := "pf", leanTy := .nm "FnName" }] },
     { leanName := "deferredMake", args := [] },
     { leanName := "deferredIsDone", args := [{ leanName := "cell", leanTy := .nm "DeferredKey" }] },
     { leanName := "deferredPoll", args := [{ leanName := "cell", leanTy := .nm "DeferredKey" }] },
     { leanName := "deferredCompleteWith", args := [{ leanName := "cell", leanTy := .nm "DeferredKey" }, { leanName := "completion", leanTy := .nm "Completion" }] },
     { leanName := "deferredInterruptWith", args := [{ leanName := "cell", leanTy := .nm "DeferredKey" }, { leanName := "interruptor", leanTy := .nm "FiberId" }] },
     { leanName := "deferredAwaitCleanup", args := [{ leanName := "cell", leanTy := .nm "DeferredKey" }, { leanName := "waiter", leanTy := .nm "FiberId" }, { leanName := "token", leanTy := .nm "Nat" }] },
     { leanName := "scopeMake", args := [{ leanName := "strategy", leanTy := .nm "FinalizerStrategy" }] },
     { leanName := "scopeAdd", args := [{ leanName := "scope", leanTy := .nm "Nat" }, { leanName := "key", leanTy := .nm "Nat" }, { leanName := "finalizer", leanTy := .nm "FinName" }] },
     { leanName := "scopeRemove", args := [{ leanName := "scope", leanTy := .nm "Nat" }, { leanName := "key", leanTy := .nm "Nat" }] },
     { leanName := "scopeIsClosed", args := [{ leanName := "scope", leanTy := .nm "Nat" }] }]

def raceName : InductiveDesc where
  leanName := "RaceName"
  site := "Stores.lean:253"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "empty", args := [] },
     { leanName := "successThenSecond", args := [] },
     { leanName := "failThenSuccess", args := [] },
     { leanName := "failThenFail", args := [] },
     { leanName := "parkOnly", args := [] },
     { leanName := "parkThenSuccess", args := [] }]

def progName : InductiveDesc where
  leanName := "ProgName"
  site := "Stores.lean:277"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "value", args := [{ leanName := "v", leanTy := .nm "Val" }] },
     { leanName := "failCause", args := [{ leanName := "cause", leanTy := .nm "CauseV" }] },
     { leanName := "syncOp", args := [{ leanName := "op", leanTy := .nm "SyncOp" }] },
     { leanName := "yieldNow", args := [{ leanName := "priority", leanTy := .nm "Nat" }] },
     { leanName := "park", args := [{ leanName := "slot", leanTy := .nm "Nat" }] },
     { leanName := "awaitDeferred", args := [{ leanName := "cell", leanTy := .nm "DeferredKey" }] },
     { leanName := "intoDeferred", args := [{ leanName := "body", leanTy := .nm "ProgName" }, { leanName := "cell", leanTy := .nm "DeferredKey" }] },
     { leanName := "intoBody", args := [{ leanName := "body", leanTy := .nm "ProgName" }, { leanName := "cell", leanTy := .nm "DeferredKey" }] },
     { leanName := "maskedPark", args := [{ leanName := "slot", leanTy := .nm "Nat" }] },
     { leanName := "awaitFibers", args := [{ leanName := "targets", leanTy := .lst (.nm "FiberId") }] },
     { leanName := "finalizerOf", args := [{ leanName := "fin", leanTy := .nm "FinName" }, { leanName := "exit", leanTy := .nm "ExitV" }] },
     { leanName := "interruptDeferred", args := [{ leanName := "cell", leanTy := .nm "DeferredKey" }] },
     { leanName := "onExitOf", args := [{ leanName := "body", leanTy := .nm "ProgName" }, { leanName := "fin", leanTy := .nm "FinName" }, { leanName := "finalizerInterruptible", leanTy := .nm "Bool" }] },
     { leanName := "seqOf", args := [{ leanName := "first", leanTy := .nm "ProgName" }, { leanName := "second", leanTy := .nm "ProgName" }] },
     { leanName := "forkThen", args := [{ leanName := "child", leanTy := .nm "ProgName" }, { leanName := "options", leanTy := .nm "Supervision.ForkOptions" }, { leanName := "mode", leanTy := .nm "Supervision.ObserverMode" }] },
     { leanName := "forkOnly", args := [{ leanName := "child", leanTy := .nm "ProgName" }, { leanName := "options", leanTy := .nm "Supervision.ForkOptions" }] },
     { leanName := "forkInScope", args := [{ leanName := "child", leanTy := .nm "ProgName" }, { leanName := "options", leanTy := .nm "Supervision.ForkOptions" }, { leanName := "scope", leanTy := .nm "Nat" }, { leanName := "key", leanTy := .nm "Nat" }] },
     { leanName := "runInScope", args := [{ leanName := "target", leanTy := .nm "FiberId" }, { leanName := "scope", leanTy := .nm "Nat" }, { leanName := "key", leanTy := .nm "Nat" }] },
     { leanName := "forkScopedOf", args := [{ leanName := "child", leanTy := .nm "ProgName" }, { leanName := "options", leanTy := .nm "Supervision.ForkOptions" }, { leanName := "key", leanTy := .nm "Nat" }] },
     { leanName := "raceOf", args := [{ leanName := "race", leanTy := .nm "RaceName" }] },
     { leanName := "closeScopeOf", args := [{ leanName := "scope", leanTy := .nm "Nat" }, { leanName := "exit", leanTy := .nm "ExitV" }] },
     { leanName := "awaitAllNew", args := [{ leanName := "body", leanTy := .nm "ProgName" }] },
     { leanName := "interruptFibers", args := [{ leanName := "targets", leanTy := .lst (.nm "FiberId") }] },
     { leanName := "joinFiber", args := [{ leanName := "target", leanTy := .nm "FiberId" }, { leanName := "mode", leanTy := .nm "Supervision.ObserverMode" }] }]

def name : InductiveDesc where
  leanName := "Name"
  site := "Stores.lean:337"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "restore", args := [{ leanName := "exit", leanTy := .nm "ExitV" }] },
     { leanName := "merge", args := [{ leanName := "exit", leanTy := .nm "ExitV" }] },
     { leanName := "seq", args := [{ leanName := "next", leanTy := .nm "ProgName" }] },
     { leanName := "joinOn", args := [{ leanName := "mode", leanTy := .nm "Supervision.ObserverMode" }] },
     { leanName := "interruptWith", args := [{ leanName := "cell", leanTy := .nm "DeferredKey" }] },
     { leanName := "doneInto", args := [{ leanName := "cell", leanTy := .nm "DeferredKey" }] },
     { leanName := "constant", args := [{ leanName := "value", leanTy := .nm "Val" }] },
     { leanName := "exitOfValue", args := [] },
     { leanName := "snapshotThen", args := [{ leanName := "body", leanTy := .nm "ProgName" }] },
     { leanName := "registerAwait", args := [{ leanName := "cell", leanTy := .nm "DeferredKey" }] },
     { leanName := "cancelAwait", args := [{ leanName := "cell", leanTy := .nm "DeferredKey" }] },
     { leanName := "externalRegister", args := [{ leanName := "slot", leanTy := .nm "Nat" }] },
     { leanName := "abortController", args := [] },
     { leanName := "cancelPark", args := [] },
     { leanName := "cancelRace", args := [{ leanName := "race", leanTy := .nm "Nat" }] },
     { leanName := "withWaiter", args := [{ leanName := "base", leanTy := .nm "Name" }, { leanName := "waiter", leanTy := .nm "FiberId" }, { leanName := "token", leanTy := .nm "Nat" }] },
     { leanName := "reFail", args := [{ leanName := "cause", leanTy := .nm "CauseV" }] },
     { leanName := "finalizerName", args := [{ leanName := "fin", leanTy := .nm "FinName" }] },
     { leanName := "closeSeq", args := [{ leanName := "remaining", leanTy := .lst (.nm "FinName") }, { leanName := "exit", leanTy := .nm "ExitV" }, { leanName := "captured", leanTy := .lst (.app "Reason" [.nm "Err", .nm "Defect", .nm "FiberId", .nm "Ann"]) }] },
     { leanName := "closePar", args := [{ leanName := "remaining", leanTy := .lst (.nm "FinName") }, { leanName := "exit", leanTy := .nm "ExitV" }, { leanName := "forked", leanTy := .lst (.nm "FiberId") }, { leanName := "closerInterruptible", leanTy := .nm "Bool" }] },
     { leanName := "mergeAwaitedExits", args := [] }]

def actionName : InductiveDesc where
  leanName := "ActionName"
  site := "Stores.lean:398"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "fork", args := [{ leanName := "program", leanTy := .nm "ProgName" }, { leanName := "options", leanTy := .nm "Supervision.ForkOptions" }] },
     { leanName := "forkIn", args := [{ leanName := "program", leanTy := .nm "ProgName" }, { leanName := "options", leanTy := .nm "Supervision.ForkOptions" }, { leanName := "scope", leanTy := .nm "Nat" }, { leanName := "key", leanTy := .nm "Nat" }] },
     { leanName := "forkScoped", args := [{ leanName := "program", leanTy := .nm "ProgName" }, { leanName := "options", leanTy := .nm "Supervision.ForkOptions" }, { leanName := "key", leanTy := .nm "Nat" }] },
     { leanName := "runIn", args := [{ leanName := "target", leanTy := .nm "FiberId" }, { leanName := "scope", leanTy := .nm "Nat" }, { leanName := "key", leanTy := .nm "Nat" }] },
     { leanName := "interrupt", args := [{ leanName := "target", leanTy := .nm "FiberId" }] },
     { leanName := "interruptScoped", args := [{ leanName := "target", leanTy := .nm "FiberId" }] },
     { leanName := "interruptAll", args := [{ leanName := "targets", leanTy := .lst (.nm "FiberId") }, { leanName := "interruptor", leanTy := .opt (.nm "FiberId") }] },
     { leanName := "awaitAll", args := [{ leanName := "targets", leanTy := .lst (.nm "FiberId") }] },
     { leanName := "snapshotChildren", args := [] },
     { leanName := "awaitNewChildren", args := [{ leanName := "snapshot", leanTy := .lst (.nm "FiberId") }] },
     { leanName := "raceAll", args := [{ leanName := "race", leanTy := .nm "RaceName" }] },
     { leanName := "setContext", args := [{ leanName := "context", leanTy := .nm "Ctx" }] },
     { leanName := "getContext", args := [] },
     { leanName := "getId", args := [] },
     { leanName := "closeScope", args := [{ leanName := "scope", leanTy := .nm "Nat" }, { leanName := "exit", leanTy := .nm "ExitV" }] },
     { leanName := "setInterruptible", args := [{ leanName := "body", leanTy := .nm "ProgName" }, { leanName := "flag", leanTy := .nm "Bool" }] },
     { leanName := "refuse", args := [{ leanName := "cause", leanTy := .nm "CauseV" }] },
     { leanName := "dropObservers", args := [{ leanName := "token", leanTy := .nm "Nat" }] },
     { leanName := "cancelRace", args := [{ leanName := "race", leanTy := .nm "Nat" }] }]

def thunk : InductiveDesc where
  leanName := "Thunk"
  site := "Stores.lean:427"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "park", args := [{ leanName := "kind", leanTy := .nm "ParkKind" }] },
     { leanName := "act", args := [{ leanName := "action", leanTy := .nm "ActionName" }] },
     { leanName := "op", args := [{ leanName := "operation", leanTy := .nm "SyncOp" }] },
     { leanName := "body", args := [{ leanName := "program", leanTy := .nm "ProgName" }] }]

def finalizerStrategy : InductiveDesc where
  leanName := "FinalizerStrategy"
  site := "Scope.lean:37"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "sequential", args := [] },
     { leanName := "parallel", args := [] }]

def scopeState : InductiveDesc where
  leanName := "ScopeState"
  site := "Scope.lean:67"
  subst := []
  leanParams := ["κ", "φ", "β", "ε", "δ", "ι", "α"]
  ctors :=
    [{ leanName := "empty", args := [] },
     { leanName := "openEmpty", args := [] },
     { leanName := "openInline", args := [{ leanName := "key", leanTy := .nm "κ" }, { leanName := "finalizer", leanTy := .nm "φ" }] },
     { leanName := "openMap", args := [{ leanName := "entries", leanTy := .lst (.app "Prod" [.nm "κ", .nm "φ"]) }] },
     { leanName := "closed", args := [{ leanName := "exit", leanTy := .app "Exit" [.nm "β", .nm "ε", .nm "δ", .nm "ι", .nm "α"] }] }]

def scope : StructDesc where
  leanName := "Scope"
  site := "Scope.lean:84"
  subst := []
  leanParams := ["κ", "φ", "β", "ε", "δ", "ι", "α"]
  fields :=
    [{ leanName := "strategy", leanTy := .nm "FinalizerStrategy" },
     { leanName := "state", leanTy := .app "ScopeState" [.nm "κ", .nm "φ", .nm "β", .nm "ε", .nm "δ", .nm "ι", .nm "α"] }]

def deferredCell : StructDesc where
  leanName := "DeferredCell"
  site := "Stores.lean:678"
  subst := []
  leanParams := []
  fields :=
    [{ leanName := "completion", leanTy := .opt (.nm "Program") },
     { leanName := "waiters", leanTy := .lst (.app "Prod" [.nm "FiberId", .nm "Nat"]) }]

def deferredStore : StructDesc where
  leanName := "DeferredStore"
  site := "Stores.lean:687"
  subst := []
  leanParams := []
  fields :=
    [{ leanName := "cells", leanTy := .lst (.nm "DeferredCell") },
     { leanName := "due", leanTy := .lst (.app "Prod" [.nm "FiberId", .app "Prod" [.nm "Nat", .nm "Program"]]) }]

def scopeEntry : StructDesc where
  leanName := "ScopeEntry"
  site := "Stores.lean:885"
  subst := []
  leanParams := []
  fields :=
    [{ leanName := "key", leanTy := .nm "Nat" },
     { leanName := "scope", leanTy := .nm "ScopeV" }]

def scopeStore : StructDesc where
  leanName := "ScopeStore"
  site := "Stores.lean:893"
  subst := []
  leanParams := []
  fields :=
    [{ leanName := "entries", leanTy := .lst (.nm "ScopeEntry") }]

def stores : StructDesc where
  leanName := "Stores"
  site := "Stores.lean:1028"
  subst := []
  leanParams := []
  fields :=
    [{ leanName := "refs", leanTy := .nm "RefHeap" },
     { leanName := "deferreds", leanTy := .nm "DeferredStore" },
     { leanName := "scopes", leanTy := .nm "ScopeStore" },
     { leanName := "nextName", leanTy := .nm "Nat" }]

end OCaml5.Ml.Derived.Stores
