(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400123`, seed 400123, 34 operations.
   Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400123 () =
  let v0 = Fibers_fixture.fork 3 in
  let v1 = Fibers_fixture.fork 1 in
  let _v2 = Fibers_fixture.started () in
  let _v3 = Store_fixtures.layer_build 3 in
  let v4 = Store_fixtures.def_make () in
  ignore (Fibers_fixture.interrupt v1);
  let _v5 = Fibers_fixture.started () in
  let v6 = Store_fixtures.ref_make 10 in
  let _v7 = Fibers_fixture.join v0 in
  ignore (Store_fixtures.ref_update v6 9);
  let v8 = Fibers_fixture.fork 2 in
  let v9 = Store_fixtures.def_make () in
  let _v10 = Fibers_fixture.started () in
  let _v11 = Fibers_fixture.await_error v1 in
  let _v12 = Fibers_fixture.await_value v0 in
  ignore (Store_fixtures.ref_update v6 9);
  let _v13 = Store_fixtures.def_await_value v4 in
  let _v14 = Store_fixtures.layer_close () in
  let _v15 = Store_fixtures.layer_build 2 in
  ignore (Fibers_fixture.interrupt v1);
  let _v16 = Fibers_fixture.started () in
  ignore (Fibers_fixture.interrupt v0);
  let _v17 = Fibers_fixture.join v0 in
  let _v18 = Fibers_fixture.join v0 in
  ignore (Fibers_fixture.interrupt v8);
  let _v19 = Fibers_fixture.join v8 in
  let _v20 = Fibers_fixture.fork 2 in
  let _v21 = Fibers_fixture.fork 3 in
  let _v22 = Store_fixtures.def_poll v9 in
  let _v23 = Store_fixtures.def_is_done v9 in
  let _v24 = Store_fixtures.ref_modify v6 4 in
  let _v25 = Fibers_fixture.await_value v0 in
  let _v26 = Store_fixtures.def_is_done v9 in
  let v27 = Fibers_fixture.started () in
  v27

let programs : (string * (unit -> value)) list = [ ("p400123", corpus_p400123) ]
