import OCaml5.Eff.World

/-!
# OCaml5.Eff.Emit

**What it is.** The OCaml text of the `eff/` library, one function per generated file:
`emitTypes` (`eff_types.ml`), `emitWire` (`eff_wire.ml`: the canonical byte encoding and its
exact, length-directed decoder over the hand-written `Eff_frame`), `emitJson` (`eff_json.ml`),
`manifest` (`eff_manifest.txt`) and `emitNative` (`eff_native.ml`: the native alphabet as data,
with `checkAtoms` verifying the atom table against `nativeAtomTy` before anything is written).

**Depends on.** `OCaml5.Eff.World`.

**Properties.**
* **Bytes are the driver's contract.** `ocaml/eff/*.ml` are byte-identical to this output
  — *tested* (regenerate and `git diff`).
* **Every generated file says so** in its first line, with the regeneration command — *by
  construction* (`header`).
* **The wire is the Lean rule.** Constructor tag 10, the index as a `Nat` frame, the framing of
  `src/Effect4/Store/Canonical.lean` — *tested* (`ocaml/eff` goldens, `dune test`).
-/

open Lean Meta
open Effect4.Program
open Effect4.Supervision (MaskMode ForkOptions ObserverMode)
open Effect4 (FinalizerStrategy ServiceKey)
open Effect4.Machine (FnName)

namespace OCaml5.Eff

/-! ## Text helpers -/

def hex4 (n : Nat) : String :=
  let s := String.ofList (Nat.toDigits 16 n)
  "".pushn '0' (4 - s.length) ++ s

/-- A JSON string: `"` and `\` escaped, control characters as `\n \r \t \b \f` or `\u00XX`,
everything else verbatim. The OCaml renderer (`eff_json_text.ml`) follows the same rule byte
for byte. -/
def jsonStr (s : String) : String :=
  let esc (c : Char) : String :=
    if c == '"' then "\\\"" else if c == '\\' then "\\\\"
    else if c == '\n' then "\\n" else if c == '\r' then "\\r" else if c == '\t' then "\\t"
    else if c.toNat == 8 then "\\b" else if c.toNat == 12 then "\\f"
    else if c.toNat < 0x20 then "\\u" ++ hex4 c.toNat else c.toString
  "\"" ++ String.join (s.toList.map esc) ++ "\""

/-- An OCaml string literal. -/
def ostr (s : String) : String :=
  let esc (c : Char) : String :=
    if c == '"' then "\\\"" else if c == '\\' then "\\\\"
    else if c.toNat < 0x20 || c.toNat == 0x7f then
      let d := toString c.toNat
      "\\" ++ "".pushn '0' (3 - d.length) ++ d
    else c.toString
  "\"" ++ String.join (s.toList.map esc) ++ "\""

def header (what : String) : String :=
  "(* GENERATED by src/OCaml5/Tools/EffGen.lean — regenerate: lake env lean --run src/OCaml5/Tools/EffGen.lean <outdir>. Do not edit. *)\n" ++
  "(* " ++ what ++ " *)\n\n"

def ctorPat (oname : String) (c : Ctor) : String :=
  if c.args.isEmpty then octor oname c.short else octor oname c.short ++ " _"

def argNames (c : Ctor) : List String := (List.range c.args.length).map fun i => s!"a{i}"

def ctorPatNamed (oname : String) (c : Ctor) : String :=
  match c.args with
  | [] => octor oname c.short
  | [_] => octor oname c.short ++ " a0"
  | _ => octor oname c.short ++ " (" ++ ", ".intercalate (argNames c) ++ ")"

def ctorApp (oname : String) (c : Ctor) (args : List String) : String :=
  match args with
  | [] => octor oname c.short
  | [a] => octor oname c.short ++ " " ++ a
  | _ => octor oname c.short ++ " (" ++ ", ".intercalate args ++ ")"

/-! ## eff_types.ml -/

def emitTypeDecl (first : Bool) (f : Family) : String :=
  let kw := if first then "type" else "and"
  let o := f.spec.oname
  if f.isStruct then
    let c := f.ctors.head!
    let fields := c.args.map fun (nm, t) => "  " ++ ofield o nm ++ " : " ++ t.render ++ ";"
    kw ++ " " ++ o ++ " = {\n" ++ "\n".intercalate fields ++ "\n}\n"
  else
    let arms := f.ctors.map fun c =>
      if c.args.isEmpty then "  | " ++ octor o c.short
      else "  | " ++ octor o c.short ++ " of " ++ " * ".intercalate (c.args.map fun (_, t) => t.renderArg)
    kw ++ " " ++ o ++ " =\n" ++ "\n".intercalate arms ++ "\n"

def emitTypeTables (f : Family) : String :=
  let o := f.spec.oname
  if f.isStruct then
    let c := f.ctors.head!
    s!"let ctor_index_{o} (_ : {o}) : int = 0\n" ++
    s!"let ctor_name_{o} (_ : {o}) : string = {ostr c.short}\n" ++
    s!"let ctor_names_{o} : string list = [{ostr c.short}]\n" ++
    s!"let field_names_{o} : string list = [" ++ "; ".intercalate (c.args.map fun (nm, _) => ostr nm) ++ "]\n\n"
  else
    let idx := (enumL f.ctors).map fun (i, c) => s!"  | {ctorPat o c} -> {i}"
    let nms := f.ctors.map fun c => s!"  | {ctorPat o c} -> {ostr c.short}"
    s!"let ctor_index_{o} : {o} -> int = function\n" ++ "\n".intercalate idx ++ "\n" ++
    s!"let ctor_name_{o} : {o} -> string = function\n" ++ "\n".intercalate nms ++ "\n" ++
    s!"let ctor_names_{o} : string list = [" ++ "; ".intercalate (f.ctors.map fun c => ostr c.short) ++ "]\n\n"

def emitTypes (bs : List (List Family)) : String :=
  header "Eff_types: the Eff program IR of lean4-effect4 (src/Effect4/Program/{Eff,Native,Typing}.lean, Machine/Supervision.lean, Machine/Scope.lean, Machine/Stores.lean, Machine/Key.lean) as OCaml variants and records. Constructor order is the Lean declaration order and ctor_index_<t> is that order (by construction: read from InductiveVal.ctors). Constructors are named <Type>_<leanCtor>, record fields <type>_<leanField>. Lean Nat is OCaml int: values above max_int (2^62 - 1) have no carrier here." ++
  "\n".intercalate (bs.map fun b =>
    "\n".intercalate ((enumL b).map fun (i, f) => emitTypeDecl (i == 0) f) ++ "\n" ++
    String.join (b.map emitTypeTables))

/-! ## eff_wire.ml -/

partial def emitOf : OTy → String → String
  | .int, x => s!"Eff_frame.emit_nat b {x}"
  | .bool, x => s!"Eff_frame.emit_bool b {x}"
  | .string, x => s!"Eff_frame.emit_string b {x}"
  | .unit, x => s!"Eff_frame.emit_unit b {x}"
  | .option a, x => s!"Eff_frame.emit_option b (fun b y -> {emitOf a "y"}) {x}"
  | .list a, x => s!"Eff_frame.emit_list b (fun b y -> {emitOf a "y"}) {x}"
  | .prod a c, x => s!"Eff_frame.emit_pair b (fun b y -> {emitOf a "y"}) (fun b y -> {emitOf c "y"}) {x}"
  | .named n, x => s!"emit_{n} b {x}"

partial def decoderOf : OTy → String
  | .int => "Eff_frame.decode_nat"
  | .bool => "Eff_frame.decode_bool"
  | .string => "Eff_frame.decode_string"
  | .unit => "Eff_frame.decode_unit"
  | .option a => s!"(Eff_frame.decode_option {decoderOf a})"
  | .list a => s!"(Eff_frame.decode_list {decoderOf a})"
  | .prod a b => s!"(Eff_frame.decode_pair {decoderOf a} {decoderOf b})"
  | .named n => s!"decode_{n}"

def emitEmitter (first : Bool) (f : Family) : String :=
  let kw := if first then "let rec" else "and"
  let o := f.spec.oname
  if f.isStruct then
    let c := f.ctors.head!
    let body := "; ".intercalate (c.args.map fun (nm, t) => emitOf t s!"r.{ofield o nm}")
    let body := if c.args.isEmpty then "()" else body
    s!"{kw} emit_{o} (b : Buffer.t) (r : {o}) : unit =\n  Eff_frame.emit_ctor b 0 (fun b -> {body})\n"
  else
    let arms := (enumL f.ctors).map fun (i, c) =>
      let names := argNames c
      let body := "; ".intercalate ((c.args.zip names).map fun ((_, t), a) => emitOf t a)
      if c.args.isEmpty then s!"  | {octor o c.short} -> Eff_frame.emit_ctor b {i} (fun _ -> ())"
      else s!"  | {ctorPatNamed o c} -> Eff_frame.emit_ctor b {i} (fun b -> {body})"
    s!"{kw} emit_{o} (b : Buffer.t) (v : {o}) : unit =\n  match v with\n" ++ "\n".intercalate arms ++ "\n"

/-- The decoder arm of one constructor: the arguments decoded in order inside `[p, e)`, the
payload consumed exactly. -/
def decodeArm (i : Nat) (c : Ctor) (build : List String → String) : String :=
  let names := argNames c
  let rec nest (rest : List ((String × OTy) × String)) (depth : Nat) : String :=
    let pad := "".pushn ' ' (6 + 2 * depth)
    match rest with
    | [] => s!"{pad}if p = e then Some ({build names}, next) else None"
    | ((_, t), a) :: more =>
      s!"{pad}(match {decoderOf t} s p e with\n{pad} | None -> None\n{pad} | Some ({a}, p) ->\n" ++
      nest more (depth + 1) ++ ")"
  s!"    | {i} ->\n" ++ nest (c.args.zip names) 0

def emitDecoder (first : Bool) (f : Family) : String :=
  let kw := if first then "let rec" else "and"
  let o := f.spec.oname
  let arms :=
    if f.isStruct then
      let c := f.ctors.head!
      [decodeArm 0 c fun names =>
        if c.args.isEmpty then "()"
        else "{ " ++ "; ".intercalate ((c.args.zip names).map fun ((nm, _), a) => s!"{ofield o nm} = {a}") ++ " }"]
    else (enumL f.ctors).map fun (i, c) => decodeArm i c (ctorApp o c)
  s!"{kw} decode_{o} (s : string) (pos : int) (limit : int) : ({o} * int) option =\n" ++
  "  match Eff_frame.read_ctor s pos limit with\n  | None -> None\n  | Some (i, p, e, next) ->\n    (match i with\n" ++
  "\n".intercalate arms ++ "\n    | _ -> None)\n"

def emitWire (bs : List (List Family)) : String :=
  header "Eff_wire: the canonical bytes of every carrier of Eff_types, and the exact decoder. Rule (src/Effect4/Store/Canonical.lean): framed tag payload = tag :: be64 (length payload) ++ payload; Unit 9 [], Bool 1 [0|1], Nat 2 base-256 big-endian no leading zero, String 3 utf8, List 4 concat, none 6 [] / some 7 x, pair 5 a++b, constructor i of an inductive 10 (encode i ++ args), a structure as constructor 0 with its fields in order. Decoding is length-directed and exact: a wrong tag, a bad index, a non-canonical Nat, invalid UTF-8, a short or long payload, or (for the _exact forms) trailing bytes are refusals (by construction: every arm checks p = e; tested: goldens, property test). encode_<t> raises Invalid_argument on a negative int or a string that is not valid UTF-8 (values outside the Lean image)." ++
  "open Eff_types\n\n" ++
  "\n".intercalate (bs.map fun b =>
    String.join ((enumL b).map fun (i, f) => emitEmitter (i == 0) f) ++ "\n" ++
    String.join (b.map fun f => s!"let encode_{f.spec.oname} (v : {f.spec.oname}) : string = Eff_frame.to_string emit_{f.spec.oname} v\n") ++ "\n" ++
    String.join ((enumL b).map fun (i, f) => emitDecoder (i == 0) f) ++ "\n" ++
    String.join (b.map fun f =>
      s!"let decode_{f.spec.oname}_exact (s : string) : {f.spec.oname} option = Eff_frame.exact decode_{f.spec.oname} s\n")) ++
  "\n(* The top level: a program is an Eff over the native alphabet. *)\n" ++
  "let encode_program : eff -> string = encode_eff\n" ++
  "let decode_program : string -> (eff * int) option = fun s -> decode_eff s 0 (String.length s)\n" ++
  "let decode_program_exact : string -> eff option = decode_eff_exact\n"

/-! ## eff_json.ml -/

partial def jsonOf : OTy → String → String
  | .int, x => s!"Eff_json_text.Int {x}"
  | .bool, x => s!"Eff_json_text.Bool {x}"
  | .string, x => s!"Eff_json_text.String {x}"
  | .unit, _ => "Eff_json_text.Array []"
  | .option a, x => s!"(match {x} with None -> Eff_json_text.Null | Some y -> {jsonOf a "y"})"
  | .list a, x => s!"Eff_json_text.Array (List.map (fun y -> {jsonOf a "y"}) {x})"
  | .prod a c, x => s!"(let (y0, y1) = {x} in Eff_json_text.Array [{jsonOf a "y0"}; {jsonOf c "y1"}])"
  | .named n, x => s!"json_{n} {x}"

def emitJsonFn (first : Bool) (f : Family) : String :=
  let kw := if first then "let rec" else "and"
  let o := f.spec.oname
  if f.isStruct then
    let c := f.ctors.head!
    let fields := "; ".intercalate (c.args.map fun (nm, t) => s!"({ostr nm}, {jsonOf t s!"r.{ofield o nm}"})")
    s!"{kw} json_{o} (r : {o}) : Eff_json_text.t =\n  Eff_json_text.Object [{fields}]\n"
  else
    let arms := f.ctors.map fun c =>
      let names := argNames c
      let items := s!"Eff_json_text.String {ostr c.short}" :: (c.args.zip names).map fun ((_, t), a) => jsonOf t a
      s!"  | {ctorPatNamed o c} -> Eff_json_text.Array [{"; ".intercalate items}]"
    s!"{kw} json_{o} (v : {o}) : Eff_json_text.t =\n  match v with\n" ++ "\n".intercalate arms ++ "\n"

def emitJson (bs : List (List Family)) : String :=
  header "Eff_json: the JSON printer of every carrier of Eff_types (a printer only; there is no JSON parser). Rule: a constructor is [\"ctorName\", arg1, ...] with the Lean constructor name; a structure is {\"field\": value} with the Lean field names; lists are arrays; options null / value; unit []; pairs [a, b]; numbers, booleans and strings as themselves. Rendering (Eff_json_text.render) is compact, with the escaping stated there; the Lean side (EffGen.lean, V.json) prints the same bytes (tested: goldens)." ++
  "open Eff_types\n\n" ++
  "\n".intercalate (bs.map fun b =>
    String.join ((enumL b).map fun (i, f) => emitJsonFn (i == 0) f) ++ "\n" ++
    String.join (b.map fun f =>
      s!"let print_{f.spec.oname} (v : {f.spec.oname}) : string = Eff_json_text.render (json_{f.spec.oname} v)\n"))

/-! ## eff_manifest.txt -/

def manifest (bs : List (List Family)) : String :=
  String.join (bs.map fun b => String.join (b.map fun f =>
    let o := f.spec.oname
    if f.isStruct then
      let c := f.ctors.head!
      s!"{f.spec.leanName} ({o}) structure: " ++ " ".intercalate (c.args.map fun (nm, t) => s!"{nm}:{t.render}") ++ "\n"
    else
      s!"{f.spec.leanName} ({o}) inductive: " ++ " ".intercalate (f.ctors.map fun c =>
        if c.args.isEmpty then c.short
        else c.short ++ "(" ++ ",".intercalate (c.args.map fun (_, t) => t.render) ++ ")") ++ "\n"))

/-! ## eff_native.ml — the alphabet as data, rendered from Lean values -/

def tyO : Ty → String
  | .never => octor "ty" "never"
  | .unit => octor "ty" "unit"
  | .nat => octor "ty" "nat"
  | .int => octor "ty" "int"
  | .string => octor "ty" "string"
  | .bool => octor "ty" "bool"
  | .handle target => s!"({octor "ty" "handle"} {ostr target})"
  | .option inner => s!"({octor "ty" "option"} {tyO inner})"
  | .list inner => s!"({octor "ty" "list"} {tyO inner})"
  | .prod l r => s!"({octor "ty" "prod"} ({tyO l}, {tyO r}))"
  | .except e v => s!"({octor "ty" "except"} ({tyO e}, {tyO v}))"
  | .exitOf v e => s!"({octor "ty" "exitOf"} ({tyO v}, {tyO e}))"
  | .causeOf e => s!"({octor "ty" "causeOf"} {tyO e})"
  | .fiberOf v e => s!"({octor "ty" "fiberOf"} ({tyO v}, {tyO e}))"
  | .union l r => s!"({octor "ty" "union"} ({tyO l}, {tyO r}))"

def kindO : RowKind → String
  | .sync => octor "row_kind" "sync"
  | .async => octor "row_kind" "async"
  | .program => octor "row_kind" "program"

def shapeO : RowShape → String
  | .call => octor "row_shape" "call"
  | .value => octor "row_shape" "value"

def keyO (k : ServiceKey) : String :=
  "{ " ++ ofield "service_key" "name" ++ " = { " ++ ofield "service_name" "value" ++ " = " ++
  toString k.name.value ++ " }; " ++
  ofield "service_key" "service" ++ " = { " ++ ofield "service_type_code" "value" ++ " = " ++
  toString k.service.value ++ " } }"

def listO (xs : List String) : String := "[" ++ "; ".intercalate xs ++ "]"

def rowO (r : Row) : String :=
  "{ " ++ "; ".intercalate
    [ ofield "row" "name" ++ " = " ++ ostr r.name
    , ofield "row" "spelling" ++ " = " ++ ostr r.spelling
    , ofield "row" "shape" ++ " = " ++ shapeO r.shape
    , ofield "row" "trailing" ++ " = " ++ listO (r.trailing.map ostr)
    , ofield "row" "kind" ++ " = " ++ kindO r.kind
    , ofield "row" "request" ++ " = " ++ tyO r.request
    , ofield "row" "answer" ++ " = " ++ tyO r.answer
    , ofield "row" "error" ++ " = " ++ tyO r.error
    , ofield "row" "requires" ++ " = " ++ listO (r.requires.map keyO)
    , ofield "row" "cite" ++ " = " ++ ostr r.cite ] ++ " }"

def fnO : FnName → String
  | .incr => octor "fn_name" "incr"
  | .double => octor "fn_name" "double"
  | .zeroWhenPositive => octor "fn_name" "zeroWhenPositive"
  | .noChange => octor "fn_name" "noChange"
  | .takeAndBump => octor "fn_name" "takeAndBump"

def stratO : FinalizerStrategy → String
  | .sequential => octor "finalizer_strategy" "sequential"
  | .parallel => octor "finalizer_strategy" "parallel"

def opO : NativeOp → String
  | .refMake => octor "native_op" "refMake"
  | .refGet => octor "native_op" "refGet"
  | .refSet => octor "native_op" "refSet"
  | .refGetAndSet => octor "native_op" "refGetAndSet"
  | .refSetAndGet => octor "native_op" "refSetAndGet"
  | .refUpdate f => s!"({octor "native_op" "refUpdate"} {fnO f})"
  | .refGetAndUpdate f => s!"({octor "native_op" "refGetAndUpdate"} {fnO f})"
  | .refUpdateAndGet f => s!"({octor "native_op" "refUpdateAndGet"} {fnO f})"
  | .refUpdateSome f => s!"({octor "native_op" "refUpdateSome"} {fnO f})"
  | .refGetAndUpdateSome f => s!"({octor "native_op" "refGetAndUpdateSome"} {fnO f})"
  | .refUpdateSomeAndGet f => s!"({octor "native_op" "refUpdateSomeAndGet"} {fnO f})"
  | .refModify f => s!"({octor "native_op" "refModify"} {fnO f})"
  | .refModifySome f => s!"({octor "native_op" "refModifySome"} {fnO f})"
  | .deferredMake => octor "native_op" "deferredMake"
  | .deferredIsDone => octor "native_op" "deferredIsDone"
  | .deferredPoll => octor "native_op" "deferredPoll"
  | .deferredSucceed => octor "native_op" "deferredSucceed"
  | .deferredFail => octor "native_op" "deferredFail"
  | .deferredAwait => octor "native_op" "deferredAwait"
  | .scopeMake s => s!"({octor "native_op" "scopeMake"} {stratO s})"

def fnNames : List FnName := [.incr, .double, .zeroWhenPositive, .noChange, .takeAndBump]

/-- Every value of `NativeOp`, in declaration order, the parameterised constructors at every
argument. Its length is checked against the environment's constructor table in `main`. -/
def allOps : List NativeOp :=
  [.refMake, .refGet, .refSet, .refGetAndSet, .refSetAndGet] ++
  (fnNames.map NativeOp.refUpdate) ++ (fnNames.map NativeOp.refGetAndUpdate) ++
  (fnNames.map NativeOp.refUpdateAndGet) ++ (fnNames.map NativeOp.refUpdateSome) ++
  (fnNames.map NativeOp.refGetAndUpdateSome) ++ (fnNames.map NativeOp.refUpdateSomeAndGet) ++
  (fnNames.map NativeOp.refModify) ++ (fnNames.map NativeOp.refModifySome) ++
  [.deferredMake, .deferredIsDone, .deferredPoll, .deferredSucceed, .deferredFail, .deferredAwait] ++
  (FinalizerStrategy.all.map NativeOp.scopeMake)

/-- The monomorphic atoms of `nativeAtomTy`, as data: name, argument types, answer. -/
def monoAtoms : List (String × List Ty × Ty) :=
  [ ("succ", [.nat], .nat), ("pred", [.nat], .nat), ("isZero", [.nat], .bool), ("not", [.bool], .bool)
  , ("add", [.nat, .nat], .nat), ("lt", [.nat, .nat], .bool), ("eq", [.nat, .nat], .bool) ]

/-- The polymorphic atoms (`pair`, `fst`, `snd`) as OCaml arms, and the probes that check
them and the refusals against `nativeAtomTy`. -/
def polyArms : List String :=
  [ s!"  | \"pair\", [a; b] -> Some ({octor "ty" "prod"} (a, b))"
  , s!"  | \"fst\", [{octor "ty" "prod"} (a, _)] -> Some a"
  , s!"  | \"snd\", [{octor "ty" "prod"} (_, b)] -> Some b" ]

def atomProbes : List (String × List Ty × Option Ty) :=
  [ ("pair", [.nat, .bool], some (.prod .nat .bool)), ("pair", [.nat, .nat], some (.prod .nat .nat))
  , ("fst", [.prod .nat .bool], some .nat), ("snd", [.prod .nat .bool], some .bool)
  , ("fst", [.nat], none), ("snd", [.nat, .nat], none), ("pair", [.nat], none), ("pair", [], none)
  , ("succ", [.bool], none), ("succ", [], none), ("succ", [.nat, .nat], none), ("add", [.nat], none)
  , ("mul", [.nat, .nat], none), ("not", [.nat], none), ("eq", [.bool, .bool], none)
  , ("lt", [.nat, .bool], none), ("isZero", [.bool], none), ("pred", [.nat, .nat], none) ]

def checkAtoms : Except String Unit := do
  for (n, args, ans) in monoAtoms do
    unless nativeAtomTy n args = some ans do
      throw s!"atom table disagrees with nativeAtomTy on {n}"
    -- every monomorphic row refuses one argument too many and one too few
    unless nativeAtomTy n (args ++ [.nat]) = none do throw s!"nativeAtomTy accepts {n} with an extra argument"
    unless nativeAtomTy n args.tail = none do throw s!"nativeAtomTy accepts {n} with a missing argument"
  for (n, args, ans) in atomProbes do
    unless nativeAtomTy n args = ans do
      throw s!"atom probe disagrees with nativeAtomTy on {n} {repr args}"

def emitNative (nullaryOps fnOps stratOps : Nat) : String :=
  header "Eff_native: the native alphabet as data. atom_ty is nativeAtomTy (src/Effect4/Program/Native.lean): the monomorphic rows are data in EffGen.lean checked against nativeAtomTy by evaluation at generation time, the three polymorphic atoms are fixed arms checked on probes (tested at generation: a disagreement aborts). row_of is NativeOp.row evaluated on every NativeOp value (all_ops, whose length is checked against the constructor table). scope_key is nativeScopeKey." ++
  "open Eff_types\n\n" ++
  "let atom_names : string list = " ++ listO ((monoAtoms.map (ostr ·.1)) ++ [ostr "pair", ostr "fst", ostr "snd"]) ++ "\n\n" ++
  "let atom_ty (name : string) (args : ty list) : ty option =\n  match name, args with\n" ++
  "\n".intercalate (monoAtoms.map fun (n, args, ans) =>
    s!"  | {ostr n}, [{"; ".intercalate (args.map tyO)}] -> Some {tyO ans}") ++ "\n" ++
  "\n".intercalate polyArms ++ "\n  | _ -> None\n\n" ++
  s!"(* {nullaryOps} nullary operations, {fnOps} over every fn_name, {stratOps} over every finalizer_strategy: {allOps.length} values. *)\n" ++
  "let all_ops : native_op list =\n  [ " ++ "\n  ; ".intercalate (allOps.map opO) ++ " ]\n\n" ++
  "let row_of : native_op -> row = function\n" ++
  "\n".intercalate (allOps.map fun op => s!"  | {opO op} ->\n    {rowO op.row}") ++ "\n\n" ++
  "let scope_key : service_key = " ++ keyO nativeScopeKey ++ "\n" ++
  "let ref_ty : ty = " ++ tyO NativeOp.refTy ++ "\n" ++
  "let deferred_ty : ty = " ++ tyO NativeOp.deferredTy ++ "\n" ++
  "let scope_ty : ty = " ++ tyO Ty.scope ++ "\n" ++
  "let context_ty : ty = " ++ tyO Ty.context ++ "\n"


end OCaml5.Eff
