import Effect4Test.Flow.AdmissionContract
import Effect4Test.Flow.DiagnosticPrecisionContract
import Effect4Test.Flow.AxiomReport
import Effect4Test.Schema.AxiomReport
import Effect4Test.Data.OpticContract
import Effect4Test.Schema.AnnotationDataPlaneContract
import Effect4Test.Schema.EffectfulFieldContract
import Effect4Test.Schema.EffectfulFieldPropertiesContract
import Effect4Test.Schema.AuthoringContract
import Effect4Test.Flow.PrivacyContract
import Effect4Test.Concurrency.FiberRepresentativeContract
import Effect4Test.Concurrency.FiberAssurance
import Effect4Test.Concurrency.FiberAxiomReport
import Effect4Test.Concurrency.FiberSupervisionContract
import Effect4Test.Concurrency.FiberSupervisionAxiomReport
import Effect4Test.Counterexamples.Concurrency.FiberSupervision
import Effect4Test.Counterexamples.Concurrency.FiberRepresentative
import Effect4Test.Counterexamples.Concurrency.RaceRepresentative
import Effect4Test.Counterexamples.Target.TypeScriptRender
import Effect4Test.Counterexamples.Schema.CensusCoverage
import Effect4Test.Counterexamples.Schema.KindAlphabetSeparation
import Effect4Test.Counterexamples.Schema.NoLocalSymbolPropertyKey
import Effect4Test.Counterexamples.Schema.NoNullLiteralKind
import Effect4Test.Counterexamples.Schema.SemanticTagSeparation
import Effect4Test.Counterexamples.Schema.WireSpellingDrift
import Effect4Test.Counterexamples.Schema.AnnotationDataPlane
import Effect4Test.Counterexamples.Schema.EffectfulField
import Effect4Test.Counterexamples.Schema.EffectfulFieldProperties
import Effect4Test.Counterexamples.Schema.RecursiveElimination
import Effect4Test.Schema.RepresentationContract
import Effect4Test.Schema.RepresentationFoldContract
import Effect4Test.Schema.SubAlphabetContract
import Effect4Test.Schema.PayloadContract
import Effect4Test.Schema.PayloadSurface
import Effect4Test.Schema.StructuralAssurance
import Effect4Test.Data.RowContract
import Effect4Test.Data.RowAssurance
import Effect4Test.Data.AxiomReport
import Effect4Test.Environment.ContextKeyContract
import Effect4Test.Environment.AxiomReport
import Effect4Test.Environment.ContextKeyAssurance
import Effect4Test.Target.TypeScript.ExprContract
import Effect4Test.Target.TypeScript.SchemaGenerationContract
import Effect4Test.Target.TypeScript.SchemaGenerationCoverage
import Effect4Test.Target.TypeScript.SchemaGenerationAxiomReport
import Effect4Test.Target.TypeScript.EffectfulFieldContract
import Effect4Test.Target.TypeScript.EffectfulFieldAxiomReport
import Effect4Test.Counterexamples.Target.EffectfulField
import Effect4Test.Semantics.CauseExitContract
import Effect4Test.Semantics.ObservationContract
import Effect4Test.Semantics.CauseExitAxiomReport
import Effect4Test.Counterexamples.Semantics.CauseExit
import Effect4Test.Runtime.ScopeContract
import Effect4Test.Runtime.ScopeAxiomReport
import Effect4Test.Counterexamples.Runtime.Scope
import Effect4Test.Runtime.FramesContract
import Effect4Test.Runtime.FramesAxiomReport
import Effect4Test.Counterexamples.Runtime.Frames
import Effect4Test.Audit.RuntimeCoverage
import Effect4Test.Audit.AxiomGate

/-!
# Effect4 test battery

The default Lake build imports every admitted contract, attack, and kernel
dependency report through this root. A test file not reachable here is not a
passing gate.
-/

#effect4_axiom_gate
