(* GENERATED by src/OCaml5/Tools/EffGen.lean; do not edit *)
(* GENERATED by src/OCaml5/Tools/EffGen.lean — regenerate: lake env lean --run src/OCaml5/Tools/EffGen.lean <outdir>. Do not edit. *)
(* Eff_native: the native alphabet as data. atom names and const-generic metadata project the complete NativeAtom inventory (src/Effect4/Program/NativeAtom.lean). Typing remains in Lean; no second atom checker is emitted. all_ops is NativeOp.spelled, one operation per spelling key (the constructor table checks the classes). scope_key is nativeScopeKey. *)

open Eff_types

let atom_names : string list = ["succ"; "pred"; "isZero"; "not"; "add"; "lt"; "eq"; "pair"; "fst"; "snd"; "strings"; "causeIsFail"; "causeError"; "causeIsDie"; "causeIsInterrupt"; "or"; "and"; "tagIs"; "isSome"; "getOrElse"; "ite"; "some"; "none"; "mul"; "nil"; "cons"; "get"; "length"; "append"; "sub"; "div"; "mod"; "concat"; "mapEmpty"; "mapGet"; "mapSet"; "mapKeys"; "mapEntries"; "mapFromEntries"; "tuple"]

(* The const-generic atoms (NativeAtom.constGeneric): a string literal argument keeps its literal type (the literal rule, DI-15). *)
let const_atoms : string list = ["pair"; "tuple"]
let const_atom (name : string) : bool = List.mem name const_atoms

(* 12 nullary operations, 1 at the faces' type arguments, 8 at every name's image at level 0 (a binder term), 1 over every finalizer_strategy: 55 values. *)
let all_ops : native_op list =
  [ Native_op_refMake
  ; Native_op_refGet
  ; Native_op_refSet
  ; Native_op_refGetAndSet
  ; Native_op_refSetAndGet
  ; (Native_op_refUpdateWith (Term_app ("succ", (Terms_cons ((Term_var 0), Terms_nil)))))
  ; (Native_op_refUpdateWith (Term_app ("mul", (Terms_cons ((Term_var 0), (Terms_cons ((Term_lit (Lit_nat 2)), Terms_nil)))))))
  ; (Native_op_refUpdateWith (Term_app ("add", (Terms_cons ((Term_var 0), (Terms_cons ((Term_lit (Lit_nat 0)), Terms_nil)))))))
  ; (Native_op_refUpdateWith (Term_var 0))
  ; (Native_op_refUpdateWith (Term_app ("add", (Terms_cons ((Term_var 0), (Terms_cons ((Term_lit (Lit_nat 1)), Terms_nil)))))))
  ; (Native_op_refGetAndUpdateWith (Term_app ("succ", (Terms_cons ((Term_var 0), Terms_nil)))))
  ; (Native_op_refGetAndUpdateWith (Term_app ("mul", (Terms_cons ((Term_var 0), (Terms_cons ((Term_lit (Lit_nat 2)), Terms_nil)))))))
  ; (Native_op_refGetAndUpdateWith (Term_app ("add", (Terms_cons ((Term_var 0), (Terms_cons ((Term_lit (Lit_nat 0)), Terms_nil)))))))
  ; (Native_op_refGetAndUpdateWith (Term_var 0))
  ; (Native_op_refGetAndUpdateWith (Term_app ("add", (Terms_cons ((Term_var 0), (Terms_cons ((Term_lit (Lit_nat 1)), Terms_nil)))))))
  ; (Native_op_refUpdateAndGetWith (Term_app ("succ", (Terms_cons ((Term_var 0), Terms_nil)))))
  ; (Native_op_refUpdateAndGetWith (Term_app ("mul", (Terms_cons ((Term_var 0), (Terms_cons ((Term_lit (Lit_nat 2)), Terms_nil)))))))
  ; (Native_op_refUpdateAndGetWith (Term_app ("add", (Terms_cons ((Term_var 0), (Terms_cons ((Term_lit (Lit_nat 0)), Terms_nil)))))))
  ; (Native_op_refUpdateAndGetWith (Term_var 0))
  ; (Native_op_refUpdateAndGetWith (Term_app ("add", (Terms_cons ((Term_var 0), (Terms_cons ((Term_lit (Lit_nat 1)), Terms_nil)))))))
  ; (Native_op_refUpdateSomeWith (Term_app ("some", (Terms_cons ((Term_app ("succ", (Terms_cons ((Term_var 0), Terms_nil)))), Terms_nil)))))
  ; (Native_op_refUpdateSomeWith (Term_app ("some", (Terms_cons ((Term_app ("mul", (Terms_cons ((Term_var 0), (Terms_cons ((Term_lit (Lit_nat 2)), Terms_nil)))))), Terms_nil)))))
  ; (Native_op_refUpdateSomeWith (Term_app ("ite", (Terms_cons ((Term_app ("lt", (Terms_cons ((Term_lit (Lit_nat 0)), (Terms_cons ((Term_var 0), Terms_nil)))))), (Terms_cons ((Term_app ("some", (Terms_cons ((Term_lit (Lit_nat 0)), Terms_nil)))), (Terms_cons ((Term_app ("none", Terms_nil)), Terms_nil)))))))))
  ; (Native_op_refUpdateSomeWith (Term_app ("none", Terms_nil)))
  ; (Native_op_refUpdateSomeWith (Term_app ("some", (Terms_cons ((Term_app ("add", (Terms_cons ((Term_var 0), (Terms_cons ((Term_lit (Lit_nat 1)), Terms_nil)))))), Terms_nil)))))
  ; (Native_op_refGetAndUpdateSomeWith (Term_app ("some", (Terms_cons ((Term_app ("succ", (Terms_cons ((Term_var 0), Terms_nil)))), Terms_nil)))))
  ; (Native_op_refGetAndUpdateSomeWith (Term_app ("some", (Terms_cons ((Term_app ("mul", (Terms_cons ((Term_var 0), (Terms_cons ((Term_lit (Lit_nat 2)), Terms_nil)))))), Terms_nil)))))
  ; (Native_op_refGetAndUpdateSomeWith (Term_app ("ite", (Terms_cons ((Term_app ("lt", (Terms_cons ((Term_lit (Lit_nat 0)), (Terms_cons ((Term_var 0), Terms_nil)))))), (Terms_cons ((Term_app ("some", (Terms_cons ((Term_lit (Lit_nat 0)), Terms_nil)))), (Terms_cons ((Term_app ("none", Terms_nil)), Terms_nil)))))))))
  ; (Native_op_refGetAndUpdateSomeWith (Term_app ("none", Terms_nil)))
  ; (Native_op_refGetAndUpdateSomeWith (Term_app ("some", (Terms_cons ((Term_app ("add", (Terms_cons ((Term_var 0), (Terms_cons ((Term_lit (Lit_nat 1)), Terms_nil)))))), Terms_nil)))))
  ; (Native_op_refUpdateSomeAndGetWith (Term_app ("some", (Terms_cons ((Term_app ("succ", (Terms_cons ((Term_var 0), Terms_nil)))), Terms_nil)))))
  ; (Native_op_refUpdateSomeAndGetWith (Term_app ("some", (Terms_cons ((Term_app ("mul", (Terms_cons ((Term_var 0), (Terms_cons ((Term_lit (Lit_nat 2)), Terms_nil)))))), Terms_nil)))))
  ; (Native_op_refUpdateSomeAndGetWith (Term_app ("ite", (Terms_cons ((Term_app ("lt", (Terms_cons ((Term_lit (Lit_nat 0)), (Terms_cons ((Term_var 0), Terms_nil)))))), (Terms_cons ((Term_app ("some", (Terms_cons ((Term_lit (Lit_nat 0)), Terms_nil)))), (Terms_cons ((Term_app ("none", Terms_nil)), Terms_nil)))))))))
  ; (Native_op_refUpdateSomeAndGetWith (Term_app ("none", Terms_nil)))
  ; (Native_op_refUpdateSomeAndGetWith (Term_app ("some", (Terms_cons ((Term_app ("add", (Terms_cons ((Term_var 0), (Terms_cons ((Term_lit (Lit_nat 1)), Terms_nil)))))), Terms_nil)))))
  ; (Native_op_refModifyWith (Term_app ("pair", (Terms_cons ((Term_var 0), (Terms_cons ((Term_app ("succ", (Terms_cons ((Term_var 0), Terms_nil)))), Terms_nil)))))))
  ; (Native_op_refModifyWith (Term_app ("pair", (Terms_cons ((Term_var 0), (Terms_cons ((Term_app ("mul", (Terms_cons ((Term_var 0), (Terms_cons ((Term_lit (Lit_nat 2)), Terms_nil)))))), Terms_nil)))))))
  ; (Native_op_refModifyWith (Term_app ("pair", (Terms_cons ((Term_var 0), (Terms_cons ((Term_app ("add", (Terms_cons ((Term_var 0), (Terms_cons ((Term_lit (Lit_nat 0)), Terms_nil)))))), Terms_nil)))))))
  ; (Native_op_refModifyWith (Term_app ("pair", (Terms_cons ((Term_var 0), (Terms_cons ((Term_var 0), Terms_nil)))))))
  ; (Native_op_refModifyWith (Term_app ("pair", (Terms_cons ((Term_var 0), (Terms_cons ((Term_app ("add", (Terms_cons ((Term_var 0), (Terms_cons ((Term_lit (Lit_nat 1)), Terms_nil)))))), Terms_nil)))))))
  ; (Native_op_refModifySomeWith (Term_app ("pair", (Terms_cons ((Term_var 0), (Terms_cons ((Term_app ("some", (Terms_cons ((Term_app ("succ", (Terms_cons ((Term_var 0), Terms_nil)))), Terms_nil)))), Terms_nil)))))))
  ; (Native_op_refModifySomeWith (Term_app ("pair", (Terms_cons ((Term_var 0), (Terms_cons ((Term_app ("some", (Terms_cons ((Term_app ("mul", (Terms_cons ((Term_var 0), (Terms_cons ((Term_lit (Lit_nat 2)), Terms_nil)))))), Terms_nil)))), Terms_nil)))))))
  ; (Native_op_refModifySomeWith (Term_app ("pair", (Terms_cons ((Term_var 0), (Terms_cons ((Term_app ("some", (Terms_cons ((Term_var 0), Terms_nil)))), Terms_nil)))))))
  ; (Native_op_refModifySomeWith (Term_app ("pair", (Terms_cons ((Term_var 0), (Terms_cons ((Term_app ("none", Terms_nil)), Terms_nil)))))))
  ; (Native_op_refModifySomeWith (Term_app ("pair", (Terms_cons ((Term_var 0), (Terms_cons ((Term_app ("some", (Terms_cons ((Term_app ("add", (Terms_cons ((Term_var 0), (Terms_cons ((Term_lit (Lit_nat 1)), Terms_nil)))))), Terms_nil)))), Terms_nil)))))))
  ; (Native_op_deferredMakeOf (Ty_nat, Ty_nat))
  ; Native_op_deferredIsDone
  ; Native_op_deferredPoll
  ; Native_op_deferredSucceed
  ; Native_op_deferredFail
  ; Native_op_deferredAwait
  ; (Native_op_scopeMake Finalizer_strategy_sequential)
  ; (Native_op_scopeMake Finalizer_strategy_parallel)
  ; Native_op_sleep
  ; Native_op_clockNow ]

let scope_key : service_key = { service_key_name = { service_name_value = 0 }; service_key_service = { service_type_code_value = 0 } }
let scope_ty : ty = (Ty_handle "Scope.Scope")
let context_ty : ty = (Ty_handle "Context.Context<unknown>")
