(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400002`, seed 400002, 15 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400002 () =
  let v0 = Fibers_fixture.fork 1 in
  let v1 = Fibers_fixture.fork 4 in
  let _v2 = Fibers_fixture.cleanups () in
  let _v3 = Extra_fixture.await_all [ v0; v1 ] in
  ignore (Fibers_fixture.interrupt v1);
  let _v4 = Store_fixtures.layer_build 1 in
  let _v5 = Store_fixtures.layer_provide_count 1 in
  let _v6 = Store_fixtures.layer_provide_count 3 in
  let _v7 = Fibers_fixture.cleanups () in
  let _v8 = Fibers_fixture.started () in
  let _v9 = Extra_fixture.interrupt_all [ v0; v1 ] in
  let _v10 = Fibers_fixture.await_value v0 in
  let _v11 = Store_fixtures.scope_make () in
  let _v12 = Fibers_fixture.started () in
  let v13 = Fibers_fixture.cleanups () in
  v13

let programs : (string * (unit -> value)) list = [ ("p400002", corpus_p400002) ]
