(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400174`, seed 400174, 31 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400174 () =
  let v0 = Fibers_fixture.fork 3 in
  ignore (Extra_fixture.yield ());
  let _v1 = Fibers_fixture.cleanups () in
  let _v2 = Fibers_fixture.join v0 in
  let _v3 = Fibers_fixture.await_error v0 in
  let _v4 = Fibers_fixture.cleanups () in
  let _v5 = Fibers_fixture.started () in
  let v6 = Store_fixtures.def_make () in
  let _v7 = Extra_fixture.interrupt_all [ v0 ] in
  let _v8 = Fibers_fixture.started () in
  let _v9 = Fibers_fixture.started () in
  let _v10 = Store_fixtures.ref_make 3 in
  let _v11 = Store_fixtures.def_is_done v6 in
  let v12 = Fibers_fixture.fork 4 in
  let _v13 = Store_fixtures.def_await_error v6 in
  let _v14 = Fibers_fixture.await_value v0 in
  let v15 = Fibers_fixture.fork 0 in
  let _v16 = Store_fixtures.def_make () in
  let _v17 = Store_fixtures.layer_build 2 in
  let _v18 = Fibers_fixture.join v15 in
  let _v19 = Store_fixtures.ref_make 5 in
  let _v20 = Store_fixtures.ref_make 5 in
  let v21 = Store_fixtures.def_make () in
  let _v22 = Store_fixtures.scope_make () in
  let _v23 = Store_fixtures.def_poll v21 in
  ignore (Fibers_fixture.interrupt v12);
  let _v24 = Store_fixtures.def_fail v6 1 in
  let _v25 = Store_fixtures.layer_close () in
  ignore (Fibers_fixture.interrupt v12);
  let _v26 = Store_fixtures.def_poll v21 in
  let v27 = Fibers_fixture.started () in
  v27

let programs : (string * (unit -> value)) list = [ ("p400174", corpus_p400174) ]
