(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400092`, seed 400092, 33 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400092 () =
  let v0 = Fibers_fixture.fork 2 in
  let _v1 = Fibers_fixture.await_error v0 in
  let v2 = Store_fixtures.ref_make 8 in
  let _v3 = Fibers_fixture.started () in
  let v4 = Store_fixtures.scope_make () in
  let _v5 = Fibers_fixture.cleanups () in
  let _v6 = Fibers_fixture.cleanups () in
  ignore (Extra_fixture.yield ());
  let _v7 = Store_fixtures.ref_modify v2 5 in
  ignore (Store_fixtures.ref_update v2 6);
  let _v8 = Fibers_fixture.await_error v0 in
  let _v9 = Fibers_fixture.cleanups () in
  let _v10 = Fibers_fixture.await_value v0 in
  let _v11 = Fibers_fixture.cleanups () in
  let v12 = Store_fixtures.scope_make () in
  let _v13 = Store_fixtures.scope_close v12 in
  ignore (Fibers_fixture.interrupt v0);
  let _v14 = Fibers_fixture.cleanups () in
  ignore (Fibers_fixture.interrupt v0);
  let _v15 = Store_fixtures.scope_add v4 3 in
  let _v16 = Fibers_fixture.cleanups () in
  let v17 = Fibers_fixture.fork 2 in
  let v18 = Fibers_fixture.fork 0 in
  let _v19 = Fibers_fixture.await_value v18 in
  let _v20 = Fibers_fixture.fork 0 in
  let _v21 = Fibers_fixture.join v18 in
  let _v22 = Fibers_fixture.join v17 in
  let v23 = Store_fixtures.def_make () in
  let _v24 = Store_fixtures.def_poll v23 in
  let _v25 = Fibers_fixture.await_value v18 in
  let _v26 = Store_fixtures.layer_build 0 in
  let _v27 = Store_fixtures.def_make () in
  let v28 = Fibers_fixture.started () in
  v28

let programs : (string * (unit -> value)) list = [ ("p400092", corpus_p400092) ]
