(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400179`, seed 400179, 30 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400179 () =
  let v0 = Fibers_fixture.fork 2 in
  let _v1 = Fibers_fixture.cleanups () in
  let _v2 = Fibers_fixture.await_value v0 in
  let _v3 = Extra_fixture.interrupt_all [ v0 ] in
  let v4 = Store_fixtures.def_make () in
  let v5 = Store_fixtures.def_make () in
  let v6 = Store_fixtures.layer_build 1 in
  let _v7 = Store_fixtures.layer_scope_of v6 in
  let _v8 = Fibers_fixture.await_error v0 in
  let _v9 = Fibers_fixture.cleanups () in
  ignore (Fibers_fixture.interrupt v0);
  let _v10 = Store_fixtures.def_await_value v4 in
  let _v11 = Fibers_fixture.await_error v0 in
  let _v12 = Store_fixtures.def_await_value v5 in
  let _v13 = Store_fixtures.def_await_value v4 in
  let _v14 = Store_fixtures.ref_make 9 in
  let _v15 = Store_fixtures.def_succeed v5 5 in
  let _v16 = Extra_fixture.await_all [ v0 ] in
  let _v17 = Fibers_fixture.await_error v0 in
  let _v18 = Store_fixtures.def_make () in
  let _v19 = Fibers_fixture.cleanups () in
  let _v20 = Fibers_fixture.fork 6 in
  let _v21 = Fibers_fixture.await_value v0 in
  let _v22 = Store_fixtures.layer_build 0 in
  let v23 = Fibers_fixture.fork 3 in
  let _v24 = Fibers_fixture.fork_detach 0 in
  let _v25 = Fibers_fixture.started () in
  let v26 = Fibers_fixture.fork 0 in
  let _v27 = Fibers_fixture.await_error v26 in
  let v28 = Fibers_fixture.await_value v23 in
  v28

let programs : (string * (unit -> value)) list = [ ("p400179", corpus_p400179) ]
