(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400112`, seed 400112, 29 operations.
   Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400112 () =
  let v0 = Fibers_fixture.fork 0 in
  let _v1 = Fibers_fixture.cleanups () in
  let _v2 = Fibers_fixture.started () in
  let v3 = Store_fixtures.def_make () in
  let _v4 = Fibers_fixture.await_error v0 in
  let _v5 = Fibers_fixture.join v0 in
  let v6 = Store_fixtures.ref_make 1 in
  let _v7 = Extra_fixture.interrupt_all [ v0 ] in
  ignore (Store_fixtures.ref_update v6 3);
  let _v8 = Fibers_fixture.fork 1 in
  ignore (Extra_fixture.yield ());
  let _v9 = Store_fixtures.ref_modify v6 7 in
  ignore (Store_fixtures.ref_set v6 4);
  ignore (Extra_fixture.yield ());
  let _v10 = Store_fixtures.def_make () in
  let _v11 = Store_fixtures.def_is_done v3 in
  let _v12 = Fibers_fixture.await_error v0 in
  let _v13 = Fibers_fixture.await_error v0 in
  let _v14 = Fibers_fixture.started () in
  let _v15 = Store_fixtures.def_succeed v3 0 in
  let _v16 = Fibers_fixture.cleanups () in
  let v17 = Fibers_fixture.fork 3 in
  let _v18 = Fibers_fixture.cleanups () in
  let _v19 = Fibers_fixture.await_error v17 in
  let _v20 = Store_fixtures.ref_get_and_set v6 3 in
  let _v21 = Fibers_fixture.started () in
  let _v22 = Store_fixtures.ref_make 5 in
  let _v23 = Store_fixtures.def_fail v3 10 in
  let v24 = Fibers_fixture.started () in
  v24

let programs : (string * (unit -> value)) list = [ ("p400112", corpus_p400112) ]
