(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400133`, seed 400133, 32 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400133 () =
  let v0 = Fibers_fixture.fork 0 in
  let _v1 = Fibers_fixture.cleanups () in
  let _v2 = Fibers_fixture.cleanups () in
  let _v3 = Store_fixtures.scope_make () in
  let v4 = Store_fixtures.ref_make 7 in
  let _v5 = Store_fixtures.ref_modify v4 6 in
  let _v6 = Fibers_fixture.await_value v0 in
  let v7 = Store_fixtures.scope_make () in
  let v8 = Fibers_fixture.fork 1 in
  let _v9 = Fibers_fixture.cleanups () in
  let _v10 = Extra_fixture.interrupt_all [ v8 ] in
  ignore (Store_fixtures.ref_update v4 8);
  let _v11 = Fibers_fixture.started () in
  let _v12 = Fibers_fixture.cleanups () in
  let _v13 = Store_fixtures.layer_build 2 in
  let v14 = Store_fixtures.ref_make 6 in
  ignore (Fibers_fixture.interrupt v0);
  let _v15 = Store_fixtures.layer_build 1 in
  let _v16 = Store_fixtures.scope_close v7 in
  ignore (Store_fixtures.ref_update v14 1);
  ignore (Fibers_fixture.interrupt v0);
  let v17 = Fibers_fixture.fork 0 in
  ignore (Extra_fixture.yield ());
  let _v18 = Fibers_fixture.await_error v8 in
  ignore (Store_fixtures.ref_update v14 8);
  let _v19 = Fibers_fixture.await_value v17 in
  let _v20 = Fibers_fixture.cleanups () in
  let _v21 = Fibers_fixture.fork 1 in
  ignore (Store_fixtures.ref_set v14 4);
  let _v22 = Fibers_fixture.await_value v17 in
  let _v23 = Store_fixtures.ref_make 1 in
  let v24 = Fibers_fixture.join v0 in
  v24

let programs : (string * (unit -> value)) list = [ ("p400133", corpus_p400133) ]
