(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400186`, seed 400186, 7 operations.
   Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400186 () =
  let v0 = Fibers_fixture.fork 2 in
  ignore (Extra_fixture.yield ());
  let _v1 = Store_fixtures.scope_make () in
  let _v2 = Store_fixtures.scope_make () in
  let _v3 = Fibers_fixture.cleanups () in
  let _v4 = Fibers_fixture.join v0 in
  let v5 = Fibers_fixture.await_value v0 in
  v5

let programs : (string * (unit -> value)) list = [ ("p400186", corpus_p400186) ]
