import { Cause, Context, Data, Deferred, Effect, Exit, Fiber, Layer, Option, Ref, Scope, pipe } from "effect"
import { ProfileRefusal, add, and, append, caseTag, caseTagR, causeError, causeIsDie, causeIsFail, causeIsInterrupt, concat, cons, div, drop, eq, fold, fst, get, getOrElse, isSome, isZero, ite, length, lt, mapEmpty, mapEntries, mapFromEntries, mapGet, mapKeys, mapSet, minus, mod, mul, nil, none, not, optionCase, or, pair, plus, pred, recordOptional, recordRequired, recordSet, recordValue, sameHandle, snd, some, strings, sub, succ, tagIs, take, tuple, tupleAt } from "./prelude.ts"
export const e4$channelBase$opened = (a0: Ref.Ref<number>): Effect.Effect<Ref.Ref<number>, never, never> => Effect.suspend(() => Effect.succeed(a0))
export const e4$channelBase$pull = (a0: Ref.Ref<number>): Effect.Effect<readonly ["End", number] | readonly ["Chunk", ReadonlyArray<number>], never, never> => Effect.suspend(() => Effect.flatMap(Ref.get(a0), (a1) => Effect.flatMap(Effect.flatMap(Ref.set(a0, add(a1, 1)), (a2) => Effect.succeed(undefined)), (a2) => Effect.suspend(() => lt(a1, 2) ? Effect.succeed(pair("Chunk", append(cons(a1, nil()), cons(add(a1, 10), nil())))) : Effect.succeed(pair("End", 42))))))
export const e4$channelBase$close = (a0: Ref.Ref<number>): Effect.Effect<void, never, never> => Effect.suspend(() => Effect.flatMap(Ref.get(a0), (a1) => Effect.flatMap(Ref.set(a0, add(a1, 100)), (a2) => Effect.succeed(undefined))))
export const e4$channelBase$reject = (a0: Ref.Ref<number>): Effect.Effect<readonly ["End", number] | readonly ["Chunk", ReadonlyArray<number>], string, never> => Effect.suspend(() => Effect.flatMap(Effect.flatMap(Ref.set(a0, 7), (a1) => Effect.succeed(undefined)), (a1) => Effect.failCause(Cause.combine(Cause.fail("input"), Cause.die(3)))))
export const e4$channelMapped$pull = (a0: Ref.Ref<number>): Effect.Effect<readonly ["End", number] | readonly ["Chunk", ReadonlyArray<number>], never, never> => Effect.suspend(() => Effect.flatMap(e4$channelBase$pull(a0), (a1) => caseTag(a1, "End", (a2) => Effect.succeed(pair("End", a2)), (a2) => Effect.flatMap(Effect.succeed(append(cons(10, nil()), cons(20, nil()))), (a3) => Effect.succeed(pair("Chunk", a3))))))
export const e4$channelMapped$done = (a0: Ref.Ref<number>): Effect.Effect<readonly ["End", number] | readonly ["Chunk", ReadonlyArray<number>], never, never> => Effect.suspend(() => Effect.flatMap(e4$channelBase$pull(a0), (a1) => caseTag(a1, "End", (a2) => Effect.flatMap(Effect.succeed(add(a2, 1)), (a3) => Effect.succeed(pair("End", a3))), (a2) => Effect.succeed(pair("Chunk", snd(a2))))))
export const e4$channelMapped$effect = (a0: Ref.Ref<number>): Effect.Effect<readonly ["End", number] | readonly ["Chunk", ReadonlyArray<number>], never, never> => Effect.suspend(() => Effect.flatMap(e4$channelBase$pull(a0), (a1) => caseTag(a1, "End", (a2) => Effect.succeed(pair("End", a2)), (a2) => Effect.flatMap(Effect.succeed(snd(a2)), (a3) => Effect.succeed(pair("Chunk", a3))))))
export const e4$channelMapped$failMap = (a0: Ref.Ref<number>): Effect.Effect<readonly ["End", number] | readonly ["Chunk", ReadonlyArray<number>], string, never> => Effect.suspend(() => Effect.flatMap(e4$channelBase$pull(a0), (a1) => caseTag(a1, "End", (a2) => Effect.succeed(pair("End", a2)), (a2) => Effect.flatMap(Effect.flatMap(Effect.flatMap(Ref.set(a0, 8), (a3) => Effect.succeed(undefined)), (a3) => Effect.fail("mapper")), (a3) => Effect.succeed(pair("Chunk", a3))))))
export const e4$channelMapped$failDone = (a0: Ref.Ref<number>): Effect.Effect<readonly ["End", number] | readonly ["Chunk", ReadonlyArray<number>], string, never> => Effect.suspend(() => Effect.flatMap(e4$channelBase$pull(a0), (a1) => caseTag(a1, "End", (a2) => Effect.flatMap(Effect.flatMap(Effect.flatMap(Ref.set(a0, 11), (a3) => Effect.succeed(undefined)), (a3) => Effect.fail("done mapper")), (a3) => Effect.succeed(pair("End", a3))), (a2) => Effect.succeed(pair("Chunk", snd(a2))))))
export const e4$channelMapped$reject = (a0: Ref.Ref<number>): Effect.Effect<readonly ["End", number] | readonly ["Chunk", ReadonlyArray<number>], string, never> => Effect.suspend(() => Effect.flatMap(e4$channelBase$reject(a0), (a1) => caseTag(a1, "End", (a2) => Effect.succeed(pair("End", a2)), (a2) => Effect.flatMap(Effect.succeed(cons(99, nil())), (a3) => Effect.succeed(pair("Chunk", a3))))))
export const e4$channelNested$pull = (a0: Ref.Ref<number>): Effect.Effect<readonly ["End", number] | readonly ["Chunk", ReadonlyArray<number>], never, never> => Effect.suspend(() => Effect.flatMap(e4$channelMapped$pull(a0), (a1) => caseTag(a1, "End", (a2) => Effect.flatMap(Effect.succeed(add(a2, 1)), (a3) => Effect.succeed(pair("End", a3))), (a2) => Effect.succeed(pair("Chunk", snd(a2))))))
export const main: Effect.Effect<number, never, never> = Effect.flatMap(Effect.flatMap(Ref.make(0), (a0) => Effect.flatMap(Effect.flatMap(Effect.scoped(Effect.flatMap(Effect.acquireRelease(e4$channelBase$opened(a0), (a1, a2) => e4$channelBase$close(a1)), (a1) => Effect.suspend(() => {
  let a2: readonly [ReadonlyArray<number>, Option.Option<number>] = pair(nil(), none())
  return Effect.map(Effect.whileLoop({
    while: () => not(isSome(snd(a2))),
    body: () => Effect.flatMap(e4$channelMapped$pull(a1), (a3) => caseTag(a3, "End", (a4) => Effect.succeed(pair(fst(a2), some(a4))), (a4) => Effect.flatMap(Effect.succeed(append(fst(a2), snd(a4))), (a5) => Effect.succeed(pair(a5, none()))))),
    step: (a3) => {
      a2 = a3
    },
  }), () => a2)
}))), (a1) => Effect.succeed(fst(a1))), (a1) => Effect.flatMap(Ref.get(a0), (a2) => Effect.succeed(tuple(a1, a2))))), (a0) => Effect.succeed(tupleAt<"1">("1")(a0)))
