export const main: Effect.Effect<ReadonlyArray<number>, never, never> = Effect.flatMap(Ref.make(recordValue<{ readonly open: boolean; readonly waiters: ReadonlyArray<{ readonly hint: Deferred.Deferred<void, never>; readonly id: Deferred.Deferred<void, never> }> }>([10, [20], [[4, [[5, [3, "open"], [5, [1, false], [10, [5], []]]], [5, [3, "waiters"], [5, [1, false], [10, [8], [[10, [20], [[4, [[5, [3, "hint"], [5, [1, false], [10, [17], [[10, [1], []], [10, [], []]]]]], [5, [3, "id"], [5, [1, false], [10, [17], [[10, [1], []], [10, [], []]]]]]]]]]]]]]]]]], { open: false, waiters: nil() })), (a0) => Effect.flatMap(Ref.make(take(cons(0, nil()), 0)), (a1) => Effect.flatMap(Effect.forkChild(Effect.flatMap(Effect.flatMap(Effect.uninterruptibleMask((a2) => Effect.succeed(a2)), (a2) => Effect.uninterruptible(Effect.flatMap(Deferred.make<void, never>(), (a3) => Effect.flatMap(Deferred.make<void, never>(), (a4) => Effect.flatMap(Ref.modify(a0, (a5) => ite(recordRequired<"open">("open")(a5), pair(true, a5), pair(false, recordSet<"waiters">("waiters")(a5)(append(fold(recordRequired<"waiters">("waiters")(a5), take(recordRequired<"waiters">("waiters")(a5), 0), (a6, a7) => ite(sameHandle(recordRequired<"id">("id")(a7), a3), a6, append(a6, cons(a7, nil())))), cons(recordValue<{ readonly hint: Deferred.Deferred<void, never>; readonly id: Deferred.Deferred<void, never> }>([10, [20], [[4, [[5, [3, "id"], [5, [1, false], [10, [17], [[10, [1], []], [10, [], []]]]]], [5, [3, "hint"], [5, [1, false], [10, [17], [[10, [1], []], [10, [], []]]]]]]]]], { id: a3, hint: a4 }), nil())))))), (a5) => Effect.suspend(() => a5 ? Effect.succeed(undefined) : Effect.onExit(pipe(Deferred.await(a4), a2), (a6) => Effect.suspend(() => causeIsInterrupt(a6) ? Ref.modify(a0, (a7) => pair(undefined, recordSet<"waiters">("waiters")(a7)(fold(recordRequired<"waiters">("waiters")(a7), take(recordRequired<"waiters">("waiters")(a7), 0), (a8, a9) => ite(sameHandle(recordRequired<"id">("id")(a9), a3), a8, append(a8, cons(a9, nil()))))))) : Effect.succeed(undefined))))))))), (a2) => Ref.update(a1, (a3) => append(a3, cons(1, nil())))), { startImmediately: true, uninterruptible: "inherit" }), (a2) => Effect.flatMap(Effect.uninterruptible(Effect.flatMap(Ref.modify(a0, (a3) => ite(recordRequired<"open">("open")(a3), pair(tuple(false, take(recordRequired<"waiters">("waiters")(a3), 0)), a3), pair(tuple(true, recordRequired<"waiters">("waiters")(a3)), recordSet<"waiters">("waiters")(a3)(take(recordRequired<"waiters">("waiters")(a3), 0))))), (a3) => Effect.flatMap(Effect.suspend(() => {
  let a4 = 0
  return Effect.map(Effect.whileLoop({
    while: () => lt(a4, length(tupleAt<"1">("1")(a3))),
    body: () => optionCase(get(tupleAt<"1">("1")(a3), a4), () => Effect.succeed(undefined), (a5) => Effect.flatMap(Effect.forkDetach(Deferred.succeed(recordRequired<"hint">("hint")(a5), undefined), { startImmediately: false, uninterruptible: true }), (a6) => Effect.succeed(undefined))),
    step: (a5) => {
      a4 = succ(a4)
    },
  }), () => a4)
}), (a4) => Effect.succeed(tupleAt<"0">("0")(a3))))), (a3) => Effect.flatMap(Effect.forkDetach(Ref.update(a1, (a4) => append(a4, cons(9, nil()))), { startImmediately: false, uninterruptible: true }), (a4) => Effect.flatMap(Effect.forkChild(Effect.flatMap(Effect.flatMap(Effect.uninterruptibleMask((a5) => Effect.succeed(a5)), (a5) => Effect.uninterruptible(Effect.flatMap(Deferred.make<void, never>(), (a6) => Effect.flatMap(Deferred.make<void, never>(), (a7) => Effect.flatMap(Ref.modify(a0, (a8) => ite(recordRequired<"open">("open")(a8), pair(true, a8), pair(false, recordSet<"waiters">("waiters")(a8)(append(fold(recordRequired<"waiters">("waiters")(a8), take(recordRequired<"waiters">("waiters")(a8), 0), (a9, a10) => ite(sameHandle(recordRequired<"id">("id")(a10), a6), a9, append(a9, cons(a10, nil())))), cons(recordValue<{ readonly hint: Deferred.Deferred<void, never>; readonly id: Deferred.Deferred<void, never> }>([10, [20], [[4, [[5, [3, "id"], [5, [1, false], [10, [17], [[10, [1], []], [10, [], []]]]]], [5, [3, "hint"], [5, [1, false], [10, [17], [[10, [1], []], [10, [], []]]]]]]]]], { id: a6, hint: a7 }), nil())))))), (a8) => Effect.suspend(() => a8 ? Effect.succeed(undefined) : Effect.onExit(pipe(Deferred.await(a7), a5), (a9) => Effect.suspend(() => causeIsInterrupt(a9) ? Ref.modify(a0, (a10) => pair(undefined, recordSet<"waiters">("waiters")(a10)(fold(recordRequired<"waiters">("waiters")(a10), take(recordRequired<"waiters">("waiters")(a10), 0), (a11, a12) => ite(sameHandle(recordRequired<"id">("id")(a12), a6), a11, append(a11, cons(a12, nil()))))))) : Effect.succeed(undefined))))))))), (a5) => Ref.update(a1, (a6) => append(a6, cons(2, nil())))), { startImmediately: true, uninterruptible: "inherit" }), (a5) => Effect.flatMap(Effect.uninterruptible(Effect.flatMap(Ref.modify(a0, (a6) => ite(recordRequired<"open">("open")(a6), pair(tuple(false, take(recordRequired<"waiters">("waiters")(a6), 0)), a6), pair(tuple(true, recordRequired<"waiters">("waiters")(a6)), recordSet<"waiters">("waiters")(a6)(take(recordRequired<"waiters">("waiters")(a6), 0))))), (a6) => Effect.flatMap(Effect.suspend(() => {
  let a7 = 0
  return Effect.map(Effect.whileLoop({
    while: () => lt(a7, length(tupleAt<"1">("1")(a6))),
    body: () => optionCase(get(tupleAt<"1">("1")(a6), a7), () => Effect.succeed(undefined), (a8) => Effect.flatMap(Effect.forkDetach(Deferred.succeed(recordRequired<"hint">("hint")(a8), undefined), { startImmediately: false, uninterruptible: true }), (a9) => Effect.succeed(undefined))),
    step: (a8) => {
      a7 = succ(a7)
    },
  }), () => a7)
}), (a7) => Effect.succeed(tupleAt<"0">("0")(a6))))), (a6) => Effect.flatMap(Fiber.join(a2), (a7) => Effect.flatMap(Fiber.join(a5), (a8) => Effect.flatMap(Fiber.join(a4), (a9) => Ref.get(a1)))))))))))
