(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400003`, seed 400003, 22 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400003 () =
  let v0 = Fibers_fixture.fork 1 in
  ignore (Fibers_fixture.interrupt v0);
  let _v1 = Fibers_fixture.cleanups () in
  let _v2 = Fibers_fixture.cleanups () in
  let _v3 = Store_fixtures.ref_make 8 in
  let _v4 = Fibers_fixture.join v0 in
  let _v5 = Store_fixtures.ref_make 1 in
  let v6 = Store_fixtures.scope_make () in
  let _v7 = Fibers_fixture.await_error v0 in
  let v8 = Store_fixtures.layer_build 1 in
  let _v9 = Store_fixtures.layer_scope_of v8 in
  let _v10 = Fibers_fixture.cleanups () in
  let _v11 = Fibers_fixture.await_value v0 in
  ignore (Store_fixtures.scope_remove v6 4);
  ignore (Fibers_fixture.interrupt v0);
  let _v12 = Store_fixtures.ref_make 1 in
  let _v13 = Store_fixtures.scope_add v6 1 in
  let _v14 = Store_fixtures.scope_make () in
  ignore (Extra_fixture.yield ());
  let _v15 = Fibers_fixture.cleanups () in
  let _v16 = Fibers_fixture.cleanups () in
  let v17 = Fibers_fixture.cleanups () in
  v17

let programs : (string * (unit -> value)) list = [ ("p400003", corpus_p400003) ]
