(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400108`, seed 400108, 37 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400108 () =
  let v0 = Fibers_fixture.fork 0 in
  let _v1 = Fibers_fixture.started () in
  let _v2 = Fibers_fixture.started () in
  let _v3 = Fibers_fixture.cleanups () in
  let _v4 = Fibers_fixture.cleanups () in
  let _v5 = Fibers_fixture.await_error v0 in
  let _v6 = Fibers_fixture.cleanups () in
  let _v7 = Fibers_fixture.await_value v0 in
  let _v8 = Fibers_fixture.cleanups () in
  let _v9 = Store_fixtures.ref_make 6 in
  let _v10 = Fibers_fixture.started () in
  ignore (Fibers_fixture.interrupt v0);
  let _v11 = Fibers_fixture.started () in
  let _v12 = Fibers_fixture.cleanups () in
  let _v13 = Fibers_fixture.await_value v0 in
  let _v14 = Store_fixtures.scope_make () in
  let _v15 = Store_fixtures.layer_build 2 in
  let v16 = Store_fixtures.def_make () in
  ignore (Fibers_fixture.interrupt v0);
  let _v17 = Fibers_fixture.started () in
  let _v18 = Extra_fixture.interrupt_all [ v0 ] in
  let _v19 = Store_fixtures.def_succeed v16 9 in
  let _v20 = Store_fixtures.def_succeed v16 3 in
  let _v21 = Fibers_fixture.cleanups () in
  let _v22 = Store_fixtures.def_fail v16 10 in
  let _v23 = Store_fixtures.def_make () in
  let _v24 = Store_fixtures.ref_make 5 in
  let _v25 = Extra_fixture.interrupt_all [ v0 ] in
  let _v26 = Store_fixtures.ref_make 4 in
  let _v27 = Store_fixtures.scope_make () in
  let _v28 = Store_fixtures.def_await_error v16 in
  let _v29 = Fibers_fixture.await_error v0 in
  let _v30 = Store_fixtures.layer_provide_count 0 in
  ignore (Extra_fixture.yield ());
  let _v31 = Store_fixtures.layer_build 0 in
  let _v32 = Fibers_fixture.join v0 in
  let v33 = Fibers_fixture.cleanups () in
  v33

let programs : (string * (unit -> value)) list = [ ("p400108", corpus_p400108) ]
