(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400100`, seed 400100, 17 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400100 () =
  let v0 = Fibers_fixture.fork 0 in
  let _v1 = Fibers_fixture.started () in
  let _v2 = Fibers_fixture.cleanups () in
  ignore (Fibers_fixture.interrupt v0);
  ignore (Extra_fixture.yield ());
  let _v3 = Fibers_fixture.started () in
  let v4 = Fibers_fixture.fork 4 in
  let v5 = Fibers_fixture.fork_detach 2 in
  let _v6 = Fibers_fixture.await_value v4 in
  let _v7 = Extra_fixture.interrupt_all [ v0; v4; v5 ] in
  let _v8 = Fibers_fixture.fork 3 in
  let _v9 = Fibers_fixture.await_value v0 in
  let _v10 = Fibers_fixture.started () in
  let _v11 = Store_fixtures.layer_build 2 in
  let _v12 = Fibers_fixture.started () in
  let _v13 = Fibers_fixture.cleanups () in
  let v14 = Fibers_fixture.join v0 in
  v14

let programs : (string * (unit -> value)) list = [ ("p400100", corpus_p400100) ]
