/-! ## Acceptance against the goldens

Appended verbatim by `--append`; not generated. The oracle is `ocaml/goldens/eff/*.hex`, the
bytes the OCaml host writes for the Wire's corpus; the spike's hand `ProgramCanonical`
(`workshop/Cas`, lane S1) agreed with these instances tree for tree on all eight programs and
retired at the landing (`REPORT-G.md`, decision 1). The corpus itself lives above this module
(`Program/Wire.lean`, `Corpus`), which imports this one, so all eight goldens are guarded there
over `Canonical.encode`; here two of the programs are restated by hand — `p42`, the facts
note's §6 receipt, and `pCatch`, which crosses a `CauseTerm` frame and an `Option Term`
frame — and the reader is exercised without the class, so that no other instance in scope
can answer for it. The hex literals are the golden files' contents. -/

namespace ProgramAcceptance

open Effect4.Program (Eff NativeOp Term Lit CauseTerm)

/-- `Effect.succeed(42)`: `Wire.Corpus.p42`, restated. -/
def p42 : Eff NativeOp := .succeed (.lit (.nat 42))

/-- A failure and an interrupt in one cause, caught: `Wire.Corpus.pCatch`, restated. -/
def pCatch : Eff NativeOp :=
  .catchCause (.failCause (.both (.fail (.lit (.nat 1))) (.interrupt none)))
    (.succeed (.lit .unit))

def programs : List (Eff NativeOp) := [p42, pCatch]

/-- The generated bytes of a program, lowercase hex: the goldens' spelling. -/
def genHex (p : Eff NativeOp) : String := hexString (Val.encode (ProgramGen.EffC.toValEff p))

/-- The generated exact decoder, spelled without the instance. -/
def genDecode (b : Bytes) : Option (Eff NativeOp) :=
  (Val.decode b).bind (guarded ProgramGen.EffC.toValEff ProgramGen.EffC.rawEff)

-- The bytes, against `ocaml/goldens/eff/p42.hex` and `pCatch.hex`.
#guard genHex p42 =
  "0a00000000000000390200000000000000000a0000000000000027020000000000000001010a0000000000000014020000000000000001010200000000000000012a"
#guard genHex pCatch =
  "0a00000000000000c5020000000000000001090a000000000000007b020000000000000001020a0000000000000068020000000000000001030a00000000000000390200000000000000000a0000000000000027020000000000000001010a000000000000001402000000000000000101020000000000000001010a0000000000000013020000000000000001020600000000000000000a000000000000002e0200000000000000000a000000000000001c020000000000000001010a0000000000000009020000000000000000"

-- The facts note's §6 receipts, on the generated image.
#guard (Val.encode (ProgramGen.EffC.toValEff p42)).length = 66
#guard (sha256 (Val.encode (ProgramGen.EffC.toValEff p42))).hex =
  "fa5f40f054198e91b2446522308e197b0a02c4edfe823f894763d3aa63ad62a3"

-- The generated reader round-trips and refuses a byte appended or dropped.
#guard programs.all fun p => genDecode (Val.encode (ProgramGen.EffC.toValEff p)) = some p
#guard programs.all fun p => genDecode (Val.encode (ProgramGen.EffC.toValEff p) ++ [0]) = none
#guard programs.all fun p =>
  genDecode (Val.encode (ProgramGen.EffC.toValEff p)).dropLast = none
-- A non-canonical natural inside a program is refused (the Wire's rule, restated).
#guard genDecode
  (framed Tag.ctor (framed Tag.nat [0, 17] ++ Val.encode (ProgramGen.TermC.toValTerm (.lit .unit))))
  = none

-- Every tree fits the generated shape.
#guard programs.all fun p =>
  (ShapeDoc.mk (.named "Eff") ProgramGen.EffC.defs).accepts (ProgramGen.EffC.toValEff p)

-- The alphabets read back constructor by constructor: the law `ofVal_toVal`, run.
#guard [Lit.unit, .nat 42, .bool true, .bool false, .str "x"].all fun l =>
  ProgramGen.LitC.ofVal (ProgramGen.LitC.toVal l) = some l
#guard [NativeOp.refMake, .refGet, .refSet, .refGetAndSet, .refSetAndGet, .refUpdate .incr,
    .refGetAndUpdate .double, .refUpdateAndGet .noChange, .refUpdateSome .incr,
    .refGetAndUpdateSome .incr, .refUpdateSomeAndGet .incr, .refModify .takeAndBump,
    .refModifySome .incr, .deferredMake, .deferredIsDone, .deferredPoll, .deferredSucceed,
    .deferredFail, .deferredAwait, .scopeMake .parallel].all fun o =>
  ProgramGen.NativeOpC.ofVal (ProgramGen.NativeOpC.toVal o) = some o
#guard [CauseTerm.fail (.lit (.nat 1)), .die (.var 0), .interrupt none,
    .interrupt (some (.var 1)), .both (.fail (.var 0)) (.die (.var 1))].all fun c =>
  guarded ProgramGen.CauseTermC.toValCauseTerm ProgramGen.CauseTermC.rawCauseTerm
    (ProgramGen.CauseTermC.toValCauseTerm c) = some c

end ProgramAcceptance
