export const main: Effect.Effect<readonly [number, number, number, number, number, number], never, never> = Effect.flatMap(Effect.flatMap(Ref.make(5), (a0) => Effect.flatMap(Ref.make(recordValue<{ readonly next: number; readonly permits: number; readonly taken: number; readonly waiters: ReadonlyArray<{ readonly hint: Deferred.Deferred<void, never>; readonly id: Deferred.Deferred<void, never>; readonly need: number; readonly stamp: number }> }>([10, [20], [[4, [[5, [3, "permits"], [5, [1, false], [10, [2], []]]], [5, [3, "taken"], [5, [1, false], [10, [2], []]]], [5, [3, "waiters"], [5, [1, false], [10, [8], [[10, [20], [[4, [[5, [3, "hint"], [5, [1, false], [10, [17], [[10, [1], []], [10, [], []]]]]], [5, [3, "id"], [5, [1, false], [10, [17], [[10, [1], []], [10, [], []]]]]], [5, [3, "need"], [5, [1, false], [10, [2], []]]], [5, [3, "stamp"], [5, [1, false], [10, [2], []]]]]]]]]]]], [5, [3, "next"], [5, [1, false], [10, [2], []]]]]]]], { permits: 1, taken: 0, waiters: nil(), next: 0 })), (a1) => Effect.succeed(recordValue<{ readonly backing: Ref.Ref<number>; readonly semaphore: Ref.Ref<{ readonly next: number; readonly permits: number; readonly taken: number; readonly waiters: ReadonlyArray<{ readonly hint: Deferred.Deferred<void, never>; readonly id: Deferred.Deferred<void, never>; readonly need: number; readonly stamp: number }> }> }>([10, [20], [[4, [[5, [3, "backing"], [5, [1, false], [10, [16], [[10, [2], []]]]]], [5, [3, "semaphore"], [5, [1, false], [10, [16], [[10, [20], [[4, [[5, [3, "next"], [5, [1, false], [10, [2], []]]], [5, [3, "permits"], [5, [1, false], [10, [2], []]]], [5, [3, "taken"], [5, [1, false], [10, [2], []]]], [5, [3, "waiters"], [5, [1, false], [10, [8], [[10, [20], [[4, [[5, [3, "hint"], [5, [1, false], [10, [17], [[10, [1], []], [10, [], []]]]]], [5, [3, "id"], [5, [1, false], [10, [17], [[10, [1], []], [10, [], []]]]]], [5, [3, "need"], [5, [1, false], [10, [2], []]]], [5, [3, "stamp"], [5, [1, false], [10, [2], []]]]]]]]]]]]]]]]]]]]]]]], { backing: a0, semaphore: a1 })))), (a0) => Effect.flatMap(Effect.flatMap(Effect.uninterruptibleMask((a1) => Effect.succeed(a1)), (a1) => Effect.uninterruptible(Effect.flatMap(Effect.flatMap(Deferred.make<void, never>(), (a2) => Effect.flatMap(Effect.suspend(() => {
  let a3: Option.Option<number> = none()
  return Effect.map(Effect.whileLoop({
    while: () => not(isSome(a3)),
    body: () => Effect.flatMap(Deferred.make<void, never>(), (a4) => Effect.flatMap(Ref.modify(recordRequired<"semaphore">("semaphore")(a0), (a5) => ite(not(lt(sub(recordRequired<"permits">("permits")(a5), recordRequired<"taken">("taken")(a5)), 1)), pair(true, recordSet<"waiters">("waiters")(recordSet<"taken">("taken")(a5)(add(recordRequired<"taken">("taken")(a5), 1)))(fold(recordRequired<"waiters">("waiters")(a5), take(recordRequired<"waiters">("waiters")(a5), 0), (a6, a7) => ite(not(sameHandle(recordRequired<"id">("id")(a7), a2)), append(a6, cons(a7, nil())), a6)))), pair(false, recordSet<"next">("next")(recordSet<"waiters">("waiters")(a5)(append(fold(recordRequired<"waiters">("waiters")(a5), take(recordRequired<"waiters">("waiters")(a5), 0), (a6, a7) => ite(not(sameHandle(recordRequired<"id">("id")(a7), a2)), append(a6, cons(a7, nil())), a6)), cons(recordValue<{ readonly hint: Deferred.Deferred<void, never>; readonly id: Deferred.Deferred<void, never>; readonly need: number; readonly stamp: number }>([10, [20], [[4, [[5, [3, "hint"], [5, [1, false], [10, [17], [[10, [1], []], [10, [], []]]]]], [5, [3, "id"], [5, [1, false], [10, [17], [[10, [1], []], [10, [], []]]]]], [5, [3, "need"], [5, [1, false], [10, [2], []]]], [5, [3, "stamp"], [5, [1, false], [10, [2], []]]]]]]], { hint: a4, id: a2, need: 1, stamp: recordRequired<"next">("next")(a5) }), nil()))))(add(recordRequired<"next">("next")(a5), 1))))), (a5) => Effect.suspend(() => a5 ? Effect.succeed(some(1)) : Effect.flatMap(Effect.onExit(pipe(Deferred.await(a4), a1), (a6) => Effect.suspend(() => causeIsInterrupt(a6) ? Ref.modify(recordRequired<"semaphore">("semaphore")(a0), (a7) => pair(undefined, recordSet<"waiters">("waiters")(a7)(fold(recordRequired<"waiters">("waiters")(a7), take(recordRequired<"waiters">("waiters")(a7), 0), (a8, a9) => ite(not(sameHandle(recordRequired<"id">("id")(a9), a2)), append(a8, cons(a9, nil())), a8))))) : Effect.succeed(undefined))), (a6) => Effect.succeed(none()))))),
    step: (a4) => {
      a3 = a4
    },
  }), () => a3)
}), (a3) => optionCase(a3, () => Effect.failCause(Cause.die("semaphore: the loop ended without a take")), (a4) => Effect.succeed(a4)))), (a2) => Effect.onExit(pipe(Ref.modify(recordRequired<"backing">("backing")(a0), (a3) => pair(a3, add(a3, fold(cons(4, nil()), 0, (a4, a5) => a5)))), a1), (a3) => Effect.uninterruptible(Effect.flatMap(Ref.modify(recordRequired<"semaphore">("semaphore")(a0), (a4) => pair(tuple(sub(recordRequired<"permits">("permits")(a4), sub(recordRequired<"taken">("taken")(a4), 1)), not(isZero(length(recordRequired<"waiters">("waiters")(a4))))), recordSet<"taken">("taken")(a4)(sub(recordRequired<"taken">("taken")(a4), 1)))), (a4) => Effect.flatMap(Effect.suspend(() => tupleAt<"1">("1")(a4) ? Effect.flatMap(Effect.forkDetach(Effect.suspend(() => {
  let a5 = some(0)
  return Effect.map(Effect.whileLoop({
    while: () => isSome(a5),
    body: () => Effect.flatMap(Ref.modify(recordRequired<"semaphore">("semaphore")(a0), (a6) => ite(isZero(sub(recordRequired<"permits">("permits")(a6), recordRequired<"taken">("taken")(a6))), pair(get(take(recordRequired<"waiters">("waiters")(a6), 0), 0), a6), pair(get(fold(recordRequired<"waiters">("waiters")(a6), take(recordRequired<"waiters">("waiters")(a6), 0), (a7, a8) => ite(or(not(isZero(length(a7))), and(not(lt(recordRequired<"stamp">("stamp")(a8), getOrElse(a5, 0))), not(lt(sub(recordRequired<"permits">("permits")(a6), recordRequired<"taken">("taken")(a6)), recordRequired<"need">("need")(a8))))), append(a7, cons(a8, nil())), a7)), 0), recordSet<"waiters">("waiters")(a6)(append(take(recordRequired<"waiters">("waiters")(a6), sub(length(recordRequired<"waiters">("waiters")(a6)), length(fold(recordRequired<"waiters">("waiters")(a6), take(recordRequired<"waiters">("waiters")(a6), 0), (a7, a8) => ite(or(not(isZero(length(a7))), and(not(lt(recordRequired<"stamp">("stamp")(a8), getOrElse(a5, 0))), not(lt(sub(recordRequired<"permits">("permits")(a6), recordRequired<"taken">("taken")(a6)), recordRequired<"need">("need")(a8))))), append(a7, cons(a8, nil())), a7))))), drop(fold(recordRequired<"waiters">("waiters")(a6), take(recordRequired<"waiters">("waiters")(a6), 0), (a7, a8) => ite(or(not(isZero(length(a7))), and(not(lt(recordRequired<"stamp">("stamp")(a8), getOrElse(a5, 0))), not(lt(sub(recordRequired<"permits">("permits")(a6), recordRequired<"taken">("taken")(a6)), recordRequired<"need">("need")(a8))))), append(a7, cons(a8, nil())), a7)), 1)))))), (a6) => optionCase(a6, () => Effect.succeed(none()), (a7) => Effect.flatMap(Deferred.succeed(recordRequired<"hint">("hint")(a7), undefined), (a8) => Effect.succeed(some(add(recordRequired<"stamp">("stamp")(a7), 1)))))),
    step: (a6) => {
      a5 = a6
    },
  }), () => undefined)
}), { startImmediately: false, uninterruptible: true }), (a5) => Effect.succeed(undefined)) : Effect.succeed(undefined)), (a5) => Effect.succeed(tupleAt<"0">("0")(a4))))))))), (a1) => Effect.flatMap(Ref.get(recordRequired<"backing">("backing")(a0)), (a2) => Effect.flatMap(Ref.get(recordRequired<"semaphore">("semaphore")(a0)), (a3) => Effect.succeed(tuple(a1, a2, recordRequired<"permits">("permits")(a3), recordRequired<"taken">("taken")(a3), length(recordRequired<"waiters">("waiters")(a3)), recordRequired<"next">("next")(a3)))))))
