import Effect4.Laws.Machine.Clauses
import Effect4.Laws.Machine.Approximation
import Effect4.Laws.Machine.RefKernel
import Effect4.Laws.Machine.StoresLaws
import Effect4.Laws.Machine.Clock
import Effect4.Laws.Machine.Behaviour
import Effect4.Laws.Machine.Book
import Effect4.Laws.Machine.ContextValue
import Effect4.Laws.Machine.Handles
import Effect4.Laws.Machine.LiveStack
import Effect4.Laws.Machine.MaskDiscipline
import Effect4.Laws.Machine.MaskRuns
import Effect4.Laws.Program.MaskRuns
import Effect4.Laws.Api.MaskRuns
import Effect4.Laws.Machine.MaskBracket
import Effect4.Laws.Program.MaskBracket
import Effect4.Laws.Machine.Scheduling
import Effect4.Laws.Machine.ScopeMachine
import Effect4.Laws.Machine.ScopeRestoration
import Effect4.Laws.Machine.StoresValue
import Effect4.Laws.Machine.Witnesses
import Effect4.Laws.Program.Denote
import Effect4.Laws.Program.Iter
import Effect4.Laws.Program.DenoteB
import Effect4.Laws.Program.IterLimit
import Effect4.Laws.Program.StoreComodel
import Effect4.Laws.Program.Folds.Looped
import Effect4.Laws.Program.Folds.Denote
import Effect4.Laws.Machine.Folds.Val
import Effect4.Laws.Program.LoopAgreement
import Effect4.Laws.Program.MeaningSound
import Effect4.Laws.Program.LoopSound
import Effect4.Laws.Program.TypedRun
import Effect4.Laws.Program.Agreement.Loop
import Effect4.Laws.Program.Agreement
import Effect4.Laws.Program.Agreement.Machine
import Effect4.Laws.Program.MeaningEq
import Effect4.Laws.Program.Sched
import Effect4.Laws.Program.DenoteR
import Effect4.Laws.Program.InterpR
import Effect4.Laws.Program.EvaluateR
import Effect4.Laws.Program.ScopeMarkers
import Effect4.Laws.Program.Typed
import Effect4.Laws.Program.Typed.RecordValues
import Effect4.Laws.Program.Typed.RecordOperations
import Effect4.Laws.Program.ScopedTyping
import Effect4.Laws.Program.TypeAlgebra
import Effect4.Laws.Program.Provision
import Effect4.Laws.Program.BuildTotal
import Effect4.Laws.Program.Template
import Effect4.Laws.Program.Residual
import Effect4.Laws.Program.Decision
import Effect4.Laws.Program.HostBoundary
import Effect4.Laws.Api.HostSession
import Effect4.Laws.Api.Runner
import Effect4.Laws.Api.RunnerBytes
import Effect4.Laws.Api.Frontier
import Effect4.Laws.Api.Fuel
import Effect4.Laws.Api.Guard
import Effect4.Laws.Api.Supervision
import Effect4.Laws.Api.Codegen
import Effect4.Laws.Api.Formation
import Effect4.Laws.Run
import Effect4.Laws.Run.Rows
import Effect4.Laws.Run.Tape
import Effect4.Laws.Program.Handles
import Effect4.Laws.Program.Means
import Effect4.Laws.Program.Intro
import Effect4.Laws.Program.Progress
import Effect4.Laws.Program.Simulation.Hooks
import Effect4.Laws.Program.Simulation.Walk
import Effect4.Laws.Program.Simulation.Fibers
import Effect4.Laws.Program.Simulation.Deliver
import Effect4.Laws.Program.Simulation.Actions
import Effect4.Laws.Program.Simulation.Evaluate
import Effect4.Laws.Program.Simulation.Pending
import Effect4.Laws.Program.Simulation.Drive
import Effect4.Laws.Program.RuntimeR
import Effect4.Laws.Program.ReasonsR
import Effect4.Laws.Program.Guard
import Effect4.Laws.Program.LayerSharing
import Effect4.Laws.Program.ReferenceTyping
import Effect4.Laws.Program.PathFold
import Effect4.Laws.Program.ReferenceExpansion
import Effect4.Laws.Program.ExpandFix
import Effect4.Laws.Program.Hoisting
import Effect4.Laws.Program.HoistingTotal
import Effect4.Laws.Program.Invocation
import Effect4.Laws.Program.ValueModel
import Effect4.Laws.Program.LinkedRows
import Effect4.Laws.Program.Typing.Sound
import Effect4.Laws.Program.Typing.Check
import Effect4.Laws.Program.Typing.CheckInversion
import Effect4.Laws.Program.Typing.CheckSound
import Effect4.Laws.Codegen.Forms
import Effect4.Laws.Codegen.Module
import Effect4.Laws.Auto.RuleSets
import Effect4.Laws.Program.AtomRules
import Effect4.Laws.Program.TyView
import Effect4.Laws.Program.Admits
import Effect4.Laws.Auto.Inversion
import Effect4.Laws.Auto.Census
import Effect4.Laws.Auto.Traversals
import Effect4.Laws.Auto.Exhaustive
import Effect4.Laws.Auto.Positions
import Effect4.Laws.Program.Typed.PositionGate
import Effect4.Laws.Program.Typed.TypedStateDecl
import Effect4.Laws.Auto.Frames
import Effect4.Laws.Auto.Obligations
import Effect4.Laws.Auto.BankCensus
import Effect4.Laws.Auto.Semantics
import Effect4.Laws.Effects.Protocol
import Effect4.Laws.Effects.Sum
import Effect4.Laws.Program.Typed.ProtocolObligations
import Effect4.Laws.Program.Typed.Vocabulary
import Effect4.Laws.Program.Typed.TypedSources
import Effect4.Laws.Program.Typed.Sources
import Effect4.Laws.Program.Typed.State
import Effect4.Laws.Program.Typed.Frames
import Effect4.Laws.Codegen.Template
import Effect4.Laws.Codegen.Read
import Effect4.Laws.Codegen.Metadata
import Effect4.Laws.Codegen.Record
import Effect4.Laws.Codegen.ReadPrint
import Effect4.Laws.Codegen.PrintReadable
import Effect4.Laws.Api.ModuleReadable
import Effect4.Laws.Store.CanonicalSpec
import Effect4.Laws.Schema.Codec
import Effect4.Laws.Program.Authoring
import Effect4.Laws.Program.Authoring.Records
import Effect4.Laws.Program.Authoring.Tuples
import Effect4.Laws.Program.Authoring.Folds
import Effect4.Laws.Program.Typed.ListFold
import Effect4.Laws.Program.Authoring.Lifts
import Effect4.Laws.Program.Authoring.Rows
import Effect4.Laws.Program.Authoring.Forms
import Effect4.Laws.Program.Authoring.Sugar
import Effect4.Laws.Program.Authoring.Loops
import Effect4.Laws.Program.Authoring.Mask
import Effect4.Laws.Program.Authoring.Ascribe
import Effect4.Laws.Program.Typed.Mask
import Effect4.Laws.Codegen.Mask
import Effect4.Laws.Program.Author
import Effect4.Laws.Machine.Refinement
import Effect4.Laws.Program.Typed.World
import Effect4.Laws.Program.Typed.Contracts
import Effect4.Laws.Program.Typed.Validity
import Effect4.Laws.Program.Typed.ForkSource
import Effect4.Laws.Program.Typed.Admission
import Effect4.Laws.Program.Typed.ExitConnector
import Effect4.Laws.Program.Typed.Residual
import Effect4.Laws.Program.Typed.Seq
import Effect4.Laws.Program.Typed.Commands.Bookkeeping
import Effect4.Laws.Program.Typed.Commands.Finish
import Effect4.Laws.Program.Typed.Commands.Race
import Effect4.Laws.Program.Typed.Commands.Registration
import Effect4.Laws.Program.Typed.Commands.Launch
import Effect4.Laws.Program.Typed.Commands.Observe
import Effect4.Laws.Program.Typed.Commands.Evaluate
import Effect4.Laws.Program.Typed.Commands.Clauses.Answer
import Effect4.Laws.Program.Typed.Commands.Clauses.Park
import Effect4.Laws.Program.Typed.Commands.Clauses.Spawn
import Effect4.Laws.Program.Typed.Commands.Clauses.Command
import Effect4.Laws.Program.Typed.Commands.Clauses.Loop
import Effect4.Laws.Program.Typed.Commands.Clauses.Store
import Effect4.Laws.Program.Typed.Commands.Clauses.All
import Effect4.Laws.Program.Typed.Results
import Effect4.Laws.Program.Typed.Edits
import Effect4.Laws.Program.Typed.AnswerSchema
import Effect4.Laws.Program.Typed.Stack
import Effect4.Laws.Program.Typed.Assembly
import Effect4.Laws.Program.Typed.HostWalk
import Effect4.Laws.Program.Typed.LayerArm
import Effect4.Laws.Program.Typed.Body
import Effect4.Laws.Program.Signature
import Effect4.Laws.Program.SoundAnySignature
import Effect4.Laws.Program.Typed.AdmittedSource
import Effect4.Laws.Auto.AnswerGate
import Effect4.Laws.Machine.Handshake
import Effect4.Laws.Machine.Keeps
import Effect4.Laws.Program.Guard.Handshake

import Effect4.Laws.Program.Folds.Checker
import Effect4.Laws.Program.Folds.Projections
import Effect4.Laws.Program.Folds.Provision
import Effect4.Laws.Program.Folds.Representation
import Effect4.Laws.Program.Folds.Straight
import Effect4.Laws.Program.Folds.Term
import Effect4.Laws.Program.Folds.Ty
import Effect4.Laws.Machine.Folds.Stores
import Effect4.Laws.Store.Folds.Val
import Effect4.Laws.Program.Typing.FoldAgreement
import Effect4.Laws.Modules.Table
import Effect4.Laws.Modules.Reading
import Effect4.Laws.Modules.Checking
import Effect4.Laws.Modules.Ascribe
import Effect4.Laws.Modules.Store
import Effect4.Laws.Modules.Queue.Capacity
import Effect4.Laws.Modules.Queue.Profile
import Effect4.Laws.Modules.Queue.Typing
import Effect4.Laws.Modules.Queue.Relation
import Effect4.Laws.Modules.Queue.Reading
import Effect4.Laws.Modules.Queue.Steps
import Effect4.Laws.Modules.Waiting
import Effect4.Laws.Modules.Queue.Ops
import Effect4.Laws.Modules.Queue.Invariant
import Effect4.Laws.Modules.Semaphore.Model
import Effect4.Laws.Modules.Semaphore.Profile
import Effect4.Laws.Modules.Semaphore.Typing
import Effect4.Laws.Modules.Semaphore.Relation
import Effect4.Laws.Modules.Semaphore.Reading
import Effect4.Laws.Modules.Semaphore.Steps
import Effect4.Laws.Modules.Semaphore.Ops
import Effect4.Laws.Modules.Pool.Model
import Effect4.Laws.Modules.Pool.Profile
import Effect4.Laws.Modules.Pool.Typing
import Effect4.Laws.Modules.Pool.Relation
import Effect4.Laws.Modules.Pool.Reading
import Effect4.Laws.Modules.Pool.Steps
import Effect4.Laws.Modules.Pool.Ops
import Effect4.Laws.Program.Typing.TermIntro

/-!
# Effect4 proof graph

The machine and program judgments, simulation, composition and execution laws.
These modules continue their definition modules' namespaces; the module paths
separate build targets. `import Effect4` never reaches this root.
-/
