(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400087`, seed 400087, 34 operations.
   Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400087 () =
  let v0 = Fibers_fixture.fork 0 in
  let v1 = Store_fixtures.ref_make 5 in
  ignore (Fibers_fixture.interrupt v0);
  let _v2 = Fibers_fixture.cleanups () in
  let _v3 = Extra_fixture.interrupt_all [ v0 ] in
  ignore (Store_fixtures.ref_set v1 7);
  let _v4 = Fibers_fixture.started () in
  let _v5 = Fibers_fixture.started () in
  ignore (Store_fixtures.ref_set v1 4);
  let _v6 = Fibers_fixture.started () in
  let _v7 = Extra_fixture.await_all [ v0 ] in
  let _v8 = Fibers_fixture.await_error v0 in
  let _v9 = Store_fixtures.ref_make 6 in
  let _v10 = Store_fixtures.scope_make () in
  let _v11 = Fibers_fixture.cleanups () in
  let v12 = Fibers_fixture.fork 0 in
  let _v13 = Store_fixtures.layer_build 1 in
  ignore (Store_fixtures.ref_update v1 10);
  let _v14 = Fibers_fixture.cleanups () in
  let _v15 = Fibers_fixture.started () in
  let v16 = Fibers_fixture.fork 1 in
  let _v17 = Extra_fixture.interrupt_all [ v12 ] in
  let _v18 = Fibers_fixture.await_value v0 in
  let _v19 = Fibers_fixture.started () in
  let _v20 = Store_fixtures.ref_modify v1 1 in
  let _v21 = Fibers_fixture.cleanups () in
  let _v22 = Fibers_fixture.join v16 in
  let _v23 = Store_fixtures.layer_provide_count 3 in
  let _v24 = Store_fixtures.layer_provide_count 3 in
  let _v25 = Fibers_fixture.await_error v16 in
  let _v26 = Fibers_fixture.cleanups () in
  let _v27 = Fibers_fixture.cleanups () in
  let _v28 = Store_fixtures.ref_get v1 in
  let v29 = Fibers_fixture.join v16 in
  v29

let programs : (string * (unit -> value)) list = [ ("p400087", corpus_p400087) ]
