(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400008`, seed 400008, 21 operations.
   Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400008 () =
  let v0 = Fibers_fixture.fork 0 in
  let _v1 = Fibers_fixture.fork 0 in
  let _v2 = Fibers_fixture.cleanups () in
  let _v3 = Fibers_fixture.await_value v0 in
  let _v4 = Store_fixtures.scope_make () in
  let _v5 = Fibers_fixture.started () in
  let _v6 = Fibers_fixture.cleanups () in
  let _v7 = Fibers_fixture.cleanups () in
  let _v8 = Fibers_fixture.cleanups () in
  let _v9 = Fibers_fixture.started () in
  let v10 = Fibers_fixture.fork 4 in
  let _v11 = Store_fixtures.ref_make 4 in
  let _v12 = Fibers_fixture.cleanups () in
  let _v13 = Fibers_fixture.started () in
  let _v14 = Fibers_fixture.join v0 in
  let _v15 = Store_fixtures.layer_build 0 in
  let _v16 = Fibers_fixture.started () in
  let _v17 = Fibers_fixture.await_error v10 in
  ignore (Extra_fixture.yield ());
  let _v18 = Fibers_fixture.fork 4 in
  let v19 = Fibers_fixture.await_value v0 in
  v19

let programs : (string * (unit -> value)) list = [ ("p400008", corpus_p400008) ]
