import Effect4.Laws.Program.TypeAlgebra

#print axioms Effect4.Row.antichain
#print axioms Effect4.Row.antichain_subset
#print axioms Effect4.Row.mem_antichain_iff
#print axioms Effect4.Row.antichain_idem
#print axioms Effect4.Row.antichain_coverage
#print axioms Effect4.Row.antichain_append_left
#print axioms Effect4.Row.antichain_append_right
#print axioms Effect4.Row.antichain_sublist
#print axioms Effect4.Row.antichain_pairwise
#print axioms Effect4.Row.ascending_antichain
#print axioms Effect4.Row.antichain_eq_self_iff
#print axioms Effect4.Row.antichain_singleton
#print axioms Effect4.Program.Ty.factors_isFactor
#print axioms Effect4.Program.Ty.factors_singleton
#print axioms Effect4.Program.Ty.mem_normalizeRow
#print axioms Effect4.Program.Ty.Normal.members
#print axioms Effect4.Program.Ty.Normal.factors
#print axioms Effect4.Program.Ty.normal_row
#print axioms Effect4.Program.Ty.normal_normalize
#print axioms Effect4.Program.Ty.normalize_ofMembers_fixed
#print axioms Effect4.Program.Ty.Normal.fixed
#print axioms Effect4.Program.hasTy_normalizeRow
#print axioms Effect4.Program.hasTy_factors
#print axioms Effect4.Program.hasTy_productMembers
#print axioms Effect4.Program.Ty.Normal.members_ascending
#print axioms Effect4.Program.Ty.Normal.ofMembers_members
#print axioms Effect4.Program.Ty.Normal.members_maximal
#print axioms Effect4.Program.Ty.normalizeRow_congr
#print axioms Effect4.Program.Ty.normalizeRow_append_comm
#print axioms Effect4.Program.Ty.normalizeRow_coverage
#print axioms Effect4.Program.Ty.normalizeRow_append_left
#print axioms Effect4.Program.Ty.normalizeRow_append_right
#print axioms Effect4.Program.Ty.normalizeRow_fixed
#print axioms Effect4.Program.Ty.join_eq_ofMembers
#print axioms Effect4.Program.Ty.normalize_join
#print axioms Effect4.Program.Ty.members_join
#print axioms Effect4.Program.Ty.key_injective
#print axioms Effect4.Program.Ty.ltKey_iff_lex
#print axioms Effect4.Program.Ty.instIsLinearOrder
#print axioms Effect4.Program.Ty.instLawfulOrderLT
#print axioms Effect4.Program.Ty.normalize_idem
#print axioms Effect4.Program.CTy.ofRaw
#print axioms Effect4.Program.CTy.ofRaw_toRaw
#print axioms Effect4.Program.hasTy_fibers
#print axioms Effect4.Program.hasTy_fibers_nil
#print axioms Effect4.Program.hasTy_normalize
#print axioms Effect4.Program.hasTy_of_normalize_eq
#print axioms Effect4.Program.Ty.join_comm
#print axioms Effect4.Program.Ty.join_assoc
#print axioms Effect4.Program.Ty.join_self
#print axioms Effect4.Program.Ty.join_never
#print axioms Effect4.Program.Ty.join_never_right
#print axioms Effect4.Program.CTy.join_self
#print axioms Effect4.Program.CTy.join_never
#print axioms Effect4.Program.CTy.join_comm
#print axioms Effect4.Program.CTy.join_assoc
