import Effect4.Laws.Program.TypeAlgebra

#print axioms Effect4.Row.antichain
#print axioms Effect4.Row.antichain_subset
#print axioms Effect4.Row.mem_antichain_iff
#print axioms Effect4.Row.antichain_idem
#print axioms Effect4.Row.antichain_coverage
#print axioms Effect4.Row.antichain_append_left
#print axioms Effect4.Row.antichain_append_right
#print axioms Effect4.Row.antichain_sublist
#print axioms Effect4.Row.antichain_pairwise
#print axioms Effect4.Row.ascending_antichain
#print axioms Effect4.Row.antichain_eq_self_iff
#print axioms Effect4.Row.antichain_singleton
#print axioms Effect4.Program.Ty.factors_isFactor
#print axioms Effect4.Program.Ty.factors_singleton
#print axioms Effect4.Program.Ty.mem_normalizeRow
#print axioms Effect4.Program.Ty.Normal.members
#print axioms Effect4.Program.Ty.Normal.factors
#print axioms Effect4.Program.Ty.normal_row
#print axioms Effect4.Program.Ty.normal_normalize
#print axioms Effect4.Program.Ty.normalize_ofMembers_fixed
#print axioms Effect4.Program.Ty.Normal.fixed
#print axioms Effect4.Program.hasTy_normalizeRow
#print axioms Effect4.Program.hasTy_factors
#print axioms Effect4.Program.hasTy_productMembers
#print axioms Effect4.Program.Ty.Normal.members_ascending
#print axioms Effect4.Program.Ty.Normal.ofMembers_members
#print axioms Effect4.Program.Ty.Normal.members_maximal
#print axioms Effect4.Program.Ty.normalizeRow_congr
#print axioms Effect4.Program.Ty.normalizeRow_append_comm
#print axioms Effect4.Program.Ty.normalizeRow_coverage
#print axioms Effect4.Program.Ty.normalizeRow_append_left
#print axioms Effect4.Program.Ty.normalizeRow_append_right
#print axioms Effect4.Program.Ty.normalizeRow_fixed
#print axioms Effect4.Program.Ty.join_eq_ofMembers
#print axioms Effect4.Program.Ty.normalize_join
#print axioms Effect4.Program.Ty.members_join
#print axioms Effect4.Program.Ty.key_injective
#print axioms Effect4.Program.Ty.ltKey_iff_lex
#print axioms Effect4.Program.Ty.instIsLinearOrder
#print axioms Effect4.Program.Ty.instLawfulOrderLT
#print axioms Effect4.Program.Ty.normalize_idem
#print axioms Effect4.Program.CTy.ofRaw
#print axioms Effect4.Program.CTy.ofRaw_toRaw
#print axioms Effect4.Program.hasTy_fibers
#print axioms Effect4.Program.hasTy_fibers_nil
#print axioms Effect4.Program.hasTy_normalize
#print axioms Effect4.Program.hasTy_of_normalize_eq
#print axioms Effect4.Program.Ty.join_comm
#print axioms Effect4.Program.Ty.join_assoc
#print axioms Effect4.Program.Ty.join_self
#print axioms Effect4.Program.Ty.join_never
#print axioms Effect4.Program.Ty.join_never_right
#print axioms Effect4.Program.CTy.join_self
#print axioms Effect4.Program.CTy.join_never
#print axioms Effect4.Program.CTy.join_comm
#print axioms Effect4.Program.CTy.join_assoc

#print axioms Effect4.Program.Ty.sub_trans
#print axioms Effect4.Program.Ty.sub_normalize_of_sub
#print axioms Effect4.Program.Ty.sub_antisymm_canonical
#print axioms Effect4.Program.Ty.sub_join_left
#print axioms Effect4.Program.Ty.sub_join_right
#print axioms Effect4.Program.Ty.join_least
#print axioms Effect4.Program.CTy.key
#print axioms Effect4.Program.CTy.key_injective
#print axioms Effect4.Program.CTy.render_toRaw
#print axioms Effect4.Program.CTy.instIsPartialOrder
#print axioms Effect4.Program.CTy.instLawfulOrderLT
#print axioms Effect4.Program.CTy.instLawfulOrderSup
#print axioms Effect4.Program.CTy.never_le

#print axioms Effect4.Program.ErrTy.instIsPartialOrder
#print axioms Effect4.Program.ErrTy.instLawfulOrderSup
#print axioms Effect4.Program.ErrTy.never_le
#print axioms Effect4.Program.ErrTy.le_join_left
#print axioms Effect4.Program.ErrTy.le_join_right
#print axioms Effect4.Program.ErrTy.join_least
#print axioms Effect4.Program.ErrTy.join_comm
#print axioms Effect4.Program.ErrTy.join_assoc
#print axioms Effect4.Program.ErrTy.join_self
#print axioms Effect4.Program.ErrTy.join_never
#print axioms Effect4.Program.ErrTy.join_never_right
#print axioms Effect4.Program.rawSupportedErrTy
#print axioms Effect4.Program.rawSupportedErrTy_iff_members
#print axioms Effect4.Program.rawSupportedErrTy_ofMembers
#print axioms Effect4.Program.supportedErrTy
#print axioms Effect4.Program.supportedErrTy_normalize
#print axioms Effect4.Program.supportedErrTy_never
#print axioms Effect4.Program.supportedErrTy_join
#print axioms Effect4.Program.admittedErrTy_eq
#print axioms Effect4.Program.admittedErrTy_eq_raw
#print axioms Effect4.Program.ErrTy.canonical
#print axioms Effect4.Program.ErrTy.supported
#print axioms Effect4.Program.ErrTy.admitted
#print axioms Effect4.Program.ErrTy.never
#print axioms Effect4.Program.ErrTy.join
#print axioms Effect4.Program.ErrTy.toRaw_never
#print axioms Effect4.Program.ErrTy.toRaw_join
#print axioms Effect4.Program.ErrTy.ext
