(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400060`, seed 400060, 25 operations.
   Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400060 () =
  let v0 = Fibers_fixture.fork_detach 4 in
  let _v1 = Fibers_fixture.cleanups () in
  let _v2 = Fibers_fixture.cleanups () in
  let v3 = Fibers_fixture.fork 0 in
  let _v4 = Fibers_fixture.started () in
  let _v5 = Fibers_fixture.started () in
  let _v6 = Fibers_fixture.await_error v3 in
  let _v7 = Extra_fixture.await_all [ v0 ] in
  let _v8 = Extra_fixture.interrupt_all [ v3 ] in
  let _v9 = Fibers_fixture.cleanups () in
  let _v10 = Store_fixtures.layer_build 2 in
  let _v11 = Fibers_fixture.await_value v0 in
  let _v12 = Fibers_fixture.await_value v0 in
  let _v13 = Fibers_fixture.started () in
  let _v14 = Fibers_fixture.fork 3 in
  let v15 = Store_fixtures.ref_make 9 in
  let _v16 = Store_fixtures.def_make () in
  let _v17 = Store_fixtures.ref_get_and_set v15 9 in
  let _v18 = Store_fixtures.ref_get v15 in
  let v19 = Fibers_fixture.fork 2 in
  let _v20 = Fibers_fixture.started () in
  let _v21 = Store_fixtures.ref_get_and_set v15 7 in
  let _v22 = Fibers_fixture.await_value v0 in
  let _v23 = Fibers_fixture.join v19 in
  let v24 = Fibers_fixture.join v0 in
  v24

let programs : (string * (unit -> value)) list = [ ("p400060", corpus_p400060) ]
