/**
 * Generated by OCaml5.Fuzz (spike P5, round four). Program `p400043`, seed 400043, 14 operations.
 *
 * Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`.
 */
import { Context, Effect } from "effect"
import type { Fiber, Option, Ref, Scope } from "effect"

/** Service `Fibers`: one method per operation of the Lean family, plus the three rows
 * `fiber-fixture.ts` does not declare and rc.112 does. */
export class Fibers extends Context.Service<Fibers, {
  readonly fork: (body: number) => Effect.Effect<Fiber.Fiber<number, number>>
  readonly forkDetach: (body: number) => Effect.Effect<Fiber.Fiber<number, number>>
  readonly join: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<number, number>
  readonly awaitValue: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<Option.Option<number>>
  readonly awaitError: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<Option.Option<number>>
  readonly interrupt: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<void>
  readonly started: Effect.Effect<ReadonlyArray<number>>
  readonly cleanups: Effect.Effect<ReadonlyArray<number>>
  readonly yieldNow: (priority: number) => Effect.Effect<void>
  readonly interruptAll: (fibers: ReadonlyArray<Fiber.Fiber<number, number>>) => Effect.Effect<void>
  readonly awaitAll: (fibers: ReadonlyArray<Fiber.Fiber<number, number>>) => Effect.Effect<void>
}>()("Fibers") {}

export const FibersRows = { "fork": { params: 1, answer: "Fiber.Fiber<number, number>" }, "forkDetach": { params: 1, answer: "Fiber.Fiber<number, number>" }, "join": { params: 1, answer: "number" }, "awaitValue": { params: 1, answer: "Option.Option<number>" }, "awaitError": { params: 1, answer: "Option.Option<number>" }, "interrupt": { params: 1, answer: "void" }, "started": { params: 0, answer: "ReadonlyArray<number>" }, "cleanups": { params: 0, answer: "ReadonlyArray<number>" }, "yieldNow": { params: 1, answer: "void" }, "interruptAll": { params: 1, answer: "void" }, "awaitAll": { params: 1, answer: "void" } }

/** Service `Layers` (`harness/trace/layer-fixture.ts`). */
export class Layers extends Context.Service<Layers, {
  readonly build: (layer: number) => Effect.Effect<Ref.Ref<number>>
  readonly provideCount: (layer: number) => Effect.Effect<number>
  readonly scopeOf: (service: Ref.Ref<number>) => Effect.Effect<Scope.Closeable>
  readonly close: Effect.Effect<ReadonlyArray<Ref.Ref<number>>>
}>()("Layers") {}

export const LayersRows = { "build": { params: 1, answer: "Ref.Ref<number>" }, "provideCount": { params: 1, answer: "number" }, "scopeOf": { params: 1, answer: "Scope.Closeable" }, "close": { params: 0, answer: "ReadonlyArray<Ref.Ref<number>>" } }

/** Lowered from `p400043` by OCaml5.Fuzz. */
export const corpus_p400043 = (n: number) =>
  Effect.gen(function* () {
    const fibers = yield* Fibers
    const layers = yield* Layers
    void n
    const v0 = yield* fibers.forkDetach(0)
    const v1 = yield* fibers.started
    const v2 = yield* layers.build(3)
    yield* fibers.interrupt(v0)
    const v3 = yield* fibers.cleanups
    const v4 = yield* fibers.cleanups
    const v5 = yield* layers.close
    const v6 = yield* fibers.started
    const v7 = yield* fibers.started
    const v8 = yield* fibers.started
    const v9 = yield* fibers.started
    const v10 = yield* fibers.interruptAll([v0])
    const v11 = yield* layers.close
    const v12 = yield* fibers.started
    return v12
  })
