-- GENERATED by tools/Effect4Gen/Authoring.lean; do not edit
-- GENERATED by tools/Effect4Gen/Authoring.lean from tools/Effect4Gen/binders.json and the Lean environment. Do not edit.
-- Regenerate (tools/Effect4Gen/Driver.lean runs this for every group; --verify refuses a diff):
--   lake env lean -M 4096 --run tools/Effect4Gen/Authoring.lean --group ScopedLaws --imports Effect4.Laws.Program.Authoring,Effect4.Program.Authoring.Lifts --out src/Effect4/Laws/Program/Authoring/Lifts.lean --append tools/Effect4Gen/guards/scopedlaws.lean -- Effect4.Program.Eff
-- Acceptance guards appended verbatim from: tools/Effect4Gen/guards/scopedlaws.lean
import Effect4.Laws.Program.Authoring
import Effect4.Program.Authoring.Lifts

set_option autoImplicit false

namespace Effect4.Program.Authoring

open Effect4.Program

theorem succeed_scoped {Op : Type} {value : TermSrc} (h0 : value.Scoped) :
    ((succeed value) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold succeed at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  simp [s0]

theorem fail_scoped {Op : Type} {error : TermSrc} (h0 : error.Scoped) :
    ((fail error) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold fail at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  simp [s0]

theorem failCause_scoped {Op : Type} {cause : CauseSrc} (h0 : cause.Scoped) :
    ((failCause cause) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold failCause at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  simp [s0]

theorem sync_scoped {Op : Type} {thunk : TermSrc} (h0 : thunk.Scoped) :
    ((sync thunk) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold sync at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  simp [s0]

theorem suspend_scoped {Op : Type} {body : Src Op} (h0 : body.Scoped) :
    ((suspend body) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold suspend at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  simp [s0]

theorem perform_scoped {Op : Type} (op : Op) {request : TermSrc} (h1 : request.Scoped) :
    ((perform op request) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold perform at h
  obtain ⟨x1, hx1, h⟩ := bind_ok h
  cases h
  have s1 := h1.holds _ _ _ hx1
  simp [s1]

theorem bind_scoped {Op : Type} (answer : String) {first : Src Op} {rest : Src Op} (h0 : first.Scoped) (h1 : rest.Scoped) :
    ((bind answer first rest) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold bind at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  obtain ⟨x1, hx1, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  have s1 := h1.holds _ _ _ hx1
  simp only [Env.push_length, List.length_cons, List.length_nil] at s1
  simp [s0, s1]

theorem catchCause_scoped {Op : Type} (cause : String) {body : Src Op} {handler : Src Op} (h0 : body.Scoped) (h1 : handler.Scoped) :
    ((catchCause cause body handler) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold catchCause at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  obtain ⟨x1, hx1, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  have s1 := h1.holds _ _ _ hx1
  simp only [Env.push_length, List.length_cons, List.length_nil] at s1
  simp [s0, s1]

theorem matchCause_scoped {Op : Type} (value : String) (cause : String) {body : Src Op} {onValue : Src Op} {onCause : Src Op} (h0 : body.Scoped) (h1 : onValue.Scoped) (h2 : onCause.Scoped) :
    ((matchCause value cause body onValue onCause) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold matchCause at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  obtain ⟨x1, hx1, h⟩ := bind_ok h
  obtain ⟨x2, hx2, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  have s1 := h1.holds _ _ _ hx1
  simp only [Env.push_length, List.length_cons, List.length_nil] at s1
  have s2 := h2.holds _ _ _ hx2
  simp only [Env.push_length, List.length_cons, List.length_nil] at s2
  simp [s0, s1, s2]

theorem onExit_scoped {Op : Type} (exit : String) {body : Src Op} {finalizer : Src Op} (h0 : body.Scoped) (h1 : finalizer.Scoped) :
    ((onExit exit body finalizer) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold onExit at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  obtain ⟨x1, hx1, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  have s1 := h1.holds _ _ _ hx1
  simp only [Env.push_length, List.length_cons, List.length_nil] at s1
  simp [s0, s1]

theorem exit_scoped {Op : Type} {body : Src Op} (h0 : body.Scoped) :
    ((exit body) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold exit at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  simp [s0]

theorem uninterruptible_scoped {Op : Type} {body : Src Op} (h0 : body.Scoped) :
    ((uninterruptible body) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold uninterruptible at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  simp [s0]

theorem interruptible_scoped {Op : Type} {body : Src Op} (h0 : body.Scoped) :
    ((interruptible body) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold interruptible at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  simp [s0]

theorem yieldNow_scoped {Op : Type} (priority : Nat) :
    ((yieldNow priority) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold yieldNow at h
  cases h
  simp

theorem awaitFiber_scoped {Op : Type} {fiber : TermSrc} (mode : Effect4.Supervision.ObserverMode) (h0 : fiber.Scoped) :
    ((awaitFiber fiber mode) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold awaitFiber at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  simp [s0]

theorem withFiber_scoped {Op : Type} {action : ActionSrc Op} (h0 : action.Scoped) :
    ((withFiber action) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold withFiber at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  simp [s0]

theorem scope_scoped {Op : Type} {body : Src Op} (h0 : body.Scoped) :
    ((scope body) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold scope at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  simp [s0]

theorem acquireRelease_scoped {Op : Type} (resource : String) (exit : String) {acquire : Src Op} {release : Src Op} (h0 : acquire.Scoped) (h1 : release.Scoped) :
    ((acquireRelease resource exit acquire release) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold acquireRelease at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  obtain ⟨x1, hx1, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  have s1 := h1.holds _ _ _ hx1
  simp only [Env.push_length, List.length_cons, List.length_nil] at s1
  simp [s0, s1]

theorem provideLayer_scoped {Op : Type} {layer : LayerSrc Op} (isLocal : Bool) {body : Src Op} (h0 : layer.Scoped) (h2 : body.Scoped) :
    ((provideLayer layer isLocal body) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold provideLayer at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  obtain ⟨x2, hx2, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  have s2 := h2.holds _ _ _ hx2
  simp [s0, s2]

theorem service_scoped {Op : Type} (key : Effect4.ServiceKey) :
    ((service key) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold service at h
  cases h
  simp

theorem provideService_scoped {Op : Type} (key : Effect4.ServiceKey) {value : TermSrc} {body : Src Op} (h1 : value.Scoped) (h2 : body.Scoped) :
    ((provideService key value body) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold provideService at h
  obtain ⟨x1, hx1, h⟩ := bind_ok h
  obtain ⟨x2, hx2, h⟩ := bind_ok h
  cases h
  have s1 := h1.holds _ _ _ hx1
  have s2 := h2.holds _ _ _ hx2
  simp [s1, s2]

theorem catchIf_scoped {Op : Type} (error : String) {test : TermSrc} {body : Src Op} {handler : Src Op} (h0 : test.Scoped) (h1 : body.Scoped) (h2 : handler.Scoped) :
    ((catchIf error test body handler) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold catchIf at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  obtain ⟨x1, hx1, h⟩ := bind_ok h
  obtain ⟨x2, hx2, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  simp only [Env.push_length, List.length_cons, List.length_nil] at s0
  have s1 := h1.holds _ _ _ hx1
  have s2 := h2.holds _ _ _ hx2
  simp only [Env.push_length, List.length_cons, List.length_nil] at s2
  simp [s0, s1, s2]

theorem selectBool_scoped {Op : Type} {scrutinee : TermSrc} {arm0 : Src Op} {arm1 : Src Op} (h0 : scrutinee.Scoped) (h2 : arm0.Scoped) (h3 : arm1.Scoped) :
    ((selectBool scrutinee arm0 arm1) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold selectBool at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  obtain ⟨x2, hx2, h⟩ := bind_ok h
  obtain ⟨x3, hx3, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  have s2 := h2.holds _ _ _ hx2
  have s3 := h3.holds _ _ _ hx3
  simp [s0, s2, s3]

theorem selectOption_scoped {Op : Type} (bound : String) {scrutinee : TermSrc} {arm0 : Src Op} {arm1 : Src Op} (h0 : scrutinee.Scoped) (h2 : arm0.Scoped) (h3 : arm1.Scoped) :
    ((selectOption bound scrutinee arm0 arm1) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold selectOption at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  obtain ⟨x2, hx2, h⟩ := bind_ok h
  obtain ⟨x3, hx3, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  have s2 := h2.holds _ _ _ hx2
  have s3 := h3.holds _ _ _ hx3
  simp only [Env.push_length, List.length_cons, List.length_nil] at s3
  simp [s0, s2, s3]

theorem selectTag_scoped {Op : Type} (payload : String) (rest : String) {scrutinee : TermSrc} (tag : String) {arm0 : Src Op} {arm1 : Src Op} (h0 : scrutinee.Scoped) (h2 : arm0.Scoped) (h3 : arm1.Scoped) :
    ((selectTag payload rest scrutinee tag arm0 arm1) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold selectTag at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  obtain ⟨x2, hx2, h⟩ := bind_ok h
  obtain ⟨x3, hx3, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  have s2 := h2.holds _ _ _ hx2
  simp only [Env.push_length, List.length_cons, List.length_nil] at s2
  have s3 := h3.holds _ _ _ hx3
  simp only [Env.push_length, List.length_cons, List.length_nil] at s3
  simp [s0, s2, s3]

theorem iterate_scoped {Op : Type} (cursor : String) (answer : String) (cursorTy : Option Effect4.Program.Ty) {initial : TermSrc} {test : TermSrc} {step : TermSrc} {result : TermSrc} {body : Src Op} (h1 : initial.Scoped) (h2 : test.Scoped) (h3 : step.Scoped) (h4 : result.Scoped) (h5 : body.Scoped) :
    ((iterate cursor answer cursorTy initial test step result body) : Src Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold iterate at h
  obtain ⟨x1, hx1, h⟩ := bind_ok h
  obtain ⟨x2, hx2, h⟩ := bind_ok h
  obtain ⟨x3, hx3, h⟩ := bind_ok h
  obtain ⟨x4, hx4, h⟩ := bind_ok h
  obtain ⟨x5, hx5, h⟩ := bind_ok h
  cases h
  have s1 := h1.holds _ _ _ hx1
  have s2 := h2.holds _ _ _ hx2
  simp only [Env.push_length, List.length_cons, List.length_nil] at s2
  have s3 := h3.holds _ _ _ hx3
  simp only [Env.push_length, List.length_cons, List.length_nil] at s3
  have s4 := h4.holds _ _ _ hx4
  simp only [Env.push_length, List.length_cons, List.length_nil] at s4
  have s5 := h5.holds _ _ _ hx5
  simp only [Env.push_length, List.length_cons, List.length_nil] at s5
  simp [s1, s2, s3, s4, s5]

theorem Action.fork_scoped {Op : Type} {program : Src Op} (options : Effect4.Supervision.ForkOptions) (h0 : program.Scoped) :
    ((Action.fork program options) : ActionSrc Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Action.fork at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  simp [s0]

theorem Action.forkIn_scoped {Op : Type} {program : Src Op} (options : Effect4.Supervision.ForkOptions) {scope : TermSrc} (h0 : program.Scoped) (h2 : scope.Scoped) :
    ((Action.forkIn program options scope) : ActionSrc Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Action.forkIn at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  obtain ⟨x2, hx2, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  have s2 := h2.holds _ _ _ hx2
  simp [s0, s2]

theorem Action.forkScoped_scoped {Op : Type} {program : Src Op} (options : Effect4.Supervision.ForkOptions) (h0 : program.Scoped) :
    ((Action.forkScoped program options) : ActionSrc Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Action.forkScoped at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  simp [s0]

theorem Action.runIn_scoped {Op : Type} {target : TermSrc} {scope : TermSrc} (h0 : target.Scoped) (h1 : scope.Scoped) :
    ((Action.runIn target scope) : ActionSrc Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Action.runIn at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  obtain ⟨x1, hx1, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  have s1 := h1.holds _ _ _ hx1
  simp [s0, s1]

theorem Action.interrupt_scoped {Op : Type} {target : TermSrc} (h0 : target.Scoped) :
    ((Action.interrupt target) : ActionSrc Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Action.interrupt at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  simp [s0]

theorem Action.interruptAll_scoped {Op : Type} {targets : TermSrc} {interruptor : Option TermSrc} (h0 : targets.Scoped) (h1 : ∀ t ∈ interruptor, t.Scoped) :
    ((Action.interruptAll targets interruptor) : ActionSrc Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Action.interruptAll at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  obtain ⟨x1, hx1, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  have s1 := elabOption_scoped h1 hx1
  simp [s0, s1]

theorem Action.awaitAll_scoped {Op : Type} {targets : TermSrc} (h0 : targets.Scoped) :
    ((Action.awaitAll targets) : ActionSrc Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Action.awaitAll at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  simp [s0]

theorem Action.raceAll_scoped {Op : Type} {entrants : List (Src Op)} (h0 : ∀ s ∈ entrants, s.Scoped) :
    ((Action.raceAll entrants) : ActionSrc Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Action.raceAll at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := elabEffs_scoped h0 hx0
  simp [s0]

theorem Action.getContext_scoped {Op : Type} :
    ((Action.getContext) : ActionSrc Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Action.getContext at h
  cases h
  simp

theorem Action.getId_scoped {Op : Type} :
    ((Action.getId) : ActionSrc Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Action.getId at h
  cases h
  simp

theorem Action.closeScope_scoped {Op : Type} {scope : TermSrc} {exit : TermSrc} (h0 : scope.Scoped) (h1 : exit.Scoped) :
    ((Action.closeScope scope exit) : ActionSrc Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Action.closeScope at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  obtain ⟨x1, hx1, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  have s1 := h1.holds _ _ _ hx1
  simp [s0, s1]

theorem Layer.succeed_scoped {Op : Type} (key : Effect4.ServiceKey) (value : Effect4.Program.Lit) :
    ((Layer.succeed key value) : LayerSrc Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Layer.succeed at h
  cases h
  simp

theorem Layer.effect_scoped {Op : Type} (key : Effect4.ServiceKey) {body : Src Op} (h1 : body.Scoped) :
    ((Layer.effect key body) : LayerSrc Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Layer.effect at h
  obtain ⟨x1, hx1, h⟩ := bind_ok h
  cases h
  have s1 := h1.holds _ _ _ hx1
  simp only [Env.closed_length] at s1
  simp [s1]

theorem Layer.effectDiscard_scoped {Op : Type} {body : Src Op} (h0 : body.Scoped) :
    ((Layer.effectDiscard body) : LayerSrc Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Layer.effectDiscard at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  simp only [Env.closed_length] at s0
  simp [s0]

theorem Layer.provide_scoped {Op : Type} {self : LayerSrc Op} {that : LayerSrc Op} (h0 : self.Scoped) (h1 : that.Scoped) :
    ((Layer.provide self that) : LayerSrc Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Layer.provide at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  obtain ⟨x1, hx1, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  have s1 := h1.holds _ _ _ hx1
  simp [s0, s1]

theorem Layer.provideMerge_scoped {Op : Type} {self : LayerSrc Op} {that : LayerSrc Op} (h0 : self.Scoped) (h1 : that.Scoped) :
    ((Layer.provideMerge self that) : LayerSrc Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Layer.provideMerge at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  obtain ⟨x1, hx1, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  have s1 := h1.holds _ _ _ hx1
  simp [s0, s1]

theorem Layer.merge_scoped {Op : Type} {left : LayerSrc Op} {right : LayerSrc Op} (h0 : left.Scoped) (h1 : right.Scoped) :
    ((Layer.merge left right) : LayerSrc Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Layer.merge at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  obtain ⟨x1, hx1, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  have s1 := h1.holds _ _ _ hx1
  simp [s0, s1]

theorem Layer.fresh_scoped {Op : Type} {inner : LayerSrc Op} (h0 : inner.Scoped) :
    ((Layer.fresh inner) : LayerSrc Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Layer.fresh at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  simp [s0]

theorem Layer.orDie_scoped {Op : Type} {inner : LayerSrc Op} (h0 : inner.Scoped) :
    ((Layer.orDie inner) : LayerSrc Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Layer.orDie at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  simp [s0]

theorem Layer.mergeAll_scoped {Op : Type} {layers : List (LayerSrc Op)} (h0 : ∀ s ∈ layers, s.Scoped) :
    ((Layer.mergeAll layers) : LayerSrc Op).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Layer.mergeAll at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := elabLayers_scoped h0 hx0
  simp [s0]

theorem Cause.fail_scoped {error : TermSrc} (h0 : error.Scoped) :
    ((Cause.fail error) : CauseSrc).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Cause.fail at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  simp [CauseTerm.scoped, s0]

theorem Cause.die_scoped {defect : TermSrc} (h0 : defect.Scoped) :
    ((Cause.die defect) : CauseSrc).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Cause.die at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  simp [CauseTerm.scoped, s0]

theorem Cause.interrupt_scoped {interruptor : Option TermSrc} (h0 : ∀ t ∈ interruptor, t.Scoped) :
    ((Cause.interrupt interruptor) : CauseSrc).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Cause.interrupt at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  cases h
  have s0 := elabOption_scoped h0 hx0
  cases x0 <;> simp_all [CauseTerm.scoped]

theorem Cause.both_scoped {left : CauseSrc} {right : CauseSrc} (h0 : left.Scoped) (h1 : right.Scoped) :
    ((Cause.both left right) : CauseSrc).Scoped := by
  refine ⟨fun env p e h => ?_⟩
  unfold Cause.both at h
  obtain ⟨x0, hx0, h⟩ := bind_ok h
  obtain ⟨x1, hx1, h⟩ := bind_ok h
  cases h
  have s0 := h0.holds _ _ _ hx0
  have s1 := h1.holds _ _ _ hx1
  simp [CauseTerm.scoped, s0, s1]


/-! ## Receipts -/

#print axioms Effect4.Program.Authoring.succeed_scoped
#print axioms Effect4.Program.Authoring.fail_scoped
#print axioms Effect4.Program.Authoring.failCause_scoped
#print axioms Effect4.Program.Authoring.sync_scoped
#print axioms Effect4.Program.Authoring.suspend_scoped
#print axioms Effect4.Program.Authoring.perform_scoped
#print axioms Effect4.Program.Authoring.bind_scoped
#print axioms Effect4.Program.Authoring.catchCause_scoped
#print axioms Effect4.Program.Authoring.matchCause_scoped
#print axioms Effect4.Program.Authoring.onExit_scoped
#print axioms Effect4.Program.Authoring.exit_scoped
#print axioms Effect4.Program.Authoring.uninterruptible_scoped
#print axioms Effect4.Program.Authoring.interruptible_scoped
#print axioms Effect4.Program.Authoring.yieldNow_scoped
#print axioms Effect4.Program.Authoring.awaitFiber_scoped
#print axioms Effect4.Program.Authoring.withFiber_scoped
#print axioms Effect4.Program.Authoring.scope_scoped
#print axioms Effect4.Program.Authoring.acquireRelease_scoped
#print axioms Effect4.Program.Authoring.provideLayer_scoped
#print axioms Effect4.Program.Authoring.service_scoped
#print axioms Effect4.Program.Authoring.provideService_scoped
#print axioms Effect4.Program.Authoring.catchIf_scoped
#print axioms Effect4.Program.Authoring.selectBool_scoped
#print axioms Effect4.Program.Authoring.selectOption_scoped
#print axioms Effect4.Program.Authoring.selectTag_scoped
#print axioms Effect4.Program.Authoring.iterate_scoped
#print axioms Effect4.Program.Authoring.Action.fork_scoped
#print axioms Effect4.Program.Authoring.Action.forkIn_scoped
#print axioms Effect4.Program.Authoring.Action.forkScoped_scoped
#print axioms Effect4.Program.Authoring.Action.runIn_scoped
#print axioms Effect4.Program.Authoring.Action.interrupt_scoped
#print axioms Effect4.Program.Authoring.Action.interruptAll_scoped
#print axioms Effect4.Program.Authoring.Action.awaitAll_scoped
#print axioms Effect4.Program.Authoring.Action.raceAll_scoped
#print axioms Effect4.Program.Authoring.Action.getContext_scoped
#print axioms Effect4.Program.Authoring.Action.getId_scoped
#print axioms Effect4.Program.Authoring.Action.closeScope_scoped
#print axioms Effect4.Program.Authoring.Layer.succeed_scoped
#print axioms Effect4.Program.Authoring.Layer.effect_scoped
#print axioms Effect4.Program.Authoring.Layer.effectDiscard_scoped
#print axioms Effect4.Program.Authoring.Layer.provide_scoped
#print axioms Effect4.Program.Authoring.Layer.provideMerge_scoped
#print axioms Effect4.Program.Authoring.Layer.merge_scoped
#print axioms Effect4.Program.Authoring.Layer.fresh_scoped
#print axioms Effect4.Program.Authoring.Layer.orDie_scoped
#print axioms Effect4.Program.Authoring.Layer.mergeAll_scoped
#print axioms Effect4.Program.Authoring.Cause.fail_scoped
#print axioms Effect4.Program.Authoring.Cause.die_scoped
#print axioms Effect4.Program.Authoring.Cause.interrupt_scoped
#print axioms Effect4.Program.Authoring.Cause.both_scoped

end Effect4.Program.Authoring

/-! ## Acceptance guards for the generated scope-preservation lemmas

Appended verbatim by `--append tools/Effect4Gen/guards/scopedlaws.lean` into
`src/Effect4/Laws/Program/Authoring/Lifts.lean`. One program of each binding shape, its
scope discharged by `authoring_scoped` (the goal's head names the lemma), so a lemma that
went missing or changed shape fails here. -/

namespace Effect4.Program.AuthoringScopedGuards

open Effect4.Program Effect4.Program.Authoring

example : Src.Scoped (Op := Unit) (bind "r" (succeed (nat 0)) (succeed (var "r"))) := by
  authoring_scoped

example : Src.Scoped (Op := Unit)
    (acquireRelease "a" "x" (succeed (nat 0)) (succeed (app "pair" [var "a", var "x"]))) := by
  authoring_scoped

example : Src.Scoped (Op := Unit)
    (iterate "i" "a" none (nat 0) (app "lt" [var "i", nat 3]) (var "a") (var "i") (succeed (var "i"))) := by
  authoring_scoped

example : Src.Scoped (Op := Unit)
    (catchIf "e" (app "eq" [var "e", str "boom"]) (fail (str "boom")) (succeed (var "e"))) := by
  authoring_scoped

example : Src.Scoped (Op := Unit)
    (provideLayer (Layer.effectDiscard (succeed (nat 1))) false (succeed (nat 1))) := by
  authoring_scoped

example : Src.Scoped (Op := Unit) (withFiber (Action.raceAll [succeed (nat 1), succeed (nat 2)])) := by
  authoring_scoped

example : Src.Scoped (Op := Unit) (withFiber (Action.interruptAll (nat 0) (some (nat 1)))) := by
  authoring_scoped

example : Src.Scoped (Op := Unit)
    (failCause (Authoring.Cause.both (Authoring.Cause.fail (nat 1)) (Authoring.Cause.interrupt none))) := by
  authoring_scoped

example : LayerSrc.Scoped (Op := Unit) (Layer.mergeAll [Layer.effectDiscard (succeed (nat 1)), Layer.ref "Db"]) := by
  authoring_scoped

end Effect4.Program.AuthoringScopedGuards

