(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400169`, seed 400169, 32 operations.
   Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400169 () =
  let v0 = Fibers_fixture.fork 4 in
  ignore (Extra_fixture.yield ());
  let _v1 = Store_fixtures.scope_make () in
  let _v2 = Fibers_fixture.cleanups () in
  let _v3 = Fibers_fixture.await_error v0 in
  ignore (Fibers_fixture.interrupt v0);
  let v4 = Store_fixtures.ref_make 6 in
  ignore (Store_fixtures.ref_set v4 0);
  let v5 = Store_fixtures.layer_build 0 in
  let _v6 = Store_fixtures.ref_get v4 in
  let v7 = Fibers_fixture.fork 1 in
  let v8 = Store_fixtures.scope_make () in
  let _v9 = Fibers_fixture.started () in
  ignore (Fibers_fixture.interrupt v7);
  let _v10 = Fibers_fixture.cleanups () in
  let _v11 = Store_fixtures.scope_close v8 in
  let _v12 = Extra_fixture.interrupt_all [ v0; v7 ] in
  let _v13 = Fibers_fixture.started () in
  let _v14 = Extra_fixture.interrupt_all [ v0; v7 ] in
  ignore (Store_fixtures.ref_set v4 2);
  let _v15 = Fibers_fixture.fork 4 in
  let v16 = Store_fixtures.def_make () in
  let _v17 = Store_fixtures.ref_get_and_set v4 0 in
  ignore (Store_fixtures.ref_update v4 8);
  let _v18 = Fibers_fixture.await_value v0 in
  let _v19 = Store_fixtures.layer_scope_of v5 in
  let _v20 = Store_fixtures.layer_build 0 in
  let v21 = Fibers_fixture.fork 0 in
  ignore (Fibers_fixture.interrupt v21);
  ignore (Fibers_fixture.interrupt v0);
  let _v22 = Store_fixtures.def_fail v16 1 in
  let v23 = Fibers_fixture.await_value v7 in
  v23

let programs : (string * (unit -> value)) list = [ ("p400169", corpus_p400169) ]
