import Lean
import OCaml5.Ml.Syntax
import OCaml5.Ml.Render
import OCaml5.Lcnf.Dump
import OCaml5.Lcnf.Types
import OCaml5.Lcnf.Translate

/-!
# LcnfGen — Lean definitions to an OCaml module, through the mono-phase LCNF

A thin driver over `OCaml5.Lcnf.Translate` and `OCaml5.Lcnf.Types`: import
`Effect4.Machine.Fibers`, translate the named constants and everything they call (up to
`--cap`), generate the types they destruct or construct (plus `--types`), render one `.ml`
file, and print a report of what was and was not covered.

    lean -M4096 --run src/OCaml5/Tools/LcnfGen.lean \
      --out ocaml/gen/machine_gen.ml --cap 60 \
      Effect4.Machine.Dispatcher.insert Effect4.Machine.Dispatcher.enqueue …

Options: `--out <path>` (default `ocaml/gen/machine_gen.ml`), `--cap <n>` (default
60), `--types A,B,…` (types to emit in full even when no translated code destructs them).

This is a tool (`IO`, `MetaM`); it is not part of any audited library.
-/

open Lean OCaml5 OCaml5.Lcnf

structure GenArgs where
  out : String := "ocaml/gen/machine_gen.ml"
  types : Array Name := #[]
  cap : Nat := 60
  roots : Array Name := #[]

partial def parseArgs : List String → GenArgs → GenArgs
  | "--out" :: p :: rest, a => parseArgs rest { a with out := p }
  | "--types" :: ts :: rest, a =>
    parseArgs rest { a with types := a.types ++ ((ts.splitOn ",").map String.toName).toArray }
  | "--cap" :: n :: rest, a => parseArgs rest { a with cap := n.toNat! }
  | r :: rest, a => parseArgs rest { a with roots := a.roots.push r.toName }
  | [], a => a

def main (argv : List String) : IO Unit := do
  initSearchPath (← findSysroot)
  let args := parseArgs argv {}
  let env ← importModules #[{ module := `Effect4.Machine.Fibers }] {} 0
  let ctx : Core.Context := { fileName := "<lcnf-gen>", fileMap := default }
  let act : MetaM Unit := do
    let closure ← translateClosure args.roots args.cap
    let gen ← generate (closure.realTypes ++ args.types) closure.mentioned
    let cmd := "lean -M4096 --run src/OCaml5/Tools/LcnfGen.lean " ++ " ".intercalate argv
    let header := "GENERATED by OCaml5.Lcnf (src/OCaml5/Lcnf/*.lean) from the mono-phase LCNF "
      ++ "of Effect4.Machine.Fibers, Lean 4.33.1. Do not edit. Regenerate with:\n   " ++ cmd
    let items : List Ml.Decl :=
      [.floatingAttrD "warning \"-26-27-32-33-35-37-39-69\"", .blank, gen.item, .blank]
        ++ emit closure.decls
    let modName := (System.FilePath.mk args.out).fileStem.getD "machine_gen"
    let m : Ml.Module := { name := modName, header := some header, items := items }
    IO.FS.writeFile args.out (Ml.render m)
    IO.println s!"wrote {args.out}"
    IO.println s!"translated ({closure.decls.size}):"
    for t in closure.decls do
      IO.println s!"  {t.leanName} -> {t.ocamlName}{if t.recursive then " [rec]" else ""}"
    IO.println s!"missing (no mono decl): {closure.missing}"
    IO.println s!"frontier (beyond --cap {args.cap}): {closure.frontier}"
    IO.println s!"wrapper referenced directly: {closure.wrapperRefs}"
    IO.println s!"todos ({closure.todos.size}):"
    for t in closure.todos do IO.println s!"  {t}"
    IO.println s!"types in full: {gen.full}"
    IO.println s!"types as abbreviations: {gen.aliases}"
    IO.println s!"types as placeholders: {gen.placeholders}"
    IO.println s!"requested but not inductive: {gen.notInductive}"
    IO.println s!"field types not spelled: {gen.unknown}"
    IO.println s!"type-name collisions: {gen.collisions}"
  let _ ← (act.run' {}).toIO ctx { env := env }
