(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400015`, seed 400015, 34 operations.
   Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400015 () =
  let v0 = Fibers_fixture.fork_detach 0 in
  let _v1 = Fibers_fixture.await_error v0 in
  let v2 = Store_fixtures.scope_make () in
  let _v3 = Fibers_fixture.cleanups () in
  let v4 = Store_fixtures.scope_make () in
  let _v5 = Fibers_fixture.started () in
  let v6 = Store_fixtures.def_make () in
  ignore (Fibers_fixture.interrupt v0);
  let _v7 = Store_fixtures.layer_build 3 in
  let _v8 = Store_fixtures.layer_build 1 in
  let _v9 = Fibers_fixture.join v0 in
  let v10 = Store_fixtures.ref_make 1 in
  let v11 = Fibers_fixture.fork 2 in
  ignore (Extra_fixture.yield ());
  let _v12 = Fibers_fixture.await_error v0 in
  let _v13 = Fibers_fixture.cleanups () in
  ignore (Store_fixtures.scope_remove v2 1);
  let _v14 = Store_fixtures.scope_close v4 in
  let _v15 = Fibers_fixture.fork_detach 3 in
  let _v16 = Store_fixtures.ref_modify v10 2 in
  let _v17 = Fibers_fixture.join v0 in
  let _v18 = Store_fixtures.def_make () in
  let _v19 = Fibers_fixture.await_value v0 in
  let _v20 = Store_fixtures.ref_get_and_set v10 5 in
  ignore (Store_fixtures.scope_remove v2 2);
  let _v21 = Fibers_fixture.await_value v11 in
  ignore (Extra_fixture.yield ());
  let _v22 = Fibers_fixture.join v11 in
  let _v23 = Store_fixtures.def_fail v6 1 in
  let _v24 = Store_fixtures.def_make () in
  let _v25 = Fibers_fixture.await_error v11 in
  let _v26 = Store_fixtures.def_succeed v6 5 in
  let _v27 = Fibers_fixture.started () in
  let v28 = Fibers_fixture.cleanups () in
  v28

let programs : (string * (unit -> value)) list = [ ("p400015", corpus_p400015) ]
