(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400198`, seed 400198, 19 operations.
   Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400198 () =
  let v0 = Fibers_fixture.fork 0 in
  let _v1 = Fibers_fixture.started () in
  let _v2 = Fibers_fixture.started () in
  let _v3 = Fibers_fixture.cleanups () in
  let _v4 = Store_fixtures.layer_build 0 in
  let v5 = Fibers_fixture.fork 1 in
  let _v6 = Fibers_fixture.started () in
  let _v7 = Store_fixtures.layer_build 2 in
  let _v8 = Fibers_fixture.started () in
  let v9 = Store_fixtures.def_make () in
  let _v10 = Store_fixtures.def_succeed v9 3 in
  let _v11 = Fibers_fixture.started () in
  let _v12 = Extra_fixture.interrupt_all [ v0; v5 ] in
  let v13 = Store_fixtures.ref_make 6 in
  ignore (Store_fixtures.ref_set v13 6);
  let _v14 = Fibers_fixture.join v5 in
  let _v15 = Store_fixtures.def_fail v9 6 in
  let _v16 = Fibers_fixture.join v0 in
  let v17 = Fibers_fixture.cleanups () in
  v17

let programs : (string * (unit -> value)) list = [ ("p400198", corpus_p400198) ]
