-- cut-from: rev=c43f954-dirty toolchain=4.33.1 inputs=a578e39e93edcf4be9df7b1fde0e95147451df239b8b71a995fd665ea940bfd6
-- GENERATED by src/OCaml5/Tools/Describe.lean from the Lean environment. Do not edit.
-- Regenerate: lake env lean -M4096 --run src/OCaml5/Tools/Describe.lean --module OCaml5.Avatar.Derived.Context serviceKey=Effect4.ServiceKey service=Effect4.Machine.Env.Service context=Effect4.Machine.Env.Context reference=Effect4.Machine.Env.Context.Reference err=Effect4.Machine.Env.Err defect=Effect4.Machine.Env.Defect contextUpdate=Effect4.Machine.Env.ContextUpdate
import OCaml5.Ml.Reflect

namespace OCaml5.Avatar.Derived.Context
open OCaml5.Ml

def serviceKey : StructDesc where
  leanName := "ServiceKey"
  site := "Key.lean:68"
  subst := []
  leanParams := []
  fields :=
    [{ leanName := "name", leanTy := .nm "ServiceName" },
     { leanName := "service", leanTy := .nm "ServiceTypeCode" }]

def service : StructDesc where
  leanName := "Service"
  site := "ContextMap.lean:31"
  subst := []
  leanParams := ["U"]
  fields :=
    [{ leanName := "key", leanTy := .nm "ServiceKey" },
     { leanName := "value", leanTy := .app "ServiceKey.Carrier" [.nm "U", .nm "key"] }]

def context : StructDesc where
  leanName := "Context"
  site := "ContextMap.lean:45"
  subst := []
  leanParams := ["U"]
  fields :=
    [{ leanName := "entries", leanTy := .lst (.app "Service" [.nm "U"]) },
     { leanName := "keysNodup", leanTy := .app "List.Nodup" [.nm "ServiceKey", .app "List.map" [.app "Service" [.nm "U"], .nm "ServiceKey", .app "Service.key" [.nm "U"], .nm "entries"]] }]

def reference : StructDesc where
  leanName := "Reference"
  site := "ContextMap.lean:264"
  subst := []
  leanParams := ["U"]
  fields :=
    [{ leanName := "key", leanTy := .nm "ServiceKey" },
     { leanName := "default", leanTy := .app "ServiceKey.Carrier" [.nm "U", .nm "key"] }]

def err : InductiveDesc where
  leanName := "Err"
  site := "Context.lean:282"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "boom", args := [] },
     { leanName := "tag", args := [{ leanName := "code", leanTy := .nm "Nat" }] }]

def defect : InductiveDesc where
  leanName := "Defect"
  site := "Context.lean:287"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "notImplemented", args := [] },
     { leanName := "asyncFiber", args := [] },
     { leanName := "badName", args := [] },
     { leanName := "serviceNotFound", args := [{ leanName := "key", leanTy := .nm "ServiceKey" }] },
     { leanName := "unknownLayer", args := [{ leanName := "index", leanTy := .nm "Nat" }] }]

def contextUpdate : InductiveDesc where
  leanName := "ContextUpdate"
  site := "Context.lean:400"
  subst := []
  leanParams := []
  ctors :=
    [{ leanName := "setTo", args := [{ leanName := "context", leanTy := .nm "Ctx" }] },
     { leanName := "provide", args := [{ leanName := "that", leanTy := .nm "Ctx" }] },
     { leanName := "provideService", args := [{ leanName := "key", leanTy := .nm "ServiceKey" }, { leanName := "value", leanTy := .nm "Val" }] }]

/-- Every description above, in order. -/
def all : List TypeDesc := [.struct serviceKey, .struct service, .struct context, .struct reference, .induct err, .induct defect, .induct contextUpdate]

end OCaml5.Avatar.Derived.Context
