/**
 * Generated by OCaml5.Fuzz (spike P5, round four). Program `p400117`, seed 400117, 28 operations.
 *
 * Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`.
 */
import { Context, Effect } from "effect"
import type { Fiber, Option, Ref, Scope } from "effect"

/** Service `Fibers`: one method per operation of the Lean family, plus the three rows
 * `fiber-fixture.ts` does not declare and rc.112 does. */
export class Fibers extends Context.Service<Fibers, {
  readonly fork: (body: number) => Effect.Effect<Fiber.Fiber<number, number>>
  readonly forkDetach: (body: number) => Effect.Effect<Fiber.Fiber<number, number>>
  readonly join: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<number, number>
  readonly awaitValue: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<Option.Option<number>>
  readonly awaitError: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<Option.Option<number>>
  readonly interrupt: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<void>
  readonly started: Effect.Effect<ReadonlyArray<number>>
  readonly cleanups: Effect.Effect<ReadonlyArray<number>>
  readonly yieldNow: (priority: number) => Effect.Effect<void>
  readonly interruptAll: (fibers: ReadonlyArray<Fiber.Fiber<number, number>>) => Effect.Effect<void>
  readonly awaitAll: (fibers: ReadonlyArray<Fiber.Fiber<number, number>>) => Effect.Effect<void>
}>()("Fibers") {}

export const FibersRows = { "fork": { params: 1, answer: "Fiber.Fiber<number, number>" }, "forkDetach": { params: 1, answer: "Fiber.Fiber<number, number>" }, "join": { params: 1, answer: "number" }, "awaitValue": { params: 1, answer: "Option.Option<number>" }, "awaitError": { params: 1, answer: "Option.Option<number>" }, "interrupt": { params: 1, answer: "void" }, "started": { params: 0, answer: "ReadonlyArray<number>" }, "cleanups": { params: 0, answer: "ReadonlyArray<number>" }, "yieldNow": { params: 1, answer: "void" }, "interruptAll": { params: 1, answer: "void" }, "awaitAll": { params: 1, answer: "void" } }

/** Service `Layers` (`harness/trace/layer-fixture.ts`). */
export class Layers extends Context.Service<Layers, {
  readonly build: (layer: number) => Effect.Effect<Ref.Ref<number>>
  readonly provideCount: (layer: number) => Effect.Effect<number>
  readonly scopeOf: (service: Ref.Ref<number>) => Effect.Effect<Scope.Closeable>
  readonly close: Effect.Effect<ReadonlyArray<Ref.Ref<number>>>
}>()("Layers") {}

export const LayersRows = { "build": { params: 1, answer: "Ref.Ref<number>" }, "provideCount": { params: 1, answer: "number" }, "scopeOf": { params: 1, answer: "Scope.Closeable" }, "close": { params: 0, answer: "ReadonlyArray<Ref.Ref<number>>" } }

/** Lowered from `p400117` by OCaml5.Fuzz. */
export const corpus_p400117 = (n: number) =>
  Effect.gen(function* () {
    const fibers = yield* Fibers
    const layers = yield* Layers
    void n
    const v0 = yield* fibers.fork(1)
    const v1 = yield* layers.build(2)
    const v2 = yield* fibers.awaitValue(v0)
    const v3 = yield* fibers.started
    const v4 = yield* fibers.started
    const v5 = yield* fibers.fork(1)
    const v6 = yield* fibers.cleanups
    yield* fibers.yieldNow(0)
    const v7 = yield* fibers.awaitValue(v5)
    const v8 = yield* fibers.interruptAll([v5])
    const v9 = yield* layers.build(1)
    const v10 = yield* fibers.fork(1)
    const v11 = yield* fibers.cleanups
    const v12 = yield* layers.provideCount(1)
    const v13 = yield* fibers.started
    const v14 = yield* fibers.started
    const v15 = yield* fibers.awaitError(v0)
    const v16 = yield* fibers.cleanups
    const v17 = yield* fibers.cleanups
    const v18 = yield* fibers.join(v0)
    const v19 = yield* fibers.join(v5)
    const v20 = yield* fibers.join(v5)
    const v21 = yield* fibers.fork(1)
    const v22 = yield* fibers.join(v21)
    const v23 = yield* fibers.join(v21)
    const v24 = yield* layers.provideCount(0)
    const v25 = yield* fibers.awaitAll([v0, v5, v10, v21])
    const v26 = yield* fibers.join(v0)
    return v26
  })
