(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400197`, seed 400197, 12 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400197 () =
  let v0 = Fibers_fixture.fork 3 in
  let _v1 = Fibers_fixture.join v0 in
  let _v2 = Store_fixtures.ref_make 2 in
  let _v3 = Fibers_fixture.cleanups () in
  let _v4 = Fibers_fixture.await_value v0 in
  let v5 = Fibers_fixture.fork 1 in
  let _v6 = Store_fixtures.scope_make () in
  let _v7 = Fibers_fixture.cleanups () in
  let _v8 = Fibers_fixture.await_value v0 in
  let _v9 = Store_fixtures.def_make () in
  let _v10 = Fibers_fixture.await_error v0 in
  let v11 = Fibers_fixture.join v5 in
  v11

let programs : (string * (unit -> value)) list = [ ("p400197", corpus_p400197) ]
