/-!
# Char.Core: the Pass A skeleton of a characterized component

A **characterized component** is a piece of the Effect runtime presented as five
hand-authored parts and nothing else: carriers, step, invariants with proofs,
tests, mutants. Everything downstream (manifests, certificates, replay drivers,
pin tables, registry rows, census and sweep rows) is generated from those five.

This module is the Pass A skeleton those five parts are written against. It is
definitions plus the handful of theorems that are cheap here and used by every
component; it declares no component. The Queue is the first inhabitant and lands
in `Effect4/Char/Queue/`.

## The algebra, and what each structure buys

| Construct | Standard structure | What naming it deletes |
| --- | --- | --- |
| `Machine S L` | a deterministic labelled transition system, `step : S → L → Option S` | the `Decidable` instance per step arm, and the twelve-goal `cases` of an inductive relation. `Next` is the *graph* of the function, so a trace reduces under `decide` |
| `Machine.run` | the free monoid `List L` acting partially on `S` | a bespoke recursion per component. `run_append` is the action law and every conservation induction folds over it |
| `Machine.restrict` | the action of the submonoid generated by an admitted set of labels | the `hclean` hypothesis threaded by hand through every arm of every boundary-relative proof. A property of boundary-free runs becomes an ordinary `Inductive` invariant of the restricted machine |
| `Reach` / `Inductive` | the initial algebra of the step relation, and an algebra map into `Prop` | N reachability inductions, replaced by one (`reach_ind`) |
| `Reading` | a monoid homomorphism `List L → List Item` per client, factored as `filterMap` and `flatMap` | a hand-written observation function per component, and its append lemma |
| `Kinds L K` | the object part of an alphabet morphism onto a finite quotient (`Signature.Hom.op` in `lean4-effects`) | the impossible enumeration of a payload-carrying label: `fail 7` and `fail 9` are one kind, so a failure model is finite data |
| `Grade` | the free bounded meet-semilattice on three independent generators, i.e. `Bool^3` under `&&` | a rung enum with a hand-proved total order, and a `meet` whose every change re-opens a grade-indexed program type |
| `Failure K` | a finite subset of the kind quotient, as a `List` with decidable membership | a `Set K = K → Prop` that cannot be printed, hashed, or `decide`d |
| `Test` / `Mutant` | one `Suite` evaluated at two points of `Machine S L` | a second trace runner per mutant, and a mutant that cannot be compared against the model |

Every one of those is a free construction interpreted by a fold, never an ad hoc
recursion. Everything that is data is `Type 0`, first-order and `DecidableEq`,
so it can be addressed by the digest of its canonical bytes; everything that
carries a function (`Machine`, `Reading`, `Kinds`) is never stored and never
compared, and its stored face is the manifest.

## The rules this module encodes

- Answers live in the label: `step` returns `Option S`, never `Option (S × O)`,
  so a trace is self-describing first-order data and a test is a `Bool`.
- The transition function is total-or-disabled; `Next` is defined as its graph.
- Invariants are extrinsic: a component declares its own `structure … : Prop`
  with named clauses and one `Inductive` witness per predicate. `Inductive`
  never mentions another invariant, so adding one touches no existing proof.
- Exactly one strengthened reachability induction, `Machine.reach_ind`, exported
  once. A component module may not write a second induction over `Reach`.
- The `Bool` / `Prop` seam is at `Machine.Sound` and nowhere else: `Grade.holds`
  is the executable body, `Sound` is the quantified proposition over it.
- `Type 0` only, no universe variables, and no proof is ever a field of a record
  that has to be stored or compared.

## What is deliberately absent from Pass A

`Guarded` and `Graded` (the law-with-anti-vacuity-kit bundles), `Pin`,
`Evidence`, `Manifest`, and the `#characterize` command elaborator. Each carries
`Prop` fields beside a `Machine` and a `Reading`, which is the elaboration cost
this skeleton has no measurement for; they enter with the Queue, one bundle per
module, and are recorded as owed items in `workshop/Char/01-model/`.
-/

set_option autoImplicit false

namespace Effect4.Char

/-! ## The machine -/

/-- A deterministic labelled transition system over first-order state and
labels. Functions only; this record is never `deriving`-ed and never stored, and
a component's data faces are its state, its labels and its manifest. -/
structure Machine (S L : Type) where
  /-- The single initial state. -/
  init : S
  /-- Total-or-disabled: `none` means the label is not enabled here, never that
  the component failed. A failure is a label. -/
  step : S → L → Option S

namespace Machine

variable {S L : Type}

/-- Run a word. Structural recursion on the list, so the kernel reduces it and a
trace theorem closes by `decide`. -/
def run (M : Machine S L) : S → List L → Option S
  | s, [] => some s
  | s, l :: ls =>
    match M.step s l with
    | some s' => M.run s' ls
    | none => none

/-- Is this label enabled here. -/
def enabled (M : Machine S L) (s : S) (l : L) : Bool := (M.step s l).isSome

/-- The accepted words, as a `Bool`. No `Decidable` instance is ever synthesized
for acceptance. -/
def accepts (M : Machine S L) (w : List L) : Bool := (M.run M.init w).isSome

/-- The one-step relation is exactly the graph of `step`. -/
def Next (M : Machine S L) (s : S) (l : L) (s' : S) : Prop := M.step s l = some s'

/-- `Next` unfolds by `Iff.rfl`; there is no second definition of the relation
to keep in step with the function. -/
theorem next_iff (M : Machine S L) (s : S) (l : L) (s' : S) :
    M.Next s l s' ↔ M.step s l = some s' := Iff.rfl

/-- Reachability: the initial algebra of the step relation. -/
inductive Reach (M : Machine S L) : S → Prop
  | init : Reach M M.init
  | step {s s' : S} {l : L} : Reach M s → M.step s l = some s' → Reach M s'

/-- The action law of the free monoid `List L` on `S`. Every conservation
induction folds over this, so no component writes its own. -/
theorem run_append (M : Machine S L) (s : S) (u v : List L) :
    M.run s (u ++ v) =
      match M.run s u with
      | some s' => M.run s' v
      | none => none := by
  induction u generalizing s with
  | nil => rfl
  | cons l u ih =>
    show (match M.step s l with
          | some s' => M.run s' (u ++ v)
          | none => none) = _
    cases hstep : M.step s l with
    | none => simp [run, hstep]
    | some s' => simp [run, hstep, ih]

/-- The cons equation of `run`, so a component's induction never unfolds the
recursion by hand. -/
theorem run_cons (M : Machine S L) (s : S) (l : L) (w : List L) :
    M.run s (l :: w) =
      match M.step s l with
      | some s1 => M.run s1 w
      | none => none := rfl

/-- The step of every word induction: a successful run of `l :: w` factors into
the step `l` takes and the run of `w` from there. Every conservation proof in
every component opens with this, so it is proved once. -/
theorem run_cons_some {M : Machine S L} {s s' : S} {l : L} {w : List L}
    (h : M.run s (l :: w) = some s') :
    ∃ s1, M.step s l = some s1 ∧ M.run s1 w = some s' := by
  rw [run_cons] at h
  cases hst : M.step s l with
  | none => rw [hst] at h; exact absurd h (by simp)
  | some s1 => exact ⟨s1, rfl, by rw [hst] at h; exact h⟩

/-- Acceptance is prefix-closed. -/
theorem accepts_prefix (M : Machine S L) (u v : List L) (h : M.accepts (u ++ v) = true) :
    M.accepts u = true := by
  unfold accepts at h ⊢
  rw [run_append] at h
  cases hu : M.run M.init u with
  | none => rw [hu] at h; exact absurd h (by simp)
  | some s => simp

/-- Every state a run reaches from a reachable state is reachable. -/
theorem reach_run (M : Machine S L) :
    ∀ (w : List L) (s s' : S), Reach M s → M.run s w = some s' → Reach M s' := by
  intro w
  induction w with
  | nil => intro s s' hr hrun; cases hrun; exact hr
  | cons l w ih =>
    intro s s' hr hrun
    cases hstep : M.step s l with
    | none =>
      rw [show M.run s (l :: w) = none from by simp [run, hstep]] at hrun
      exact absurd hrun (by simp)
    | some s'' =>
      have hrest : M.run s'' w = some s' := by
        rw [show M.run s (l :: w) = M.run s'' w from by simp [run, hstep]] at hrun
        exact hrun
      exact ih s'' s' (Reach.step hr hstep) hrest

/-- Every state a run from `init` reaches is reachable. -/
theorem reach_of_run (M : Machine S L) {w : List L} {s : S} (h : M.run M.init w = some s) :
    Reach M s := reach_run M w M.init s Reach.init h

/-- The machine restricted to an admitted set of labels: the action of the
submonoid `adm` generates. A property of boundary-free runs of `M` is an
ordinary `Inductive` invariant of `M.restrict adm`, which is what keeps the
admissibility hypothesis out of every arm of every proof. -/
def restrict (M : Machine S L) (adm : L → Bool) : Machine S L where
  init := M.init
  step := fun s l => if adm l then M.step s l else none

/-- A step of the restriction is an admitted label and a step of the machine.
This is what keeps the admissibility hypothesis out of every arm: a component's
case analysis destructs this once and then works on `M.step`. -/
theorem step_restrict_some {M : Machine S L} {adm : L → Bool} {s s' : S} {l : L}
    (h : (M.restrict adm).step s l = some s') : adm l = true ∧ M.step s l = some s' := by
  cases hadm : adm l with
  | false => simp [restrict, hadm] at h
  | true => exact ⟨rfl, by simpa [restrict, hadm] using h⟩

/-- On a word every label of which is admitted, the restriction runs as the
machine does. This is the bridge between the two readings of "boundary-free
run", and it is proved once here rather than inlined per component. -/
theorem run_restrict (M : Machine S L) (adm : L → Bool) (s : S) (w : List L)
    (h : w.all adm = true) : (M.restrict adm).run s w = M.run s w := by
  induction w generalizing s with
  | nil => rfl
  | cons l w ih =>
    rw [List.all_cons, Bool.and_eq_true] at h
    have hstepEq : (M.restrict adm).step s l = M.step s l := by
      simp only [restrict, h.1, if_true]
    cases hstep : M.step s l with
    | none => simp [run, hstepEq, hstep]
    | some s' => simp [run, hstepEq, hstep, ih s' h.2]

end Machine

/-! ## Invariants

A component declares its own predicate as a named `structure … : Prop`, one
clause per proof site, and proves exactly one `Inductive` witness for it.
`Inductive` mentions no other invariant, so adding one touches no existing
proof. -/

/-- An inductive invariant: two obligations, no more. -/
structure Inductive {S L : Type} (M : Machine S L) (I : S → Prop) : Prop where
  /-- The invariant holds initially. -/
  init : I M.init
  /-- Every enabled step preserves it. -/
  step : ∀ {s s' : S} {l : L}, I s → M.step s l = some s' → I s'

namespace Inductive

/-- An inductive invariant holds on every reachable state. This is the
bootstrap; everything else goes through `Machine.reach_ind`. -/
theorem reach {S L : Type} {M : Machine S L} {I : S → Prop}
    (h : Inductive M I) {s : S} (hr : Machine.Reach M s) : I s := by
  induction hr with
  | init => exact h.init
  | step _ hstep ih => exact h.step ih hstep

/-- An inductive invariant holds at the end of every run from `init`. -/
theorem run {S L : Type} {M : Machine S L} {I : S → Prop}
    (h : Inductive M I) {w : List L} {s : S} (hrun : M.run M.init w = some s) : I s :=
  h.reach (M.reach_of_run hrun)

end Inductive

namespace Machine

/-- **The one strengthened reachability induction.** The bare recursor of
`Reach` hands the step case `P s` and nothing else, so every downstream fact
would re-prove the invariant. This bundles reachability and an inductive
invariant into the step hypothesis. A component module goes through this and
does not write a second induction over `Reach`. -/
theorem reach_ind {S L : Type} {M : Machine S L} {I P : S → Prop}
    (hI : Inductive M I)
    (hinit : P M.init)
    (hstep : ∀ {s s' : S} {l : L},
      Machine.Reach M s → I s → P s → M.step s l = some s' → P s')
    {s : S} (h : Machine.Reach M s) : P s := by
  induction h with
  | init => exact hinit
  | step hr hst ih => exact hstep hr (hI.reach hr) ih hst

end Machine

/-! ## The reading

How a word and a state are read as deliveries, per client. The client index is
present from the start: for a single-consumer component it is `Unit`, and for a
`PubSub` it is the subscriber id. Retrofitting it later would change every grade
statement. -/

/-- Item identities are `Nat`, never Lean values: canonical content is
first-order data, so a component that needs richer items assigns them store ids
and reads the id here. -/
abbrev Item := Nat

/-- What a component's alphabet means for delivery.

`accepts` and `emits` read the label alone, which is sound because answers live
in the label; `residue` reads the state, which is what makes conservation
statable. `acc` and `del` are monoid homomorphisms from `List L`, which is the
whole content of a conservation induction's append step. -/
structure Reading (S L C : Type) where
  /-- The client that handed an item in on this label, if any. -/
  accepts : L → Option (C × Item)
  /-- The items this label handed out, and to which client, in order. -/
  emits : L → List (C × Item)
  /-- What the component still holds for a client at this state. -/
  residue : S → C → List Item

namespace Reading

variable {S L C : Type}

/-- The one client filter both homomorphisms use. -/
def forClient [DecidableEq C] (c : C) (p : C × Item) : Option Item :=
  if p.1 = c then some p.2 else none

/-- The items client `c` handed in, in order. A `filterMap` over the word, so
`List.filterMap_append` is its append law. -/
def acc [DecidableEq C] (R : Reading S L C) (c : C) (w : List L) : List Item :=
  w.filterMap (fun l => (R.accepts l).bind (forClient c))

/-- The items the component handed out to client `c`, in order. A `flatMap` over
the word, so `List.flatMap_append` is its append law. -/
def del [DecidableEq C] (R : Reading S L C) (c : C) (w : List L) : List Item :=
  w.flatMap (fun l => (R.emits l).filterMap (forClient c))

theorem acc_append [DecidableEq C] (R : Reading S L C) (c : C) (u v : List L) :
    R.acc c (u ++ v) = R.acc c u ++ R.acc c v := List.filterMap_append

theorem del_append [DecidableEq C] (R : Reading S L C) (c : C) (u v : List L) :
    R.del c (u ++ v) = R.del c u ++ R.del c v := List.flatMap_append

end Reading

/-! ## Conservation, from a one-label table

`ALGEBRA.md` section 7.2 replaces a per-component seven-case list induction with one generic
theorem plus a per-label table. `LocalBalance` is that table's statement and
`Machine.conservation` is the generic theorem, proved once here for the room. -/

/-- **Local balance**: the one-label, word-free form of a conservation equation,
relative to an invariant. What the component holds for a client, followed by what
this label accepts from that client, is what this label delivers to it followed by
what the component holds after.

The invariant parameter is load-bearing. Without it a component whose alphabet has
a no-op arm (the queue's refused `offer` on a closed queue: the label accepts an
item and the state does not move) has no true local table at all. -/
def LocalBalance {S L C : Type} [DecidableEq C]
    (M : Machine S L) (R : Reading S L C) (I : S → Prop) : Prop :=
  ∀ (c : C) (s s' : S) (l : L), I s → M.step s l = some s' →
    R.residue s c ++ R.acc c [l] = R.del c [l] ++ R.residue s' c

namespace Machine

/-- **Conservation.** A component whose one-label table balances conserves items
over every run from an invariant-satisfying state. Proved once, by list induction
and `List.append_assoc` alone; the reverse reduction of an already-written word
induction to the table is where `List.append_cancel_right` is used instead.

A boundary-relative conservation theorem is this at `M := N.restrict (F.admits κ)`,
converted back to `N` by `run_restrict`. The failure model therefore enters once, at
the instantiation, and never as a hypothesis threaded through the arms. -/
theorem conservation {S L C : Type} [DecidableEq C]
    {M : Machine S L} {R : Reading S L C} {I : S → Prop}
    (hI : Inductive M I) (hlocal : LocalBalance M R I)
    {w : List L} {s0 s : S} (hinv : I s0) (hrun : M.run s0 w = some s) (c : C) :
    R.residue s0 c ++ R.acc c w = R.del c w ++ R.residue s c := by
  induction w generalizing s0 with
  | nil =>
    injection hrun with h
    subst h
    simp [Reading.acc, Reading.del]
  | cons l w ih =>
    obtain ⟨s1, hst, hrest⟩ := run_cons_some hrun
    have hinv1 : I s1 := hI.step hinv hst
    have hstep := hlocal c s0 s1 l hinv hst
    have hih := ih hinv1 hrest
    rw [show l :: w = [l] ++ w from rfl, R.acc_append, R.del_append,
      ← List.append_assoc, hstep, List.append_assoc, hih, ← List.append_assoc]

end Machine

/-! ## Label kinds and the failure model

A label may carry a payload, so a failure model cannot be a list of labels: the
queue's excluded set includes `fail e` for every `e : Nat`. `Kinds` is the alphabet
morphism onto the finite quotient by constructor, so the excluded set is a list of
*kinds* and stays first-order finite data. `spell` is the same quotient's
manifest face, which is how a heterogeneous registry avoids a `Sigma` type. -/

/-- The finite quotient of a label alphabet: one kind per constructor, its
spelling, and the enumeration of the quotient. Carries a function, so like
`Machine` it is never stored and never compared. -/
structure Kinds (L K : Type) where
  /-- The constructor of a label. -/
  kind : L → K
  /-- Every kind, in manifest order. -/
  all : List K
  /-- The manifest spelling of a kind. One name binds all surfaces. -/
  spell : K → String

namespace Kinds

/-- Does the enumeration cover the kinds these labels take. The component's
receipt is this at `= true` over its test alphabet, by `decide`. -/
def covers {L K : Type} [DecidableEq K] (κ : Kinds L K) (ls : List L) : Bool :=
  ls.all (fun l => κ.all.contains (κ.kind l))

/-- Are the spellings distinct. A duplicate spelling would make two kinds one
manifest row. -/
def spellingsNodup {L K : Type} (κ : Kinds L K) : Bool :=
  go (κ.all.map κ.spell)
where
  go : List String → Bool
    | [] => true
    | a :: r => !(r.contains a) && go r

end Kinds

/-- The excluded kinds and the named escapes of one failure model. First-order
data, so it is stored and addressed like any other content. Each escape owes a
reachability witness in the component's kit; an escape clause with no reachable
witness is a weaker grade misdescribed.

Ruling R1 of `docs/research/2026-09-05-workshop-char/RULINGS.md`: the field lists the labels a graded run may
**not** contain, which is what `clean` computes, and it is named `excluded` rather
than `boundary` so the name says what it holds. Model names read as what the model
admits, so the queue's `F-none` has `excluded = [fail, shutdown]` and its
`F-shutdown` has `excluded = [fail]`. A smaller `excluded` set is a stronger claim,
and `Machine.sound_of_excluded_subset` transports soundness to any superset. -/
structure Failure (K : Type) where
  /-- The manifest spelling of the model, e.g. `"F-shutdown"`. -/
  name : String
  /-- The kinds a run must not contain for the grade to be claimed. -/
  excluded : List K
  /-- One plain sentence per escape clause. -/
  escapes : List String
deriving DecidableEq, Repr, Inhabited

namespace Failure

variable {L K : Type}

/-- Is this label outside the boundary. This is the admitted set of
`Machine.restrict`. -/
def admits [DecidableEq K] (F : Failure K) (κ : Kinds L K) (l : L) : Bool :=
  !(F.excluded.contains (κ.kind l))

/-- Does this word stay inside the failure model. -/
def clean [DecidableEq K] (F : Failure K) (κ : Kinds L K) (w : List L) : Bool :=
  w.all (F.admits κ)

/-- Did this word touch the boundary. -/
def hit [DecidableEq K] (F : Failure K) (κ : Kinds L K) (w : List L) : Bool :=
  !(F.clean κ w)

/-- The excluded kinds by their manifest spellings, which is what a grade row
stores (ruling R1: the spellings, not the kinds). -/
def excludedSpelled (F : Failure K) (κ : Kinds L K) : List String :=
  F.excluded.map κ.spell

theorem clean_eq_not_hit [DecidableEq K] (F : Failure K) (κ : Kinds L K) (w : List L) :
    F.clean κ w = !(F.hit κ w) := (Bool.not_not _).symm

/-- A label admitted by a larger excluded set is admitted by a smaller one. -/
theorem admits_mono [DecidableEq K] {F F' : Failure K} (κ : Kinds L K)
    (hsub : ∀ k, F.excluded.contains k = true → F'.excluded.contains k = true) (l : L)
    (h : F'.admits κ l = true) : F.admits κ l = true := by
  cases hc : F.excluded.contains (κ.kind l) with
  | false => simp only [Failure.admits, hc, Bool.not_false]
  | true =>
    have h' : F'.excluded.contains (κ.kind l) = true := hsub _ hc
    simp only [Failure.admits, h', Bool.not_true] at h
    exact absurd h (by decide)

/-- A word clean for a larger excluded set is clean for a smaller one. -/
theorem clean_mono [DecidableEq K] {F F' : Failure K} (κ : Kinds L K)
    (hsub : ∀ k, F.excluded.contains k = true → F'.excluded.contains k = true) (w : List L)
    (h : F'.clean κ w = true) : F.clean κ w = true := by
  simp only [Failure.clean, List.all_eq_true] at h ⊢
  exact fun l hl => Failure.admits_mono κ hsub l (h l hl)

/-- A word that hits a smaller excluded set hits a larger one. -/
theorem hit_mono [DecidableEq K] {F F' : Failure K} (κ : Kinds L K)
    (hsub : ∀ k, F.excluded.contains k = true → F'.excluded.contains k = true) (w : List L)
    (h : F.hit κ w = true) : F'.hit κ w = true := by
  simp only [Failure.hit] at h ⊢
  cases hc : F'.clean κ w with
  | false => rfl
  | true =>
    rw [Failure.clean_mono κ hsub w hc, Bool.not_true] at h
    exact absurd h (by decide)

end Failure

/-! ## The grade

Three independent `Bool` axes, not a rung enum. `Grade` under `meet` is the free
bounded meet-semilattice on three generators, which is exactly `Bool^3` under
`&&`: commutative, associative, idempotent, with `top` as unit. Independent axes
are what keep ordering guarantees out of the delivery monoid, and keeping the
grade a *value* on a manifest rather than a type-level index is what keeps
`DecidableEq`, `Repr` and a canonical encoding. -/

/-- The delivery grade. Adding an axis is a freeze revision, recorded like any
other, because it changes the stored encoding of every manifest. -/
structure Grade where
  /-- Nothing accepted is dropped. -/
  noLoss : Bool
  /-- The component introduces no duplicate. -/
  noDup : Bool
  /-- Per client, what was delivered is a prefix of what was accepted. -/
  order : Bool
deriving DecidableEq, Repr, Inhabited

namespace Grade

/-- Every axis claimed. -/
def top : Grade := ⟨true, true, true⟩

/-- No axis claimed. -/
def bot : Grade := ⟨false, false, false⟩

/-- The weakest grade claiming only what both claim. -/
def meet (a b : Grade) : Grade :=
  ⟨a.noLoss && b.noLoss, a.noDup && b.noDup, a.order && b.order⟩

/-- `le a b` means every axis `a` claims is claimed by `b`. A `Bool`, so
`decide` needs no instance synthesis. -/
def le (a b : Grade) : Bool :=
  (!a.noLoss || b.noLoss) && (!a.noDup || b.noDup) && (!a.order || b.order)

theorem meet_comm (a b : Grade) : meet a b = meet b a := by
  cases a with | mk x y z => cases b with | mk p q r =>
  cases x <;> cases y <;> cases z <;> cases p <;> cases q <;> cases r <;> rfl

theorem meet_assoc (a b c : Grade) : meet (meet a b) c = meet a (meet b c) := by
  cases a with | mk x y z => cases b with | mk p q r => cases c with | mk u v w =>
  cases x <;> cases y <;> cases z <;> cases p <;> cases q <;> cases r <;>
    cases u <;> cases v <;> cases w <;> rfl

theorem meet_idem (a : Grade) : meet a a = a := by
  cases a with | mk x y z => cases x <;> cases y <;> cases z <;> rfl

theorem meet_top (a : Grade) : meet a top = a := by
  cases a with | mk x y z => cases x <;> cases y <;> cases z <;> rfl

theorem meet_bot (a : Grade) : meet a bot = bot := by
  cases a with | mk x y z => cases x <;> cases y <;> cases z <;> rfl

theorem meet_le_left (a b : Grade) : le (meet a b) a = true := by
  cases a with | mk x y z => cases b with | mk p q r =>
  cases x <;> cases y <;> cases z <;> cases p <;> cases q <;> cases r <;> rfl

theorem meet_le_right (a b : Grade) : le (meet a b) b = true := by
  cases a with | mk x y z => cases b with | mk p q r =>
  cases x <;> cases y <;> cases z <;> cases p <;> cases q <;> cases r <;> rfl

theorem le_refl (a : Grade) : le a a = true := by
  cases a with | mk x y z => cases x <;> cases y <;> cases z <;> rfl

/-- The overclaim guard, kept refutable: `meet` is a meet, not a join. -/
theorem meet_is_not_join : ∃ a b : Grade, le a (meet a b) = false :=
  ⟨top, bot, rfl⟩

end Grade

/-! ## The grade denotation

`Grade.holds` is the executable body; `Machine.Sound` is the quantified
proposition over it. These are one idea stated twice, tied by `Sound`'s
definition, so `holds` is a freeze surface in its own right. -/

/-- A `Bool` `List.Nodup` over items, structurally recursive so the kernel
reduces it. -/
def nodupB : List Item → Bool
  | [] => true
  | a :: r => !(r.contains a) && nodupB r

/-- A prefix of a duplicate-free list is duplicate-free. This is what turns the
conservation equation into the `noDup` axis: `acc = del ++ residue`, so freshness
of the accepted word transfers to the delivered prefix. -/
theorem nodupB_append_left (a b : List Item) (h : nodupB (a ++ b) = true) :
    nodupB a = true := by
  induction a with
  | nil => rfl
  | cons x r ih =>
    rw [List.cons_append, nodupB, Bool.and_eq_true] at h
    rw [nodupB, Bool.and_eq_true]
    refine ⟨?_, ih h.2⟩
    have hx := h.1
    rw [Bool.not_eq_true'] at hx ⊢
    rw [List.contains_append, Bool.or_eq_false_iff] at hx
    exact hx.1

/-- What a grade promises of one run for one client: a word and the state it
reached. `noLoss` is not a word property, which is why the residue appears. -/
def Grade.holds {S L C K : Type} [DecidableEq C] [DecidableEq K]
    (R : Reading S L C) (κ : Kinds L K) (F : Failure K) (g : Grade)
    (c : C) (w : List L) (s : S) : Bool :=
  (!g.noLoss || F.hit κ w || (R.acc c w == R.del c w ++ R.residue s c)) &&
  (!g.noDup || nodupB (R.del c w)) &&
  (!g.order || (R.del c w ++ R.residue s c).isPrefixOf (R.acc c w))

/-- Soundness at a grade: the `Prop` whose body is the `Bool` above. The
`Prop`/`Bool` seam of this API is exactly here. -/
def Machine.Sound {S L C K : Type} [DecidableEq C] [DecidableEq K]
    (M : Machine S L) (R : Reading S L C) (κ : Kinds L K) (F : Failure K) (g : Grade) : Prop :=
  ∀ (c : C) (w : List L) (s : S), M.run M.init w = some s → Grade.holds R κ F g c w s = true

namespace Machine

/-- Antitone in the grade: a weaker grade is sound whenever a stronger one is. -/
theorem sound_mono {S L C K : Type} [DecidableEq C] [DecidableEq K] {M : Machine S L}
    {R : Reading S L C} {κ : Kinds L K} {F : Failure K} {g g' : Grade}
    (hle : Grade.le g' g = true) (h : M.Sound R κ F g) : M.Sound R κ F g' := by
  intro c w s hrun
  have hg := h c w s hrun
  cases g with | mk x y z =>
  cases g' with | mk p q r =>
  cases x <;> cases y <;> cases z <;> cases p <;> cases q <;> cases r <;>
    simp_all [Grade.le, Grade.holds]

/-- Monotone in the failure model, in the direction ruling R1 fixes: a larger
`excluded` set is a weaker claim, so soundness transports to any superset. -/
theorem sound_of_excluded_subset {S L C K : Type} [DecidableEq C] [DecidableEq K]
    {M : Machine S L} {R : Reading S L C} {κ : Kinds L K} {F F' : Failure K} {g : Grade}
    (hsub : ∀ k, F.excluded.contains k = true → F'.excluded.contains k = true)
    (h : M.Sound R κ F g) : M.Sound R κ F' g := by
  intro c w s hrun
  have hh := h c w s hrun
  simp only [Grade.holds] at hh ⊢
  cases hf' : F'.hit κ w with
  | true => simp_all
  | false =>
    have hf : F.hit κ w = false := by
      cases hfc : F.hit κ w with
      | false => rfl
      | true => rw [Failure.hit_mono κ hsub w hfc] at hf'; exact absurd hf' (by simp)
    simp_all

/-- Meet-soundness at one machine, a corollary of `sound_mono` and
`meet_le_left`. -/
theorem meet_sound_self {S L C K : Type} [DecidableEq C] [DecidableEq K] {M : Machine S L}
    {R : Reading S L C} {κ : Kinds L K} {F : Failure K} {g₁ g₂ : Grade}
    (h : M.Sound R κ F g₁) : M.Sound R κ F (Grade.meet g₁ g₂) :=
  sound_mono (Grade.meet_le_left g₁ g₂) h

end Machine

/-! ## Tests, suites and mutants

A test is data and a suite runs a `Bool`. The runner takes the machine as an
argument rather than closing over the model, which is the whole reason the
mutant layer is free: the same test data is executed against a mutant. -/

/-- A test is data. `accept = false` is a negative test: the word must be
refused. `residue` lists the clients whose residue is checked; a client absent
from the list is unconstrained. There is no `S` parameter: no field mentions the
state, and a phantom parameter would block `deriving Repr`. -/
structure Test (L C : Type) where
  /-- The test's name, which is also its manifest row and its host test name. -/
  name : String
  /-- The word to run from `init`. -/
  labels : List L
  /-- Must the word be accepted. -/
  accept : Bool := true
  /-- Expected residue per client at the reached state. Unread when
  `accept = false`. -/
  residue : List (C × List Item) := []
deriving Repr, Inhabited

/-- Run one test against a machine and a reading. -/
def Test.run {S L C : Type} [DecidableEq C]
    (M : Machine S L) (R : Reading S L C) (t : Test L C) : Bool :=
  match M.run M.init t.labels with
  | some s => t.accept && t.residue.all (fun p => R.residue s p.1 == p.2)
  | none => !t.accept

/-- A component's test suite. -/
abbrev Suite (L C : Type) := List (Test L C)

/-- Run a whole suite. -/
def Suite.run {S L C : Type} [DecidableEq C]
    (M : Machine S L) (R : Reading S L C) (ts : Suite L C) : Bool :=
  ts.all (Test.run M R)

/-- A mutant is a replacement machine, quarantined by layout and never imported
by the model. `attacks` names the obligation it attacks and is required to be
some declared property's id; `represents` is the plain sentence a reader gets
when the mutant is killed. -/
structure Mutant (S L : Type) where
  /-- The register id, e.g. `"Q-W1"`. -/
  id : String
  /-- The id of the obligation this mutant attacks. -/
  attacks : String
  /-- What killing this mutant shows. -/
  represents : String
  /-- The damaged machine. -/
  machine : Machine S L

/-- The suite kills the mutant. -/
def Mutant.killed {S L C : Type} [DecidableEq C]
    (R : Reading S L C) (ts : Suite L C) (m : Mutant S L) : Bool :=
  !(Suite.run m.machine R ts)

/-- The suite is not vacuously discriminating: the mutant passes at least one
test. Without this, a suite that refuses everything kills every mutant. -/
def Mutant.survivesSome {S L C : Type} [DecidableEq C]
    (R : Reading S L C) (ts : Suite L C) (m : Mutant S L) : Bool :=
  ts.any (Test.run m.machine R)

/-- The flat row a proof-carrying bundle projects to; this is what a manifest
holds and what the registry stores. -/
structure Entry where
  /-- One name binds all surfaces: this id is the Lean theorem name, the
  manifest row, and the host test name. -/
  id : String
  /-- The schema family, e.g. `"GUARDED"` or `"GRADED"`. -/
  family : String
  /-- The one-sentence statement, in plain prose. -/
  sentence : String
deriving DecidableEq, Repr, Inhabited

/-! ## Unit-client helpers

`Reading.forClient` at the unit client is the identity on the second component.
`simp` does not see that unaided, and it normalizes an emitted chunk through
`List.filterMap_map`, so the composed shape is needed as well. Two Unit-client
readings use these (the Queue, and the refutation machine below), which is the
rule for promoting a helper from a component module into this one. -/

namespace Reading

theorem forClient_unit (i : Item) : forClient () ((), i) = some i := rfl

/-- A chunk tagged for the unit client filters back to itself. -/
theorem chunk_forClient (c : List Item) :
    (c.map (fun m => ((), m))).filterMap (forClient ()) = c := by
  induction c with
  | nil => rfl
  | cons a r ih => simp [forClient_unit, ih]

/-- The same fact in the shape `simp` leaves after `List.filterMap_map`. -/
theorem chunk_forClient_comp (c : List Item) :
    List.filterMap (forClient () ∘ fun m => ((), m)) c = c := by
  induction c with
  | nil => rfl
  | cons a r ih => simp [Function.comp, forClient, ih]

end Reading

/-! ## Conservation with loss

`docs/research/2026-09-05-workshop-char/01-model/07-open-questions.md` Q2 asks for a second local table,
`LocalBalanceLe`, whose rows may end in a `lost` remainder, and a second generic
theorem `Machine.conservation_le` concluding
`∃ lost, residue s₀ ++ acc w = del w ++ residue s ++ lost`, from which `order` is
`List.prefix_append`. The table is stated below exactly as Q2 spells it.

The theorem, from that table alone, is **false**. In the induction step the loss
of the first label sits between `residue s₁` and `acc w'`, and the induction
hypothesis speaks only about `residue s₁ ++ acc w'`, so a component that loses
an item and then accepts and delivers a later one has `acc = [1, 2]`,
`del = [2]`, and no `lost` closes `[1, 2] = [2] ++ lost`. `Refute.lossy` below is
that component, its table is proved, and the conclusion is refuted, both in the
kernel. What is true from the table alone is a sublist statement, which does not
give `order`.

What makes the Queue's `order` axis true on lossy runs is that a loss **seals**
the queue: after a `shutdown` or a refused `offer` the queue is no longer
`opened`, it never reopens, and from then on every step delivers only from what
it already held and retains nothing it accepts. `Sealing` states that as three
word-free clauses relative to a sealed region `D`, and `conservation_le` takes
it as one extra hypothesis. The conclusion is Q2's, unchanged. -/

/-- **Local balance, with loss**: `docs/research/2026-09-05-workshop-char/01-model/07-open-questions.md` Q2,
verbatim. What the component holds for a client followed by what this label
accepts is what the label delivers, followed by what the component holds after,
followed by what the label lost. -/
def LocalBalanceLe {S L C : Type} [DecidableEq C]
    (M : Machine S L) (R : Reading S L C) (I : S → Prop) : Prop :=
  ∀ (c : C) (s s' : S) (l : L), I s → M.step s l = some s' →
    ∃ lost, R.residue s c ++ R.acc c [l] = R.del c [l] ++ R.residue s' c ++ lost

/-- **Sealing**: the clause Q2's table is missing, relative to a sealed region
`D`. A step either loses nothing or lands in `D`; `D` is closed under the step;
and inside `D` every step delivers only from what was held, so nothing accepted
there is ever retained. Three named clauses, each word-free. -/
structure Sealing {S L C : Type} [DecidableEq C]
    (M : Machine S L) (R : Reading S L C) (I D : S → Prop) : Prop where
  /-- A step that is not exactly balanced lands in the sealed region. -/
  seals : ∀ (c : C) (s s' : S) (l : L), I s → M.step s l = some s' →
    R.residue s c ++ R.acc c [l] = R.del c [l] ++ R.residue s' c ∨ D s'
  /-- The sealed region is closed under the step. -/
  closed : ∀ {s s' : S} {l : L}, I s → D s → M.step s l = some s' → D s'
  /-- Inside the sealed region a step hands out a prefix of what was held and
  keeps the rest of that prefix; what it accepts is not retained. -/
  drains : ∀ (c : C) (s s' : S) (l : L), I s → D s → M.step s l = some s' →
    ∃ t, R.residue s c = R.del c [l] ++ R.residue s' c ++ t

namespace Machine

/-- Inside the sealed region, over a whole run: what is delivered followed by
what is still held is a prefix of what was held at the start. -/
theorem run_sealed {S L C : Type} [DecidableEq C]
    {M : Machine S L} {R : Reading S L C} {I D : S → Prop}
    (hI : Inductive M I) (hS : Sealing M R I D)
    {w : List L} {s0 s : S} (hinv : I s0) (hD : D s0) (hrun : M.run s0 w = some s) (c : C) :
    ∃ t, R.residue s0 c = R.del c w ++ R.residue s c ++ t := by
  induction w generalizing s0 with
  | nil =>
    injection hrun with h
    subst h
    exact ⟨[], by simp [Reading.del]⟩
  | cons l w ih =>
    obtain ⟨s1, hst, hrest⟩ := run_cons_some hrun
    have hinv1 : I s1 := hI.step hinv hst
    have hD1 : D s1 := hS.closed hinv hD hst
    obtain ⟨t1, h1⟩ := hS.drains c s0 s1 l hinv hD hst
    obtain ⟨t2, h2⟩ := ih hinv1 hD1 hrest
    refine ⟨t2 ++ t1, ?_⟩
    rw [show l :: w = [l] ++ w from rfl, R.del_append, h1, h2]
    simp only [List.append_assoc]

/-- **Conservation with loss.** Q2's conclusion, proved generically from Q2's
table plus `Sealing`. The induction is `conservation`'s; the step splits on
`seals`, and the sealed branch is `run_sealed`. -/
theorem conservation_le {S L C : Type} [DecidableEq C]
    {M : Machine S L} {R : Reading S L C} {I D : S → Prop}
    (hI : Inductive M I) (hlocal : LocalBalanceLe M R I) (hS : Sealing M R I D)
    {w : List L} {s0 s : S} (hinv : I s0) (hrun : M.run s0 w = some s) (c : C) :
    ∃ lost, R.residue s0 c ++ R.acc c w = R.del c w ++ R.residue s c ++ lost := by
  induction w generalizing s0 with
  | nil =>
    injection hrun with h
    subst h
    exact ⟨[], by simp [Reading.acc, Reading.del]⟩
  | cons l w ih =>
    obtain ⟨s1, hst, hrest⟩ := run_cons_some hrun
    have hinv1 : I s1 := hI.step hinv hst
    obtain ⟨lost2, hih⟩ := ih hinv1 hrest
    rw [show l :: w = [l] ++ w from rfl, R.acc_append, R.del_append]
    rcases hS.seals c s0 s1 l hinv hst with hbal | hD1
    · refine ⟨lost2, ?_⟩
      rw [← List.append_assoc, hbal, List.append_assoc, hih]
      simp only [List.append_assoc]
    · obtain ⟨lost1, hle⟩ := hlocal c s0 s1 l hinv hst
      obtain ⟨t, hsealed⟩ := run_sealed hI hS hinv1 hD1 hrest c
      refine ⟨t ++ lost1 ++ R.acc c w, ?_⟩
      rw [← List.append_assoc, hle, hsealed]
      simp only [List.append_assoc]

/-- The `order` axis on every run, lossy or not: what was delivered followed by
what is still held is a prefix of what was accepted, from a state that held
nothing for the client. -/
theorem order_le {S L C : Type} [DecidableEq C]
    {M : Machine S L} {R : Reading S L C} {I D : S → Prop}
    (hI : Inductive M I) (hlocal : LocalBalanceLe M R I) (hS : Sealing M R I D)
    {w : List L} {s0 s : S} (hinv : I s0) (hrun : M.run s0 w = some s) (c : C)
    (hempty : R.residue s0 c = []) :
    (R.del c w ++ R.residue s c).isPrefixOf (R.acc c w) = true := by
  obtain ⟨lost, h⟩ := conservation_le hI hlocal hS hinv hrun c
  rw [hempty, List.nil_append] at h
  rw [h]
  exact List.isPrefixOf_iff_prefix.mpr (List.prefix_append _ _)

/-- The `noDup` axis on every run, lossy or not, relative to freshness of the
accepted word: a component that conserves up to loss introduces no duplicate. -/
theorem noDup_le {S L C : Type} [DecidableEq C]
    {M : Machine S L} {R : Reading S L C} {I D : S → Prop}
    (hI : Inductive M I) (hlocal : LocalBalanceLe M R I) (hS : Sealing M R I D)
    {w : List L} {s0 s : S} (hinv : I s0) (hrun : M.run s0 w = some s) (c : C)
    (hempty : R.residue s0 c = [])
    (hfresh : nodupB (R.acc c w) = true) :
    nodupB (R.del c w) = true := by
  obtain ⟨lost, h⟩ := conservation_le hI hlocal hS hinv hrun c
  rw [hempty, List.nil_append] at h
  rw [h, List.append_assoc] at hfresh
  exact nodupB_append_left _ _ hfresh

end Machine

/-- The trivial invariant, for a table that needs none. -/
theorem Inductive.true {S L : Type} (M : Machine S L) : Inductive M (fun _ => True) :=
  ⟨trivial, fun _ _ => trivial⟩

/-! ## The refutation of Q2's generic theorem without sealing

A three-label component over a list: `offer` keeps an item, `lose` accepts an
item and drops it on the spot, `take` hands out the whole buffer. Its
`LocalBalanceLe` table holds with the trivial invariant, and the word
`[lose 1, offer 2, take [2]]` has `acc = [1, 2]`, `del = [2]`, empty residue,
and no `lost` with `[1, 2] = [2] ++ [] ++ lost`. This is why `conservation_le`
takes `Sealing`. Kept so the dead shape stays refutable. -/
namespace Refute

inductive LossyLabel where
  | offer (i : Item)
  | lose (i : Item)
  | take (c : List Item)
deriving DecidableEq, Repr, Inhabited

def lossy : Machine (List Item) LossyLabel where
  init := []
  step := fun b l =>
    match l with
    | .offer i => some (b ++ [i])
    | .lose _ => some b
    | .take c => if c = b then some [] else none

def lossyReading : Reading (List Item) LossyLabel Unit where
  accepts := fun l => match l with
    | .offer i => some ((), i)
    | .lose i => some ((), i)
    | .take _ => none
  emits := fun l => match l with
    | .take c => c.map (fun i => ((), i))
    | _ => []
  residue := fun b _ => b

/-- Q2's table holds for the lossy component with no invariant at all. -/
theorem lossy_localBalanceLe : LocalBalanceLe lossy lossyReading (fun _ => True) := by
  intro c b b' l _ hstep
  cases c
  cases l with
  | offer i =>
    injection hstep with h; subst h
    exact ⟨[], by simp [lossyReading, Reading.acc, Reading.del, Reading.forClient]⟩
  | lose i =>
    injection hstep with h; subst h
    exact ⟨[i], by simp [lossyReading, Reading.acc, Reading.del, Reading.forClient]⟩
  | take c =>
    simp only [lossy] at hstep
    split at hstep
    · injection hstep with h; subst h
      subst ‹c = b›
      exact ⟨[], by simp [lossyReading, Reading.acc, Reading.del, Reading.chunk_forClient_comp]⟩
    · injection hstep

theorem lossy_run :
    lossy.run lossy.init [.lose 1, .offer 2, .take [2]] = some [] := by decide

/-- Q2's conclusion fails on the lossy component. -/
theorem lossy_not_conserved :
    ¬ ∃ lost, lossyReading.residue lossy.init () ++
        lossyReading.acc () [.lose 1, .offer 2, .take [2]] =
      lossyReading.del () [.lose 1, .offer 2, .take [2]] ++ lossyReading.residue [] () ++ lost := by
  intro ⟨lost, h⟩
  simp [lossyReading, lossy, Reading.acc, Reading.del, Reading.forClient] at h

end Refute

/-! ## The proof-carrying bundles

`docs/research/2026-09-05-workshop-char/01-model/06-guarded-graded.md`, with the three reached-run fields
its section 1 and `07-open-questions.md` Q3 ask for on `Guarded`: a witness is
a run, not a state somebody typed. Each bundle is a `Type` with `Prop` fields,
is never stored, and projects to `Entry`. -/

/-- A trace property with its anti-vacuity kit: the claim holds on every run
under the guard, there is a reached run that satisfies the guard, and there is
a reached run that does not and on which the claim fails. The negative pair is
what makes the guard non-vacuous, and it is a *field*, so it cannot be
forgotten. `C` is unused by the fields and is there so a `Guarded` and a
`Graded` of one component have the same parameter list. -/
structure Guarded (S L C : Type) where
  id : String
  sentence : String
  machine : Machine S L
  guard : List L → S → Bool
  claim : List L → S → Bool
  law : ∀ (w : List L) (s : S), guard w s = true → claim w s = true
  posWord : List L
  posState : S
  pos_reached : machine.run machine.init posWord = some posState
  pos_guard : guard posWord posState = true
  negWord : List L
  negState : S
  neg_reached : machine.run machine.init negWord = some negState
  neg_guard : guard negWord negState = false
  neg_claim : claim negWord negState = false

/-- The flat row of a `Guarded`. -/
def Guarded.entry {S L C : Type} (g : Guarded S L C) : Entry :=
  ⟨g.id, "GUARDED", g.sentence⟩

/-- A grade row with its anti-vacuity kit: soundness at the declared grade, one
reached witness per escape clause, a word that stays inside the failure model,
and the id of the mutant whose survival would show the grade vacuous. -/
structure Graded (S L C K : Type) [DecidableEq C] [DecidableEq K] where
  id : String
  sentence : String
  machine : Machine S L
  reading : Reading S L C
  kinds : Kinds L K
  failure : Failure K
  grade : Grade
  law : machine.Sound reading kinds failure grade
  /-- One reached witness per entry of `failure.escapes`, in order. -/
  escapeWitnesses : List (List L × S)
  escapes_reachable : ∀ p ∈ escapeWitnesses, machine.run machine.init p.1 = some p.2
  escapes_covered : escapeWitnesses.length = failure.escapes.length
  /-- The grade is not vacuous by exclusion: some run stays inside the model. -/
  quietWord : List L
  quiet_clean : failure.clean kinds quietWord = true
  /-- The id of the mutant that violates this grade. The carrier must be able
  to express the grade's failure, and this field is where that is checked
  rather than reviewed. -/
  vacuityMutant : String

/-- The flat row of a `Graded`. -/
def Graded.entry {S L C K : Type} [DecidableEq C] [DecidableEq K]
    (g : Graded S L C K) : Entry := ⟨g.id, "GRADED", g.sentence⟩

end Effect4.Char
