import Lean
import Tools.GeneratedStamp
import Effect4.Machine.Term
import Effect4.Program.AtomInventory

open Lean Meta Elab
open Effect4.Program

namespace Effect4Gen.AtomLifts

/-- Each atom with its constructor's name. `NativeAtom.all` is generated in the inductive's
declaration order (`tools/Effect4Gen/Atoms.lean`), so the two lists pair one to one. -/
def withCtorNames : MetaM (List (NativeAtom × String)) := do
  let iv ← getConstInfoInduct ``NativeAtom
  unless iv.ctors.length == NativeAtom.all.length do
    throwError "NativeAtom.all has {NativeAtom.all.length} atoms and the inductive {iv.ctors.length}"
  return NativeAtom.all.zip (iv.ctors.map fun c => c.getString!)

/-- One authoring function, with a docstring that names the atom's constructor. -/
def emitWrapper (atom : NativeAtom) (cName : String) : String :=
  let r := NativeAtom.row atom
  let doc := if r.arity.isNone then
    s!"/-- `{r.name}` (the atom `NativeAtom.{cName}`, variadic). -/"
  else
    s!"/-- `{r.name}` (the atom `NativeAtom.{cName}`). -/"
  match r.arity with
  | none =>
    s!"{doc}\ndef {r.name} (xs : List TermSrc) : TermSrc := app \"{r.name}\" xs\n"
  | some 0 =>
    s!"{doc}\ndef {r.name} : TermSrc := app \"{r.name}\" []\n"
  | some n =>
    let xs := (List.range n).map fun i => s!"x{i}"
    let params := String.intercalate " " xs
    let args := String.intercalate ", " xs
    s!"{doc}\ndef {r.name} ({params} : TermSrc) : TermSrc := app \"{r.name}\" [{args}]\n"

/-- The scope lemma for one atom function: one application of `app_scoped`. -/
def emitLemma (atom : NativeAtom) : String :=
  let r := NativeAtom.row atom
  match r.arity with
  | none =>
    s!"theorem {r.name}_scoped \{xs : List TermSrc} (h : ∀ x ∈ xs, x.Scoped) :\n    ({r.name} xs).Scoped :=\n  app_scoped \"{r.name}\" h\n"
  | some 0 =>
    s!"theorem {r.name}_scoped :\n    ({r.name}).Scoped :=\n  app_scoped \"{r.name}\" TermSrc.Scoped_nil\n"
  | some n =>
    let xs := (List.range n).map fun i => s!"x{i}"
    let params := String.intercalate " " xs
    let hyps := String.intercalate " " ((List.range n).map fun i => s!"(h{i} : x{i}.Scoped)")
    let proof := (List.range n).foldr (fun i acc => s!"(TermSrc.Scoped_cons h{i} {acc})") "TermSrc.Scoped_nil"
    s!"theorem {r.name}_scoped \{{params} : TermSrc} {hyps} :\n    ({r.name} {params}).Scoped :=\n  app_scoped \"{r.name}\" {proof}\n"

structure Args where
  group : String := "Atoms"
  imports : List String := []
  out : Option String := none
  headerOut : Option String := none
  append : Option String := none
  moduleHeader : Bool := false
  metaImports : List String := []
  types : List String := []

partial def parseArgs : List String → Args → Except String Args
  | [], a => .ok a
  | "--group" :: g :: rest, a => parseArgs rest { a with group := g }
  | "--imports" :: i :: rest, a => parseArgs rest { a with imports := (i.splitOn ",").filter (· != "") }
  | "--out" :: o :: rest, a => parseArgs rest { a with out := some o }
  | "--header-out" :: o :: rest, a => parseArgs rest { a with headerOut := some o }
  | "--append" :: p :: rest, a => parseArgs rest { a with append := some p }
  | "--module" :: rest, a => parseArgs rest { a with moduleHeader := true }
  | "--meta-imports" :: i :: rest, a =>
    parseArgs rest { a with metaImports := (i.splitOn ",").filter (· != "") }
  | "--" :: rest, a => parseArgs rest a
  | t :: rest, a =>
    if t.startsWith "--" then .error s!"unknown option {t}" else parseArgs rest { a with types := a.types ++ [t] }

def run (args : Args) : MetaM (Array String) := do
  let outPath := (args.headerOut.orElse (fun _ => args.out) |>.getD "<stdout>").replace "\\" "/"
  let head := "lake exe effect4gen-catalogue AtomLifts --group " ++ args.group ++ Tools.GeneratedStamp.moduleFlags args.moduleHeader args.metaImports
    ++ " --imports " ++ String.intercalate "," args.imports ++ " --out " ++ outPath
    ++ (match args.append with | some p => " --append " ++ p.replace "\\" "/" | none => "")
  let mut lines : Array String := #[
    "-- GENERATED by tools/Effect4Gen/AtomLifts.lean from NativeAtom.all and NativeAtom.row. Do not edit.",
    "-- Regenerate (tools/Effect4Gen/Driver.lean runs this for every group; --verify refuses a diff):",
    "--   " ++ head ++ (if args.types.isEmpty then "" else " -- " ++ String.intercalate " " args.types)]
  if let some p := args.append then
    lines := lines.push s!"-- Acceptance guards appended verbatim from: {p.replace "\\" "/"}"
  lines := lines ++ (args.imports.map fun i => s!"import {i}").toArray
  lines := lines ++ #["", "set_option autoImplicit false", "", "namespace Effect4.Program.Authoring.Atom", "", "open Effect4.Program Effect4.Program.Authoring", ""]
  match args.group with
  | "Atoms" =>
    for (atom, cName) in (← withCtorNames) do
      lines := lines.push (emitWrapper atom cName)
  | "AtomsLaws" =>
    for atom in NativeAtom.all do
      lines := lines.push (emitLemma atom)
  | g => throwError "unknown group {g}: Atoms or AtomsLaws"
  lines := Tools.GeneratedStamp.trimBlankTail lines ++ #["", "end Effect4.Program.Authoring.Atom", ""]
  if let some p := args.append then
    let txt ← IO.FS.readFile p
    lines := lines ++ (txt.splitOn "\n").toArray.map (·.replace "\r" "")
  return lines

end Effect4Gen.AtomLifts

open Effect4Gen.AtomLifts in
/-- One generator run: parse the arguments, load the environment `--imports` names, write the
file. `lake exe effect4gen-catalogue AtomLifts <args>` runs it (`Effect4Gen/CatalogueExe.lean`). -/
def Effect4Gen.AtomLifts.cli (argv : List String) : IO Unit := do
  let args ← match parseArgs argv {} with
    | .ok a => pure a
    | .error e => throw (IO.userError e)
  if args.imports.isEmpty then
    throw (IO.userError "--imports names the modules the emitted file imports; none given")
  Lean.initSearchPath (← Lean.findSysroot)
  let env ← Lean.importModules (args.imports.map fun i => { module := i.toName }).toArray {} 0
  let ctx : Core.Context := { fileName := "<gen>", fileMap := default }
  let act : MetaM Unit := do
    let lines ← run args
    let stamp := Tools.GeneratedStamp.note "tools/Effect4Gen/AtomLifts.lean"
    let text := Tools.GeneratedStamp.endWithOneNewline ("-- " ++ stamp ++ "\n" ++ String.intercalate "\n" lines.toList ++ "\n")
    let text := if args.moduleHeader then Tools.GeneratedStamp.moduleText args.metaImports text
      else text
    match args.out with
    | some p => IO.FS.writeFile p text
    | none => IO.println text
  let _ ← (act.run' {}).toIO ctx { env := env }
