import Lean
import Tools.GeneratedStamp
import Effect4.Program.NativeAtom

/-!
# Effect4Gen.PreludeAtoms — the TypeScript prelude's atom block, from the table

`harness/truth/prelude.ts` was the last hand-transcribed face of the atom alphabet, and said so
in its own header ("Hand-written transcription (no generator exists for it yet); when either
Lean table changes, this file changes with it, and the self-test refuses an atom it does not
export"). The self-test made an appended atom impossible to leave *untested*; it could still be
left *unwritten*, and the failure was a red harness rather than a generated file.

This group closes that row. One export per atom: the body is the `prelude` column of
`NativeAtom.row` (`src/Effect4/Machine/Term.lean`), the doc is the `cite` column of
`NativeAtom.spec` (`src/Effect4/Program/NativeAtom.lean`), so the face carries the citation the
table carries. `prelude.ts` re-exports every name and keeps the hand-written self-test table;
`run-truth.ts` still refuses an atom of the generated profile that has no case in it.

    lake env lean -M 4096 --run tools/Effect4Gen/PreludeAtoms.lean --group PreludeAtoms
      --imports Effect4.Program.NativeAtom --out harness/truth/prelude-atoms.gen.ts

A file of its own, rather than a second group of `tools/Effect4Gen/Atoms.lean`, because it
reads the typing half, and the typing half imports what `Atoms.lean` writes: one emitter for
both would be a module importing the file it produces.

This is a tool (`IO`, `Lean.Meta`); it is not part of any audited library.
-/

open Lean Meta Elab
open Effect4.Program

namespace Effect4Gen.PreludeAtoms

/-- One export: the doc is `Spec.cite` wrapped as a JSDoc block, the body is
`AtomRow.prelude`, verbatim. -/
def entry (atom : NativeAtom) : List String :=
  let r := NativeAtom.row atom
  let doc := ((NativeAtom.spec atom).cite.splitOn "\n").map fun line =>
    if line.isEmpty then " *" else " * " ++ line
  ["/**"] ++ doc ++ [" */", "export const " ++ r.name ++ " = " ++ r.prelude, ""]

/-- The whole file: the imports the bodies need, the one shared reader the cause atoms call,
and the atoms in the inventory's order. `queryCause` is the host image of
`Effect4.Program.queryReasons?`; it is not an atom, so it is written here rather than carried
in a row. -/
def render (head : String) : List String :=
  [ "// GENERATED by tools/Effect4Gen/PreludeAtoms.lean from NativeAtom.row and NativeAtom.spec \
     — do not edit."
  , "// Regenerate (tools/Effect4Gen/Driver.lean runs this for every group; the drift check is \
     make check-gen):"
  , "//   " ++ head
  , "//"
  , "// One export per atom of the alphabet (`Effect4.Program.NativeAtom`). `prelude.ts`"
  , "// re-exports every name below and keeps the hand-written self-test table that exercises"
  , "// them; `run-truth.ts` refuses an atom of the generated profile that has no case there."
  , "import { Cause, Exit, Option } from \"effect\""
  , ""
  , "/** The two query inputs advertised by NativeAtom (`Effect4.Program.queryReasons?`): a"
  , " * cause, or an exit, whose success side has no reasons. */"
  , "const queryCause = <A, E>(input: Cause.Cause<E> | Exit.Exit<A, E>): Cause.Cause<E> =>"
  , "  Exit.isExit(input) ? Exit.isFailure(input) ? input.cause : Cause.empty : input"
  , ""
  ] ++ NativeAtom.all.flatMap entry

structure Args where
  group : String := "PreludeAtoms"
  imports : List String := []
  out : Option String := none
  headerOut : Option String := none
  append : Option String := none
  types : List String := []

partial def parseArgs : List String → Args → Except String Args
  | [], a => .ok a
  | "--group" :: g :: rest, a => parseArgs rest { a with group := g }
  | "--imports" :: i :: rest, a => parseArgs rest { a with imports := (i.splitOn ",").filter (· != "") }
  | "--out" :: o :: rest, a => parseArgs rest { a with out := some o }
  | "--header-out" :: o :: rest, a => parseArgs rest { a with headerOut := some o }
  | "--append" :: p :: rest, a => parseArgs rest { a with append := some p }
  | "--" :: rest, a => parseArgs rest a
  | t :: rest, a =>
    if t.startsWith "--" then .error s!"unknown option {t}" else parseArgs rest { a with types := a.types ++ [t] }

def run (args : Args) : MetaM (Array String) := do
  let outPath := (args.headerOut.orElse (fun _ => args.out) |>.getD "<stdout>").replace "\\" "/"
  let head := "lake env lean -M 4096 --run tools/Effect4Gen/PreludeAtoms.lean --group "
    ++ args.group ++ " --imports " ++ String.intercalate "," args.imports
    ++ " --out " ++ outPath
  match args.group with
  | "PreludeAtoms" => return (render head).toArray
  | g => throwError "unknown group {g}: PreludeAtoms"

end Effect4Gen.PreludeAtoms

open Effect4Gen.PreludeAtoms in
def main (argv : List String) : IO Unit := do
  let args ← match parseArgs argv {} with
    | .ok a => pure a
    | .error e => throw (IO.userError e)
  if args.imports.isEmpty then
    throw (IO.userError "--imports names the modules the generator reads; none given")
  Lean.initSearchPath (← Lean.findSysroot)
  let env ← Lean.importModules (args.imports.map fun i => { module := i.toName }).toArray {} 0
  let ctx : Core.Context := { fileName := "<gen>", fileMap := default }
  let act : MetaM Unit := do
    let lines ← run args
    let stamp := Tools.GeneratedStamp.note "tools/Effect4Gen/PreludeAtoms.lean"
    let text := "// " ++ stamp ++ "\n" ++ String.intercalate "\n" lines.toList ++ "\n"
    match args.out with
    | some p => IO.FS.writeFile p text
    | none => IO.println text
  let _ ← (act.run' {}).toIO ctx { env := env }
