(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400017`, seed 400017, 12 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400017 () =
  let v0 = Fibers_fixture.fork 0 in
  let v1 = Store_fixtures.ref_make 5 in
  let v2 = Fibers_fixture.fork 2 in
  ignore (Fibers_fixture.interrupt v2);
  let _v3 = Fibers_fixture.cleanups () in
  let _v4 = Store_fixtures.ref_get v1 in
  let _v5 = Fibers_fixture.started () in
  let _v6 = Fibers_fixture.started () in
  let _v7 = Fibers_fixture.await_value v0 in
  let v8 = Fibers_fixture.fork_detach 4 in
  let _v9 = Fibers_fixture.await_value v2 in
  let v10 = Fibers_fixture.join v8 in
  v10

let programs : (string * (unit -> value)) list = [ ("p400017", corpus_p400017) ]
