#!/usr/bin/env python3
"""Generate `e4d_pins.ml`: the rc.112 pin, the per-file digests, the build note.

`avatar_main.ml` stamps every `input` row with one digest over all its sources at once. The
daemon stamps each file with its own SHA-256, so a `pins` answer says which file changed --
which matters when seat W1 is editing the avatar under the daemon's feet.

The avatar digests are taken from the sources actually compiled (the build directory), not
from the working tree, so that a build pinned to a git revision reports the revision's
digests and not the tree's.

The pin itself is not invented: it is the `pin effects <sha>` row of
`generated/traces/masks.tsv`, the same row `avatar/build-avatar.sh` reads out of a golden.

Usage:
  gen_pins.py <repo> <build dir> <avatar modules, space separated> <corpus text>
              <server dir> <masks.tsv> <ocaml version> <node version>
"""
import hashlib
import os
import sys


def ocaml_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def digest(path):
    with open(path, "rb") as handle:
        return hashlib.sha256(handle.read()).hexdigest()


def main():
    (repo, build, avatar_modules, corpus_text, server, masks,
     ocaml_version, node_version) = sys.argv[1:9]

    pin = ""
    with open(masks) as handle:
        for line in handle:
            cells = line.rstrip("\n").split("\t")
            if len(cells) >= 3 and cells[0] == "pin" and cells[1] == "effects":
                pin = cells[2]

    inputs = []
    for name in sorted(avatar_modules.split()):
        inputs.append(("workshop/OCaml5/avatar/" + name, digest(os.path.join(build, name))))
    inputs.append(("workshop/OCaml5/avatar/corpus/programs.txt", digest(corpus_text)))

    server_files = []
    for name in sorted(os.listdir(server)):
        if name.endswith(".ml") or name in ("build-server.sh", "server_runtime.js"):
            server_files.append(("workshop/OCaml5/server/" + name, os.path.join(server, name)))
    for name in sorted(os.listdir(os.path.join(server, "tools"))):
        server_files.append(("workshop/OCaml5/server/tools/" + name,
                             os.path.join(server, "tools", name)))
    inputs.extend((label, digest(path)) for label, path in server_files)
    inputs.append(("generated/traces/masks.tsv", digest(masks)))
    inputs.append(("Effect4/Deep/Fibers.lean",
                   digest(os.path.join(repo, "Effect4/Deep/Fibers.lean"))))

    # The generator digest: the server's own sources and its build script, in one hash, the
    # way `build-avatar.sh` stamps the avatar's `generator` row.
    combined = hashlib.sha256()
    for _label, path in server_files:
        with open(path, "rb") as handle:
            combined.update(handle.read())

    print("(* GENERATED by workshop/OCaml5/server/tools/gen_pins.py. Do not edit. *)")
    print()
    print("let pin = %s" % ocaml_string(pin))
    print("let generator_sha = %s" % ocaml_string(combined.hexdigest()))
    print("let build_note = %s" % ocaml_string(
        "ocaml %s; js_of_ocaml 5.7.1 --enable effects; node %s" % (ocaml_version, node_version)))
    print()
    print("let inputs : (string * string) list = [")
    for label, sha in inputs:
        print("  (%s, %s);" % (ocaml_string(label), ocaml_string(sha)))
    print("]")


if __name__ == "__main__":
    main()
