import Test.Program.QueueMask
import Test.Program.QueueDefs
import Effect4.Store.Domain.ProgramWire

/-!
The writer of the Queue's engine fixture. `make gen-fixtures` runs it, with every other lane's
writer (`scripts/generate.py --only fixtures`, the group `fixtures` of `docs/GENERATED.md`).
Alone, run it from the repository's root, after a build of `Test.Program.QueueMask`:

    lake env lean --run ocaml/engine/test/queue/write.lean

It writes `queue.txt` and `queue-defs.txt` beside this file, or into the folder that its one
argument names. `queue.txt` holds five runs over the library's operations
(`src/Effect4/Modules/Queue/Ops.lean`): the scenarios R1, R4, R2 and R5 of
`Test/Program/QueueScenarios.lean`, and the masked caller of `Test/Program/QueueMask.lean`.
`queue-defs.txt` holds the four scenarios again over the Queue's definitions
(`src/Effect4/Modules/Queue/Defs.lean`, `Test/Program/QueueDefs.lean`): each program has a
definition block, and each operation is an invocation (decisions row 328, slice PROC-4). A run holds the fuel, the program's canonical bytes
(`Effect4.Program.Wire.hexOf`) and the root's exit of Lean's machine, in the spelling of the
engine's `show_exit` (`ocaml/engine/e4_engine.ml`). The battery `Test/Program/QueueEngine.lean`
binds the committed file to these programs, and `test_queue.ml`, beside this file, reads it.
-/

open Effect4 Effect4.Machine Effect4.Program
open Test.Program.QueueScenarios (r1 r2 r4 r5 r1With r2With r4With r5With mk)
open Test.Program.QueueMask (maskedCaller)
open Test.Program.QueueDefs (invoked mkDefs)

/-- A Boolean or a number in the spelling of the engine's `show_val`. -/
def showScalar : Val → Option String
  | .bool b => some (toString b)
  | .nat n => some (toString n)
  | _ => none

/-- A value in the spelling of the engine's `show_val`. The scenarios answer Booleans, numbers
and flat lists of them: any other value has no spelling here, and the writer refuses it. -/
def showVal : Val → Option String
  | .list xs => (xs.mapM showScalar).map fun parts => "list[" ++ ",".intercalate parts ++ "]"
  | v => showScalar v

/-- An exit in the spelling of the engine's `show_exit`. Only a success has a spelling here. -/
def showExit : ExitV → Option String
  | .success v => (showVal v).map ("success " ++ ·)
  | .failure _ => none

def fuel : Nat := 20000

/-- One run of a fixture: its name, its fuel, its program's bytes and its exit. -/
def runText (name : String) (m : Authoring.Module NativeOp) : Option String := do
  let built ← (Effect4.Api.Author.build m).toOption
  let exit ← (Api.run built.program fuel).exit
  let shown ← showExit exit
  pure (s!"run {name}\nfuel {fuel}\nprogram {Wire.hexOf built.program}\nexit {shown}\nend\n")

/-- The fixture's runs, in the file's order: each name with its scenario. R1 fills and empties a
queue. R4 holds a second offer at capacity one. In R2 a taker waits and an offer wakes it. In R5
a waiting taker is interrupted. `masked` is a taker under a masked caller (decisions row
222). -/
def runs : List (String × Authoring.Module NativeOp) :=
  [("r1", mk r1), ("r4", mk r4), ("r2", mk r2), ("r5", mk r5), ("masked", mk maskedCaller)]

/-- The runs of `queue-defs.txt`: the same four scenarios, each a module with the Queue's
definitions and each operation an invocation. -/
def defsRuns : List (String × Authoring.Module NativeOp) :=
  [("r1", mkDefs (r1With invoked)), ("r4", mkDefs (r4With invoked)),
    ("r2", mkDefs (r2With invoked)), ("r5", mkDefs (r5With invoked))]

def header : String :=
  "# GENERATED by ocaml/engine/test/queue/write.lean; do not edit.\n" ++
    "# Write again: lake env lean --run ocaml/engine/test/queue/write.lean\n"

def main (args : List String) : IO UInt32 := do
  let folder := args.head?.getD "ocaml/engine/test/queue"
  match runs.mapM (fun (name, m) => runText name m),
      defsRuns.mapM (fun (name, m) => runText name m) with
  | some texts, some defsTexts =>
    IO.FS.writeFile s!"{folder}/queue.txt" (header ++ String.join texts)
    IO.println s!"wrote {folder}/queue.txt"
    IO.FS.writeFile s!"{folder}/queue-defs.txt" (header ++ String.join defsTexts)
    IO.println s!"wrote {folder}/queue-defs.txt"
    return 0
  | _, _ =>
    IO.eprintln "write.lean: a scenario does not build, does not finish, or answers a value with no spelling"
    return 1
