(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400163`, seed 400163, 26 operations.
   Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400163 () =
  let v0 = Fibers_fixture.fork 1 in
  let _v1 = Fibers_fixture.cleanups () in
  let v2 = Store_fixtures.layer_build 3 in
  ignore (Fibers_fixture.interrupt v0);
  ignore (Fibers_fixture.interrupt v0);
  let _v3 = Fibers_fixture.cleanups () in
  let v4 = Fibers_fixture.fork 4 in
  let v5 = Store_fixtures.scope_make () in
  ignore (Store_fixtures.scope_remove v5 3);
  let _v6 = Extra_fixture.await_all [ v0; v4 ] in
  ignore (Store_fixtures.scope_remove v5 2);
  let _v7 = Fibers_fixture.cleanups () in
  let _v8 = Fibers_fixture.started () in
  let _v9 = Store_fixtures.layer_scope_of v2 in
  let v10 = Store_fixtures.scope_make () in
  let _v11 = Store_fixtures.layer_scope_of v2 in
  let _v12 = Fibers_fixture.started () in
  ignore (Fibers_fixture.interrupt v0);
  let _v13 = Fibers_fixture.started () in
  let _v14 = Fibers_fixture.started () in
  let _v15 = Store_fixtures.scope_close v10 in
  let _v16 = Store_fixtures.layer_provide_count 1 in
  let _v17 = Store_fixtures.layer_build 3 in
  let _v18 = Fibers_fixture.join v0 in
  let _v19 = Fibers_fixture.cleanups () in
  let v20 = Fibers_fixture.join v4 in
  v20

let programs : (string * (unit -> value)) list = [ ("p400163", corpus_p400163) ]
