/**
 * Generated by OCaml5.Fuzz (spike P5, round four). Program `p400190`, seed 400190, 35 operations.
 *
 * Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`.
 */
import { Context, Effect } from "effect"
import type { Deferred, Fiber, Option, Result } from "effect"

/** Service `Fibers`: one method per operation of the Lean family, plus the three rows
 * `fiber-fixture.ts` does not declare and rc.112 does. */
export class Fibers extends Context.Service<Fibers, {
  readonly fork: (body: number) => Effect.Effect<Fiber.Fiber<number, number>>
  readonly forkDetach: (body: number) => Effect.Effect<Fiber.Fiber<number, number>>
  readonly join: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<number, number>
  readonly awaitValue: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<Option.Option<number>>
  readonly awaitError: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<Option.Option<number>>
  readonly interrupt: (fiber: Fiber.Fiber<number, number>) => Effect.Effect<void>
  readonly started: Effect.Effect<ReadonlyArray<number>>
  readonly cleanups: Effect.Effect<ReadonlyArray<number>>
  readonly yieldNow: (priority: number) => Effect.Effect<void>
  readonly interruptAll: (fibers: ReadonlyArray<Fiber.Fiber<number, number>>) => Effect.Effect<void>
  readonly awaitAll: (fibers: ReadonlyArray<Fiber.Fiber<number, number>>) => Effect.Effect<void>
}>()("Fibers") {}

export const FibersRows = { "fork": { params: 1, answer: "Fiber.Fiber<number, number>" }, "forkDetach": { params: 1, answer: "Fiber.Fiber<number, number>" }, "join": { params: 1, answer: "number" }, "awaitValue": { params: 1, answer: "Option.Option<number>" }, "awaitError": { params: 1, answer: "Option.Option<number>" }, "interrupt": { params: 1, answer: "void" }, "started": { params: 0, answer: "ReadonlyArray<number>" }, "cleanups": { params: 0, answer: "ReadonlyArray<number>" }, "yieldNow": { params: 1, answer: "void" }, "interruptAll": { params: 1, answer: "void" }, "awaitAll": { params: 1, answer: "void" } }

/** Service `Deferreds` (`harness/trace/deferred-fixture.ts`). */
export class Deferreds extends Context.Service<Deferreds, {
  readonly make: Effect.Effect<Deferred.Deferred<number, number>>
  readonly succeed: (cell: Deferred.Deferred<number, number>, value: number) => Effect.Effect<boolean>
  readonly fail: (cell: Deferred.Deferred<number, number>, error: number) => Effect.Effect<boolean>
  readonly isDone: (cell: Deferred.Deferred<number, number>) => Effect.Effect<boolean>
  readonly poll: (cell: Deferred.Deferred<number, number>) => Effect.Effect<Option.Option<Result.Result<number, number>>>
  readonly awaitValue: (cell: Deferred.Deferred<number, number>) => Effect.Effect<number, number>
  readonly awaitError: (cell: Deferred.Deferred<number, number>) => Effect.Effect<number, number>
}>()("Deferreds") {}

export const DeferredsRows = { "make": { params: 0, answer: "Deferred.Deferred<number, number>" }, "succeed": { params: 2, answer: "boolean" }, "fail": { params: 2, answer: "boolean" }, "isDone": { params: 1, answer: "boolean" }, "poll": { params: 1, answer: "Option.Option<Result.Result<number, number>>" }, "awaitValue": { params: 1, answer: "number" }, "awaitError": { params: 1, answer: "number" } }

/** Lowered from `p400190` by OCaml5.Fuzz. */
export const corpus_p400190 = (n: number) =>
  Effect.gen(function* () {
    const fibers = yield* Fibers
    const deferreds = yield* Deferreds
    void n
    const v0 = yield* fibers.fork(0)
    const v1 = yield* fibers.fork(2)
    const v2 = yield* fibers.started
    const v3 = yield* fibers.fork(4)
    const v4 = yield* fibers.awaitError(v3)
    const v5 = yield* fibers.fork(0)
    const v6 = yield* fibers.cleanups
    const v7 = yield* fibers.cleanups
    const v8 = yield* fibers.awaitError(v1)
    const v9 = yield* fibers.forkDetach(0)
    yield* fibers.yieldNow(0)
    const v10 = yield* fibers.started
    const v11 = yield* fibers.fork(2)
    const v12 = yield* deferreds.make
    const v13 = yield* fibers.started
    const v14 = yield* fibers.started
    const v15 = yield* fibers.awaitError(v9)
    const v16 = yield* fibers.started
    const v17 = yield* fibers.join(v11)
    const v18 = yield* fibers.awaitValue(v9)
    const v19 = yield* fibers.cleanups
    const v20 = yield* deferreds.awaitError(v12)
    yield* fibers.interrupt(v9)
    yield* fibers.interrupt(v3)
    const v21 = yield* fibers.started
    const v22 = yield* fibers.cleanups
    const v23 = yield* fibers.started
    const v24 = yield* fibers.awaitAll([v9])
    const v25 = yield* deferreds.awaitError(v12)
    const v26 = yield* fibers.fork(4)
    const v27 = yield* fibers.fork(1)
    const v28 = yield* fibers.started
    const v29 = yield* fibers.join(v3)
    yield* fibers.interrupt(v0)
    const v30 = yield* fibers.join(v3)
    return v30
  })
