-- GENERATED by tools/Effect4Gen/Authoring.lean; do not edit
-- GENERATED by tools/Effect4Gen/Authoring.lean from tools/Effect4Gen/binders.json and the Lean environment. Do not edit.
-- Regenerate (tools/Effect4Gen/Driver.lean runs this for every group; --verify refuses a diff):
--   lake env lean -M 4096 --run tools/Effect4Gen/Authoring.lean --group Authoring --imports Effect4.Program.Authoring --out src/Effect4/Program/Authoring/Lifts.lean --append tools/Effect4Gen/guards/authoring.lean -- Effect4.Program.Eff
-- Acceptance guards appended verbatim from: tools/Effect4Gen/guards/authoring.lean
import Effect4.Program.Authoring

set_option autoImplicit false

namespace Effect4.Program.Authoring

open Effect4.Program

/-- `Effect4.Program.Eff.succeed`. -/
def succeed {Op : Type} (value : TermSrc) : Src Op :=
  fun env p => do
    let x0 ← value env p
    .ok (.succeed x0)

/-- `Effect4.Program.Eff.fail`. -/
def fail {Op : Type} (error : TermSrc) : Src Op :=
  fun env p => do
    let x0 ← error env p
    .ok (.fail x0)

/-- `Effect4.Program.Eff.failCause`. -/
def failCause {Op : Type} (cause : CauseSrc) : Src Op :=
  fun env p => do
    let x0 ← cause env p
    .ok (.failCause x0)

/-- `Effect4.Program.Eff.sync`. -/
def sync {Op : Type} (thunk : TermSrc) : Src Op :=
  fun env p => do
    let x0 ← thunk env p
    .ok (.sync x0)

/-- `Effect4.Program.Eff.suspend`. -/
def suspend {Op : Type} (body : Src Op) : Src Op :=
  fun env p => do
    let x0 ← body env (p ++ [0])
    .ok (.suspend x0)

/-- `Effect4.Program.Eff.perform`. -/
def perform {Op : Type} (op : Op) (request : TermSrc) : Src Op :=
  fun env p => do
    let x1 ← request env p
    .ok (.perform op x1)

/-- `Effect4.Program.Eff.bind`: `rest` sees `answer`. -/
def bind {Op : Type} (answer : String) (first : Src Op) (rest : Src Op) : Src Op :=
  fun env p => do
    let x0 ← first env (p ++ [0])
    let x1 ← rest (env.push [answer]) (p ++ [1])
    .ok (.bind x0 x1)

/-- `Effect4.Program.Eff.catchCause`: `handler` sees `cause`. -/
def catchCause {Op : Type} (cause : String) (body : Src Op) (handler : Src Op) : Src Op :=
  fun env p => do
    let x0 ← body env (p ++ [0])
    let x1 ← handler (env.push [cause]) (p ++ [1])
    .ok (.catchCause x0 x1)

/-- `Effect4.Program.Eff.matchCause`: `onValue` sees `value`; `onCause` sees `cause`. -/
def matchCause {Op : Type} (value : String) (cause : String) (body : Src Op) (onValue : Src Op) (onCause : Src Op) : Src Op :=
  fun env p => do
    let x0 ← body env (p ++ [0])
    let x1 ← onValue (env.push [value]) (p ++ [1])
    let x2 ← onCause (env.push [cause]) (p ++ [2])
    .ok (.matchCause x0 x1 x2)

/-- `Effect4.Program.Eff.onExit`: `finalizer` sees `exit`. -/
def onExit {Op : Type} (exit : String) (body : Src Op) (finalizer : Src Op) : Src Op :=
  fun env p => do
    let x0 ← body env (p ++ [0])
    let x1 ← finalizer (env.push [exit]) (p ++ [1])
    .ok (.onExit x0 x1)

/-- `Effect4.Program.Eff.exit`. -/
def exit {Op : Type} (body : Src Op) : Src Op :=
  fun env p => do
    let x0 ← body env (p ++ [0])
    .ok (.exit x0)

/-- `Effect4.Program.Eff.uninterruptible`. -/
def uninterruptible {Op : Type} (body : Src Op) : Src Op :=
  fun env p => do
    let x0 ← body env (p ++ [0])
    .ok (.uninterruptible x0)

/-- `Effect4.Program.Eff.interruptible`. -/
def interruptible {Op : Type} (body : Src Op) : Src Op :=
  fun env p => do
    let x0 ← body env (p ++ [0])
    .ok (.interruptible x0)

/-- `Effect4.Program.Eff.branch`. -/
def branch {Op : Type} (test : TermSrc) (thenB : Src Op) (elseB : Src Op) : Src Op :=
  fun env p => do
    let x0 ← test env p
    let x1 ← thenB env (p ++ [0])
    let x2 ← elseB env (p ++ [1])
    .ok (.branch x0 x1 x2)

/-- `Effect4.Program.Eff.whileLoop`: `test` sees `cursor`; `step` sees `cursor`, `answer`; `body` sees `cursor`. -/
def whileLoop {Op : Type} (cursor : String) (answer : String) (initial : TermSrc) (test : TermSrc) (step : TermSrc) (body : Src Op) : Src Op :=
  fun env p => do
    let x0 ← initial env p
    let x1 ← test (env.push [cursor]) p
    let x2 ← step (env.push [cursor, answer]) p
    let x3 ← body (env.push [cursor]) (p ++ [0])
    .ok (.whileLoop x0 x1 x2 x3)

/-- `Effect4.Program.Eff.yieldNow`. -/
def yieldNow {Op : Type} (priority : Nat) : Src Op :=
  fun _ _ => .ok (.yieldNow priority)

/-- `Effect4.Program.Eff.callback`. -/
def callback {Op : Type} (register : Op) (request : TermSrc) : Src Op :=
  fun env p => do
    let x1 ← request env p
    .ok (.callback register x1)

/-- `Effect4.Program.Eff.awaitFiber`. -/
def awaitFiber {Op : Type} (fiber : TermSrc) (mode : Effect4.Supervision.ObserverMode) : Src Op :=
  fun env p => do
    let x0 ← fiber env p
    .ok (.awaitFiber x0 mode)

/-- `Effect4.Program.Eff.withFiber`. -/
def withFiber {Op : Type} (action : ActionSrc Op) : Src Op :=
  fun env p => do
    let x0 ← action env (p ++ [0])
    .ok (.withFiber x0)

/-- `Effect4.Program.Eff.scoped`. -/
def scope {Op : Type} (body : Src Op) : Src Op :=
  fun env p => do
    let x0 ← body env (p ++ [0])
    .ok (.scoped x0)

/-- `Effect4.Program.Eff.acquireRelease`: `release` sees `resource`, `exit`. -/
def acquireRelease {Op : Type} (resource : String) (exit : String) (acquire : Src Op) (release : Src Op) : Src Op :=
  fun env p => do
    let x0 ← acquire env (p ++ [0])
    let x1 ← release (env.push [resource, exit]) (p ++ [1])
    .ok (.acquireRelease x0 x1)

/-- `Effect4.Program.Eff.provideLayer`. -/
def provideLayer {Op : Type} (layer : LayerSrc Op) (isLocal : Bool) (body : Src Op) : Src Op :=
  fun env p => do
    let x0 ← layer env (p ++ [0])
    let x2 ← body env (p ++ [1])
    .ok (.provideLayer x0 isLocal x2)

/-- `Effect4.Program.Eff.service`. -/
def service {Op : Type} (key : Effect4.ServiceKey) : Src Op :=
  fun _ _ => .ok (.service key)

/-- `Effect4.Program.Eff.provideService`. -/
def provideService {Op : Type} (key : Effect4.ServiceKey) (value : TermSrc) (body : Src Op) : Src Op :=
  fun env p => do
    let x1 ← value env p
    let x2 ← body env (p ++ [0])
    .ok (.provideService key x1 x2)

/-- `Effect4.Program.Eff.catchIf`: `test` sees `error`; `handler` sees `error`. -/
def catchIf {Op : Type} (error : String) (test : TermSrc) (body : Src Op) (handler : Src Op) : Src Op :=
  fun env p => do
    let x0 ← test (env.push [error]) p
    let x1 ← body env (p ++ [0])
    let x2 ← handler (env.push [error]) (p ++ [1])
    .ok (.catchIf x0 x1 x2)

/-- `Effect4.Program.ActionTerm.fork`. -/
def Action.fork {Op : Type} (program : Src Op) (options : Effect4.Supervision.ForkOptions) : ActionSrc Op :=
  fun env p => do
    let x0 ← program env (p ++ [0])
    .ok (.fork x0 options)

/-- `Effect4.Program.ActionTerm.forkIn`. -/
def Action.forkIn {Op : Type} (program : Src Op) (options : Effect4.Supervision.ForkOptions) (scope : TermSrc) : ActionSrc Op :=
  fun env p => do
    let x0 ← program env (p ++ [0])
    let x2 ← scope env p
    .ok (.forkIn x0 options x2)

/-- `Effect4.Program.ActionTerm.forkScoped`. -/
def Action.forkScoped {Op : Type} (program : Src Op) (options : Effect4.Supervision.ForkOptions) : ActionSrc Op :=
  fun env p => do
    let x0 ← program env (p ++ [0])
    .ok (.forkScoped x0 options)

/-- `Effect4.Program.ActionTerm.runIn`. -/
def Action.runIn {Op : Type} (target : TermSrc) (scope : TermSrc) : ActionSrc Op :=
  fun env p => do
    let x0 ← target env p
    let x1 ← scope env p
    .ok (.runIn x0 x1)

/-- `Effect4.Program.ActionTerm.interrupt`. -/
def Action.interrupt {Op : Type} (target : TermSrc) : ActionSrc Op :=
  fun env p => do
    let x0 ← target env p
    .ok (.interrupt x0)

/-- `Effect4.Program.ActionTerm.interruptAll`. -/
def Action.interruptAll {Op : Type} (targets : TermSrc) (interruptor : Option TermSrc) : ActionSrc Op :=
  fun env p => do
    let x0 ← targets env p
    let x1 ← elabOption interruptor env p
    .ok (.interruptAll x0 x1)

/-- `Effect4.Program.ActionTerm.awaitAll`. -/
def Action.awaitAll {Op : Type} (targets : TermSrc) : ActionSrc Op :=
  fun env p => do
    let x0 ← targets env p
    .ok (.awaitAll x0)

/-- `Effect4.Program.ActionTerm.raceAll`. -/
def Action.raceAll {Op : Type} (entrants : List (Src Op)) : ActionSrc Op :=
  fun env p => do
    let x0 ← elabEffs entrants env (p ++ [0])
    .ok (.raceAll x0)

/-- `Effect4.Program.ActionTerm.getContext`. -/
def Action.getContext {Op : Type} : ActionSrc Op :=
  fun _ _ => .ok (.getContext)

/-- `Effect4.Program.ActionTerm.getId`. -/
def Action.getId {Op : Type} : ActionSrc Op :=
  fun _ _ => .ok (.getId)

/-- `Effect4.Program.ActionTerm.closeScope`. -/
def Action.closeScope {Op : Type} (scope : TermSrc) (exit : TermSrc) : ActionSrc Op :=
  fun env p => do
    let x0 ← scope env p
    let x1 ← exit env p
    .ok (.closeScope x0 x1)

/-- `Effect4.Program.LayerTerm.succeed`. -/
def Layer.succeed {Op : Type} (key : Effect4.ServiceKey) (value : Effect4.Program.Lit) : LayerSrc Op :=
  fun _ _ => .ok (.succeed key value)

/-- `Effect4.Program.LayerTerm.effect`: `body` is closed. -/
def Layer.effect {Op : Type} (key : Effect4.ServiceKey) (body : Src Op) : LayerSrc Op :=
  fun env p => do
    let x1 ← body env.closed (p ++ [0])
    .ok (.effect key x1)

/-- `Effect4.Program.LayerTerm.effectDiscard`: `body` is closed. -/
def Layer.effectDiscard {Op : Type} (body : Src Op) : LayerSrc Op :=
  fun env p => do
    let x0 ← body env.closed (p ++ [0])
    .ok (.effectDiscard x0)

/-- `Effect4.Program.LayerTerm.provide`. -/
def Layer.provide {Op : Type} (self : LayerSrc Op) (that : LayerSrc Op) : LayerSrc Op :=
  fun env p => do
    let x0 ← self env (p ++ [0])
    let x1 ← that env (p ++ [1])
    .ok (.provide x0 x1)

/-- `Effect4.Program.LayerTerm.provideMerge`. -/
def Layer.provideMerge {Op : Type} (self : LayerSrc Op) (that : LayerSrc Op) : LayerSrc Op :=
  fun env p => do
    let x0 ← self env (p ++ [0])
    let x1 ← that env (p ++ [1])
    .ok (.provideMerge x0 x1)

/-- `Effect4.Program.LayerTerm.merge`. -/
def Layer.merge {Op : Type} (left : LayerSrc Op) (right : LayerSrc Op) : LayerSrc Op :=
  fun env p => do
    let x0 ← left env (p ++ [0])
    let x1 ← right env (p ++ [1])
    .ok (.merge x0 x1)

/-- `Effect4.Program.LayerTerm.fresh`. -/
def Layer.fresh {Op : Type} (inner : LayerSrc Op) : LayerSrc Op :=
  fun env p => do
    let x0 ← inner env (p ++ [0])
    .ok (.fresh x0)

/-- `Effect4.Program.LayerTerm.orDie`. -/
def Layer.orDie {Op : Type} (inner : LayerSrc Op) : LayerSrc Op :=
  fun env p => do
    let x0 ← inner env (p ++ [0])
    .ok (.orDie x0)

/-- `Effect4.Program.LayerTerm.mergeAll`. -/
def Layer.mergeAll {Op : Type} (layers : List (LayerSrc Op)) : LayerSrc Op :=
  fun env p => do
    let x0 ← elabLayers layers env (p ++ [0])
    .ok (.mergeAll x0)

/-- `Effect4.Program.CauseTerm.fail`. -/
def Cause.fail (error : TermSrc) : CauseSrc :=
  fun env p => do
    let x0 ← error env p
    .ok (.fail x0)

/-- `Effect4.Program.CauseTerm.die`. -/
def Cause.die (defect : TermSrc) : CauseSrc :=
  fun env p => do
    let x0 ← defect env p
    .ok (.die x0)

/-- `Effect4.Program.CauseTerm.interrupt`. -/
def Cause.interrupt (interruptor : Option TermSrc) : CauseSrc :=
  fun env p => do
    let x0 ← elabOption interruptor env p
    .ok (.interrupt x0)

/-- `Effect4.Program.CauseTerm.both`. -/
def Cause.both (left : CauseSrc) (right : CauseSrc) : CauseSrc :=
  fun env p => do
    let x0 ← left env p
    let x1 ← right env p
    .ok (.both x0 x1)


/-! ## Receipts -/

#print axioms Effect4.Program.Authoring.succeed
#print axioms Effect4.Program.Authoring.fail
#print axioms Effect4.Program.Authoring.failCause
#print axioms Effect4.Program.Authoring.sync
#print axioms Effect4.Program.Authoring.suspend
#print axioms Effect4.Program.Authoring.perform
#print axioms Effect4.Program.Authoring.bind
#print axioms Effect4.Program.Authoring.catchCause
#print axioms Effect4.Program.Authoring.matchCause
#print axioms Effect4.Program.Authoring.onExit
#print axioms Effect4.Program.Authoring.exit
#print axioms Effect4.Program.Authoring.uninterruptible
#print axioms Effect4.Program.Authoring.interruptible
#print axioms Effect4.Program.Authoring.branch
#print axioms Effect4.Program.Authoring.whileLoop
#print axioms Effect4.Program.Authoring.yieldNow
#print axioms Effect4.Program.Authoring.callback
#print axioms Effect4.Program.Authoring.awaitFiber
#print axioms Effect4.Program.Authoring.withFiber
#print axioms Effect4.Program.Authoring.scope
#print axioms Effect4.Program.Authoring.acquireRelease
#print axioms Effect4.Program.Authoring.provideLayer
#print axioms Effect4.Program.Authoring.service
#print axioms Effect4.Program.Authoring.provideService
#print axioms Effect4.Program.Authoring.catchIf
#print axioms Effect4.Program.Authoring.Action.fork
#print axioms Effect4.Program.Authoring.Action.forkIn
#print axioms Effect4.Program.Authoring.Action.forkScoped
#print axioms Effect4.Program.Authoring.Action.runIn
#print axioms Effect4.Program.Authoring.Action.interrupt
#print axioms Effect4.Program.Authoring.Action.interruptAll
#print axioms Effect4.Program.Authoring.Action.awaitAll
#print axioms Effect4.Program.Authoring.Action.raceAll
#print axioms Effect4.Program.Authoring.Action.getContext
#print axioms Effect4.Program.Authoring.Action.getId
#print axioms Effect4.Program.Authoring.Action.closeScope
#print axioms Effect4.Program.Authoring.Layer.succeed
#print axioms Effect4.Program.Authoring.Layer.effect
#print axioms Effect4.Program.Authoring.Layer.effectDiscard
#print axioms Effect4.Program.Authoring.Layer.provide
#print axioms Effect4.Program.Authoring.Layer.provideMerge
#print axioms Effect4.Program.Authoring.Layer.merge
#print axioms Effect4.Program.Authoring.Layer.fresh
#print axioms Effect4.Program.Authoring.Layer.orDie
#print axioms Effect4.Program.Authoring.Layer.mergeAll
#print axioms Effect4.Program.Authoring.Cause.fail
#print axioms Effect4.Program.Authoring.Cause.die
#print axioms Effect4.Program.Authoring.Cause.interrupt
#print axioms Effect4.Program.Authoring.Cause.both

end Effect4.Program.Authoring

/-! ## Acceptance guards for the generated authoring lifts

Appended verbatim by `--append tools/Effect4Gen/guards/authoring.lean` into
`src/Effect4/Program/Authoring/Lifts.lean`. One constructor of each binding shape, elaborated
by name and compared with the tree written by level; the full battery is
`Test/Program/AuthoringContract.lean`. -/

namespace Effect4.Program.AuthoringGuards

open Effect4.Program Effect4.Program.Authoring

#guard elaborate (bind "r" (succeed (nat 0)) (succeed (var "r")) : Src NativeOp)
  = .ok (.bind (.succeed (.lit (.nat 0))) (.succeed (.var 0)))

#guard elaborate (bind "r" (succeed (nat 0)) (succeed (var "q")) : Src NativeOp)
  = .error ⟨[1], .unbound "q"⟩

#guard elaborate (acquireRelease "a" "x" (succeed (nat 0)) (succeed (app "pair" [var "a", var "x"])) : Src NativeOp)
  = .ok (.acquireRelease (.succeed (.lit (.nat 0)))
          (.succeed (.app "pair" (.cons (.var 0) (.cons (.var 1) .nil)))))

#guard elaborate (provideLayer (Layer.effectDiscard (succeed (var "r"))) false (succeed (nat 1)) : Src NativeOp)
  = .error ⟨[0, 0], .unbound "r"⟩

#guard elaborate (withFiber (Action.raceAll [succeed (nat 1), succeed (nat 2)]) : Src NativeOp)
  = .ok (.withFiber (.raceAll (.cons (.succeed (.lit (.nat 1))) (.cons (.succeed (.lit (.nat 2))) .nil))))

end Effect4.Program.AuthoringGuards

