-- GENERATED by tools/Effect4Gen/Rows.lean; do not edit
-- GENERATED by tools/Effect4Gen/Rows.lean from NativeOp.spelled (Program/Native.lean) and the NativeOp declarations. Do not edit.
-- Regenerate (tools/Effect4Gen/Driver.lean runs this for every group; --verify refuses a diff):
--   lake exe effect4gen-catalogue Rows --group Rows --module --meta-imports Effect4.Program.Authoring.Lifts --imports Effect4.Program.Authoring.Lifts --out src/Effect4/Program/Authoring/Rows.lean --append tools/Effect4Gen/guards/rows.lean
-- Acceptance guards appended verbatim from: tools/Effect4Gen/guards/rows.lean
module

public import Effect4.Program.Authoring.Lifts
meta import Effect4.Program.Authoring.Lifts

@[expose] public section

set_option autoImplicit false

namespace Effect4.Program.Authoring

open Effect4.Program

namespace Ref

/-- `Ref.make` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:173`). -/
def make (request : TermSrc) : Src NativeOp :=
  perform .refMake request

/-- `Ref.get` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:200`). -/
def get (request : TermSrc) : Src NativeOp :=
  perform .refGet request

/-- `Ref.set` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:306-307`). -/
def set (x0 x1 : TermSrc) : Src NativeOp :=
  perform .refSet (app "pair" [x0, x1])

/-- `Ref.getAndSet` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:399-404`). -/
def getAndSet (x0 x1 : TermSrc) : Src NativeOp :=
  perform .refGetAndSet (app "pair" [x0, x1])

/-- `Ref.setAndGet` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:747`). -/
def setAndGet (x0 x1 : TermSrc) : Src NativeOp :=
  perform .refSetAndGet (app "pair" [x0, x1])

/-- `Ref.update` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:1273-1276`).
`f` is the binder term, written under the name `current` of the cell's current value. -/
def update (current : String) (f request : TermSrc) : Src NativeOp :=
  performTerm .refUpdateWith current f request

/-- `Ref.getAndUpdate` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:496-501`).
`f` is the binder term, written under the name `current` of the cell's current value. -/
def getAndUpdate (current : String) (f request : TermSrc) : Src NativeOp :=
  performTerm .refGetAndUpdateWith current f request

/-- `Ref.updateAndGet` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:1368`).
`f` is the binder term, written under the name `current` of the cell's current value. -/
def updateAndGet (current : String) (f request : TermSrc) : Src NativeOp :=
  performTerm .refUpdateAndGetWith current f request

/-- `Ref.updateSome` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:1502-1508`).
`f` is the binder term, written under the name `current` of the cell's current value. -/
def updateSome (current : String) (f request : TermSrc) : Src NativeOp :=
  performTerm .refUpdateSomeWith current f request

/-- `Ref.getAndUpdateSome` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:635-643`).
`f` is the binder term, written under the name `current` of the cell's current value. -/
def getAndUpdateSome (current : String) (f request : TermSrc) : Src NativeOp :=
  performTerm .refGetAndUpdateSomeWith current f request

/-- `Ref.updateSomeAndGet` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:1639-1646`).
`f` is the binder term, written under the name `current` of the cell's current value. -/
def updateSomeAndGet (current : String) (f request : TermSrc) : Src NativeOp :=
  performTerm .refUpdateSomeAndGetWith current f request

/-- `Ref.modify` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:896-901`).
`f` is the binder term, written under the name `current` of the cell's current value. -/
def modify (current : String) (f request : TermSrc) : Src NativeOp :=
  performTerm .refModifyWith current f request

/-- `Ref.modifySome` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:1159-1163`).
`f` is the binder term, written under the name `current` of the cell's current value. -/
def modifySome (current : String) (f request : TermSrc) : Src NativeOp :=
  performTerm .refModifySomeWith current f request

end Ref

namespace Deferred

/-- `Deferred.make` (`vendor/effect-4.0.0-rc.112/src/Deferred.ts:171`). -/
def make (value : Effect4.Program.Ty) (error : Effect4.Program.Ty) : Src NativeOp :=
  perform (.deferredMakeOf value error) unit

/-- `Deferred.isDone` (`vendor/effect-4.0.0-rc.112/src/Deferred.ts:1366`). -/
def isDone (request : TermSrc) : Src NativeOp :=
  perform .deferredIsDone request

/-- `Deferred.poll` (`vendor/effect-4.0.0-rc.112/src/Deferred.ts:1414-1416`). -/
def poll (request : TermSrc) : Src NativeOp :=
  perform .deferredPoll request

/-- `Deferred.succeed` (`vendor/effect-4.0.0-rc.112/src/Deferred.ts:1514`). -/
def succeed (x0 x1 : TermSrc) : Src NativeOp :=
  perform .deferredSucceed (app "pair" [x0, x1])

/-- `Deferred.fail` (`vendor/effect-4.0.0-rc.112/src/Deferred.ts:669`). -/
def fail (x0 x1 : TermSrc) : Src NativeOp :=
  perform .deferredFail (app "pair" [x0, x1])

/-- `Deferred.await` (`vendor/effect-4.0.0-rc.112/src/Deferred.ts:223`). -/
def await (request : TermSrc) : Src NativeOp :=
  perform .deferredAwait request

end Deferred

namespace Scope

/-- `Scope.make` (`vendor/effect-4.0.0-rc.112/src/Scope.ts:240`). -/
def make (strategy : Effect4.FinalizerStrategy) : Src NativeOp :=
  perform (.scopeMake strategy) unit

end Scope

namespace Effect

/-- `Effect.sleep` (`vendor/effect-4.0.0-rc.112/src/internal/effect.ts:6114-6116`). -/
def sleep (request : TermSrc) : Src NativeOp :=
  perform .sleep request

/-- `Effect.currentTimeMillis` (`vendor/effect-4.0.0-rc.112/src/internal/effect.ts:6118`). -/
def currentTimeMillis : Src NativeOp :=
  perform .clockNow unit

end Effect

end Effect4.Program.Authoring

/-! ## Acceptance guards for the generated row wrappers

Appended verbatim by `--append tools/Effect4Gen/guards/rows.lean` into
`src/Effect4/Program/Authoring/Rows.lean`. One row of each request shape, elaborated by name
against the tree written by level. -/

namespace Effect4.Program.AuthoringRowsGuards

open Effect4.Program Effect4.Program.Authoring

#guard elaborate (Ref.make (nat 0)) = .ok (.perform .refMake (.lit (.nat 0)))
#guard elaborate (Ref.set (var "r") (nat 1)) = .error ⟨[], .unbound "r"⟩
#guard elaborate (bind "r" (Ref.make (nat 0)) (Ref.set (var "r") (nat 1)))
  = .ok (.bind (.perform .refMake (.lit (.nat 0)))
          (.perform .refSet (.app "pair" (.cons (.var 0) (.cons (.lit (.nat 1)) .nil)))))
-- A term row elaborates its binder term under the name of the cell's current value: at the
-- root that name is level 0, and under one binder it is level 1, above the outer name.
#guard elaborate (Ref.update "a" (app "succ" [var "a"]) (nat 0))
  = .ok (.perform (.refUpdateWith (.app "succ" (.cons (.var 0) .nil))) (.lit (.nat 0)))
#guard elaborate (bind "r" (Ref.make (nat 0))
    (Ref.modify "a" (app "pair" [var "a", app "add" [var "a", var "r"]]) (var "r")))
  = .ok (.bind (.perform .refMake (.lit (.nat 0)))
          (.perform (.refModifyWith (.app "pair" (.cons (.var 1)
            (.cons (.app "add" (.cons (.var 1) (.cons (.var 0) .nil))) .nil)))) (.var 0)))
-- The current value's name is the term's alone: the request does not see it.
#guard elaborate (Ref.update "a" (var "a") (var "a")) = .error ⟨[], .unbound "a"⟩
-- An async row authors as the reader reads it: a `perform`, the one invocation form.
#guard elaborate (Effect.sleep (nat 5)) = .ok (.perform .sleep (.lit (.nat 5)))
-- `Deferred.make` takes its type arguments: the operation carries them (decisions row 42).
#guard elaborate (Deferred.make .nat .nat) = .ok (.perform (.deferredMakeOf .nat .nat) (.lit .unit))

end Effect4.Program.AuthoringRowsGuards
