-- GENERATED by tools/Effect4Gen/Rows.lean; do not edit
-- GENERATED by tools/Effect4Gen/Rows.lean from NativeOp.all (Program/Native.lean) and the NativeOp declarations. Do not edit.
-- Regenerate (tools/Effect4Gen/Driver.lean runs this for every group; --verify refuses a diff):
--   lake env lean -M 4096 --run tools/Effect4Gen/Rows.lean --group Rows --imports Effect4.Program.Authoring.Lifts --out src/Effect4/Program/Authoring/Rows.lean --append tools/Effect4Gen/guards/rows.lean
-- Acceptance guards appended verbatim from: tools/Effect4Gen/guards/rows.lean
import Effect4.Program.Authoring.Lifts

set_option autoImplicit false

namespace Effect4.Program.Authoring

open Effect4.Program

namespace Ref

/-- `Ref.make` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:173`). -/
def make (request : TermSrc) : Src NativeOp :=
  perform .refMake request

/-- `Ref.get` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:200`). -/
def get (request : TermSrc) : Src NativeOp :=
  perform .refGet request

/-- `Ref.set` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:306-307`). -/
def set (x0 x1 : TermSrc) : Src NativeOp :=
  perform .refSet (app "pair" [x0, x1])

/-- `Ref.getAndSet` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:399-404`). -/
def getAndSet (x0 x1 : TermSrc) : Src NativeOp :=
  perform .refGetAndSet (app "pair" [x0, x1])

/-- `Ref.setAndGet` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:747`). -/
def setAndGet (x0 x1 : TermSrc) : Src NativeOp :=
  perform .refSetAndGet (app "pair" [x0, x1])

/-- `Ref.update` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:1273-1276`). -/
def update (f : Effect4.Machine.FnName) (request : TermSrc) : Src NativeOp :=
  perform (.refUpdate f) request

/-- `Ref.getAndUpdate` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:496-501`). -/
def getAndUpdate (f : Effect4.Machine.FnName) (request : TermSrc) : Src NativeOp :=
  perform (.refGetAndUpdate f) request

/-- `Ref.updateAndGet` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:1368`). -/
def updateAndGet (f : Effect4.Machine.FnName) (request : TermSrc) : Src NativeOp :=
  perform (.refUpdateAndGet f) request

/-- `Ref.updateSome` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:1502-1508`). -/
def updateSome (f : Effect4.Machine.FnName) (request : TermSrc) : Src NativeOp :=
  perform (.refUpdateSome f) request

/-- `Ref.getAndUpdateSome` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:635-643`). -/
def getAndUpdateSome (f : Effect4.Machine.FnName) (request : TermSrc) : Src NativeOp :=
  perform (.refGetAndUpdateSome f) request

/-- `Ref.updateSomeAndGet` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:1639-1646`). -/
def updateSomeAndGet (f : Effect4.Machine.FnName) (request : TermSrc) : Src NativeOp :=
  perform (.refUpdateSomeAndGet f) request

/-- `Ref.modify` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:896-901`). -/
def modify (f : Effect4.Machine.FnName) (request : TermSrc) : Src NativeOp :=
  perform (.refModify f) request

/-- `Ref.modifySome` (`vendor/effect-4.0.0-rc.112/src/Ref.ts:1159-1163`). -/
def modifySome (f : Effect4.Machine.FnName) (request : TermSrc) : Src NativeOp :=
  perform (.refModifySome f) request

end Ref

namespace Deferred

/-- `Deferred.make` (`vendor/effect-4.0.0-rc.112/src/Deferred.ts:171`). -/
def make : Src NativeOp :=
  perform .deferredMake unit

/-- `Deferred.isDone` (`vendor/effect-4.0.0-rc.112/src/Deferred.ts:1382`). -/
def isDone (request : TermSrc) : Src NativeOp :=
  perform .deferredIsDone request

/-- `Deferred.poll` (`vendor/effect-4.0.0-rc.112/src/Deferred.ts:1414-1416`). -/
def poll (request : TermSrc) : Src NativeOp :=
  perform .deferredPoll request

/-- `Deferred.succeed` (`vendor/effect-4.0.0-rc.112/src/Deferred.ts:1514`). -/
def succeed (x0 x1 : TermSrc) : Src NativeOp :=
  perform .deferredSucceed (app "pair" [x0, x1])

/-- `Deferred.fail` (`vendor/effect-4.0.0-rc.112/src/Deferred.ts:669`). -/
def fail (x0 x1 : TermSrc) : Src NativeOp :=
  perform .deferredFail (app "pair" [x0, x1])

/-- `Deferred.await` (`vendor/effect-4.0.0-rc.112/src/Deferred.ts:173-186`). -/
def await (request : TermSrc) : Src NativeOp :=
  perform .deferredAwait request

end Deferred

namespace Scope

/-- `Scope.make` (`vendor/effect-4.0.0-rc.112/src/internal/effect.ts:3914-3922`). -/
def make (strategy : Effect4.FinalizerStrategy) : Src NativeOp :=
  perform (.scopeMake strategy) unit

end Scope

namespace Effect

/-- `Effect.sleep` (`vendor/effect-4.0.0-rc.112/src/internal/effect.ts:6114-6116`). -/
def sleep (request : TermSrc) : Src NativeOp :=
  perform .sleep request

/-- `Effect.currentTimeMillis` (`vendor/effect-4.0.0-rc.112/src/internal/effect.ts:6118`). -/
def currentTimeMillis : Src NativeOp :=
  perform .clockNow unit

end Effect

/-! ## Receipts -/

#print axioms Effect4.Program.Authoring.Ref.make
#print axioms Effect4.Program.Authoring.Ref.get
#print axioms Effect4.Program.Authoring.Ref.set
#print axioms Effect4.Program.Authoring.Ref.getAndSet
#print axioms Effect4.Program.Authoring.Ref.setAndGet
#print axioms Effect4.Program.Authoring.Ref.update
#print axioms Effect4.Program.Authoring.Ref.getAndUpdate
#print axioms Effect4.Program.Authoring.Ref.updateAndGet
#print axioms Effect4.Program.Authoring.Ref.updateSome
#print axioms Effect4.Program.Authoring.Ref.getAndUpdateSome
#print axioms Effect4.Program.Authoring.Ref.updateSomeAndGet
#print axioms Effect4.Program.Authoring.Ref.modify
#print axioms Effect4.Program.Authoring.Ref.modifySome
#print axioms Effect4.Program.Authoring.Deferred.make
#print axioms Effect4.Program.Authoring.Deferred.isDone
#print axioms Effect4.Program.Authoring.Deferred.poll
#print axioms Effect4.Program.Authoring.Deferred.succeed
#print axioms Effect4.Program.Authoring.Deferred.fail
#print axioms Effect4.Program.Authoring.Deferred.await
#print axioms Effect4.Program.Authoring.Scope.make
#print axioms Effect4.Program.Authoring.Effect.sleep
#print axioms Effect4.Program.Authoring.Effect.currentTimeMillis

end Effect4.Program.Authoring

/-! ## Acceptance guards for the generated row wrappers

Appended verbatim by `--append tools/Effect4Gen/guards/rows.lean` into
`src/Effect4/Program/Authoring/Rows.lean`. One row of each request shape, elaborated by name
against the tree written by level. -/

namespace Effect4.Program.AuthoringRowsGuards

open Effect4.Program Effect4.Program.Authoring

#guard elaborate (Ref.make (nat 0)) = .ok (.perform .refMake (.lit (.nat 0)))
#guard elaborate (Ref.set (var "r") (nat 1)) = .error ⟨[], .unbound "r"⟩
#guard elaborate (bind "r" (Ref.make (nat 0)) (Ref.set (var "r") (nat 1)))
  = .ok (.bind (.perform .refMake (.lit (.nat 0)))
          (.perform .refSet (.app "pair" (.cons (.var 0) (.cons (.lit (.nat 1)) .nil)))))
#guard elaborate Deferred.make = .ok (.perform .deferredMake (.lit .unit))
#guard elaborate (Ref.update .incr (nat 0)) = .ok (.perform (.refUpdate .incr) (.lit (.nat 0)))

end Effect4.Program.AuthoringRowsGuards

