(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400085`, seed 400085, 20 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400085 () =
  let v0 = Fibers_fixture.fork 0 in
  let _v1 = Fibers_fixture.cleanups () in
  let _v2 = Fibers_fixture.started () in
  let v3 = Store_fixtures.def_make () in
  let _v4 = Fibers_fixture.await_error v0 in
  let _v5 = Fibers_fixture.await_error v0 in
  let _v6 = Fibers_fixture.await_error v0 in
  let _v7 = Store_fixtures.def_succeed v3 1 in
  let _v8 = Fibers_fixture.cleanups () in
  let _v9 = Store_fixtures.def_poll v3 in
  let _v10 = Fibers_fixture.started () in
  let v11 = Fibers_fixture.fork_detach 0 in
  let _v12 = Fibers_fixture.started () in
  let v13 = Store_fixtures.ref_make 1 in
  ignore (Store_fixtures.ref_set v13 8);
  let v14 = Store_fixtures.scope_make () in
  let _v15 = Extra_fixture.interrupt_all [ v11 ] in
  let _v16 = Store_fixtures.scope_close v14 in
  let _v17 = Store_fixtures.def_await_value v3 in
  let v18 = Fibers_fixture.join v0 in
  v18

let programs : (string * (unit -> value)) list = [ ("p400085", corpus_p400085) ]
