(* `Effect4/Deep/ForkFlow.lean` → `deep_forkflow.ml`: the fiber profile's alphabet -- the twelve
   `FiberOp` rows with their index, the value codings of the profile's requests and answers,
   and the refusal alphabet -- declaration by declaration in the Lean order.

   Seat F2, 2026-09-04. Report: `docs/research/2026-09-04-seat-w1-deep-port.md` §F2.10.

   The carriers below the banner are GENERATED from `OCaml5.Avatar.ForkFlow` in
   `src/OCaml5/Render.lean` (`render-deep.sh forkflow`). `Val` here is
   `Effects.Trace.Val` (`Effects/Trace.lean:41-50`: `str`, `nat`, `bool`, `pair`, `unit`,
   `none`, `some`), which the wire `value` spells one for one -- the one alphabet the trace
   wire describes (`Effect4/Target/TypeScript/Trace.lean`); `BlockId` and `FiberId` are `int`.

   What refuses, and why: §3-§9 of `ForkFlow.lean` -- the run-time refusal over a
   `RegionFlow` (`checkRoot`, `checkFork`, `refusal?`, `:467-548`), the compile
   (`fiberPrim`, `compileFork`, `compileForkAt`, `:575-775`), the interp (`forkTable`,
   `forkParkOf`, `forkActionOf`, `forkWithFiberOf`, `forkInterp`, `forkOracle`, `:800-1023`),
   `WellSourced` and its invariants (`:1033-1240`), the decision partition (`:1261-1305`),
   the fuel bound (`:1321-1342`) and the witnesses (`:1352-1712`) -- are the compile of the
   profile over the Flow IR (`RegionFlow`, `RegionBlock`, `Code`, `Config`, `OpSpec`,
   `FlowAlphabet`), for which the avatar has no carriers: the avatar's programs are OCaml
   control (DIVERGENCE 1), not a flow, so there is nothing to compile from. They refuse by
   name. The value alphabet is the part a host and the avatar share, and it is executable.

   Behavioural properties (packages plan §4.5): (1) `ofIndex ∘ index = id` on every row and
   `ofIndex n = none` for `n ≥ 12` (`ofIndex_index`, `ofIndex_ge`); (2) each coding has its
   inverse: `handleOf (handleValue id) = some id`, `listOf (listValue vs) = some vs`,
   `rootRequestOf (RootRequest.value r) = some r`, `forkRequestOf (ForkRequest.value r) =
   some r` (`handleOf_handleValue`, `listOf_listValue`, `rootRequestOf_value`,
   `forkRequestOf_value`); (3) `exitAsValue` projects a failure to its first `fail` error and
   a cause with only a `die`/`interrupt` to `unit` -- the recorded loss (`:371-380`);
   (4) the three `direct` rows (`join`, `await`, `yieldNow`) are the ones with no
   `WithFiberAction` channel to refuse through (`:196-201`). *)

open Deep_fibers

(* Generated by OCaml5.Ml (`Render.lean`, seat W1). Do not edit; edit the descriptions (`Ml.Deep.ForkFlow`, seat F2).
   One declaration per `Effect4/Deep/ForkFlow.lean` carrier of the profile's alphabet, same order. *)

(* `FiberOp` (`ForkFlow.lean:122`), 12 constructors, prefix `Fo`. Generated by OCaml5.Ml. *)

type fiber_op =
  | Fofork
  | FoforkScoped
  | Fojoin
  | Foawait
  | Fointerrupt
  | FointerruptAll
  | FochildrenSnapshot
  | FoawaitChildren
  | ForaceAll
  | FouninterruptibleIn
  | FointerruptibleIn
  | FoyieldNow

(* `RootRequest` (`ForkFlow.lean:382`), 2 Lean fields, 2 rendered. Generated by OCaml5.Ml. *)

type root_request = { root : int; args : value list }

(* `ForkRequest` (`ForkFlow.lean:401`), 4 Lean fields, 4 rendered. Generated by OCaml5.Ml. *)

type fork_request = {
  root : int;
  args : value list;
  daemon : bool;
  region : int option;
}

(* `ForkRefusal` (`ForkFlow.lean:449`), 6 constructors, prefix `Fr`. Generated by OCaml5.Ml. *)

type fork_refusal =
  | FrrequestMalformed of value
  | FrrootUndeclared of int
  | FrrootUnknown of int
  | FrrootArity of int * int * int
  | FrhandleMalformed of value
  | FrscopedNamesRegion of int

(* ===== END GENERATED ===== *)

(* ==================================================================================
   `Effect4/Deep/ForkFlow.lean`, in the Lean declaration order.
   ================================================================================== *)

(* ------------------------------------------- §1 the fiber profile (`:111-316`) *)

(* `FiberOp.index` (`:153`). *)
let fiber_op_index : fiber_op -> int = function
  | Fofork -> 0 | FoforkScoped -> 1 | Fojoin -> 2 | Foawait -> 3 | Fointerrupt -> 4
  | FointerruptAll -> 5 | FochildrenSnapshot -> 6 | FoawaitChildren -> 7 | ForaceAll -> 8
  | FouninterruptibleIn -> 9 | FointerruptibleIn -> 10 | FoyieldNow -> 11

(* `FiberOp.ofIndex` (`:168`). *)
let fiber_op_of_index : int -> fiber_op option = function
  | 0 -> Some Fofork | 1 -> Some FoforkScoped | 2 -> Some Fojoin | 3 -> Some Foawait
  | 4 -> Some Fointerrupt | 5 -> Some FointerruptAll | 6 -> Some FochildrenSnapshot
  | 7 -> Some FoawaitChildren | 8 -> Some ForaceAll | 9 -> Some FouninterruptibleIn
  | 10 -> Some FointerruptibleIn | 11 -> Some FoyieldNow | _ -> None

(* `FiberOp.count` (`:186`). *)
let fiber_op_count : int = 12

(* `FiberOp.direct` (`:196`). *)
let fiber_op_direct : fiber_op -> bool = function
  | Fojoin | Foawait | FoyieldNow -> true
  | _ -> false

(* `handleTy` (`:206`), `exitTy` (`:214`), `forkParams` (`:219`), `rootParams` (`:225`),
   `forkRequestTy`/`rootRequestTy` (`:231-234`): the TypeScript spellings of the profile. *)
let handle_ty (answer_ty : string) (error_ty : string) : string =
  "Fiber.Fiber<" ^ answer_ty ^ ", " ^ error_ty ^ ">"
let exit_ty (answer_ty : string) (error_ty : string) : string =
  "Result.Result<" ^ answer_ty ^ ", " ^ error_ty ^ ">"
let fork_params : (string * string) list =
  [ ("root", "number"); ("args", "ReadonlyArray<unknown>"); ("daemon", "boolean");
    ("region", "Option.Option<number>") ]
let root_params : (string * string) list = [ ("root", "number"); ("args", "ReadonlyArray<unknown>") ]

(* `requestSpelling` (`ScriptFlow.lean:201-204`): the right-nested product. *)
let rec request_spelling : (string * string) list -> string = function
  | [] -> "void"
  | [ (_, ty) ] -> ty
  | (_, ty) :: rest -> "readonly [" ^ ty ^ ", " ^ request_spelling rest ^ "]"
let fork_request_ty : string = request_spelling fork_params
let root_request_ty : string = request_spelling root_params

(* `fiberProfile` (`:239`), `profileTable` (`:308`), `profileOpOf` (`:314`): `OpSpec` rows of
   the Flow IR; refused. *)
let fiber_profile () : 'a = refuse "Effect4.Deep.ForkFlow.fiberProfile"
let profile_table () : 'a = refuse "Effect4.Deep.ForkFlow.profileTable"

(* ------------------------------------------- §2 the value alphabet (`:318-437`) *)

(* `handleValue` (`:325`), `handleOf` (`:330`): the `Fiber` tag and the child's id. *)
let handle_value (id : int) : value = Vpair (Vstring "Fiber", Vnat id)
let handle_of : value -> int option = function
  | Vpair (Vstring "Fiber", Vnat n) -> Some n
  | _ -> None

(* `natOf` (`:338`). *)
let nat_of : value -> int option = function Vnat n -> Some n | _ -> None

(* `listValue` (`:344`), `listOf` (`:348`): right-nested pairs terminated by `unit`
   (`Effects/Trace.lean:67-68`). *)
let rec list_value : value list -> value = function
  | [] -> Vunit
  | v :: rest -> Vpair (v, list_value rest)
let rec list_of : value -> value list option = function
  | Vunit -> Some []
  | Vpair (v, rest) -> Option.map (fun vs -> v :: vs) (list_of rest)
  | _ -> None

(* `handlesValue` (`:358`), `handlesOf` (`:360`). *)
let handles_value (ids : int list) : value = list_value (List.map handle_value ids)
let handles_of (v : value) : int list option =
  match list_of v with
  | None -> None
  | Some values ->
    List.fold_right
      (fun v acc -> match (handle_of v, acc) with Some id, Some rest -> Some (id :: rest) | _ -> None)
      values (Some [])

(* `exitAsValue` (`:371`): `pair (bool true) value` / `pair (bool false) firstError`; a cause
   with no typed failure reads as `unit` (the recorded loss). *)
let exit_as_value : exitv -> value = function
  | Esuccess v -> Vpair (Vbool true, v)
  | Efailure c -> Vpair (Vbool false, match cause_fail_of c with Some e -> Vnat e | None -> Vunit)

(* `RootRequest.value` (`:387`), `rootRequestOf` (`:390`). *)
let root_request_value (r : root_request) : value = Vpair (Vnat r.root, list_value r.args)
let root_request_of : value -> root_request option = function
  | Vpair (Vnat root, args) -> Option.map (fun args -> { root; args }) (list_of args)
  | _ -> None

(* `ForkRequest.value` (`:409`), `forkRequestOf` (`:417`): the right-nested product of the
   four `forkParams`. *)
let fork_request_value (r : fork_request) : value =
  Vpair
    ( Vnat r.root,
      Vpair
        ( list_value r.args,
          Vpair (Vbool r.daemon, match r.region with None -> Vnone | Some region -> Vsome (Vnat region)) ) )
let fork_request_of : value -> fork_request option = function
  | Vpair (Vnat root, Vpair (args, Vpair (Vbool daemon, region))) -> (
    match (list_of args, region) with
    | Some args, Vnone -> Some { root; args; daemon; region = None }
    | Some args, Vsome (Vnat region) -> Some { root; args; daemon; region = Some region }
    | _ -> None)
  | _ -> None

(* `entrantsOf` (`:431`): one entrant of a `raceAll`, a declared root and its arguments. *)
let entrants_of (v : value) : (int * value list) list option =
  match list_of v with
  | None -> None
  | Some values ->
    List.fold_right
      (fun v acc ->
        match (v, acc) with
        | Vpair (Vnat root, args), Some rest ->
          Option.map (fun args -> (root, args) :: rest) (list_of args)
        | _ -> None)
      values (Some [])

(* ------------------------------------------- §3-§9: over the Flow IR, refused *)

let check_root () : 'a = refuse "Effect4.Deep.ForkFlow.checkRoot"
let check_fork () : 'a = refuse "Effect4.Deep.ForkFlow.checkFork"
let refusal () : 'a = refuse "Effect4.Deep.ForkFlow.refusal?"
let compile_refusal () : 'a = refuse "Effect4.Deep.ForkFlow.compileRefusal?"
let fiber_prim () : 'a = refuse "Effect4.Deep.ForkFlow.fiberPrim"
let compile_fork () : 'a = refuse "Effect4.Deep.ForkFlow.compileFork"
let compile_fork_at () : 'a = refuse "Effect4.Deep.ForkFlow.compileForkAt"
let fork_table () : 'a = refuse "Effect4.Deep.ForkFlow.forkTable"
let fork_park_of () : 'a = refuse "Effect4.Deep.ForkFlow.forkParkOf"
let fork_action_of () : 'a = refuse "Effect4.Deep.ForkFlow.forkActionOf"
let fork_with_fiber_of () : 'a = refuse "Effect4.Deep.ForkFlow.forkWithFiberOf"
let fork_interp () : 'a = refuse "Effect4.Deep.ForkFlow.forkInterp"
let fork_answer_of () : 'a = refuse "Effect4.Deep.ForkFlow.forkAnswerOf"
let fork_oracle () : 'a = refuse "Effect4.Deep.ForkFlow.forkOracle"
let well_sourced () : 'a = refuse "Effect4.Deep.ForkFlow.WellSourced"
let runner_fuel () : 'a = refuse "Effect4.Deep.ForkFlow.runnerFuel"
let run_witness () : 'a = refuse "Effect4.Deep.ForkFlow.runWitness"
