(* `Effect4/Deep/Stores.lean` → `deep_stores.ml`: the concrete stores and the `RunInterp`
   over them, declaration by declaration, in the Lean order.

   Seat W1, 2026-09-04. Report: `docs/research/2026-09-04-seat-w1-deep-port.md`.

   The carriers below the banner are GENERATED from `OCaml5.Ml.Deep.Stores` in
   `src/OCaml5/Render.lean` — same field order, same constructor order, same arity —
   and are not to be edited here. The functions are hand-ported arm for arm, each with the
   `Stores.lean` line it is the port of. Anything not ported calls `Deep_fibers.refuse` with
   the Lean declaration's name.

   Three substitutions run through the whole file and each is a row of the report's table:

   * `Val` (`Stores.lean:141`) is the avatar's wire alphabet `value` (`deep_fibers.ml:64`).
     The two are different alphabets: `Val.fiber`/`.cell`/`.promise`/`.scopeHandle` are one
     `Vhandle` under the wire's first-seen handle counter (`handle_index`), and
     `Val.exitNil`/`.exitCons` are one `Vlist`. The map is in the report.
   * `Prim ν σ β ε δ ι α` is `program = unit -> value`: DIVERGENCE 1, a program is OCaml
     control and not a tree. Every `Stores.lean` function whose result is a `Prim` therefore
     builds a thunk that performs the avatar's own effects, or refuses.
   * `RunMachine.update`/`modify` are the identity over `mutable` fields (DIVERGENCE 3), so
     `DeferredStore.setCell` and `ScopeStore.setEntry` are the identity here: a cell and an
     entry are records the store already holds. Both are still declared, so the diff against
     the Lean file has a line to land on.

   The Deferred slot (`DeferredCell.completion`, `Stores.lean:678-685`) holds what Lean holds
   since the drift re-diff of 2026-09-04: an `Option Program`, here `program option` -- the
   closure `completion_prim` builds from the `Completion` a `SyncOp.deferredCompleteWith`
   names (`completionPrim`, `Stores.lean:1083`), or `prim_of_exit` for `deferredInterruptWith`
   (`Prim.ofExit`, `:1223`). A due resume carries that program (`Aprogram`, the avatar's
   `Prim` in answer position), as Lean's `due` carries the effect. The one thing the avatar
   cannot do with the program is what Lean does with it -- make it the waiter's *current*
   primitive -- because the fixture's `awaitValue`/`awaitError` rows need the exit on the arm's
   stack; so the awaiting arm runs the stored program for its exit there (`exit_of_run`),
   which is exact for `Prim.ofExit` and refuses for `Completion.ofRefGet` (report row W1-2).

   DB-07 (`Stores.lean:33-40`) is unchanged by the port: every operation below writes the
   store forward and no arm reads a snapshot taken before a step. *)

open Deep_fibers

(* `Prim ν σ β ε δ ι α` (DIVERGENCE 1). *)
type program = unit -> value

(* `Supervision.MaskMode` and `Supervision.ForkOptions` are `deep_fibers.ml`'s now
   (`mask_mode`, `fork_options`): `spawn` reads all three options (report row W1-5,
   closed by seat F1). *)
(* Generated by OCaml5.Ml (`Render.lean`, seat W1). Do not edit; edit the descriptions.
   One declaration per `Effect4/Deep/Stores.lean` carrier, same field and constructor order. *)

(* `RefKey` (`Stores.lean:56`), 1 Lean fields, 1 rendered. Generated by OCaml5.Ml. *)

type ref_key = { index : int }

(* `DeferredKey` (`Stores.lean:62`), 1 Lean fields, 1 rendered. Generated by OCaml5.Ml. *)

type deferred_key = { index : int }

(* `Err` (`Stores.lean:73`), 2 constructors, prefix `E`. Generated by OCaml5.Ml. *)

type err = Eboom | Etag of int

(* `Defect` (`Stores.lean:81`), 5 constructors, prefix `X`. Generated by OCaml5.Ml. *)

type defect =
  | XnotImplemented
  | XasyncFiber
  | XbadName
  | XmissingService
  | Xuser of int

(* `FnName` (`Stores.lean:94`), 5 constructors, prefix `Fn`. Generated by OCaml5.Ml. *)

type fn_name =
  | Fnincr
  | Fndouble
  | FnzeroWhenPositive
  | FnnoChange
  | FntakeAndBump

(* `FinName` (`Stores.lean:110`), 6 constructors, prefix `Fin`. Generated by OCaml5.Ml. *)

type fin_name =
  | FininterruptFiber of int * bool
  | FincloseChildScope of int
  | FindetachFromParent of int * int
  | Finrelease of int * bool
  | FinawaitNewChildren of int list
  | FinparkThen of int

(* The tuple aliases the descriptions name, because `LTy` has no product head. `answer` is `deep_fibers.ml:131`. *)

type scope_entry_pair = int * fin_name

type waiter_pair = int * int

(* `FiberId × Nat × Prim`; the `Prim` is the avatar's `answer` (DIVERGENCE 1). *)

type due_pair = int * int * answer

(* `Effect4/Runtime/Scope.lean`: the two carriers `ScopeStore` is made of. *)

(* `FinalizerStrategy` (`Scope.lean:39`), 2 constructors, prefix `Fs`. Generated by OCaml5.Ml. *)

type finalizer_strategy = Fssequential | Fsparallel

(* `ScopeState` (`Scope.lean:71`), 5 constructors, prefix `Ss`. Generated by OCaml5.Ml. *)

type scope_state =
  | Ssempty
  | SsopenEmpty
  | SsopenInline of int * fin_name
  | SsopenMap of scope_entry_pair list
  | Ssclosed of exitv

(* `Scope` (`Scope.lean:86`), 2 Lean fields, 2 rendered. Generated by OCaml5.Ml. *)

type scope = { strategy : finalizer_strategy; mutable state : scope_state }

(* `Ctx` (`Stores.lean:130`), 3 Lean fields, 3 rendered. Generated by OCaml5.Ml. *)

type ctx = { ambient_scope : int option; max_ops_before_yield : int; prevent_yield : bool }

(* `Completion` (`Stores.lean:184`), 2 constructors, prefix `Co`. Generated by OCaml5.Ml. *)

type completion = CoofExit of exitv | CoofRefGet of ref_key

(* `SyncOp` (`Stores.lean:193`), 23 constructors, prefix `S`. Generated by OCaml5.Ml. *)

type sync_op =
  | SrefMake of value
  | SrefGet of ref_key
  | SrefSet of ref_key * value
  | SrefGetAndSet of ref_key * value
  | SrefSetAndGet of ref_key * value
  | SrefUpdate of ref_key * fn_name
  | SrefGetAndUpdate of ref_key * fn_name
  | SrefUpdateAndGet of ref_key * fn_name
  | SrefUpdateSome of ref_key * fn_name
  | SrefGetAndUpdateSome of ref_key * fn_name
  | SrefUpdateSomeAndGet of ref_key * fn_name
  | SrefModify of ref_key * fn_name
  | SrefModifySome of ref_key * fn_name
  | SdeferredMake
  | SdeferredIsDone of deferred_key
  | SdeferredPoll of deferred_key
  | SdeferredCompleteWith of deferred_key * completion
  | SdeferredInterruptWith of deferred_key * int
  | SdeferredAwaitCleanup of deferred_key * int * int
  | SscopeMake of finalizer_strategy
  | SscopeAdd of int * int * fin_name
  | SscopeRemove of int * int
  | SscopeIsClosed of int

(* `RaceName` (`Stores.lean:248`), 6 constructors, prefix `Rn`. Generated by OCaml5.Ml. *)

type race_name =
  | Rnempty
  | RnsuccessThenSecond
  | RnfailThenSuccess
  | RnfailThenFail
  | RnparkOnly
  | RnparkThenSuccess

(* `ProgName`, `Name`, `ActionName` and `Thunk` are one mutually recursive group in OCaml, which Lean does not need because its four are separate inductives over already-declared types. Order inside the group is the Lean order. *)

(* `ProgName` (`Stores.lean:265`), 24 constructors, prefix `P`. Generated by OCaml5.Ml. *)

type prog_name =
  | Pvalue of value
  | PfailCause of cause
  | PsyncOp of sync_op
  | PyieldNow of int
  | Ppark of int
  | PawaitDeferred of deferred_key
  | PintoDeferred of prog_name * deferred_key
  | PintoBody of prog_name * deferred_key
  | PmaskedPark of int
  | PawaitFibers of int list
  | PfinalizerOf of fin_name * exitv
  | PinterruptDeferred of deferred_key
  | PonExitOf of prog_name * fin_name * bool
  | PseqOf of prog_name * prog_name
  | PforkThen of prog_name * fork_options * observer_mode
  | PforkOnly of prog_name * fork_options
  | PforkInScope of prog_name * fork_options * int * int
  | PrunInScope of int * int * int
  | PforkScopedOf of prog_name * fork_options * int
  | PraceOf of race_name
  | PcloseScopeOf of int * exitv
  | PawaitAllNew of prog_name
  | PinterruptFibers of int list
  | PjoinFiber of int * observer_mode

(* `Name` (`Stores.lean:321`), 21 constructors, prefix `N`. Generated by OCaml5.Ml. *)

type name =
  | Nrestore of exitv
  | Nmerge of exitv
  | Nseq of prog_name
  | NjoinOn of observer_mode
  | NinterruptWith of deferred_key
  | NdoneInto of deferred_key
  | Nconstant of value
  | NexitOfValue
  | NsnapshotThen of prog_name
  | NregisterAwait of deferred_key
  | NcancelAwait of deferred_key
  | NexternalRegister of int
  | NabortController
  | NcancelPark
  | NcancelRace of int
  | NwithWaiter of name * int * int
  | NreFail of cause
  | NfinalizerName of fin_name
  | NcloseSeq of fin_name list * exitv * reason list
  | NclosePar of fin_name list * exitv * int list * bool
  | NmergeAwaitedExits

(* `ActionName` (`Stores.lean:377`), 19 constructors, prefix `A`. Generated by OCaml5.Ml. *)

type action_name =
  | Afork of prog_name * fork_options
  | AforkIn of prog_name * fork_options * int * int
  | AforkScoped of prog_name * fork_options * int
  | ArunIn of int * int * int
  | Ainterrupt of int
  | AinterruptScoped of int
  | AinterruptAll of int list * int option
  | AawaitAll of int list
  | AsnapshotChildren
  | AawaitNewChildren of int list
  | AraceAll of race_name
  | AsetContext of ctx
  | AgetContext
  | AgetId
  | AcloseScope of int * exitv
  | AsetInterruptible of prog_name * bool
  | Arefuse of cause
  | AdropObservers of int
  | AcancelRace of int

(* `Thunk` (`Stores.lean:403`), 4 constructors, prefix `T`. Generated by OCaml5.Ml. *)

type thunk =
  | Tpark of park_kind
  | Tact of action_name
  | Top of sync_op
  | Tbody of prog_name

(* The three stores and the `St` over them. *)

(* `DeferredCell` (`Stores.lean:680`), 2 Lean fields, 2 rendered. Generated by OCaml5.Ml. *)

type deferred_cell = { mutable completion : program option; mutable waiters : waiter_pair list }

(* `DeferredStore` (`Stores.lean:663`), 2 Lean fields, 2 rendered. Generated by OCaml5.Ml. *)

type deferred_store = { mutable cells : deferred_cell list; mutable due : due_pair list }

(* `ScopeEntry` (`Stores.lean:859`), 2 Lean fields, 2 rendered. Generated by OCaml5.Ml. *)

type scope_entry = { key : int; mutable scope : scope }

(* `ScopeStore` (`Stores.lean:867`), 1 Lean fields, 1 rendered. Generated by OCaml5.Ml. *)

type scope_store = { mutable entries : scope_entry list }

(* `Stores` (`Stores.lean:1002`), 4 Lean fields, 4 rendered. Generated by OCaml5.Ml. *)

type stores = {
  mutable refs : value list;
  deferreds : deferred_store;
  scopes : scope_store;
  mutable next_name : int;
}

(* ===== END GENERATED =====================================================
   Everything below is hand-ported: one OCaml declaration per Lean declaration, in the Lean
   order, each citing the line it is the port of. *)

(* ==================================================================================
   `Effect4/Runtime/Scope.lean`: the state machine `ScopeStore` is keyed over.
   `Stores.lean:850` reuses it unchanged; there is no `deep_runtime_scope.ml` in this pass,
   so the operations the store calls are ported here under their own Lean sites.
   ================================================================================== *)

(* `ScopeState.entries` (`Scope.lean:98`). *)
let scope_state_entries : scope_state -> scope_entry_pair list = function
  | Ssempty -> []
  | SsopenEmpty -> []
  | SsopenInline (key, finalizer) -> [ (key, finalizer) ]
  | SsopenMap table -> table
  | Ssclosed _ -> []

(* `ScopeState.isOpen` (`Scope.lean:106`). *)
let scope_state_is_open : scope_state -> bool = function
  | Ssempty -> false
  | SsopenEmpty -> true
  | SsopenInline (_, _) -> true
  | SsopenMap _ -> true
  | Ssclosed _ -> false

(* `ScopeState.isClosed` (`Scope.lean:114`). *)
let scope_state_is_closed : scope_state -> bool = function
  | Ssclosed _ -> true
  | Ssempty -> false
  | SsopenEmpty -> false
  | SsopenInline (_, _) -> false
  | SsopenMap _ -> false

(* `ScopeState.closingExit?` (`Scope.lean:122`). *)
let scope_state_closing_exit : scope_state -> exitv option = function
  | Ssclosed exit_ -> Some exit_
  | Ssempty -> None
  | SsopenEmpty -> None
  | SsopenInline (_, _) -> None
  | SsopenMap _ -> None

(* JavaScript `Map.prototype.set` (`Scope.lean:326`): overwrite in place, else append. *)
let table_insert (table : scope_entry_pair list) (key : int) (finalizer : fin_name) :
    scope_entry_pair list =
  if List.exists (fun (k, _) -> k = key) table then
    List.map (fun (k, f) -> if k = key then (key, finalizer) else (k, f)) table
  else table @ [ (key, finalizer) ]

(* JavaScript `Map.prototype.delete` (`Scope.lean:334`). *)
let table_remove (table : scope_entry_pair list) (key : int) : scope_entry_pair list =
  List.filter (fun (k, _) -> k <> key) table

(* `addState` (`Scope.lean:470`). *)
let add_state (state : scope_state) (key : int) (finalizer : fin_name) : scope_state =
  match state with
  | Ssempty -> SsopenInline (key, finalizer)
  | SsopenEmpty -> SsopenInline (key, finalizer)
  | SsopenInline (existing_key, existing) ->
    SsopenMap (table_insert [ (existing_key, existing) ] key finalizer)
  | SsopenMap table -> SsopenMap (table_insert table key finalizer)
  | Ssclosed exit_ -> Ssclosed exit_

(* `removeState` (`Scope.lean:661`). *)
let remove_state (state : scope_state) (key : int) : scope_state =
  match state with
  | SsopenInline (existing_key, existing) ->
    if existing_key = key then SsopenEmpty else SsopenInline (existing_key, existing)
  | SsopenMap table -> SsopenMap (table_remove table key)
  | Ssempty -> Ssempty
  | SsopenEmpty -> SsopenEmpty
  | Ssclosed exit_ -> Ssclosed exit_

(* `Scope.make` (`Scope.lean:241`). *)
let scope_make (strategy : finalizer_strategy) : scope = { strategy; state = Ssempty }

(* `Scope.finalizers` (`Scope.lean:250`). *)
let scope_finalizers (self : scope) : scope_entry_pair list = scope_state_entries self.state

(* `Scope.isClosed` (`Scope.lean:262`). *)
let scope_is_closed (self : scope) : bool = scope_state_is_closed self.state

(* `Scope.closingExit?` (`Scope.lean:265`). *)
let scope_closing_exit (self : scope) : exitv option = scope_state_closing_exit self.state

(* `Scope.addUnsafe` (`Scope.lean:481`). The Lean function answers a new `Scope`; `state` is
   `mutable` here, so the caller already holds it (DIVERGENCE 3). *)
let scope_add_unsafe (self : scope) (key : int) (finalizer : fin_name) : unit =
  self.state <- add_state self.state key finalizer

(* `Scope.addExit` (`Scope.lean:613`): register while open, run now when closed. *)
let scope_add_exit (run : fin_name -> exitv -> exitv) (self : scope) (key : int)
    (finalizer : fin_name) : exitv =
  match scope_closing_exit self with
  | Some exit_ -> run finalizer exit_
  | None ->
    scope_add_unsafe self key finalizer;
    Esuccess Vunit (* `Exit.void` *)

(* `Scope.removeUnsafe` (`Scope.lean:672`). *)
let scope_remove_unsafe (self : scope) (key : int) : unit =
  self.state <- remove_state self.state key

(* `Scope.closeState` (`Scope.lean:779`): state first, so the written state cannot depend on
   what any finalizer does. *)
let scope_close_state (self : scope) (exit_ : exitv) : unit =
  if scope_is_closed self then () else self.state <- Ssclosed exit_

(* `Scope.closeOrder` (`Scope.lean:785`): the materialised registration list, backwards. *)
let scope_close_order (self : scope) : fin_name list =
  List.rev (List.map snd (scope_finalizers self))

(* `Scope.closeExits` (`Scope.lean:790`). *)
let scope_close_exits (run : fin_name -> exitv -> exitv) (self : scope) (exit_ : exitv) :
    exitv list =
  List.map (fun finalizer -> run finalizer exit_) (scope_close_order self)

(* `Scope.fork` (`Scope.lean:1036`): one shared key links a parent finalizer closing the
   child to a child finalizer removing itself from the parent. The parent is mutated and the
   child is answered. *)
let scope_fork (parent : scope) (strategy : finalizer_strategy) (key : int)
    (close_child : fin_name) (detach_from_parent : fin_name) : scope =
  match scope_closing_exit parent with
  | Some exit_ -> { strategy; state = Ssclosed exit_ }
  | None ->
    scope_add_unsafe parent key close_child;
    let child = scope_make strategy in
    scope_add_unsafe child key detach_from_parent;
    child

(* ==================================================================================
   `Effect4/Deep/Stores.lean`, in the Lean declaration order.
   ================================================================================== *)

(* `Ann := Unit` (`Stores.lean:89`): `ReasonAnnotations Ann` is the avatar's `string list`
   of keys, so `Ann` itself has no OCaml declaration. *)

(* ------------------------------------------------------------- the Ref heap (`Ref.ts`) *)

(* `refPeek` (`Stores.lean:424`): `self.ref.current`; a dangling key is a frontier. *)
let ref_peek (heap : value list) (cell : ref_key) : value option =
  List.nth_opt heap cell.index

(* `refPoke` (`Stores.lean:427`): `self.ref.current = value`, i.e. `List.set`. *)
let ref_poke (heap : value list) (cell : ref_key) (value : value) : value list =
  List.mapi (fun i x -> if i = cell.index then value else x) heap

(* `FnName.total` (`Stores.lean:431`). *)
let fn_name_total (f : fn_name) (v : value) : value =
  match (f, v) with
  | Fnincr, Vnat n -> Vnat (n + 1)
  | Fndouble, Vnat n -> Vnat (n * 2)
  | FntakeAndBump, Vnat n -> Vnat (n + 1)
  | _, value -> value

(* `FnName.partialUpdate` (`Stores.lean:438`). *)
let fn_name_partial_update (f : fn_name) (v : value) : value option =
  match (f, v) with
  | FnnoChange, _ -> None
  | FnzeroWhenPositive, Vnat n when n > 0 -> Some (Vnat 0)
  | FnzeroWhenPositive, _ -> None
  | f, value -> Some (fn_name_total f value)

(* `FnName.modify` (`Stores.lean:445`). *)
let fn_name_modify (f : fn_name) (v : value) : value * value =
  match (f, v) with
  | FntakeAndBump, Vnat n -> (Vnat n, Vnat (n + 1))
  | f, value -> (value, fn_name_total f value)

(* `FnName.modifySome` (`Stores.lean:450`). *)
let fn_name_modify_some (f : fn_name) (v : value) : value * value option =
  match (f, v) with
  | FnnoChange, value -> (value, None)
  | f, value -> (fst (fn_name_modify f value), Some (snd (fn_name_modify f value)))

(* `refStep` (`Stores.lean:457`), thirteen arms and the fall-through. `None` is a frontier: a
   key no allocation of this heap minted. Every arm is one `Effect.sync` thunk, so the read
   and the write of a read-modify-write happen with no intervening runtime step. *)
let ref_step (op : sync_op) (heap : value list) : (value * value list) option =
  let map f = Option.map f in
  match op with
  | SrefMake initial -> Some (Vhandle (List.length heap), heap @ [ initial ])
  | SrefGet cell -> map (fun a -> (a, heap)) (ref_peek heap cell)
  | SrefSet (cell, value) ->
    map (fun _ -> (Vhandle cell.index, ref_poke heap cell value)) (ref_peek heap cell)
  | SrefGetAndSet (cell, value) ->
    map (fun a -> (a, ref_poke heap cell value)) (ref_peek heap cell)
  | SrefSetAndGet (cell, value) ->
    map (fun _ -> (value, ref_poke heap cell value)) (ref_peek heap cell)
  | SrefUpdate (cell, f) ->
    map (fun a -> (Vunit, ref_poke heap cell (fn_name_total f a))) (ref_peek heap cell)
  | SrefGetAndUpdate (cell, f) ->
    map (fun a -> (a, ref_poke heap cell (fn_name_total f a))) (ref_peek heap cell)
  | SrefUpdateAndGet (cell, f) ->
    map (fun a -> (fn_name_total f a, ref_poke heap cell (fn_name_total f a)))
      (ref_peek heap cell)
  | SrefUpdateSome (cell, pf) ->
    map
      (fun a ->
        ( Vunit,
          match fn_name_partial_update pf a with
          | Some a' -> ref_poke heap cell a'
          | None -> heap ))
      (ref_peek heap cell)
  | SrefGetAndUpdateSome (cell, pf) ->
    map
      (fun a ->
        ( a,
          match fn_name_partial_update pf a with
          | Some a' -> ref_poke heap cell a'
          | None -> heap ))
      (ref_peek heap cell)
  | SrefUpdateSomeAndGet (cell, pf) ->
    Option.bind (ref_peek heap cell) (fun a ->
        match fn_name_partial_update pf a with
        | Some a' ->
          map (fun fresh -> (fresh, ref_poke heap cell a'))
            (ref_peek (ref_poke heap cell a') cell)
        | None -> Some (a, heap))
  | SrefModify (cell, f) ->
    map (fun a -> (fst (fn_name_modify f a), ref_poke heap cell (snd (fn_name_modify f a))))
      (ref_peek heap cell)
  | SrefModifySome (cell, pf) ->
    map
      (fun a ->
        ( fst (fn_name_modify_some pf a),
          ref_poke heap cell (Option.value (snd (fn_name_modify_some pf a)) ~default:a) ))
      (ref_peek heap cell)
  | _ -> None

(* ---------------------------------------------------- the Deferred store (`Deferred.ts`) *)

(* `DeferredStore.make` (`Stores.lean:673`): both fields undefined. *)
let deferred_store_make (self : deferred_store) : deferred_key =
  let key = { index = List.length self.cells } in
  self.cells <- self.cells @ [ { completion = None; waiters = [] } ];
  key

(* `DeferredStore.cellAt` (`Stores.lean:677`); `None` is a frontier. *)
let deferred_store_cell_at (self : deferred_store) (cell : deferred_key) :
    deferred_cell option =
  List.nth_opt self.cells cell.index

(* `DeferredStore.setCell` (`Stores.lean:681`). The identity here: a cell is a record with
   `mutable` fields, so replacing it is writing it (DIVERGENCE 3). Declared so that the
   diff against the Lean file has a line to land on. *)
let deferred_store_set_cell (_self : deferred_store) (_cell : deferred_key)
    (_value : deferred_cell) : unit =
  ()

(* `DeferredStore.isDone` (`Stores.lean:711-713`): done-ness is exactly the presence of a
   completion. (`Option.is_some`, not `<> None`: the slot holds a closure, which OCaml's
   structural equality must not be asked to compare.) *)
let deferred_store_is_done (self : deferred_store) (cell : deferred_key) : bool option =
  Option.map (fun (c : deferred_cell) -> Option.is_some c.completion)
    (deferred_store_cell_at self cell)

(* `DeferredStore.poll` (`Stores.lean:715-717`): a non-blocking sync read of the slot, which
   is Lean's `Option Program` -- the stored primitive, never run by the store. *)
let deferred_store_poll (self : deferred_store) (cell : deferred_key) :
    program option option =
  Option.map (fun (c : deferred_cell) -> c.completion) (deferred_store_cell_at self cell)

(* `DeferredStore.register` (`Stores.lean:719-728`), the store half of `registerAsync`:
   resume at once with the stored effect when done, otherwise append this waiter in
   registration order and park. *)
let deferred_store_register (self : deferred_store) (cell : deferred_key) (waiter : int)
    (token : int) : program option =
  match deferred_store_cell_at self cell with
  | None -> None
  | Some c -> (
    match c.completion with
    | Some effect -> Some effect
    | None ->
      c.waiters <- c.waiters @ [ (waiter, token) ];
      deferred_store_set_cell self cell c;
      None)

(* `DeferredStore.cancel` (`Stores.lean:705`): splice this waiter out, order-preserving; a
   no-op once completion has cleared the array. *)
let deferred_store_cancel (self : deferred_store) (cell : deferred_key) (waiter : int)
    (token : int) : unit =
  match deferred_store_cell_at self cell with
  | None -> ()
  | Some c ->
    c.waiters <- List.filter (fun (w, t) -> not (w = waiter && t = token)) c.waiters;
    deferred_store_set_cell self cell c

(* `DeferredStore.complete` (`Stores.lean:739-751`): a completion attempt answers `false` and
   changes nothing when an effect is already stored; otherwise the effect is stored, the
   waiter list is *cleared*, and every waiter is owed a resume with that effect in
   registration order. The `answer` a due resume carries (`due_pair`'s third component, the
   avatar's `Prim`, DIVERGENCE 1) is `Aprogram effect`, the stored program itself, as Lean's
   `(w.1, w.2, effect)` (`:751`). *)
let deferred_store_complete (self : deferred_store) (cell : deferred_key)
    (effect : program) : bool =
  match deferred_store_cell_at self cell with
  | None -> false
  | Some c -> (
    match c.completion with
    | Some _ -> false
    | None ->
      let waiters = c.waiters in
      c.completion <- Some effect;
      c.waiters <- [];
      deferred_store_set_cell self cell c;
      self.due <- self.due @ List.map (fun (w, t) -> (w, t, Aprogram effect)) waiters;
      true)

(* `DeferredStore.drainDue` (`Stores.lean:727`): the resumes the store owes now, in
   registration order. *)
let deferred_store_drain_due (self : deferred_store) : due_pair list =
  let due = self.due in
  self.due <- [];
  due

(* ---------------------------------------------------------------- the Scope store *)

(* `finExit` (`Stores.lean:854`): the pure finalizer meaning `Effect4.Scope.close` takes.
   Only `release _ true` fails. *)
let fin_exit (fin : fin_name) (_exit : exitv) : exitv =
  match fin with
  | Finrelease (label, true) -> Efailure (cause_fail label)
  | _ -> Esuccess Vunit

(* `ScopeStore.entryAt` (`Stores.lean:875`); `None` is a frontier. *)
let scope_store_entry_at (self : scope_store) (key : int) : scope_entry option =
  List.find_opt (fun (e : scope_entry) -> e.key = key) self.entries

(* `ScopeStore.setEntry` (`Stores.lean:879`). The identity here, as `setCell` is. *)
let scope_store_set_entry (_self : scope_store) (_entry : scope_entry) : unit = ()

(* `ScopeStore.make` (`Stores.lean:883`): a new scope starts `Empty`. *)
let scope_store_make (self : scope_store) (key : int) (strategy : finalizer_strategy) : unit =
  self.entries <- self.entries @ [ { key; scope = scope_make strategy } ]

(* `ScopeStore.addFinalizer` (`Stores.lean:888`): register while open, run now when closed. *)
let scope_store_add_finalizer (self : scope_store) (key : int) (finalizer_key : int)
    (finalizer : fin_name) : exitv =
  match scope_store_entry_at self key with
  | None -> Esuccess Vunit
  | Some entry ->
    let answer = scope_add_exit fin_exit entry.scope finalizer_key finalizer in
    scope_store_set_entry self entry;
    answer

(* `ScopeStore.removeFinalizer` (`Stores.lean:897`). *)
let scope_store_remove_finalizer (self : scope_store) (key : int) (finalizer_key : int) : unit =
  match scope_store_entry_at self key with
  | None -> ()
  | Some entry ->
    scope_remove_unsafe entry.scope finalizer_key;
    scope_store_set_entry self entry

(* `ScopeStore.forkChild` (`Stores.lean:905`). *)
let scope_store_fork_child (self : scope_store) (parent_key : int) (child_key : int)
    (shared_key : int) (strategy : finalizer_strategy) : unit =
  match scope_store_entry_at self parent_key with
  | None -> ()
  | Some parent ->
    let child_scope =
      scope_fork parent.scope strategy shared_key
        (FincloseChildScope child_key)
        (FindetachFromParent (parent_key, shared_key))
    in
    scope_store_set_entry self parent;
    self.entries <- self.entries @ [ { key = child_key; scope = child_scope } ]

(* `ScopeStore.status` (`Stores.lean:919`): `None` unknown, `Some None` open,
   `Some (Some exit)` closed. *)
let scope_store_status (self : scope_store) (key : int) : exitv option option =
  Option.map (fun (e : scope_entry) -> scope_closing_exit e.scope)
    (scope_store_entry_at self key)

(* `ScopeStore.closeOrderOf` (`Stores.lean:924`). *)
let scope_store_close_order_of (self : scope_store) (key : int) : fin_name list =
  match scope_store_entry_at self key with
  | None -> []
  | Some entry -> scope_close_order entry.scope

(* `ScopeStore.closeState` (`Stores.lean:931`): state first. *)
let scope_store_close_state (self : scope_store) (key : int) (exit_ : exitv) : unit =
  match scope_store_entry_at self key with
  | None -> ()
  | Some entry ->
    scope_close_state entry.scope exit_;
    scope_store_set_entry self entry

(* ================================================================================== *)
(* `σ`, extended. `Deep.Fibers` declares `store_request` as an extensible variant because
   the machine is parametric in `σ` and never inspects it (`deep_fibers.ml:446`); these are
   the requests `Deep.Stores` answers.

   The first three are the Lean alphabet itself: `Prim.sync (Thunk.op op)`,
   `Prim.async (Name.registerAwait cell) …` and `ProgName.interruptDeferred`. The rest are
   the *harness fixture's* alphabet (`harness/trace/{ref,deferred,scope}-fixture.ts`,
   generated by `harness/trace/Generate.lean`), which is a different profile of the same
   stores: `Ref.update(r, n => n + a)` is a JavaScript closure over `a`, and `FnName`
   (`Stores.lean:94`) has five named functions and no parameterised one, so the fixture's
   rows cannot be spelled as `SyncOp` arms. They run on the same `RefHeap`/`DeferredStore`/
   `ScopeStore` through the same `refPeek`/`refPoke`/`DeferredStore.*`/`ScopeStore.*`
   primitives `refStep` and `syncOpStep` are built from. Report row W1-3. *)
type Deep_fibers.store_request +=
  | Rsync of sync_op                                (* Prim.sync (Thunk.op _) *)
  | Rawait_deferred of deferred_key                 (* ProgName.awaitDeferred *)
  | Rinterrupt_deferred of deferred_key             (* ProgName.interruptDeferred *)
  (* the `Refs` / `ERefs` families *)
  | Rref_make of int
  | Rref_get of int
  | Rref_set of int * int
  | Rref_update of int * int
  | Rref_modify of int * int
  | Rref_get_and_set of int * int
  | Rref_try_take of int * int
  (* the `Deferreds` family *)
  | Rdef_make
  | Rdef_succeed of int * int
  | Rdef_fail of int * int
  | Rdef_is_done of int
  | Rdef_poll of int
  | Rdef_await_value of int
  | Rdef_await_error of int
  (* the `Scopes` family *)
  | Rscope_make
  | Rscope_add of int * int
  | Rscope_remove of int * int
  | Rscope_close of int

(* `ScopeStore.closeResultOf` (`Stores.lean:939`), through `Scope.closeResult`
   (`Scope.lean:796`): the three arms of rc.112 `scopeCloseUnsafe`. *)
let scope_close_result (run : fin_name -> exitv -> exitv) (self : scope) (exit_ : exitv) :
    exitv =
  if scope_is_closed self then Esuccess Vunit
  else
    match scope_close_exits run self exit_ with
    | [] -> Esuccess Vunit
    | [ only ] -> only
    | first :: second :: rest ->
      let reasons =
        List.concat_map (function Esuccess _ -> [] | Efailure c -> c.reasons)
          (first :: second :: rest)
      in
      if reasons = [] then Esuccess Vunit
      else Efailure { reasons; annotations = [] }

let scope_store_close_result_of (self : scope_store) (key : int) (exit_ : exitv) : exitv =
  match scope_store_entry_at self key with
  | None -> Esuccess Vunit
  | Some entry -> scope_close_result fin_exit entry.scope exit_

(* `voidAllOf` (`Stores.lean:948`): `exitAsVoidAll` at the value alphabet. *)
let void_all_of (reasons : reason list) : exitv =
  match reasons with
  | [] -> Esuccess Vunit
  | reason :: rest -> Efailure { reasons = reason :: rest; annotations = [] }

(* `Exit.causeReasons`. *)
let cause_reasons : exitv -> reason list = function
  | Esuccess _ -> []
  | Efailure c -> c.reasons

(* `mergeExits` (`Stores.lean:954`). *)
let merge_exits (exits : exitv list) : exitv =
  void_all_of (List.concat_map cause_reasons exits)

(* `reifyExitVal` (`Stores.lean:965`): an `Exit` as a value of the one value alphabet. The
   wire alphabet has no `exitOk`/`exitErr` pair, so this is the machine's own
   `exit_value _ MAwait` (`deep_fibers.ml:652`) and it loses the typed error -- the loss
   A0 DIVERGENCE 6 already records. *)
let reify_exit_val : exitv -> value = function
  | Esuccess value -> Vsome value
  | Efailure _ -> Vnone

(* `exitsVal` (`Stores.lean:971`): the exits a countdown collected, as one value. Lean's
   `Val.exitCons`/`exitNil` spine is the avatar's `Vlist`. Since seat F1 the machine's
   `resume_prim RexitsValue` answers the exits themselves (`Aexits`), and this is the
   projection the Lean alphabet applies (`PawaitFibers`), while the wire's `awaitAll` row
   applies its own (raw values) at `answer_countdown` -- one function, two projections at
   two sites, which closes report row W1-7. *)
let exits_val (exits : exitv list) : value = Vlist (List.map reify_exit_val exits)

(* `reasonsOfVal` (`Stores.lean:976`). Lossy at this alphabet: `reifyExitVal` mapped every
   failure to `Vnone`, so the reasons are not recoverable from the value. The Lean theorem
   `reasonsOfVal_exitsVal` (`:984`) therefore has no avatar counterpart -- a finding, not a
   defect of this function. *)
let rec reasons_of_val : value -> reason list = function
  | Vlist xs -> List.concat_map reasons_of_val xs
  | _ -> []

(* ------------------------------------------------------------------ the service state *)

(* `Stores.empty` (`Stores.lean:1016`). *)
let stores_empty () : stores =
  { refs = []; deferreds = { cells = []; due = [] }; scopes = { entries = [] }; next_name = 0 }

(* The machine's `St`. Lean threads it through `RunMachine.state`; the avatar's machine has
   no such field because `update`/`modify` are the identity over `mutable` fields
   (DIVERGENCE 3), so the store is one record this module owns. *)
let store : stores = stores_empty ()

let store_reset () : unit =
  store.refs <- [];
  store.deferreds.cells <- [];
  store.deferreds.due <- [];
  store.scopes.entries <- [];
  store.next_name <- 0

(* ------------------------------------------------------------ names into programs *)

(* `raceEntrants` (`Stores.lean:1026`). *)
let race_entrants : race_name -> prog_name list = function
  | Rnempty -> []
  | RnsuccessThenSecond -> [ Pvalue (Vnat 1); Pvalue (Vnat 2) ]
  | RnfailThenSuccess -> [ PfailCause (cause_fail 1); Pvalue (Vnat 9) ]
  | RnfailThenFail -> [ PfailCause (cause_fail 1); PfailCause (cause_fail 2) ]
  (* `2f77f7d`: one entrant that parks (R2-13); a parked loser and an immediate winner (R2-12) *)
  | RnparkOnly -> [ Ppark 1 ]
  | RnparkThenSuccess -> [ Ppark 1; Pvalue (Vnat 2) ]

(* `Prim.ofExit exit` as a program: the avatar's return/`raise` pair. This is what
   `DeferredStore.complete` stores for `deferredInterruptWith` (`Stores.lean:1220-1223`) and,
   through `completion_prim`, for every `Completion.ofExit`. *)
let prim_of_exit (e : exitv) : program =
  match e with
  | Esuccess v -> fun () -> v
  | Efailure cause -> fun () -> raise (Einterrupt_exn cause)

(* `completionPrim` (`Stores.lean:1081-1085`): the stored primitive a `Completion` names --
   `done exit = completeWith (Prim.ofExit exit)` (`completionPrim_ofExit`, `:1433`). The
   `ofRefGet` arm is `Prim.sync (Thunk.op (SyncOp.refGet cell))`, an effect stored and not
   run; the avatar's awaiting arms run the stored program on the *arm's* stack for its exit
   (the fixture's rows need it there), where a `sync` cannot be performed, so that arm still
   refuses by name when run (report row W1-2; no program of the avatar's alphabets stores
   one). *)
let completion_prim (c : completion) : program =
  match c with
  | CoofExit exit_ -> prim_of_exit exit_
  | CoofRefGet _cell -> fun () -> refuse "Effect4.Deep.completionPrim (Completion.ofRefGet)"

(* `finProgram` (`Stores.lean:1036`): the program a scope finalizer *name* runs
   (`internal/effect.ts:4021`). All five arms ported (seat F1): `interruptFiber` by its
   `skipSelf` flag is `interruptScoped`/`interrupt` on the fiber id; `closeChildScope` is
   `closeScope`, whose program the arm installs and the wrapper runs; `parkThen` is a
   `Prim.async` at an external slot, i.e. a park the tape's `answerAsync` resumes. *)
let fin_program (fin : fin_name) (exit_ : exitv) : program =
  match fin with
  | FininterruptFiber (fiber, true) -> fun () -> Effect.perform (Op_interrupt_scoped fiber)
  | FininterruptFiber (fiber, false) -> fun () -> Effect.perform (Op_interrupt_fiber fiber)
  | FincloseChildScope scope ->
    fun () ->
      ignore (Effect.perform (Op_close_scope (scope, exit_)));
      take_current_program () ()
  | FindetachFromParent (parent, key) ->
    fun () -> Effect.perform (Op_store (Rsync (SscopeRemove (parent, key))))
  | Finrelease (label, fails) ->
    fun () -> if fails then raise (Efail_exn label) else Vunit
  | FinparkThen _slot -> fun () -> Effect.perform (Op_never ())
  (* `57924eb` (R2-7): `awaitAllChildren`'s finalizer (`:5319-5333`) -- await the children
     added since the snapshot, on any exit, under the finalizer mask; the wire arm takes the
     snapshot as handles. *)
  | FinawaitNewChildren snapshot ->
    fun () ->
      Effect.perform
        (Op_await_new_children (Vlist (List.map (fun id -> Vhandle (handle_index "fiber" id)) snapshot)))

(* The exit of a program run on this stack: `Prim.exitFrame` (`Runtime.lean`), the avatar's
   `try`. A typed failure and a delivered cause are both `Exit.failure`. *)
let exit_of_run (program : program) : exitv =
  try Esuccess (program ()) with
  | Efail_exn code -> Efailure (cause_fail code)
  | Einterrupt_exn c -> Efailure c

(* `Prim.ofExit` on this stack: return the value or re-raise the cause. *)
let deliver_exit (e : exitv) : value =
  match e with Esuccess v -> v | Efailure c -> raise (Einterrupt_exn c)

(* `Prim.onExit body finalizer flag` (`Runtime.lean:125`) on this stack: the body's exit is
   taken (`exit_of_run`), the frame's `contAll` masks the fiber and names the finalizer
   (`Op_on_exit_enter`, one iteration, as `finalizerOr` is), the finalizer program runs,
   the restoring `setInterruptible true` frame is passed (`Op_set_interruptible`, which
   delivers a cause recorded meanwhile, M2), and the original exit is restored
   (`restoreName`) or the finalizer's failure merged over it (`mergeName`,
   `Runtime.lean:874-880`). Seat F1. *)
let on_exit_program (body : program) (fin_name_str : string) (finalizer : exitv -> program)
    (fin_interruptible : bool) : program =
 fun () ->
  let exit_ = exit_of_run body in
  let previous = Effect.perform (Op_on_exit_enter (fin_name_str, exit_, fin_interruptible)) in
  let fin_exit = exit_of_run (finalizer exit_) in
  (match previous with
   | Vbool true when not fin_interruptible ->
     ignore (Effect.perform (Op_set_interruptible true))
   | _ -> ());
  match fin_exit with
  | Esuccess _ -> deliver_exit exit_
  | Efailure c ->
    deliver_exit
      (match exit_ with
       | Esuccess _ -> Efailure c
       | Efailure previous -> Efailure (cause_combine previous c))

(* The `WithFiberAction.setInterruptible body flag` region (`Fibers.lean:930-937`, M2) on
   this stack: set the flag, run the body, restore the previous flag through the same arm,
   which delivers a cause recorded meanwhile when interruptibility returns. *)
let masked_region (flag : bool) (body : program) : program =
 fun () ->
  let previous =
    match Effect.perform (Op_set_interruptible flag) with Vbool b -> b | _ -> true
  in
  let exit_ = exit_of_run body in
  ignore (Effect.perform (Op_set_interruptible previous));
  deliver_exit exit_

(* The name a finalizer program carries in the `finalizerProgram` event
   (`RunEvent.finalizerProgram`'s `ν` is `Name.finalizerName fin`). *)
let fin_name_string : fin_name -> string = function
  | FininterruptFiber (fiber, skip) -> Printf.sprintf "interruptFiber(%d,%b)" fiber skip
  | FincloseChildScope scope -> Printf.sprintf "closeChildScope(%d)" scope
  | FindetachFromParent (parent, key) -> Printf.sprintf "detachFromParent(%d,%d)" parent key
  | Finrelease (label, fails) -> Printf.sprintf "release(%d,%b)" label fails
  | FinparkThen slot -> Printf.sprintf "parkThen(%d)" slot
  | FinawaitNewChildren snapshot ->
    Printf.sprintf "awaitNewChildren([%s])" (String.concat ";" (List.map string_of_int snapshot))

(* `progOf` (`Stores.lean:1057`), the interpretation of the declared program names, arm for
   arm. Every arm is ported (seat F1): the forks over a `ProgName` go through the Lean
   alphabet's own effects (`Op_fork_prog`, `Op_fork_in`, `Op_fork_scoped`, `Op_run_in`,
   `Op_race_all_prog`, `Op_close_scope`), `onExitOf` is `on_exit_program`, and
   `intoDeferred`/`intoBody` are the mask region around an `exitFrame`. The answer of a
   fork is the child's wire handle (report row W1-1: `Val.fiber` is `Vhandle`). *)
let rec prog_of (p : prog_name) : program =
  match p with
  | Pvalue v -> fun () -> v
  | PfailCause cause -> fun () -> raise (Einterrupt_exn cause)
  | PsyncOp op -> fun () -> Effect.perform (Op_store (Rsync op))
  | PyieldNow priority -> fun () -> Effect.perform (Op_yield_now priority)
  | Ppark _slot -> fun () -> Effect.perform (Op_never ())
  | PawaitDeferred cell -> fun () -> Effect.perform (Op_store (Rawait_deferred cell))
  | PintoDeferred (body, cell) ->
    (* `uninterruptibleMask(restore => …)` (`Deferred.ts:1778`), M2 *)
    masked_region false (prog_of (PintoBody (body, cell)))
  | PintoBody (body, cell) ->
    (* `flatMap(exit(restore(self)), exit => done(deferred, exit))` (`Deferred.ts:1779-1782`) *)
    fun () ->
      let exit_ = exit_of_run (masked_region true (prog_of body)) in
      Effect.perform (Op_store (Rsync (SdeferredCompleteWith (cell, CoofExit exit_))))
  | PmaskedPark slot -> masked_region false (prog_of (Ppark slot))
  | PawaitFibers targets ->
    fun () -> exits_val (Effect.perform (Op_await_fibers targets))
  | PfinalizerOf (fin, exit_) -> fin_program fin exit_
  | PinterruptDeferred cell ->
    fun () -> Effect.perform (Op_store (Rinterrupt_deferred cell))
  | PonExitOf (body, fin, flag) ->
    on_exit_program (prog_of body) (fin_name_string fin) (fin_program fin) flag
  | PseqOf (first, second) ->
    fun () ->
      ignore (prog_of first ());
      prog_of second ()
  | PforkThen (child, options, mode) ->
    fun () ->
      let handle = Effect.perform (Op_fork_prog (prog_of child, options)) in
      Effect.perform (Op_join_on (handle_target "fiber" (match handle with Vhandle h -> h | _ -> -1), mode))
  | PforkOnly (child, options) -> fun () -> Effect.perform (Op_fork_prog (prog_of child, options))
  | PforkInScope (child, options, scope, key) ->
    fun () -> Effect.perform (Op_fork_in (prog_of child, options, scope, key))
  | PrunInScope (target, scope, key) ->
    fun () -> Effect.perform (Op_run_in (target, scope, key))
  | PforkScopedOf (child, options, key) ->
    fun () -> Effect.perform (Op_fork_scoped (prog_of child, options, key))
  | PraceOf race ->
    fun () -> race_all_program (List.map prog_of (race_entrants race))
  | PcloseScopeOf (scope, exit_) ->
    fun () ->
      ignore (Effect.perform (Op_close_scope (scope, exit_)));
      take_current_program () ()
  | PawaitAllNew body ->
    (* `Stores.lean` (`57924eb`, R2-7): `snapshotThen body` is `onExit(self, _ => asVoid(
       fiberAwaitAll(new children)))` (`:5314-5333`) -- the await is the finalizer program
       `FinName.awaitNewChildren snapshot`, run on any exit under the finalizer mask, and
       the body's own value is answered. *)
    fun () ->
      let snapshot =
        match Effect.perform (Op_snapshot_children ()) with
        | Vlist items -> List.filter_map (function Vhandle h -> Some (handle_target "fiber" h) | _ -> None) items
        | _ -> []
      in
      on_exit_program (prog_of body) (fin_name_string (FinawaitNewChildren snapshot))
        (fin_program (FinawaitNewChildren snapshot)) false ()
  (* `Stores.lean:1130-1131` (`2f77f7d`): `fiberInterruptAll(targets)` (`:889-896`), the
     settled race's cleanup half (R2-12); `fiberJoin`/`fiberAwait` on an existing handle. *)
  | PinterruptFibers targets -> fun () -> Effect.perform (Op_interrupt_fibers targets)
  | PjoinFiber (target, mode) -> fun () -> Effect.perform (Op_join_on (target, mode))

(* `raceSettleProgram` (`Stores.lean:1134-1142`, R2-12) is `Deep_fibers.race_settle_program`:
   the machine resumes the host with it (`Aprogram`), so it lives beside the machine. *)
let race_settle_program = race_settle_program

(* `cancelProgram` (`Stores.lean:1107`): the cancel effect a cancel *name* runs. `cancelName`
   attached the parked fiber's identity and its resume token, so `_await`'s cleanup splices
   exactly that resume out. *)
let cancel_program (n : name) : program =
  match n with
  | NwithWaiter (NcancelAwait cell, waiter, token) ->
    fun () -> Effect.perform (Op_store (Rsync (SdeferredAwaitCleanup (cell, waiter, token))))
  (* `2f77f7d`: a fiber-observer park's cleanup drops the observers of that token (R2-3); a
     race park's cleanup interrupts the race's live entrants (R2-13). The machine runs the
     same two from the park closures (`Deep_fibers.drop_observers`, `cancel_race`). *)
  | NwithWaiter (NcancelPark, _, token) -> fun () -> Effect.perform (Op_drop_observers token)
  | NwithWaiter (NcancelRace race, _, _) -> fun () -> Effect.perform (Op_cancel_race race)
  | _ -> fun () -> Vunit

(* `closeSeqChain` (`Stores.lean:1115`): the finalizers in `closeOrder`, each awaited through
   its own exit, with the captured reasons merged by `exitAsVoidAll` at the end. Lean builds
   a `Prim` chain of `onSuccessAndFailure` frames; the avatar's chain is the OCaml `try`, so
   the recursion is a loop and `Name.closeSeq` is the loop's accumulator rather than a name. *)
let rec close_seq_chain (fins : fin_name list) (exit_ : exitv) (captured : reason list) :
    program =
  match fins with
  | [] -> fun () -> ( match void_all_of captured with
                      | Esuccess v -> v
                      | Efailure c -> raise (Einterrupt_exn c))
  | fin :: rest ->
    fun () ->
      let captured =
        try
          ignore (fin_program fin exit_ ());
          captured
        with
        | Efail_exn code -> captured @ [ Rfail code ]
        | Einterrupt_exn c -> captured @ c.reasons
      in
      close_seq_chain rest exit_ captured ()

(* `closeParChain` (`Stores.lean:1126`; `internal/effect.ts:3819-3826`): each finalizer is
   forked as an *immediate daemon* whose mask is the closing fiber's, then all of them are
   awaited together and every exit merged (`Name.mergeAwaitedExits`, M6: the merge reads
   the exits the countdown collected -- `Op_await_fibers` answers them as exits, so the
   reasons survive). Seat F1. *)
let rec close_par_chain (closer_interruptible : bool) (fins : fin_name list) (exit_ : exitv)
    (forked : int list) : program =
  match fins with
  | [] ->
    fun () ->
      let exits = Effect.perform (Op_await_fibers forked) in
      deliver_exit (merge_exits exits)
  | fin :: rest ->
    fun () ->
      let handle =
        Effect.perform
          (Op_fork_prog
             ( fin_program fin exit_,
               { start_immediately = true;
                 daemon = true;
                 mask_mode = (if closer_interruptible then Minterruptible else Muninterruptible) } ))
      in
      let child = match handle with Vhandle h -> handle_target "fiber" h | _ -> -1 in
      close_par_chain closer_interruptible rest exit_ (forked @ [ child ]) ()

(* `storesCloseScope` (`Stores.lean:1143`): `Effect4.Scope.closeState` runs first, so the
   state is written before any finalizer program is built, and the close of an already
   closed scope is void. `None` is an unknown scope key, which the machine turns into
   `Stuck.unknownScope` (M7). *)
let stores_close_scope (scope : int) (exit_ : exitv) (closer_interruptible : bool)
    (state : stores) : program option =
  match scope_store_entry_at state.scopes scope with
  | None -> None
  | Some entry ->
    if scope_is_closed entry.scope then Some (fun () -> Vunit)
    else begin
      let order = scope_close_order entry.scope in
      let strategy = entry.scope.strategy in
      scope_store_close_state state.scopes scope exit_;
      match strategy with
      | Fssequential -> Some (close_seq_chain order exit_ [])
      | Fsparallel -> Some (close_par_chain closer_interruptible order exit_ [])
    end

(* --------------------------------------------------- the store steps under `Prim.sync` *)

(* `syncOpStep` (`Stores.lean:1160`): every `sync` thunk that reads or writes the service
   state. `None` falls back to the pure `syncValue`. The store is written in place, so the
   Lean pair `(Stores × Val)` is the `Val` alone. *)
let sync_op_step (op : sync_op) (st : stores) : value option =
  match op with
  | SdeferredMake ->
    let key = deferred_store_make st.deferreds in
    Some (Vhandle key.index)
  | SdeferredIsDone cell ->
    Option.map (fun flag -> Vbool flag) (deferred_store_is_done st.deferreds cell)
  | SdeferredPoll cell ->
    Option.map (fun slot -> Vbool (slot <> None)) (deferred_store_poll st.deferreds cell)
  | SdeferredCompleteWith (cell, completion) ->
    (* `Stores.lean:1217-1219`: the store receives `completionPrim completion` *)
    Some (Vbool (deferred_store_complete st.deferreds cell (completion_prim completion)))
  | SdeferredInterruptWith (cell, interruptor) ->
    (* `Stores.lean:1220-1224`: `Prim.ofExit (Exit.failure (Cause.interrupt (some interruptor)))` *)
    Some
      (Vbool
         (deferred_store_complete st.deferreds cell
            (prim_of_exit (Efailure (cause_interrupt (Some interruptor))))))
  | SdeferredAwaitCleanup (cell, waiter, token) ->
    deferred_store_cancel st.deferreds cell waiter token;
    Some Vunit
  | SscopeMake strategy ->
    let key = st.next_name in
    scope_store_make st.scopes key strategy;
    st.next_name <- key + 1;
    Some (Vhandle key)
  | SscopeAdd (scope, key, finalizer) ->
    ignore (scope_store_add_finalizer st.scopes scope key finalizer);
    Some Vunit
  | SscopeRemove (scope, key) ->
    scope_store_remove_finalizer st.scopes scope key;
    Some Vunit
  | SscopeIsClosed scope ->
    Option.map (fun (entry : scope_entry) -> Vbool (scope_is_closed entry.scope))
      (scope_store_entry_at st.scopes scope)
  | op ->
    Option.map
      (fun (v, refs) ->
        st.refs <- refs;
        v)
      (ref_step op st.refs)

(* -------------------------------------------------------------------- continuations *)

(* `contAOf` (`Stores.lean:1193`), `contEOf` (`:1225`) and `actionOf` (`:1236`) REFUSE. A
   continuation name means "the `Prim` the frame machine pushes"; the avatar's frame is the
   OCaml stack and its continuation is the `continue k` the arm already holds
   (DIVERGENCE 1), so there is nothing for these three to return that the machine would
   read. They are the three declarations of `Stores.lean` that the substitution makes
   unreachable rather than merely unwritten. *)
let cont_a_of (_n : name) (_v : value) : program = refuse "Effect4.Deep.contAOf"
let cont_e_of (_n : name) (_c : cause) : program = refuse "Effect4.Deep.contEOf"
let action_of (_a : action_name) : program = refuse "Effect4.Deep.actionOf"

(* ------------------------------------------------------------------------- the interp *)

(* `defaultBudget` (`Stores.lean:1263`). *)
let default_budget : int = 2048

(* `emptyCtx` (`Stores.lean:1266`). *)
let empty_ctx : ctx =
  { ambient_scope = None; max_ops_before_yield = default_budget; prevent_yield = false }

(* `stackKey` (`Stores.lean:1270`). *)
let stack_key (fiber : int) : string =
  match fiber with 0 -> "stack0" | 1 -> "stack1" | 2 -> "stack2" | _ -> "stackN"

(* `stackAnnotationsOf` (`Stores.lean:1283`): `Ann` is `Unit`, so the key carries the
   identity and the value carries nothing -- which is the avatar's `string list`. *)
let stack_annotations_of (fiber : int) : string list = [ stack_key fiber ]

(* ==================================================================================
   The arms. `RunInterp`'s meanings are handler-arm code in the avatar (A0 DIVERGENCE 5);
   what is new here is that the *store* they run on is `Stores.lean`'s, not three hashtables
   of ints. Every arm keeps the wire rows `harness/trace/Generate.lean` lowers.
   ================================================================================== *)

(* A wire handle back to the store key it names. `handle_target` would also check the kind;
   the arms this replaces (`ref_cell`/`deferred_cell`/`scope_cell`, `deep_fibers.ml:1570-1587`
   before this port) read the owner index without checking it, and three of P5's generated
   programs pass a handle of one kind to an operation of another and rely on that. Keeping
   the laxness keeps those three running; report row W1-6 records it as a defect of the wire
   decoding, not of the store. *)
let owner_index h : int =
  match Hashtbl.find_opt handle_owner h with Some (_, id) -> id | None -> -1

let ref_key_of_handle h : ref_key = { index = owner_index h }
let deferred_key_of_handle h : deferred_key = { index = owner_index h }
let scope_key_of_handle h : int = owner_index h

let peek_exn (cell : ref_key) : value =
  match ref_peek store.refs cell with
  | Some v -> v
  | None -> failwith (Printf.sprintf "unknown ref cell %d" cell.index)

let nat_of = function Vnat n -> n | _ -> 0

(* `refStep`'s read-modify-write shape (`Stores.lean:457`) with the fixture's own closure in
   the `FnName` slot: one `Effect.sync` thunk, so the read and the write happen with no
   intervening runtime step. *)
let ref_rmw (cell : ref_key) (f : int -> int * int) : value =
  let before = nat_of (peek_exn cell) in
  let answer, after = f before in
  store.refs <- ref_poke store.refs cell (Vnat after);
  Vnat answer

let deferred_cell_exn (cell : deferred_key) : deferred_cell =
  match deferred_store_cell_at store.deferreds cell with
  | Some c -> c
  | None -> failwith (Printf.sprintf "unknown deferred cell %d" cell.index)

(* `Deferred.completeWith` at the fixture's alphabet: the first completion wins and the
   waiters it owes are queued for `dueResumes` in registration order
   (`Deferred.ts:1655-1659`, M1). *)
let arm_def_complete m f name h (exit_ : exitv) (payload : value) (ko : value kops) : unit =
  push_row (Rop (name, Vpair (Vhandle h, payload)));
  (* `done(self, exit)` = `completeWith(self, exit)` (`Deferred.ts:570-571`): the stored
     program is `Prim.ofExit exit` (`completionPrim_ofExit`) *)
  let fresh = deferred_store_complete store.deferreds (deferred_key_of_handle h)
      (prim_of_exit exit_) in
  (* Lean's `iteration` delivers the `sync`'s value into the frame and runs `Cmd.drainDue` as
     a nested command *before* the completing fiber continues, so the waiter it woke runs
     first. The service `answer` row is what the host face emits when the effect completes,
     i.e. after that nested work -- hence the drain before the row. *)
  drive m m.drive_fuel [ CdrainDue ];
  answer_row m f name (Vbool fresh) ko

(* `Deferred.await` and its flip (`Deferred.ts:173-186`): a `Prim.async` whose registration
   (`Stores.lean:1354`, `RunInterp.registerAsync`) answers at once when the cell is settled
   and otherwise adds the waiter under the token and parks; its cancel is
   `cancelName (cancelAwait cell) fiber token` (M3), the store step that splices exactly
   that waiter out (`_await`'s cleanup, `Deferred.ts:178-185`), run by the `AsyncFinalizer`
   frame's `contE` when the cause carries an interrupt (`Fibers.lean:709-712`,
   `Runtime.lean:883-888`). Seat F2: the park is `Deep_fibers.arm_async`, the PARK
   section's one `Async` primitive; the rows are the fixture's. *)
let arm_def_await m f h which (ko : value kops) : unit =
  let name = match which with `Value -> "awaitValue" | `Error -> "awaitError" in
  push_row (Rop (name, Vhandle h));
  let cell = deferred_key_of_handle h in
  (* The stored program is what the waiter continues with (Lean: `current := effect`,
     `Fibers.lean:1120-1126` for the immediate answer, `Cmd.resume` for a due one). The
     fixture projects its *exit* into the `awaitValue`/`awaitError` answer, so the program is
     run here, on the arm's stack, for that exit: exact for `Prim.ofExit` (a pure thunk), a
     refusal by name for `Completion.ofRefGet` (report row W1-2). *)
  let answer_of (p : program) : answer =
    match (which, exit_of_run p) with
    | `Value, Esuccess v -> Aval v
    | `Value, Efailure cause -> Acause cause
    | `Error, Efailure cause ->
      Aval (match cause_fail_of cause with Some e -> Vnat e | None -> Vunit)
    | `Error, Esuccess v -> Acause (cause_fail (nat_of v))
  in
  let settle (p : program) : unit =
    match answer_of p with
    | Aval v -> answer_row_now m f name v ko
    | Acause cause -> fail_op name ko cause
    | Aexits _ | Aprogram _ -> answer_row_now m f name Vunit ko
  in
  arm_async m f
    ~register:(fun token ->
      match deferred_store_register store.deferreds cell f.id token with
      | Some p -> Some (answer_of p)
      | None -> None)
    ~cancel:(Some (fun token ->
      (* M3: `SyncOp.deferredAwaitCleanup cell waiter token`, the waiter's own token *)
      ignore (sync_op_step (SdeferredAwaitCleanup (cell, f.id, token)) store)))
    ~on_answer:(fun a ->
      match a with
      (* a due resume carries the stored program, as Lean's `due` carries the effect *)
      | Aprogram p -> settle p
      | Aval _ | Aexits _ -> (
        (* a resume from outside the store (the tape's `answerAsync`): the slot is read
           back, which holds the same program the store would have carried *)
        match (deferred_cell_exn cell).completion with
        | Some p -> settle p
        | None -> answer_row_now m f name Vunit ko)
      | Acause c -> fail_op name ko c)
    ko

(* One `store_request`, one arm. The three at the head are the Lean alphabet; the rest are
   the fixture's (see the `store_request` extension above). *)
let store_arm m f (req : Deep_fibers.store_request) (ko : value kops) : unit =
  let state name request compute = arm_state m f name request compute ko in
  match req with
  (* --- the Lean alphabet ------------------------------------------------------- *)
  | Rsync op -> (
    (* `Sync[evaluate]` (`:931-935`, R2-1): the thunk, the resumes it owes (`Cmd.drainDue`
       as the nested command of `Outcome.answered`, `Fibers.lean:749-751`), then the pop
       through `deliver` (`Cmd.deliver`), whose `getCont` sees what the drain recorded. *)
    match sync_op_step op store with
    | Some v ->
      drive m m.drive_fuel [ CdrainDue ];
      deliver f ko v
    | None -> refuse "Effect4.Deep.stores.syncState (no arm)")
  | Rawait_deferred cell -> arm_def_await m f (handle_index "deferred" cell.index) `Value ko
  | Rinterrupt_deferred cell ->
    (* `Deferred.interrupt` (`Deferred.ts:1231-1232`): `withFiber` reads the id, then
       `interruptWith`, a stateful `sync` -- so the resumes it owes are drained on the spot
       (M1), before the completing fiber continues. *)
    let v =
      match sync_op_step (SdeferredInterruptWith (cell, f.id)) store with
      | Some v -> v
      | None -> Vunit
    in
    drive m m.drive_fuel [ CdrainDue ];
    deliver f ko v
  (* --- the `Refs` and `ERefs` families ------------------------------------------ *)
  | Rref_make initial ->
    push_row (Rop ("make", Vnat initial));
    let cell : ref_key = { index = List.length store.refs } in
    store.refs <- store.refs @ [ Vnat initial ];
    answer_row m f "make" (Vhandle (handle_index "ref" cell.index)) ko
  | Rref_get h -> state "get" (Vhandle h) (fun () -> peek_exn (ref_key_of_handle h))
  | Rref_set (h, v) ->
    state "set" (Vpair (Vhandle h, Vnat v)) (fun () ->
        store.refs <- ref_poke store.refs (ref_key_of_handle h) (Vnat v);
        Vunit)
  | Rref_update (h, a) ->
    state "update" (Vpair (Vhandle h, Vnat a)) (fun () ->
        ignore (ref_rmw (ref_key_of_handle h) (fun before -> (before, before + a)));
        Vunit)
  | Rref_modify (h, a) ->
    state "modify" (Vpair (Vhandle h, Vnat a)) (fun () ->
        ref_rmw (ref_key_of_handle h) (fun before -> (before, before + a)))
  | Rref_get_and_set (h, v) ->
    state "getAndSet" (Vpair (Vhandle h, Vnat v)) (fun () ->
        ref_rmw (ref_key_of_handle h) (fun before -> (before, v)))
  | Rref_try_take (h, a) ->
    state "tryTake" (Vpair (Vhandle h, Vnat a)) (fun () ->
        let cell = ref_key_of_handle h in
        let before = nat_of (peek_exn cell) in
        if before >= a then begin
          store.refs <- ref_poke store.refs cell (Vnat (before - a));
          Vpair (Vbool true, Vnat (before - a))
        end
        else Vpair (Vbool false, Vstring "underflow"))
  (* --- the `Deferreds` family ---------------------------------------------------- *)
  | Rdef_make ->
    push_row (Rop ("make", Vunit));
    let cell = deferred_store_make store.deferreds in
    answer_row m f "make" (Vhandle (handle_index "deferred" cell.index)) ko
  | Rdef_succeed (h, v) -> arm_def_complete m f "succeed" h (Esuccess (Vnat v)) (Vnat v) ko
  | Rdef_fail (h, e) -> arm_def_complete m f "fail" h (Efailure (cause_fail e)) (Vnat e) ko
  | Rdef_is_done h ->
    state "isDone" (Vhandle h) (fun () ->
        Vbool
          (match deferred_store_is_done store.deferreds (deferred_key_of_handle h) with
           | Some b -> b
           | None -> false))
  | Rdef_poll h ->
    (* The fixture's `poll` answers the completion's *exit*; `SyncOp.deferredPoll`
       (`Stores.lean:234`, `:1215-1216`) answers `Val.bool slot.isSome`, because Lean's slot
       holds a `Program` it must not run. The avatar's slot holds that program; the fixture
       runs it here for its exit, which is exact for `Prim.ofExit` (every program the
       fixture stores) and refuses by name for `Completion.ofRefGet`. Report row W1-4. *)
    state "poll" (Vhandle h) (fun () ->
        match (deferred_cell_exn (deferred_key_of_handle h)).completion with
        | None -> Vnone
        | Some p -> (
          match exit_of_run p with
          | Esuccess v -> Vsome (Vpair (Vbool true, v))
          | Efailure c ->
            Vsome
              (Vpair (Vbool false, match cause_fail_of c with Some e -> Vnat e | None -> Vunit))))
  | Rdef_await_value h -> arm_def_await m f h `Value ko
  | Rdef_await_error h -> arm_def_await m f h `Error ko
  (* --- the `Scopes` family -------------------------------------------------------- *)
  | Rscope_make ->
    push_row (Rop ("make", Vunit));
    let key = store.next_name in
    scope_store_make store.scopes key Fssequential;
    store.next_name <- key + 1;
    answer_row m f "make" (Vhandle (handle_index "scope" key)) ko
  | Rscope_add (h, key) ->
    state "addFinalizer" (Vpair (Vhandle h, Vnat key)) (fun () ->
        let scope = scope_key_of_handle h in
        let was_open =
          match scope_store_status store.scopes scope with Some None -> true | _ -> false
        in
        ignore (scope_store_add_finalizer store.scopes scope key (Finrelease (key, false)));
        Vbool was_open)
  | Rscope_remove (h, key) ->
    state "remove" (Vpair (Vhandle h, Vnat key)) (fun () ->
        scope_store_remove_finalizer store.scopes (scope_key_of_handle h) key;
        Vunit)
  | Rscope_close h ->
    state "close" (Vhandle h) (fun () ->
        let scope = scope_key_of_handle h in
        (* `storesCloseScope` (`Stores.lean:1143`): the close order is read before
           `closeState` writes, and a closed scope's order is empty. *)
        let order = scope_store_close_order_of store.scopes scope in
        scope_store_close_state store.scopes scope (Esuccess Vunit);
        Vlist
          (List.map
             (function Finrelease (label, _) -> Vnat label | _ -> Vunit)
             order))
  | _ -> refuse "Effect4.Deep.stores (unknown store_request)"

(* `stores : RunInterp Name Thunk Val Err Defect FiberId Ann Ctx Stores`
   (`Stores.lean:1293`), the slots the machine calls. Field for field with the Lean record,
   minus the ones the substitution makes unreachable (`contA`, `contE`, `withFiberOf`,
   `parkOf`, `finalizerProgram`, `restoreName`, `mergeName`, `cancelName`, `abortName`,
   `reifyExit`, `exitValue`, `fiberValue`, `fibersValue`, `exitsValue`, `voidValue`,
   `encodeFiber`, `iterNext`/`loop*`, `suspendBody`, `finalizerExit`, `notImplemented`,
   `cancelThenFail`, `syncValue`, `emptyContext`, `contextValue`, `ambientScope`,
   `budgetOf`, `stackAnnotations`, `asyncFiberError`) -- those are the avatar's own control
   or the fixture's, and the report lists every one. *)
let stores : run_interp =
  { store_arm;
    (* `RunInterp.dueResumes` (`Fibers.lean:414`) = `Stores.lean:1362`. *)
    due_resumes = (fun () -> deferred_store_drain_due store.deferreds);
    (* `RunInterp.scopeStatus` (`:427`) = `Stores.lean:1370`. *)
    scope_status = (fun scope -> scope_store_status store.scopes scope);
    (* `RunInterp.scopeLinkFiber` (`:431`) = `Stores.lean:1371`. `forkIn` registers the
       self-guarded finalizer (`:5370`), `fiberRunIn` the unguarded one (`:5458`) -- M4.
       `Supervision.ScopeMode` is an int in the substitution: 0 is `forkIn`. *)
    scope_link_fiber =
      (fun mode scope key fiber ->
        match scope_store_entry_at store.scopes scope with
        | None -> false
        | Some _ ->
          let skip_self = mode = 0 in
          ignore
            (scope_store_add_finalizer store.scopes scope key
               (FininterruptFiber (fiber, skip_self)));
          true);
    (* `RunInterp.dropFinalizer` (`:434`) = `Stores.lean:1382`. *)
    drop_finalizer =
      (fun scope key ->
        match scope_store_entry_at store.scopes scope with
        | None -> false
        | Some _ ->
          scope_store_remove_finalizer store.scopes scope key;
          true);
    (* `RunInterp.closeScope` (`:440`) = `Stores.lean:1386`. *)
    close_scope =
      (fun scope exit_ closer_interruptible _closer ->
        stores_close_scope scope exit_ closer_interruptible store);
    (* `RunInterp.stackAnnotations` (`:457`) = `Stores.lean:1283`. *)
    stack_annotations = stack_annotations_of }

(* Install. Lean hands the interp to `stepDecision` as an argument; the avatar's machine
   reads it out of `Deep_fibers.interp`, and each store module chains its own arm over the
   one below (`deep_layer.ml` chains over this). *)
let () =
  let previous = (!interp).store_arm in
  (!interp).store_arm <-
    (fun m f req ko ->
      match req with
      | Rsync _ | Rawait_deferred _ | Rinterrupt_deferred _ | Rref_make _ | Rref_get _
      | Rref_set _ | Rref_update _ | Rref_modify _ | Rref_get_and_set _ | Rref_try_take _
      | Rdef_make | Rdef_succeed _ | Rdef_fail _ | Rdef_is_done _ | Rdef_poll _
      | Rdef_await_value _ | Rdef_await_error _ | Rscope_make | Rscope_add _
      | Rscope_remove _ | Rscope_close _ ->
        stores.store_arm m f req ko
      | _ -> previous m f req ko);
  (!interp).due_resumes <- stores.due_resumes;
  (!interp).scope_status <- stores.scope_status;
  (!interp).scope_link_fiber <- stores.scope_link_fiber;
  (!interp).drop_finalizer <- stores.drop_finalizer;
  (!interp).close_scope <- stores.close_scope;
  (* `RunInterp.stackAnnotations` (`:457`) = `Stores.lean:1283`. *)
  (!interp).stack_annotations <- stack_annotations_of
