(* `Effect4/Deep/Context.lean` → `deep_context.ml`: the first-order environment (M4a `Requirement`
   and `Service`, M4b `Context`), the machine's value alphabet `Val`, the well-known keys and
   references, the four hooks `Deep.Fibers` reads off `χ`, and `ContextUpdate`, declaration by
   declaration in the Lean order.

   Seat F2, 2026-09-04. Report: `docs/research/2026-09-04-seat-w1-deep-port.md` §F2.9.

   The carriers below the banner are GENERATED from `OCaml5.Ml.Deep.Context` in
   `src/OCaml5/Render.lean` (`render-deep.sh context`). Substitutions, each a row of the
   report: `Context.keysNodup` (`Context.lean:184`) is a *proof* and is ERASED (F2-L2) -- `add`
   and `mergeEntries` keep the keys unique by construction, which is what the proof states;
   `Val` (`:797`) is generated as its own carrier `val_` so that `encode`/`decode` and the
   hooks keep the Lean shape, and `wire_of_val` is the projection onto the avatar's wire
   alphabet (W1-1: `fiber`/`scopeHandle`/`memoMap`/`promise` are one `Vhandle` under the
   first-seen counter, `exitOk`/`exitErr` become `Vsome`/`Vnone`, a context spine becomes a
   `Vlist` of pairs); `CauseV`/`ExitV` are the wire's `cause`/`exitv`; `ServiceProgram`,
   `UsesOnly` and `interpret` (`:105-160`, `:485`) are an `Effects` free program and a `Prop`
   over it, and refuse; `transportAll` (`:756`) moves between universes and refuses.

   Nothing on the fiber reads this module yet: the avatar's `χ` is `unit` (A0 §18, report
   Q6). `deep_layer.ml` names `service_key`, `defect` and `context_update` from here.

   Behavioural properties (packages plan §4.5), each the port of a named `Context.lean`
   theorem (`ENV-PG-CONTEXT`, `:489-560`): (1) `get?_empty` -- the empty context answers
   nothing; (2) `get?_add_same`/`get?_add_other` -- `add` binds its key and no other;
   (3) `get?_merge` -- `merge` is right-biased: the *argument*'s binding wins; (4)
   `merge_assoc`, `merge_empty_left`, `merge_empty_right`; (5) `merge_shadows`, `add_add_same`
   -- the later binding of a key wins; (6) `keys` are unique (`setEntries_nodup`); (7)
   `satisfies_empty/single/union/weaken`; (8) `decode_encode` -- the context value
   round-trips; (9) `hooks_empty` -- the empty context's hooks are rc.112's defaults
   (no ambient scope, 2048, `false`). *)

open Deep_fibers

(* Generated by OCaml5.Ml (`Render.lean`, seat W1). Do not edit; edit the descriptions (`Ml.Deep.Context`, seat F2).
   One declaration per `Effect4/Deep/Context.lean` carrier (and `ServiceKey` of `Context/Key.lean`), same field and constructor order. *)

(* `ServiceKey` (`Context/Key.lean:79`), 2 Lean fields, 2 rendered. Generated by OCaml5.Ml. *)

type service_key = { name : int; service : int }

(* `Err` (`Context.lean:772`), 2 constructors, prefix `Ce`. Generated by OCaml5.Ml. *)

type err = Ceboom | Cetag of int

(* `Defect` (`Context.lean:781`), 5 constructors, prefix `Cx`. Generated by OCaml5.Ml. *)

type defect =
  | CxnotImplemented
  | CxasyncFiber
  | CxbadName
  | CxserviceNotFound of service_key
  | CxunknownLayer of int

(* `CauseV`/`ExitV` (`Context.lean:829-832`) over this `Err`/`Defect`: the avatar's `cause`/`exitv` carry the wire's `int` error and `string` defect (W1-1); the aliases name the site. *)

type cause_v = cause

type exit_v = exitv

(* `Val`, `Service ValU` and `Context ValU` are one mutually recursive group in OCaml (`ctxCons` names a key and a value; `Context` holds services). *)

(* `Val` (`Context.lean:797`), 15 constructors, prefix `Cv`. Generated by OCaml5.Ml. *)

type val_ =
  | Cvunit
  | Cvnat of int
  | Cvbool of bool
  | Cvfiber of int
  | Cvfibers of int list
  | CvscopeHandle of int
  | CvmemoMap of int
  | Cvpromise of int
  | Cvpair of val_ * val_
  | CvexitOk of val_
  | CvexitErr of cause_v
  | CvexitNil
  | CvexitCons of val_ * val_
  | CvctxNil
  | CvctxCons of service_key * val_ * val_

(* `Service` (`Context.lean:89`), 2 Lean fields, 2 rendered. Generated by OCaml5.Ml. *)

type service = { key : service_key; value : val_ }

(* `Context` (`Context.lean:180`), 2 Lean fields, 1 rendered. Generated by OCaml5.Ml.
     ERASED keysNodup: a proof (`(entries.map Service.key).Nodup`); kept by construction (F2-L2) *)

type context = { entries : service list }

(* `Reference` (`Context.lean:406`), 2 Lean fields, 2 rendered. Generated by OCaml5.Ml. *)

type reference = { key : service_key; default : val_ }

(* `ContextUpdate` (`Context.lean:1005`), 3 constructors, prefix `Cu`. Generated by OCaml5.Ml. *)

type context_update = CusetTo of context | Cuprovide of context | CuprovideService of service_key * val_

(* ===== END GENERATED ===== *)

(* ==================================================================================
   `Effect4/Deep/Context.lean`, in the Lean declaration order.
   ================================================================================== *)

(* ------------------------------------------- M4a: `Requirement` (`:56-79`, fence F-REQ) *)

(* `ServiceKey`'s order (`Context/Key.lean:96-`): name-major lexicographic. *)
let key_compare (a : service_key) (b : service_key) : int =
  match compare a.name b.name with 0 -> compare a.service b.service | c -> c

(* `Row.normalize`: the strictly ascending, duplicate-free key list -- the canonical row. *)
let row_normalize (keys : service_key list) : service_key list =
  List.sort_uniq key_compare keys

(* `Requirement.empty` (`:68`), `.single` (`:71`), `.union` (`:74`), `.ofList` (`:77`). *)
let requirement_empty : service_key list = []
let requirement_single (key : service_key) : service_key list = [ key ]
let requirement_union (r : service_key list) (s : service_key list) : service_key list =
  row_normalize (r @ s)
let requirement_of_list (keys : service_key list) : service_key list = row_normalize keys

(* ------------------------------------------- M4a: `Service` (`:81-170`, fence F-SVC) *)

(* `serviceSig`, `ServiceProgram`, `UsesOnly` and its laws (`:100-162`): an `Effects`
   signature, a free program over it and a `Prop`; no carrier here. *)
let service_program () : 'a = refuse "Effect4.Deep.Env.ServiceProgram"
let uses_only () : 'a = refuse "Effect4.Deep.Env.UsesOnly"

(* `UniverseAgreement` (`:169`): a `Prop` over two universes; `ValU` is the one universe. *)

(* ------------------------------------------- M4b: `Context` (`:172-763`, fence F-ENV) *)

(* `rightBiased` (`:188`). *)
let right_biased (x : 'a option) (y : 'a option) : 'a option =
  match y with Some _ -> y | None -> x

(* `Context.empty` (`:197`). *)
let context_empty : context = { entries = [] }

(* `Context.lookup` (`:201`): the first entry with the key. *)
let rec context_lookup (key : service_key) : service list -> val_ option = function
  | [] -> None
  | s :: rest -> if s.key = key then Some s.value else context_lookup key rest

(* `Context.get?` (`:209`). *)
let context_get (self : context) (key : service_key) : val_ option = context_lookup key self.entries

(* `Context.keys` (`:213`). *)
let context_keys (self : context) : service_key list = List.map (fun (s : service) -> s.key) self.entries

(* `Context.setEntries` (`:217`): overwrite in place, else append (`setEntries_nil/_cons_same/
   _cons_other`, `:254-268`); the keys stay unique (`setEntries_nodup`, `:361`). *)
let rec context_set_entries (key : service_key) (value : val_) : service list -> service list =
  function
  | [] -> [ { key; value } ]
  | s :: rest ->
    if s.key = key then { key; value } :: rest else s :: context_set_entries key value rest

(* `Context.add` (`:376`). *)
let context_add (self : context) (key : service_key) (value : val_) : context =
  { entries = context_set_entries key value self.entries }

(* `Context.mergeEntries` (`:380`): the argument's entries added in order, so its bindings win. *)
let rec context_merge_entries (self : context) : service list -> context = function
  | [] -> self
  | s :: rest -> context_merge_entries (context_add self s.key s.value) rest

(* `Context.merge` (`:387`): right-biased (`get?_merge`, `:546`). *)
let context_merge (self : context) (that : context) : context =
  context_merge_entries self that.entries

(* `Context.mergeAll` (`:391`). *)
let rec context_merge_all : context list -> context = function
  | [] -> context_empty
  | c :: rest -> context_merge c (context_merge_all rest)

(* `Context.Equiv` (`:396`), decided over the keys of both sides (`equiv_iff`, `:509`). *)
let context_equiv (a : context) (b : context) : bool =
  List.for_all (fun key -> context_get a key = context_get b key) (context_keys a @ context_keys b)

(* `Context.keysRow` (`:399`). *)
let context_keys_row (self : context) : service_key list = row_normalize (context_keys self)

(* `Context.Satisfies` (`:402`): every required key is bound. *)
let context_satisfies (self : context) (r : service_key list) : bool =
  List.for_all (fun key -> context_get self key <> None) r

(* `Context.getRef` (`:411`): the reference's default when unbound. *)
let context_get_ref (self : context) (r : reference) : val_ =
  match context_get self r.key with Some v -> v | None -> r.default

(* `References.default?` (`:420`). *)
let references_default (refs : reference list) (key : service_key) : val_ option =
  Option.map (fun (r : reference) -> r.default) (List.find_opt (fun (r : reference) -> r.key = key) refs)

(* `Context.getOption` (`:430`): the binding, else the reference default, else none. *)
let context_get_option (refs : reference list) (self : context) (key : service_key) : val_ option =
  match context_get self key with Some v -> Some v | None -> references_default refs key

(* `Context.getOrElse` (`:436`). *)
let context_get_or_else (refs : reference list) (self : context) (key : service_key)
    (orElse : unit -> val_) : val_ =
  match context_get_option refs self key with Some v -> v | None -> orElse ()

(* `Context.getUnsafe?` (`:442`): `Context.getUnsafe`'s throw is the `serviceNotFound` defect
   (`:2134`), answered as `None` here and raised by the caller. *)
let context_get_unsafe (refs : reference list) (self : context) (key : service_key) : val_ option =
  context_get_option refs self key

(* `Context.interpret` (`:485`): over a `ServiceProgram`; refuses with it. *)
let context_interpret () : 'a = refuse "Effect4.Deep.Env.Context.interpret"

(* `Context.transportAll` (`:756`): between universes; `ValU` is the one universe here. *)
let context_transport_all () : 'a = refuse "Effect4.Deep.Env.Context.transportAll"

(* ------------------------------------------- the machine's `χ` (`:765-935`) *)

(* `ValU` (`:835`): every code reads as `Val`; `ValU_carrier`/`ValU_collides` are `rfl`. *)

(* `Service.valueVal` (`:847`). *)
let service_value_val (s : service) : val_ = s.value

(* `Ctx := Context ValU` (`:864`); `Context.addV` (`:884`), `Context.getV` (`:887`). *)
let context_add_v = context_add
let context_get_v = context_get

(* The well-known keys (`:912-925`) and references (`:928-931`). *)
let scope_key : service_key = { name = 0; service = 0 }
let max_ops_key : service_key = { name = 1; service = 1 }
let prevent_yield_key : service_key = { name = 2; service = 2 }
let current_memo_map_key : service_key = { name = 3; service = 3 }
let max_ops_ref : reference = { key = max_ops_key; default = Cvnat 2048 }
let prevent_yield_ref : reference = { key = prevent_yield_key; default = Cvbool false }

(* ------------------------------------------- the hooks `Deep.Fibers` reads off `χ` (`:935-1000`) *)

(* `scopeOfVal` (`:936`), `natOfVal` (`:940`), `boolOfVal` (`:943`). *)
let scope_of_val : val_ option -> int option = function
  | Some (CvscopeHandle scope) -> Some scope
  | _ -> None
let nat_of_val (default : int) : val_ -> int = function Cvnat n -> n | _ -> default
let bool_of_val (default : bool) : val_ -> bool = function Cvbool b -> b | _ -> default

(* `ambientScope` (`:948`): `RunInterp.ambientScope`. *)
let ambient_scope (c : context) : int option = scope_of_val (context_get c scope_key)

(* `budgetOf` (`:952`): `RunInterp.budgetOf`, rc.112's defaults where unbound. *)
let budget_of (c : context) : int * bool =
  (nat_of_val 2048 (context_get_ref c max_ops_ref), bool_of_val false (context_get_ref c prevent_yield_ref))

(* `encodeEntries` (`:957`), `encode` (`:962`): the context as its entry spine. *)
let rec encode_entries : service list -> val_ = function
  | [] -> CvctxNil
  | s :: rest -> CvctxCons (s.key, s.value, encode_entries rest)
let encode (c : context) : val_ = encode_entries c.entries

(* `spine` (`:965`), `decode` (`:971`): read back; `decode` insists on unique keys. *)
let rec spine : val_ -> service list option = function
  | CvctxNil -> Some []
  | CvctxCons (key, value, rest) -> Option.map (fun es -> { key; value } :: es) (spine rest)
  | _ -> None
let decode (v : val_) : context option =
  match spine v with
  | None -> None
  | Some es ->
    let keys = List.map (fun (s : service) -> s.key) es in
    if List.length (List.sort_uniq key_compare keys) = List.length keys then Some { entries = es } else None

(* `ContextUpdate.apply` (`:1015`): `f(prevContext)` (`:2089`). *)
let context_update_apply (u : context_update) (prev : context) : context =
  match u with
  | CusetTo context -> context

  | Cuprovide that -> context_merge prev that
  | CuprovideService (key, value) -> context_add prev key value

(* `HooksAgree` (`:1030`): a `Prop` over an interp; `Deep.Layer.interp` satisfies it by `rfl`.
   The avatar's interp has no context hooks yet (Q6). *)

(* ------------------------------------------- the projection onto the wire (W1-1) *)

(* `Val` → the avatar's wire `value`: the map is not injective (report row W1-1). *)
let rec wire_of_val : val_ -> value = function
  | Cvunit -> Vunit
  | Cvnat n -> Vnat n
  | Cvbool b -> Vbool b
  | Cvfiber id -> Vhandle (handle_index "fiber" id)
  | Cvfibers ids -> Vlist (List.map (fun id -> Vhandle (handle_index "fiber" id)) ids)
  | CvscopeHandle scope -> Vhandle (handle_index "layerScope" scope)
  | CvmemoMap id -> Vhandle (handle_index "memoMap" id)
  | Cvpromise cell -> Vhandle (handle_index "deferred" cell)
  | Cvpair (a, b) -> Vpair (wire_of_val a, wire_of_val b)
  | CvexitOk v -> Vsome (wire_of_val v)
  | CvexitErr _ -> Vnone
  | CvexitNil -> Vlist []
  | CvexitCons (h, t) -> (
    match wire_of_val t with Vlist rest -> Vlist (wire_of_val h :: rest) | other -> Vlist [ wire_of_val h; other ])
  | CvctxNil -> Vlist []
  | CvctxCons (key, v, rest) -> (
    match wire_of_val rest with
    | Vlist tail -> Vlist (Vpair (Vpair (Vnat key.name, Vnat key.service), wire_of_val v) :: tail)
    | other -> Vlist [ Vpair (Vpair (Vnat key.name, Vnat key.service), wire_of_val v); other ])
