#!/usr/bin/env python3
"""Seat F1: the census join as data.

`Test/Audit/RuntimeCoverage.lean` joins every census row to the Lean theorems that
witness it. This extracts the rows that name an `Effect4.Machine.*` witness -- a clause of
`src/Effect4/Machine/Clauses.lean`, a store clause of `Stores.lean`, a layer clause of
`Layer.lean` or a witness theorem of `Witnesses.lean` -- and renders them as the OCaml
module `deep_census.ml`, one record per row, in the row order of the Lean file. The
avatar's clause report reads the join back from that module, so the OCaml model inherits
the Lean model's coverage structure rather than restating it.

    extract-census.py            # print the module
    extract-census.py --check    # diff against deep_census.ml, exit 1 on drift
    extract-census.py --write    # rewrite deep_census.ml

The witness namespace is checked with the report. Inline comments between row fields
are accepted, and every row must parse; a partial extraction is a failure.
"""
import re, sys, os
here = os.path.dirname(os.path.abspath(__file__))
# <repo>/ocaml/avatar -> <repo>. The estate lived under `workshop/OCaml5/` until
# 2026-09-04, and the census file was `Effect4Test/Audit/` before "Prod cleanup 4".
repo = os.path.abspath(os.path.join(here, '..', '..'))
census = os.path.join(repo, 'Test', 'Audit', 'RuntimeCoverage.lean')
if not os.path.exists(census):
    sys.exit('no census file at %s' % census)
src = open(census, encoding='utf-8').read()
start = src.index('private def censusRows')
body = src[start:]
rows = re.findall(
    r'\{ id := "([^"]+)", kind := "([^"]+)", disposition := "([^"]+)", coverage := "([^"]+)"'
    r'(?:\s|--[^\n]*\n)*,\s*witnesses :=\s*\[(.*?)\]\s*\}', body, re.S)
total = len(rows)
declared = re.findall(r'\{ id := "([^"]+)"', body)
if [row[0] for row in rows] != declared:
    sys.exit('FAIL census extraction: not every declared row parsed in source order')
out = []
out.append('(* Generated by extract-census.py from `Test/Audit/RuntimeCoverage.lean`'
           ' (`censusRows`). Do not edit.')
out.append('   One record per census row that names an `Effect4.Machine.*` witness, in the Lean row order:')
out.append('   the row id, its kind, its disposition, its coverage, and the Deep witnesses it joins to')
out.append('   (`Clauses.lean` clauses, `Stores.lean`/`Layer.lean` clauses, `Witnesses.lean` theorems).')
out.append('   `deep_clauses.ml` and `deep_witnesses.ml` read the join back from here. *)')
out.append('')
out.append('type row = { id : string; kind : string; disposition : string; coverage : string; deep : string list }')
out.append('')
out.append('let rows : row list =')
out.append('  [')
kept = 0
for rid, kind, disp, cov, ws in rows:
    names = re.findall(r'w `([A-Za-z0-9_.\'?]+)', ws)
    deep = [n for n in names if n.startswith('Effect4.Machine.')]
    if not deep:
        continue
    kept += 1
    out.append(f'    {{ id = "{rid}"; kind = "{kind}"; disposition = "{disp}"; coverage = "{cov}";')
    out.append('      deep =')
    out.append('        [ ' + ';\n          '.join(f'"{n}"' for n in deep) + ' ] };')
out.append('  ]')
out.append('')
out.append(f'(* {kept} of the {total} census rows name a Deep witness. *)')
out.append(f'let rows_total : int = {total}')
text = '\n'.join(out) + '\n'
target = os.path.join(here, 'deep_census.ml')
mode = sys.argv[1] if len(sys.argv) > 1 else ''
if mode == '--write':
    open(target, 'w', encoding='utf-8', newline='\n').write(text); print(f'{target}: REWRITTEN ({kept} rows)')
elif mode == '--check':
    have = open(target, encoding='utf-8', newline='').read() if os.path.exists(target) else ''
    if have == text:
        print(f'{target}: IDENTICAL to RuntimeCoverage.lean ({kept} of {total} rows)')
    else:
        import difflib
        print(f'{target}: DIFFERS from RuntimeCoverage.lean')
        for line in difflib.unified_diff(have.splitlines(), text.splitlines(), 'avatar', 'lean', lineterm=''):
            print('    ' + line)
        sys.exit(1)
else:
    sys.stdout.write(text)
