(* The `Refs`, `ERefs`, `Deferreds` and `Scopes` families, transcribed from
   `harness/trace/{ref,deferred,scope}-fixture.ts` (themselves generated by
   `harness/trace/Generate.lean`). Round three of spike A0.

   Every program is the same sequence of service calls the TypeScript fixture makes; the
   handlers are the avatar's `RunInterp.syncState` arms over the three S2 stores. *)

open Deep_fibers
open Deep_stores
open Deep_layer

let handle = function Vhandle h -> h | _ -> failwith "not a handle"
let nat = function Vnat n -> n | _ -> failwith "not a nat"

(* ---------------------------------------------------------------- Refs / ERefs *)

let ref_make n = Effect.perform (Op_store (Rref_make n))
let ref_get r = Effect.perform (Op_store (Rref_get (handle r)))
let ref_set r v = ignore (Effect.perform (Op_store (Rref_set (handle r, v))))
let ref_update r a = ignore (Effect.perform (Op_store (Rref_update (handle r, a))))
let ref_modify r a = Effect.perform (Op_store (Rref_modify (handle r, a)))
let ref_get_and_set r v = Effect.perform (Op_store (Rref_get_and_set (handle r, v)))
let ref_try_take r a = Effect.perform (Op_store (Rref_try_take (handle r, a)))

(* `Generate.lean` lowers each program at its own `n`; the ref family is lowered at 7 and
   each deferred program at the value its golden's first request row carries. *)
let n0 = 7

let ref_make_get () =
  let r = ref_make n0 in
  ref_get r

let ref_set_get () =
  let r = ref_make n0 in
  ref_set r 9;
  ref_get r

let ref_update_twice () =
  let r = ref_make n0 in
  ref_update r 1;
  ref_update r 1;
  ref_get r

let ref_modify_old () =
  let r = ref_make n0 in
  let before = ref_modify r 5 in
  ignore (ref_get r);
  before

let ref_get_and_set_old () =
  let r = ref_make n0 in
  let before = ref_get_and_set r 100 in
  ignore (ref_get r);
  before

let ref_two_refs () =
  let a = ref_make n0 in
  let b = ref_make (n0 + 1) in
  ref_set a 0;
  ignore (ref_get b);
  ref_update b 1;
  ignore (ref_get a);
  ref_get b

let ref_take_underflow () =
  let r = ref_make n0 in
  ignore (ref_try_take r 2);
  ignore (ref_try_take r 9);
  ref_get r

(* ---------------------------------------------------------------- Deferreds *)

let def_make () = Effect.perform (Op_store Rdef_make)
let def_succeed d v = Effect.perform (Op_store (Rdef_succeed (handle d, v)))
let def_fail d e = Effect.perform (Op_store (Rdef_fail (handle d, e)))
let def_is_done d = Effect.perform (Op_store (Rdef_is_done (handle d)))
let def_poll d = Effect.perform (Op_store (Rdef_poll (handle d)))
let def_await_value d = Effect.perform (Op_store (Rdef_await_value (handle d)))
let def_await_error d = Effect.perform (Op_store (Rdef_await_error (handle d)))

(* The pure atoms of `harness/trace/atoms.ts`. *)
let flag_to_nat = function Vbool true -> Vnat 1 | _ -> Vnat 0
let poll_value = function Vsome (Vpair (Vbool true, v)) -> v | _ -> Vnat 0
let add_nat a b = Vnat (nat a + nat b)

let deferred_succeed_await n () =
  let d = def_make () in
  ignore (def_succeed d n);
  def_await_value d

let deferred_fail_await n () =
  let d = def_make () in
  ignore (def_fail d n);
  def_await_error d

let deferred_double_complete n () =
  let d = def_make () in
  ignore (def_succeed d n);
  let again = def_succeed d 9 in
  flag_to_nat again

let deferred_poll_pending n () =
  let d = def_make () in
  ignore (def_poll d);
  ignore (def_succeed d n);
  let after = def_poll d in
  poll_value after

let deferred_two_handles n () =
  let a = def_make () in
  let b = def_make () in
  ignore (def_succeed a n);
  ignore (def_fail b 3);
  let x = def_await_value a in
  let y = def_await_error b in
  add_nat x y

let deferred_pending_await n () =
  ignore n;
  let d = def_make () in
  ignore (def_is_done d);
  def_await_value d

(* ---------------------------------------------------------------- Scopes *)

let scope_make () = Effect.perform (Op_store Rscope_make)
let scope_add s key = Effect.perform (Op_store (Rscope_add (handle s, key)))
let scope_remove s key = ignore (Effect.perform (Op_store (Rscope_remove (handle s, key))))
let scope_close s = Effect.perform (Op_store (Rscope_close (handle s)))

let scope_lifo () =
  let s = scope_make () in
  ignore (scope_add s 1);
  ignore (scope_add s 2);
  ignore (scope_add s 3);
  scope_close s

let scope_add_after_closed () =
  let s = scope_make () in
  ignore (scope_add s 1);
  ignore (scope_close s);
  scope_add s 2

let scope_remove_program () =
  let s = scope_make () in
  ignore (scope_add s 1);
  ignore (scope_add s 2);
  scope_remove s 1;
  scope_close s

let scope_close_twice () =
  let s = scope_make () in
  ignore (scope_add s 1);
  ignore (scope_add s 2);
  ignore (scope_close s);
  scope_close s

let ref_programs : (string * (unit -> value)) list =
  [ ("makeGet", ref_make_get); ("setGet", ref_set_get); ("updateTwice", ref_update_twice);
    ("modifyOld", ref_modify_old); ("getAndSetOld", ref_get_and_set_old);
    ("twoRefs", ref_two_refs); ("takeUnderflow", ref_take_underflow) ]

(* The `n` of each program is the one its golden's first request row carries. *)
let deferred_programs : (string * (unit -> value)) list =
  [ ("deferredSucceedAwait", deferred_succeed_await 7);
    ("deferredFailAwait", deferred_fail_await 5);
    ("deferredDoubleComplete", deferred_double_complete 4);
    ("deferredPollPending", deferred_poll_pending 6);
    ("deferredTwoHandles", deferred_two_handles 8);
    ("deferredPendingAwait", deferred_pending_await 0) ]

let scope_programs : (string * (unit -> value)) list =
  [ ("lifo", scope_lifo); ("addAfterClosed", scope_add_after_closed);
    ("remove", scope_remove_program); ("closeTwice", scope_close_twice) ]

(* ---------------------------------------------------------------- Layers *)

let layer_build k = Effect.perform (Op_store (Rlayer_build k))
let layer_provide_count base = Effect.perform (Op_store (Rlayer_provide_count base))
let layer_scope_of h = Effect.perform (Op_store (Rlayer_scope_of (handle h)))
let layer_close () = Effect.perform (Op_store Rlayer_close)

let layer_build_once () =
  ignore (layer_build 0);
  layer_provide_count 0

let layer_build_memo () =
  ignore (layer_build 0);
  ignore (layer_build 0);
  layer_provide_count 0

let layer_release_order () =
  ignore (layer_build 0);
  ignore (layer_build 1);
  layer_close ()

let layer_scoped_release () =
  let h = layer_build 2 in
  let s = layer_scope_of h in
  ignore (layer_close ());
  s

let layer_fresh_rebuild () =
  ignore (layer_build 3);
  ignore (layer_build 3);
  layer_provide_count 1

let layer_fresh_region () =
  ignore (layer_build 1);
  let h = layer_build 3 in
  layer_scope_of h

let layer_fresh_release () =
  ignore (layer_build 1);
  ignore (layer_build 3);
  layer_close ()

let layer_rebuild_after_close () =
  ignore (layer_build 0);
  ignore (layer_close ());
  ignore (layer_build 0);
  ignore (layer_close ());
  layer_provide_count 0

let layer_programs : (string * (unit -> value)) list =
  [ ("buildOnce", layer_build_once); ("buildMemo", layer_build_memo);
    ("releaseOrder", layer_release_order); ("scopedRelease", layer_scoped_release);
    ("freshRebuild", layer_fresh_rebuild); ("freshRegion", layer_fresh_region);
    ("freshRelease", layer_fresh_release); ("rebuildAfterClose", layer_rebuild_after_close) ]
