(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400018`, seed 400018, 19 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400018 () =
  let v0 = Fibers_fixture.fork_detach 0 in
  let v1 = Fibers_fixture.fork 1 in
  let _v2 = Fibers_fixture.cleanups () in
  let _v3 = Fibers_fixture.started () in
  let _v4 = Extra_fixture.interrupt_all [ v0; v1 ] in
  let _v5 = Fibers_fixture.started () in
  let v6 = Store_fixtures.scope_make () in
  ignore (Fibers_fixture.interrupt v0);
  let _v7 = Fibers_fixture.cleanups () in
  let _v8 = Fibers_fixture.started () in
  let _v9 = Fibers_fixture.fork 1 in
  let _v10 = Store_fixtures.scope_close v6 in
  let _v11 = Fibers_fixture.fork 0 in
  let _v12 = Fibers_fixture.cleanups () in
  let _v13 = Fibers_fixture.cleanups () in
  let _v14 = Fibers_fixture.fork 2 in
  let _v15 = Fibers_fixture.fork 2 in
  let _v16 = Store_fixtures.ref_make 6 in
  let v17 = Fibers_fixture.started () in
  v17

let programs : (string * (unit -> value)) list = [ ("p400018", corpus_p400018) ]
