(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400056`, seed 400056, 33 operations.
   Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400056 () =
  let v0 = Fibers_fixture.fork 3 in
  let _v1 = Fibers_fixture.join v0 in
  let v2 = Fibers_fixture.fork 3 in
  let v3 = Store_fixtures.def_make () in
  let _v4 = Fibers_fixture.started () in
  let _v5 = Fibers_fixture.started () in
  let _v6 = Store_fixtures.def_succeed v3 2 in
  let v7 = Store_fixtures.ref_make 4 in
  let _v8 = Store_fixtures.def_is_done v3 in
  let _v9 = Fibers_fixture.join v2 in
  let _v10 = Fibers_fixture.await_value v2 in
  let _v11 = Fibers_fixture.join v2 in
  let _v12 = Fibers_fixture.started () in
  let _v13 = Fibers_fixture.cleanups () in
  let _v14 = Fibers_fixture.started () in
  let _v15 = Fibers_fixture.started () in
  let v16 = Store_fixtures.scope_make () in
  let _v17 = Store_fixtures.def_make () in
  let _v18 = Fibers_fixture.await_error v0 in
  let _v19 = Store_fixtures.ref_get v7 in
  ignore (Store_fixtures.ref_update v7 1);
  let _v20 = Store_fixtures.ref_make 8 in
  let _v21 = Store_fixtures.scope_add v16 2 in
  let v22 = Store_fixtures.ref_make 6 in
  let _v23 = Extra_fixture.await_all [ v0; v2 ] in
  let v24 = Fibers_fixture.fork 2 in
  let _v25 = Fibers_fixture.await_value v2 in
  let _v26 = Fibers_fixture.join v24 in
  let _v27 = Fibers_fixture.fork_detach 1 in
  let _v28 = Fibers_fixture.await_value v2 in
  let _v29 = Store_fixtures.def_make () in
  ignore (Store_fixtures.ref_set v22 4);
  let v30 = Fibers_fixture.started () in
  v30

let programs : (string * (unit -> value)) list = [ ("p400056", corpus_p400056) ]
