(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400176`, seed 400176, 9 operations.
   Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400176 () =
  let v0 = Fibers_fixture.fork 0 in
  let _v1 = Fibers_fixture.started () in
  let _v2 = Fibers_fixture.started () in
  let _v3 = Store_fixtures.ref_make 7 in
  let _v4 = Store_fixtures.ref_make 3 in
  let _v5 = Store_fixtures.layer_build 3 in
  let _v6 = Fibers_fixture.await_error v0 in
  let _v7 = Store_fixtures.ref_make 5 in
  let v8 = Fibers_fixture.await_value v0 in
  v8

let programs : (string * (unit -> value)) list = [ ("p400176", corpus_p400176) ]
