(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400153`, seed 400153, 28 operations.
   Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400153 () =
  let v0 = Fibers_fixture.fork 3 in
  let _v1 = Fibers_fixture.cleanups () in
  ignore (Fibers_fixture.interrupt v0);
  let _v2 = Fibers_fixture.cleanups () in
  let v3 = Fibers_fixture.fork 3 in
  let _v4 = Fibers_fixture.cleanups () in
  let _v5 = Fibers_fixture.cleanups () in
  let v6 = Store_fixtures.ref_make 8 in
  ignore (Fibers_fixture.interrupt v3);
  let _v7 = Extra_fixture.interrupt_all [ v3 ] in
  ignore (Store_fixtures.ref_set v6 9);
  let v8 = Store_fixtures.scope_make () in
  let _v9 = Fibers_fixture.await_value v3 in
  let _v10 = Store_fixtures.def_make () in
  let v11 = Fibers_fixture.fork 4 in
  let _v12 = Store_fixtures.scope_add v8 1 in
  let _v13 = Fibers_fixture.await_value v0 in
  let _v14 = Store_fixtures.scope_close v8 in
  ignore (Extra_fixture.yield ());
  let _v15 = Fibers_fixture.started () in
  let v16 = Fibers_fixture.fork 0 in
  let _v17 = Fibers_fixture.started () in
  let _v18 = Store_fixtures.layer_build 0 in
  let _v19 = Store_fixtures.ref_get_and_set v6 9 in
  let _v20 = Store_fixtures.scope_add v8 4 in
  let _v21 = Fibers_fixture.await_value v16 in
  let _v22 = Store_fixtures.ref_make 1 in
  let v23 = Fibers_fixture.await_value v11 in
  v23

let programs : (string * (unit -> value)) list = [ ("p400153", corpus_p400153) ]
