import Effect4.Schema.EffectfulField
import Effect4.Codegen.Schema

/-!
# Checked TypeScript generation for effectful Schema fields

This module resolves one admitted property marker to the structured
`EffectfulFieldDecl` target node. It never stores host functions and never
uses `Decl.raw`.
-/

open TypeScript

namespace Effect4.Codegen.EffectfulField

open Effect4 Effects

/-- Target spellings associated with one retained portable operation. -/
structure OperationBinding where
  alphabet : AlphabetId
  operation : OperationId
  serviceName : String
  serviceImport : String
  methodName : String
  errorType : String
  errorImport : String

/-- Inputs needed to lower one existing annotated Schema property. -/
structure Request where
  sourceType : String
  sourceImport : String
  property : PropertySignature
  read : OperationBinding
  write : OperationBinding

private def namesReady (request : Request) (fieldName : String) : Bool :=
  [ fieldName
  , request.sourceType
  , request.read.serviceName
  , request.read.methodName
  , request.read.errorType
  , request.write.serviceName
  , request.write.methodName
  , request.write.errorType
  ].all Schema.targetIdentifier

private def importsReady (request : Request) : Bool :=
  [ request.sourceImport
  , request.read.serviceImport
  , request.read.errorImport
  , request.write.serviceImport
  , request.write.errorImport
  ].all fun path => !path.isEmpty

private def bindingsMatch (request : Request)
    (spec : EffectfulFieldSpec) : Bool :=
  decide (request.read.alphabet = spec.alphabet) &&
    decide (request.write.alphabet = spec.alphabet) &&
    decide (request.read.operation = spec.readOperation) &&
    decide (request.write.operation = spec.writeOperation)

/-- Decide the first checked target profile: one string-keyed String property,
one exact marker, exact operation identities, and legal imported spellings. -/
def requestReady (request : Request) : Bool :=
  match request.property.name, request.property.type,
      EffectfulFieldSpec.check request.property.annotations with
  | .string fieldName, .string _ _, some spec =>
      namesReady request fieldName && importsReady request &&
        bindingsMatch request spec
  | _, _, _ => false

/-- Logical spelling of checked target admission. -/
def RequestReady (request : Request) : Prop :=
  requestReady request = true

theorem requestReady_iff (request : Request) :
    requestReady request = true <-> RequestReady request :=
  Iff.rfl

private def requestFieldName (request : Request) : String :=
  match request.property.name with
  | .string name => name
  | _ => ""

/-- Lower an admitted request to structured target syntax. -/
def decl? (request : Request) : Option Decl :=
  if requestReady request then
    match request.property.name with
    | .string fieldName =>
        some (.effectfulField
          { fieldName
            sourceType := request.sourceType
            fieldType := "string"
            readService := request.read.serviceName
            readMethod := request.read.methodName
            readError := request.read.errorType
            writeService := request.write.serviceName
            writeMethod := request.write.methodName
            writeError := request.write.errorType })
    | _ => none
  else none

private def distinctBindings (bindings : List (String × String)) :
    List (String × String) :=
  bindings.eraseDups

/-- Assemble the complete Effect v4 target module with deterministic exact
import deduplication. -/
def module? (request : Request) : Option Module := do
  let declaration ← decl? request
  let serviceImports := distinctBindings
    [ (request.read.serviceName, request.read.serviceImport)
    , (request.write.serviceName, request.write.serviceImport) ]
  let typeImports := distinctBindings
    [ (request.sourceType, request.sourceImport)
    , (request.read.errorType, request.read.errorImport)
    , (request.write.errorType, request.write.errorImport) ]
  pure
    { header := ["Generated by Effect4 effectful Schema fields.", "", "Do not edit."]
      imports :=
        [Import.named ["Effect", "Optic"] "effect"] ++
          (serviceImports.map fun binding => Import.named [binding.1] binding.2) ++
          (typeImports.map fun binding => Import.types [binding.1] binding.2)
      decls := [declaration] }

private def directionalRowsPresent (request : Request) (source : String) : Bool :=
  source.contains
      ("Effect.Services<ReturnType<typeof " ++ requestFieldName request ++ ".get>>") &&
    (source.contains
        ("Effect.Services<ReturnType<typeof " ++ requestFieldName request ++
          ".replace>>") &&
      source.contains
        (request.read.errorType ++ " | " ++ request.write.errorType))

/-- Render only modules whose emitted directional type receipts are present. -/
def source? (request : Request) (style : Style) : Option String := do
  let target ← module? request
  let source := Render.module style target
  if directionalRowsPresent request source then some source else none

/-- High-level checked generation alias. -/
def generate? (request : Request) (style : Style) : Option String :=
  source? request style

theorem decl?_never_raw {request : Request} {declaration : Decl}
    (lowered : decl? request = some declaration) :
    ∀ text, declaration != Decl.raw text := by
  by_cases ready : requestReady request
  · cases keyEq : request.property.name with
    | string fieldName =>
        simp [decl?, ready, keyEq] at lowered
        subst declaration
        intro text
        rfl
    | number value => simp [decl?, ready, keyEq] at lowered
    | globalSymbol value => simp [decl?, ready, keyEq] at lowered
  · simp [decl?, ready] at lowered

/-- Successful rendering exposes the directional service and error rows used
by the host and language-service gates. -/
theorem source_contains_directional_rows
    (fieldName readError writeError : String)
    {request : Request} {style : Style} {source : String}
    (generated : source? request style = some source)
    (fieldName_eq : request.property.name = .string fieldName)
    (readError_eq : request.read.errorType = readError)
    (writeError_eq : request.write.errorType = writeError) :
    source.contains
      ("Effect.Services<ReturnType<typeof " ++ fieldName ++ ".get>>") = true /\
    source.contains
      ("Effect.Services<ReturnType<typeof " ++ fieldName ++
        ".replace>>") = true /\
    source.contains
      (readError ++ " | " ++ writeError) = true := by
  unfold source? at generated
  cases moduleResult : module? request with
  | none => simp [moduleResult] at generated
  | some target =>
      simp only [moduleResult] at generated
      by_cases present : directionalRowsPresent request (Render.module style target)
      · simp [present] at generated
        cases generated
        unfold directionalRowsPresent at present
        have requestFieldName_eq : requestFieldName request = fieldName := by
          unfold requestFieldName
          rw [fieldName_eq]
        simp only [Bool.and_eq_true] at present
        rw [requestFieldName_eq, readError_eq, writeError_eq] at present
        exact present
      · simp [present] at generated

end Effect4.Codegen.EffectfulField
