import Effect4.Codegen.Emit

/-!
# Codegen.Entities — the constructor module of a domain, references before referrers

Rule `surface.entity.constructor` (`Rule.entityConstructor`), the `entities.generated.ts` of
the Surface plan's §13.4 and the module every other TypeScript artefact imports its entity
constants from (`import { User, NotFound } from "./entities.generated"`). This is the row
`Effect4/Surface/Entity.lean` records as owed: the persisted-document module needs no order
because each document carries its own references table, while a constant that names another
constant must come after it.

One `export const <Name> = <constructor spelling>` per entity, in a Kahn order: an entity is
emitted once every entity it refers to has been, ties broken by declaration order, so the
order is a function of the rows. A cycle, including a self-reference, has no such order and
is `referenceCycle`; rc.112 spells recursion with `Schema.suspend`, which the constructor
spelling refuses by name (`schema.suspend`), so this module never smuggles one in.

| | |
| --- | --- |
| Carrier | none of its own: `Domain` is `Surface/Entity.lean`'s, `TypeScript.Module` the target package's |
| Operations | `dependencies`, `order`, `entityDecl`, `module`; the `Emit .entityConstructor` instance |
| Laws | `order_length` is owed; `order_nodup` is owed. The receipts are the `#guard`s below |
| Structure | a topological sort over the reference graph, then one spelling per node |
| Payoff | `api.generated.ts` and `mcp.generated.ts` import a module that exists and typechecks with the field types they need |
| Anti-vacuity | the `shop` fixture: `Address` before `User`; a self-referencing entity refused by name; an unspellable property refused by name with its site |
| Generation | this module *is* generation |
-/

set_option autoImplicit false

namespace Effect4.Codegen.Entities

open Effect4 Effect4.Schema Effect4.Surface Effect4.Codegen
open TypeScript (Expr Decl Module)

/-- The rule this module implements. -/
def rule : Rule := .entityConstructor

/-- The entities an entity refers to, syntactically, without repeats. -/
def dependencies (entity : Entity) : List String :=
  dedupe [] (referenceKeys 64 entity.rep)

/-- One round of the Kahn walk: the pending entities whose dependencies are all emitted. -/
def ready (emitted : List String) (pending : List Entity) : List Entity :=
  pending.filter fun entity => (dependencies entity).all emitted.contains

/-- The walk, fuel-bounded by the number of entities: every round emits at least one entity
or stops on a cycle. -/
def orderFuel : Nat → List Entity → List Entity → Except Refusal (List Entity)
  | _, [], done => .ok done
  | 0, pending, _ => .error (.referenceCycle rule.id ((pending.head?.map Entity.name).getD ""))
  | fuel + 1, pending, done =>
    let emitted := done.map Entity.name
    match ready emitted pending with
    | [] => .error (.referenceCycle rule.id ((pending.head?.map Entity.name).getD ""))
    | next =>
      orderFuel fuel (pending.filter fun entity => !(next.any (·.name == entity.name)))
        (done ++ next)

/-- The entities of a domain, references before referrers, or the first entity of a cycle. -/
def order (dom : Domain) : Except Refusal (List Entity) :=
  orderFuel dom.entities.length dom.entities []

/-- The doc comment of an entity: its `description`, which a well-formed entity has. -/
def docLines (entity : Entity) : List String :=
  match Representation.descriptionOf entity.rep with
  | some text => [text]
  | none => []

/-- `export const <Name> = <spelling>`, the spelling's refusal addressed to this rule and the
entity. -/
def entityDecl (dom : Domain) (entity : Entity) : Except Refusal Decl :=
  (addressed rule.id entity.name (Spell.spell dom.refs entity.rep)).map fun spelled =>
    .const { doc := docLines entity, name := entity.name, value := spelled }

/--
The constructor module of a domain.

`none` is never an answer: the domain's own refusal when it is not well formed, a
`referenceCycle` when no order exists, or the constructor spelling's refusal for one entity,
addressed to that entity.

surface: rule.surface.entity.constructor
-/
def module (dom : Domain) : Except Refusal Module := do
  let _ ← Domain.check dom
  let ordered ← order dom
  let decls ← traverse (entityDecl dom) ordered
  .ok
    { header := ["Generated by Effect4 Surface.", "", "Do not edit."]
      imports := [.all "Schema" "effect/Schema"]
      decls := decls }

instance : Emit .entityConstructor := ⟨module⟩

/-! ## Anti-vacuity: the `shop` fixture -/

#guard (order shopDomain).map (·.map Entity.name) == .ok ["Address", "User"]

-- the same order whichever way the domain declares them
#guard (order { shopDomain with entities := [userEntity, addressEntity] }).map (·.map Entity.name) ==
  .ok ["Address", "User"]

-- the module builds, imports `Schema` only, and binds each entity once, in that order
#guard (module shopDomain).toOption.map (fun target => target.decls.length) == some 2
#guard ((module shopDomain).toOption.map fun target =>
    target.decls.map fun declaration =>
      match declaration with
      | .const c => c.name
      | _ => "") == some ["Address", "User"]
#guard ((module shopDomain).toOption.map fun target =>
    target.imports.map (TypeScript.Render.import_ TypeScript.house0)) ==
  some ["import * as Schema from \"effect/Schema\"\n"]

-- the rendered constant of the referenced entity, byte for byte (a property's description
-- lives on its signature, not on its type, so the field types carry no `.annotate`)
#guard ((module shopDomain).toOption.bind fun target =>
    target.decls.head?.map (TypeScript.Render.decl TypeScript.house0)) ==
  some ("/** A postal address. */\nexport const Address = Schema.Struct({ \"street\": Schema.String, " ++
    "\"city\": Schema.String }).annotate({ \"identifier\": \"Address\", \"description\": \"A postal address.\" })\n")

-- a self-reference is a cycle, named
private def loopEntity : Entity :=
  { name := "Loop"
    domain := "loop"
    rep := Representation.describe "A loop." (Representation.identify "Loop"
      (Schema.struct [PropertySignature.describe "next" (Schema.property "next" (Schema.reference "Loop"))]))
    key := ["next"] }

#guard (order { name := "loop", entities := [loopEntity] }).toOption.isNone
#guard (order { name := "loop", entities := [loopEntity] }) ==
  .error (.referenceCycle "surface.entity.constructor" "Loop")

-- an ill-formed domain answers its own refusal, unwrapped
#guard refusal? (module { shopDomain with entities := [userEntity] }) ==
  some (.referenceUnresolved "User" "Address")

-- a well-formed entity whose property the spelling cannot lower is refused by shape, at its site
private def suspendedEntity : Entity :=
  { addressEntity with
    name := "Suspended"
    rep := Representation.describe "Suspended." (Representation.identify "Suspended"
      (Schema.struct [PropertySignature.describe "self" (Schema.property "self"
        (Schema.suspend Schema.string))])) }

#guard Entity.check { name := "shop", entities := [suspendedEntity], active := true }
  { suspendedEntity with key := ["self"] } == .ok ()
#guard refusal? (module { name := "shop", entities := [{ suspendedEntity with key := ["self"] }], active := true }) ==
  some (.refusedShape "surface.entity.constructor" "schema.suspend" "Suspended")

end Effect4.Codegen.Entities
