/**
 * Generated by Effect4 Schema.
 *
 * Do not edit.
 */
import * as Schema from "effect/Schema"
import * as SchemaRepresentation from "effect/SchemaRepresentation"

/** Raw Effect Schema document. */
export const AllRepresentationsSchemaJson: Schema.Json = {
  "representation": { "_tag": "String", "checks": [] },
  "references": {
    "case/Declaration": {
      "_tag": "Declaration",
      "representation": { "id": "effect4/schema/declaration", "payload": null },
      "typeParameters": [{ "_tag": "String", "checks": [] }],
      "checks": [
        {
          "_tag": "Filter",
          "representation": {
            "id": "effect/schema/isTrimmed",
            "payload": null,
            "schemas": [{ "_tag": "String", "checks": [] }],
          },
          "aborted": false,
        },
        {
          "_tag": "FilterGroup",
          "representation": {
            "id": "effect/schema/isTrimmed",
            "payload": null,
            "schemas": [{ "_tag": "String", "checks": [] }],
          },
          "annotations": Object.fromEntries([["__proto__", "annotation"]]),
          "checks": [
            {
              "_tag": "Filter",
              "representation": { "id": "effect/schema/isTrimmed", "payload": null },
              "aborted": false,
            },
          ],
        },
      ],
    },
    "case/Reference": { "_tag": "Reference", "$ref": "StringRef" },
    "case/Suspend": {
      "_tag": "Suspend",
      "checks": [],
      "thunk": { "_tag": "Reference", "$ref": "StringRef" },
    },
    "case/Null": { "_tag": "Null", "checks": [] },
    "case/Undefined": { "_tag": "Undefined", "checks": [] },
    "case/Void": { "_tag": "Void", "checks": [] },
    "case/Never": { "_tag": "Never", "checks": [] },
    "case/Unknown": { "_tag": "Unknown", "checks": [] },
    "case/Any": { "_tag": "Any", "checks": [] },
    "case/String": { "_tag": "String", "checks": [] },
    "case/Number": { "_tag": "Number", "checks": [] },
    "case/Boolean": { "_tag": "Boolean", "checks": [] },
    "case/BigInt": { "_tag": "BigInt", "checks": [] },
    "case/Symbol": { "_tag": "Symbol", "checks": [] },
    "case/Literal": {
      "_tag": "Literal",
      "checks": [],
      "literal": { "type": "number", "value": new DataView(Uint8Array.of(128, 0, 0, 0, 0, 0, 0, 0).buffer).getFloat64(0, false) },
    },
    "case/UniqueSymbol": {
      "_tag": "UniqueSymbol",
      "checks": [],
      "symbol": "Symbol(effect4/global-symbol)",
    },
    "case/ObjectKeyword": { "_tag": "ObjectKeyword", "checks": [] },
    "case/Enum": {
      "_tag": "Enum",
      "checks": [],
      "enums": [["word", { "type": "string", "value": "word" }], ["not-a-number", { "type": "number", "value": "NaN" }]],
    },
    "case/TemplateLiteral": {
      "_tag": "TemplateLiteral",
      "checks": [],
      "parts": [
        {
          "_tag": "Literal",
          "checks": [],
          "literal": { "type": "string", "value": "prefix" },
        },
        {
          "_tag": "Literal",
          "checks": [],
          "literal": { "type": "number", "value": new DataView(Uint8Array.of(0, 0, 0, 0, 0, 0, 0, 0).buffer).getFloat64(0, false) },
        },
        {
          "_tag": "Literal",
          "checks": [],
          "literal": { "type": "bigint", "value": "42" },
        },
        {
          "_tag": "Literal",
          "checks": [],
          "literal": { "type": "boolean", "value": true },
        },
      ],
    },
    "case/Arrays": {
      "_tag": "Arrays",
      "checks": [],
      "elements": [
        {
          "isOptional": false,
          "type": { "_tag": "String", "checks": [] },
        },
      ],
      "rest": [{ "_tag": "Number", "checks": [] }],
    },
    "case/Objects": {
      "_tag": "Objects",
      "checks": [],
      "propertySignatures": [
        {
          "name": { "type": "symbol", "value": "Symbol(effect4/property-key)" },
          "type": { "_tag": "Boolean", "checks": [] },
          "isOptional": false,
          "isMutable": false,
          "annotations": Object.fromEntries([["__proto__", "property-annotation"]]),
        },
      ],
      "indexSignatures": [{ "parameter": { "_tag": "String", "checks": [] }, "type": { "_tag": "Unknown", "checks": [] } }],
    },
    "case/Union": {
      "_tag": "Union",
      "checks": [],
      "types": [
        { "_tag": "String", "checks": [] },
        {
          "_tag": "Union",
          "checks": [],
          "types": [{ "_tag": "Number", "checks": [] }, { "_tag": "Boolean", "checks": [] }],
          "mode": "oneOf",
        },
      ],
      "mode": "anyOf",
    },
    "StringRef": { "_tag": "String", "checks": [] },
  },
}

/** Effect Schema document decoded from the generated raw value. */
export const AllRepresentationsSchema: SchemaRepresentation.Document = SchemaRepresentation.fromJson(AllRepresentationsSchemaJson)
