// cut-from: rev=ae9b493-dirty toolchain=4.33.1 inputs=a6cd936439ee01d4125d7efe9c33788d912d2d17f45e635f6e93faf003607734
/**
 * Generated by Effect4 Schema.
 *
 * Do not edit.
 */
import * as Schema from "effect/Schema"

/** Raw Effect Schema multi-root document. */
export const TwoRootsSchemaJson: Schema.Json = {
  "representations": [{ "_tag": "String", "checks": [] }, { "_tag": "Boolean", "checks": [] }],
  "references": { "shared": { "_tag": "Number", "checks": [] } },
}
