(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400082`, seed 400082, 35 operations.
   Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400082 () =
  let v0 = Fibers_fixture.fork_detach 2 in
  let _v1 = Fibers_fixture.started () in
  let _v2 = Fibers_fixture.cleanups () in
  let _v3 = Fibers_fixture.started () in
  let _v4 = Fibers_fixture.started () in
  let _v5 = Fibers_fixture.cleanups () in
  let _v6 = Extra_fixture.await_all [ v0 ] in
  let _v7 = Store_fixtures.layer_build 0 in
  let v8 = Fibers_fixture.fork 1 in
  let v9 = Fibers_fixture.fork 0 in
  ignore (Fibers_fixture.interrupt v0);
  let _v10 = Fibers_fixture.await_error v0 in
  let _v11 = Fibers_fixture.join v0 in
  let _v12 = Fibers_fixture.started () in
  let v13 = Fibers_fixture.fork 3 in
  let _v14 = Fibers_fixture.cleanups () in
  ignore (Fibers_fixture.interrupt v8);
  let _v15 = Store_fixtures.def_make () in
  let _v16 = Store_fixtures.layer_provide_count 3 in
  let _v17 = Fibers_fixture.join v0 in
  let _v18 = Extra_fixture.interrupt_all [ v8 ] in
  let _v19 = Extra_fixture.interrupt_all [ v0; v8; v9; v13 ] in
  let _v20 = Store_fixtures.scope_make () in
  let v21 = Fibers_fixture.fork 0 in
  let _v22 = Fibers_fixture.started () in
  let _v23 = Extra_fixture.await_all [ v21 ] in
  let _v24 = Extra_fixture.await_all [ v0; v8; v9; v13; v21 ] in
  let _v25 = Fibers_fixture.cleanups () in
  let _v26 = Fibers_fixture.started () in
  ignore (Fibers_fixture.interrupt v21);
  let _v27 = Fibers_fixture.await_value v0 in
  let _v28 = Store_fixtures.def_make () in
  let _v29 = Fibers_fixture.started () in
  let _v30 = Store_fixtures.layer_build 0 in
  let v31 = Fibers_fixture.join v0 in
  v31

let programs : (string * (unit -> value)) list = [ ("p400082", corpus_p400082) ]
