(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400200`, seed 400200, 33 operations.
   Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400200 () =
  let v0 = Fibers_fixture.fork 1 in
  let _v1 = Fibers_fixture.await_value v0 in
  let _v2 = Fibers_fixture.cleanups () in
  let v3 = Fibers_fixture.fork 4 in
  let _v4 = Fibers_fixture.join v0 in
  let _v5 = Fibers_fixture.cleanups () in
  let _v6 = Fibers_fixture.join v3 in
  let _v7 = Store_fixtures.layer_build 0 in
  let _v8 = Fibers_fixture.cleanups () in
  let _v9 = Fibers_fixture.fork 3 in
  let v10 = Store_fixtures.scope_make () in
  ignore (Store_fixtures.scope_remove v10 1);
  let v11 = Fibers_fixture.fork_detach 4 in
  let _v12 = Extra_fixture.interrupt_all [ v0 ] in
  ignore (Extra_fixture.yield ());
  let v13 = Fibers_fixture.fork 1 in
  ignore (Fibers_fixture.interrupt v11);
  let _v14 = Fibers_fixture.cleanups () in
  let _v15 = Fibers_fixture.cleanups () in
  let v16 = Store_fixtures.ref_make 9 in
  let _v17 = Store_fixtures.ref_make 2 in
  let _v18 = Store_fixtures.layer_build 3 in
  let _v19 = Fibers_fixture.cleanups () in
  let _v20 = Fibers_fixture.cleanups () in
  ignore (Fibers_fixture.interrupt v13);
  let _v21 = Fibers_fixture.join v11 in
  let _v22 = Store_fixtures.scope_add v10 2 in
  let _v23 = Store_fixtures.ref_get v16 in
  ignore (Fibers_fixture.interrupt v3);
  let _v24 = Store_fixtures.ref_make 4 in
  let _v25 = Fibers_fixture.join v3 in
  let _v26 = Fibers_fixture.fork_detach 1 in
  let v27 = Fibers_fixture.started () in
  v27

let programs : (string * (unit -> value)) list = [ ("p400200", corpus_p400200) ]
