import Effect4.Evidence.Char.Conformance.VectorSet

/-!
# Conformance.Compose: the product machine and the injection of a part's vectors

Owner: how vector sets compose. Two components compose as the **product**
machine (disjoint parallel composition: a label of either side moves that side
alone), and each part's vectors inject into the product's, provably sound
(`injectL_sound`) and monotone (`injectL_mono`). So assembling components
re-runs nothing: the parts' evidence lifts.

Where it sits in the semantic compiler: **linking**. What it makes mechanical:
the lift of a part's vectors into an assembly, which is otherwise a re-run per
assembly.

## What does not compose, said plainly

The product is the composition with **no communication**. A usage edge in
`05-registry/04-usage-edges.md`, where `Stream.fromQueue` calls `Queue.takeAll`,
is a *coupling*: the user's word drives the used component's word through a map
the product does not have. The theorem that would carry a part's grade across
that seam is `hagree` (`05-registry/05-composite-grades.md`, statement (C)): a
reading morphism `φ : L₀ → List L₁` under which the user's reading factors
through the used one. It does not exist, and nothing here pretends to it. Until
it is a named theorem in the environment, the composite claim is a HELD row
whose residual names `hagree`, and the composite grade is an upper bound only.
Interleaved words of the product (labels of both sides mixed) are also not
generated by injection; they are the product's own enumeration, and whether
they say anything about the coupled system is exactly the `hagree` question.

## The algebra

| | |
| --- | --- |
| Carrier | `Machine.prod M₁ M₂ : Machine (S₁ × S₂) (L₁ ⊕ L₂)`, `Reading.prod`, `Fact.inl`, `injectL` |
| Operations | `injWord`, `Fact.inl`, `injectL` |
| Laws | `Machine.run_prod_inl` (the injection is a homomorphism of the action), `Reading.prod_acc_inl`, `Reading.prod_del_inl`, `factOf_prod_inl`, `injectL_mono`, `injectL_sound` |
| Structure | the product of two labelled transition systems; `injWord` is the monoid homomorphism `List L₁ → List (L₁ ⊕ L₂)` induced by `Sum.inl`, and `run_prod_inl` is the statement that the product's action restricts along it to the left action |
| Payoff | deletes the re-run of each part's vectors when parts are assembled |
| Anti-vacuity | `Conformance/Cell.lean` injects the cell's set into the cell-times-cell product and shows the count is preserved |
| Generation | mechanical |
-/

set_option autoImplicit false

namespace Effect4.Char

section Composition

variable {S₁ S₂ L₁ L₂ C₁ C₂ : Type}

/-- The product of two machines: disjoint parallel composition, no communication.
A label of either side moves that side's state alone. -/
def Machine.prod (M₁ : Machine S₁ L₁) (M₂ : Machine S₂ L₂) : Machine (S₁ × S₂) (L₁ ⊕ L₂) where
  init := (M₁.init, M₂.init)
  step := fun s l =>
    match l with
    | .inl l₁ => (M₁.step s.1 l₁).map fun s₁ => (s₁, s.2)
    | .inr l₂ => (M₂.step s.2 l₂).map fun s₂ => (s.1, s₂)

/-- A word of the left part, injected. -/
def injWord (w : List L₁) : List (L₁ ⊕ L₂) := w.map Sum.inl

/-- A left label steps the left part. -/
theorem Machine.prod_step_inl (M₁ : Machine S₁ L₁) (M₂ : Machine S₂ L₂) (s₁ : S₁) (s₂ : S₂)
    (l : L₁) : (M₁.prod M₂).step (s₁, s₂) (Sum.inl l) = (M₁.step s₁ l).map fun t => (t, s₂) := rfl

/-- **The injection is a homomorphism of the action**: running an injected word
on the product runs the word on the left part and leaves the right alone. -/
theorem Machine.run_prod_inl (M₁ : Machine S₁ L₁) (M₂ : Machine S₂ L₂) (s₁ : S₁) (s₂ : S₂)
    (w : List L₁) :
    (M₁.prod M₂).run (s₁, s₂) (injWord w) = (M₁.run s₁ w).map fun t => (t, s₂) := by
  induction w generalizing s₁ with
  | nil => rfl
  | cons l w ih =>
    rw [show injWord (l :: w) = Sum.inl l :: injWord w from rfl, Machine.run_cons, Machine.run_cons,
      Machine.prod_step_inl]
    cases M₁.step s₁ l with
    | none => rfl
    | some t => exact ih t

/-- The product reading: each side reads its own labels, clients are tagged by side. -/
def Reading.prod [DecidableEq C₁] [DecidableEq C₂] (R₁ : Reading S₁ L₁ C₁)
    (R₂ : Reading S₂ L₂ C₂) : Reading (S₁ × S₂) (L₁ ⊕ L₂) (C₁ ⊕ C₂) where
  accepts := fun l =>
    match l with
    | .inl l₁ => (R₁.accepts l₁).map fun p => (Sum.inl p.1, p.2)
    | .inr l₂ => (R₂.accepts l₂).map fun p => (Sum.inr p.1, p.2)
  emits := fun l =>
    match l with
    | .inl l₁ => (R₁.emits l₁).map fun p => (Sum.inl p.1, p.2)
    | .inr l₂ => (R₂.emits l₂).map fun p => (Sum.inr p.1, p.2)
  residue := fun s c =>
    match c with
    | .inl c₁ => R₁.residue s.1 c₁
    | .inr c₂ => R₂.residue s.2 c₂

theorem Reading.prod_acc_inl [DecidableEq C₁] [DecidableEq C₂] (R₁ : Reading S₁ L₁ C₁)
    (R₂ : Reading S₂ L₂ C₂) (c : C₁) (w : List L₁) :
    (R₁.prod R₂).acc (Sum.inl c) (injWord w) = R₁.acc c w := by
  induction w with
  | nil => rfl
  | cons l w ih =>
    have hstep : ((R₁.prod R₂).accepts (Sum.inl l)).bind (Reading.forClient (Sum.inl c)) =
        (R₁.accepts l).bind (Reading.forClient c) := by
      simp only [Reading.prod]
      cases R₁.accepts l with
      | none => rfl
      | some p =>
        simp only [Option.map_some, Option.bind_some, Reading.forClient]
        by_cases h : p.1 = c
        · simp [h]
        · simp [h]
    simp only [injWord, List.map_cons, Reading.acc, List.filterMap_cons] at ih ⊢
    rw [hstep, ih]

theorem Reading.prod_del_inl [DecidableEq C₁] [DecidableEq C₂] (R₁ : Reading S₁ L₁ C₁)
    (R₂ : Reading S₂ L₂ C₂) (c : C₁) (w : List L₁) :
    (R₁.prod R₂).del (Sum.inl c) (injWord w) = R₁.del c w := by
  induction w with
  | nil => rfl
  | cons l w ih =>
    have hstep : ((R₁.prod R₂).emits (Sum.inl l)).filterMap (Reading.forClient (Sum.inl c)) =
        (R₁.emits l).filterMap (Reading.forClient c) := by
      simp only [Reading.prod, List.filterMap_map]
      congr 1
      funext p
      simp only [Function.comp, Reading.forClient]
      by_cases h : p.1 = c
      · simp [h]
      · simp [h]
    simp only [injWord, List.map_cons, Reading.del, List.flatMap_cons] at ih ⊢
    rw [hstep, ih]

/-- A client reading of the left part, injected. -/
def ClientReading.inl (r : ClientReading C₁) : ClientReading (C₁ ⊕ C₂) :=
  ⟨Sum.inl r.client, r.acc, r.del, r.residue⟩

/-- A fact of the left part, injected. -/
def Fact.inl (f : Fact L₁ C₁) : Fact (L₁ ⊕ L₂) (C₁ ⊕ C₂) :=
  ⟨injWord f.word, f.accept, f.readings.map ClientReading.inl⟩

/-- **Soundness of the injection.** The product's fact for an injected word is the
injection of the part's fact. So a part's vectors are the product's vectors. -/
theorem factOf_prod_inl [DecidableEq C₁] [DecidableEq C₂] (M₁ : Machine S₁ L₁)
    (M₂ : Machine S₂ L₂) (R₁ : Reading S₁ L₁ C₁) (R₂ : Reading S₂ L₂ C₂) (clients : List C₁)
    (w : List L₁) :
    factOf (M₁.prod M₂) (R₁.prod R₂) (clients.map Sum.inl) (injWord w) =
      (factOf M₁ R₁ clients w).inl := by
  unfold factOf
  rw [show (M₁.prod M₂).init = (M₁.init, M₂.init) from rfl, Machine.run_prod_inl]
  cases M₁.run M₁.init w with
  | none => rfl
  | some s =>
    simp only [Option.map_some, Fact.inl, List.map_map]
    congr 2
    funext c
    simp only [Function.comp_apply, ClientReading.inl, Reading.prod_acc_inl, Reading.prod_del_inl]
    rfl

/-- Inject a part's vector set into the product's. -/
def injectL [DecidableEq L₁] [DecidableEq L₂] [DecidableEq C₁] [DecidableEq C₂]
    (vs : VectorSet L₁ C₁) : VectorSet (L₁ ⊕ L₂) (C₁ ⊕ C₂) :=
  GSet.ofList (vs.elems.map fun x => (x.1.inl, x.2))

/-- The injection is monotone. -/
theorem injectL_mono [DecidableEq L₁] [DecidableEq L₂] [DecidableEq C₁] [DecidableEq C₂]
    {vs vs' : VectorSet L₁ C₁} (h : GSet.Sub vs vs') :
    GSet.Sub (injectL (L₂ := L₂) (C₂ := C₂) vs) (injectL vs') :=
  GSet.ofList_mono fun x hx => by
    obtain ⟨y, hy, rfl⟩ := List.mem_map.1 hx
    exact List.mem_map.2 ⟨y, GSet.mem_of_has (h y (GSet.has_of_mem hy)), rfl⟩

/-- The injection is sound: a set sound for the part is, injected, sound for the product. -/
theorem injectL_sound [DecidableEq L₁] [DecidableEq L₂] [DecidableEq C₁] [DecidableEq C₂]
    (M₁ : Machine S₁ L₁) (M₂ : Machine S₂ L₂) (R₁ : Reading S₁ L₁ C₁) (R₂ : Reading S₂ L₂ C₂)
    (clients : List C₁) {vs : VectorSet L₁ C₁} (h : VectorSet.Sound M₁ R₁ clients vs) :
    VectorSet.Sound (M₁.prod M₂) (R₁.prod R₂) (clients.map Sum.inl) (injectL vs) :=
  VectorSet.sound_ofList fun x hx => by
    obtain ⟨y, hy, rfl⟩ := List.mem_map.1 hx
    have hy' := h y.1 y.2 (GSet.has_of_mem hy)
    show y.1.inl = factOf (M₁.prod M₂) (R₁.prod R₂) (clients.map Sum.inl) (injWord y.1.word)
    rw [factOf_prod_inl, ← hy']

end Composition

end Effect4.Char
