import Effect4.Evidence.Char.Core
import Effect4.Store.Store

/-!
# Conformance.Vector: the fact, its provenance, and the vector

Owner: what one conformance vector *is*. A `Fact` is a word over the label
alphabet, whether the model accepts it, and the reading per client at the
reached state. It is computed by `factOf`, which is `Machine.run` and the
`Reading` and nothing else, so a fact is a **decided statement about the model**
and never an authored expectation. A `Provenance` is a label saying who
produced it. A `Vector` is a fact with every tag it carries.

Where it sits in the semantic compiler: `Fact` is the **instruction** of the
intermediate representation, and `factOf` is the only way to mint one. What it
makes mechanical: no vector can state a reading its own model does not have
(`factOf_accept`, `factOf_readings`), so the front end never writes a vector; it
writes the five parts and the compiler mints the facts.

## The algebra

| | |
| --- | --- |
| Carrier | `Fact L C = ⟨word, accept, readings⟩`, `Provenance` (six constructors), `Vector L C = ⟨fact, tags⟩`; all `deriving DecidableEq, Repr`, `Canonical` when `L` and `C` are |
| Operations | `factOf M R clients w`; `Vector.addr`; `Provenance.spell` |
| Laws | `factOf_word`, `factOf_accept`, `factOf_readings`, `factOf_refused` |
| Structure | `factOf` is the composite of the partial action `Machine.run` with the reading homomorphisms `Reading.acc`, `Reading.del`, evaluated at the reached state; the address is `digestOf ∘ Fact`, a function of the fact alone |
| Payoff | deletes the `{op, expect}` pair the effect-nats fixture keeps in step by hand, and the class of bug where a fixture's expectation matches no state the model can be in |
| Anti-vacuity | `factOf_refused` and `factOf_readings` are two different shapes; the worked instance has both accepted and refused facts |
| Generation | `Fact`s are generated by `factOf`; `Provenance.doctest`'s ratifier is the one hand-authored datum, and it is a tag |

Why the tag is not in the address: the same fact minted by two generators is
one fact with two tags. Ratifying a doctest, or an enumeration later finding an
authored word, adds a tag and moves nothing. That is what "a label on the
vector, never a change to it" means, mechanically.
-/

set_option autoImplicit false

namespace Effect4.Char

open Effect4.Store

/-- What one client sees at the end of one word: handed in, handed out, still held. -/
structure ClientReading (C : Type) where
  client : C
  acc : List Item
  del : List Item
  residue : List Item
deriving DecidableEq, Repr

/-- **The fact.** A word, whether the model accepts it, and the reading per client
at the reached state. Minted by `factOf`, never authored. This is the addressed
unit: `digestOf` of a `Fact` is the vector's address. -/
structure Fact (L C : Type) where
  word : List L
  accept : Bool
  readings : List (ClientReading C)
deriving DecidableEq, Repr

/-- Who produced a vector. A label on a fact, never a change to it. -/
inductive Provenance where
  /-- An authored test of the suite, by test name. -/
  | authored (test : String)
  /-- This word separates the named mutant from the model. -/
  | mutantKill (mutant test : String)
  /-- This word does not separate the named mutant from the model. -/
  | mutantSurvives (mutant test : String)
  /-- Found by bounded enumeration; the depth is the word's length. -/
  | enumerated (depth : Nat)
  /-- A one-step refusal found by bounded enumeration. -/
  | refused (depth : Nat)
  /-- A pinned doctest span, ratified by a named person: the one hand step. -/
  | doctest (span ratifiedBy : String)
deriving DecidableEq, Repr, Inhabited

/-- The manifest spelling of a tag. -/
def Provenance.spell : Provenance → String
  | .authored t => "authored:" ++ t
  | .mutantKill m t => "kills:" ++ m ++ ":" ++ t
  | .mutantSurvives m t => "survives:" ++ m ++ ":" ++ t
  | .enumerated d => "enumerated:" ++ toString d
  | .refused d => "refused:" ++ toString d
  | .doctest s r => "doctest:" ++ s ++ ":" ++ r

/-- **The vector**, as a fixture row reads it: one fact and every tag it carries.
The fibre of a `VectorSet` over one fact; a projection, not the stored unit. -/
structure Vector (L C : Type) where
  fact : Fact L C
  tags : List Provenance
deriving DecidableEq, Repr

instance : Canonical Provenance := ⟨fun p =>
  match p with
  | .authored t => encode ((0 : Nat), t)
  | .mutantKill m t => encode ((1 : Nat), m, t)
  | .mutantSurvives m t => encode ((2 : Nat), m, t)
  | .enumerated d => encode ((3 : Nat), d)
  | .refused d => encode ((4 : Nat), d)
  | .doctest s r => encode ((5 : Nat), s, r)⟩

instance {C : Type} [Canonical C] : Canonical (ClientReading C) :=
  ⟨fun r => encode (r.client, r.acc, r.del, r.residue)⟩

instance {L C : Type} [Canonical L] [Canonical C] : Canonical (Fact L C) :=
  ⟨fun f => encode (f.word, f.accept, f.readings)⟩

instance {L C : Type} [Canonical L] [Canonical C] : Canonical (Vector L C) :=
  ⟨fun v => encode (v.fact, v.tags)⟩

/-- The address of a vector is the address of its fact. Tags do not move it. -/
def Vector.addr {L C : Type} [Canonical L] [Canonical C] (v : Vector L C) : Digest :=
  digestOf v.fact

/-- **The model decides the fact.** `factOf` is `M.run` and the reading, so a fact
is a computation over the model that the kernel reduces. -/
def factOf {S L C : Type} [DecidableEq C] (M : Machine S L) (R : Reading S L C)
    (clients : List C) (w : List L) : Fact L C :=
  match M.run M.init w with
  | some s => ⟨w, true, clients.map fun c => ⟨c, R.acc c w, R.del c w, R.residue s c⟩⟩
  | none => ⟨w, false, []⟩

theorem factOf_word {S L C : Type} [DecidableEq C] (M : Machine S L) (R : Reading S L C)
    (clients : List C) (w : List L) : (factOf M R clients w).word = w := by
  unfold factOf; cases M.run M.init w <;> rfl

/-- A fact's acceptance is the model's acceptance, definitionally. -/
theorem factOf_accept {S L C : Type} [DecidableEq C] (M : Machine S L) (R : Reading S L C)
    (clients : List C) (w : List L) : (factOf M R clients w).accept = M.accepts w := by
  unfold factOf Machine.accepts; cases M.run M.init w <;> rfl

/-- A fact's readings are the reading at the reached state, definitionally. -/
theorem factOf_readings {S L C : Type} [DecidableEq C] (M : Machine S L) (R : Reading S L C)
    (clients : List C) {w : List L} {s : S} (h : M.run M.init w = some s) :
    (factOf M R clients w).readings =
      clients.map fun c => ⟨c, R.acc c w, R.del c w, R.residue s c⟩ := by
  simp [factOf, h]

/-- A refused word's fact is the refusal and nothing else. -/
theorem factOf_refused {S L C : Type} [DecidableEq C] (M : Machine S L) (R : Reading S L C)
    (clients : List C) {w : List L} (h : M.run M.init w = none) :
    factOf M R clients w = ⟨w, false, []⟩ := by
  simp [factOf, h]

/-- A fact minted by `factOf` is the model's fact for its own word: the one lemma
every generator's soundness reduces to. -/
theorem factOf_idem {S L C : Type} [DecidableEq C] (M : Machine S L) (R : Reading S L C)
    (clients : List C) (w : List L) :
    factOf M R clients w = factOf M R clients (factOf M R clients w).word := by
  rw [factOf_word]

end Effect4.Char
