import { Cause, Context, Data, Deferred, Effect, Exit, Fiber, Layer, Option, Ref, Scope, pipe } from "effect"
import { ProfileRefusal, add, and, append, caseTag, caseTagR, causeError, causeIsDie, causeIsFail, causeIsInterrupt, concat, cons, div, drop, eq, fold, fst, get, getOrElse, isSome, isZero, ite, length, lt, mapEmpty, mapEntries, mapFromEntries, mapGet, mapKeys, mapSet, minus, mod, mul, nil, none, not, optionCase, or, pair, plus, pred, recordOptional, recordRequired, recordSet, recordValue, sameHandle, snd, some, strings, sub, succ, tagIs, take, tuple, tupleAt } from "./prelude.ts"
export const main: Effect.Effect<readonly [number, number, number, number, number, number], never, never> = Effect.flatMap(Effect.succeed(2), (a0) => Effect.flatMap(Effect.flatMap(Ref.make(5), (a1) => Effect.flatMap(Ref.make(recordValue<{ readonly next: number; readonly permits: number; readonly taken: number; readonly waiters: ReadonlyArray<{ readonly hint: Deferred.Deferred<void, never>; readonly id: Deferred.Deferred<void, never>; readonly need: number; readonly stamp: number }> }>([10, [20], [[4, [[5, [3, "permits"], [5, [1, false], [10, [2], []]]], [5, [3, "taken"], [5, [1, false], [10, [2], []]]], [5, [3, "waiters"], [5, [1, false], [10, [8], [[10, [20], [[4, [[5, [3, "hint"], [5, [1, false], [10, [17], [[10, [1], []], [10, [], []]]]]], [5, [3, "id"], [5, [1, false], [10, [17], [[10, [1], []], [10, [], []]]]]], [5, [3, "need"], [5, [1, false], [10, [2], []]]], [5, [3, "stamp"], [5, [1, false], [10, [2], []]]]]]]]]]]], [5, [3, "next"], [5, [1, false], [10, [2], []]]]]]]], { permits: 1, taken: 0, waiters: nil(), next: 0 })), (a2) => Effect.succeed(recordValue<{ readonly backing: Ref.Ref<number>; readonly semaphore: Ref.Ref<{ readonly next: number; readonly permits: number; readonly taken: number; readonly waiters: ReadonlyArray<{ readonly hint: Deferred.Deferred<void, never>; readonly id: Deferred.Deferred<void, never>; readonly need: number; readonly stamp: number }> }> }>([10, [20], [[4, [[5, [3, "backing"], [5, [1, false], [10, [16], [[10, [2], []]]]]], [5, [3, "semaphore"], [5, [1, false], [10, [16], [[10, [20], [[4, [[5, [3, "next"], [5, [1, false], [10, [2], []]]], [5, [3, "permits"], [5, [1, false], [10, [2], []]]], [5, [3, "taken"], [5, [1, false], [10, [2], []]]], [5, [3, "waiters"], [5, [1, false], [10, [8], [[10, [20], [[4, [[5, [3, "hint"], [5, [1, false], [10, [17], [[10, [1], []], [10, [], []]]]]], [5, [3, "id"], [5, [1, false], [10, [17], [[10, [1], []], [10, [], []]]]]], [5, [3, "need"], [5, [1, false], [10, [2], []]]], [5, [3, "stamp"], [5, [1, false], [10, [2], []]]]]]]]]]]]]]]]]]]]]]]], { backing: a1, semaphore: a2 })))), (a1) => Effect.flatMap(Effect.flatMap(Effect.uninterruptibleMask((a2) => Effect.succeed(a2)), (a2) => Effect.uninterruptible(Effect.flatMap(Effect.flatMap(Deferred.make<void, never>(), (a3) => Effect.flatMap(Effect.suspend(() => {
  let a4: Option.Option<number> = none()
  return Effect.map(Effect.whileLoop({
    while: () => not(isSome(a4)),
    body: () => Effect.flatMap(Deferred.make<void, never>(), (a5) => Effect.flatMap(Ref.modify(recordRequired<"semaphore">("semaphore")(a1), (a6) => ite(not(lt(sub(recordRequired<"permits">("permits")(a6), recordRequired<"taken">("taken")(a6)), 1)), pair(true, recordSet<"waiters">("waiters")(recordSet<"taken">("taken")(a6)(add(recordRequired<"taken">("taken")(a6), 1)))(fold(recordRequired<"waiters">("waiters")(a6), take(recordRequired<"waiters">("waiters")(a6), 0), (a7, a8) => ite(not(sameHandle(recordRequired<"id">("id")(a8), a3)), append(a7, cons(a8, nil())), a7)))), pair(false, recordSet<"next">("next")(recordSet<"waiters">("waiters")(a6)(append(fold(recordRequired<"waiters">("waiters")(a6), take(recordRequired<"waiters">("waiters")(a6), 0), (a7, a8) => ite(not(sameHandle(recordRequired<"id">("id")(a8), a3)), append(a7, cons(a8, nil())), a7)), cons(recordValue<{ readonly hint: Deferred.Deferred<void, never>; readonly id: Deferred.Deferred<void, never>; readonly need: number; readonly stamp: number }>([10, [20], [[4, [[5, [3, "hint"], [5, [1, false], [10, [17], [[10, [1], []], [10, [], []]]]]], [5, [3, "id"], [5, [1, false], [10, [17], [[10, [1], []], [10, [], []]]]]], [5, [3, "need"], [5, [1, false], [10, [2], []]]], [5, [3, "stamp"], [5, [1, false], [10, [2], []]]]]]]], { hint: a5, id: a3, need: 1, stamp: recordRequired<"next">("next")(a6) }), nil()))))(add(recordRequired<"next">("next")(a6), 1))))), (a6) => Effect.suspend(() => a6 ? Effect.succeed(some(1)) : Effect.flatMap(Effect.onExit(pipe(Deferred.await(a5), a2), (a7) => Effect.suspend(() => causeIsInterrupt(a7) ? Ref.modify(recordRequired<"semaphore">("semaphore")(a1), (a8) => pair(undefined, recordSet<"waiters">("waiters")(a8)(fold(recordRequired<"waiters">("waiters")(a8), take(recordRequired<"waiters">("waiters")(a8), 0), (a9, a10) => ite(not(sameHandle(recordRequired<"id">("id")(a10), a3)), append(a9, cons(a10, nil())), a9))))) : Effect.succeed(undefined))), (a7) => Effect.succeed(none()))))),
    step: (a5) => {
      a4 = a5
    },
  }), () => a4)
}), (a4) => optionCase(a4, () => Effect.failCause(Cause.die("semaphore: the loop ended without a take")), (a5) => Effect.succeed(a5)))), (a3) => Effect.onExit(pipe(Ref.modify(recordRequired<"backing">("backing")(a1), (a4) => pair(a4, add(a4, a0))), a2), (a4) => Effect.uninterruptible(Effect.flatMap(Ref.modify(recordRequired<"semaphore">("semaphore")(a1), (a5) => pair(tuple(sub(recordRequired<"permits">("permits")(a5), sub(recordRequired<"taken">("taken")(a5), 1)), not(isZero(length(recordRequired<"waiters">("waiters")(a5))))), recordSet<"taken">("taken")(a5)(sub(recordRequired<"taken">("taken")(a5), 1)))), (a5) => Effect.flatMap(Effect.suspend(() => tupleAt<"1">("1")(a5) ? Effect.flatMap(Effect.forkDetach(Effect.suspend(() => {
  let a6 = some(0)
  return Effect.map(Effect.whileLoop({
    while: () => isSome(a6),
    body: () => Effect.flatMap(Ref.modify(recordRequired<"semaphore">("semaphore")(a1), (a7) => ite(isZero(sub(recordRequired<"permits">("permits")(a7), recordRequired<"taken">("taken")(a7))), pair(get(take(recordRequired<"waiters">("waiters")(a7), 0), 0), a7), pair(get(fold(recordRequired<"waiters">("waiters")(a7), take(recordRequired<"waiters">("waiters")(a7), 0), (a8, a9) => ite(or(not(isZero(length(a8))), and(not(lt(recordRequired<"stamp">("stamp")(a9), getOrElse(a6, 0))), not(lt(sub(recordRequired<"permits">("permits")(a7), recordRequired<"taken">("taken")(a7)), recordRequired<"need">("need")(a9))))), append(a8, cons(a9, nil())), a8)), 0), recordSet<"waiters">("waiters")(a7)(append(take(recordRequired<"waiters">("waiters")(a7), sub(length(recordRequired<"waiters">("waiters")(a7)), length(fold(recordRequired<"waiters">("waiters")(a7), take(recordRequired<"waiters">("waiters")(a7), 0), (a8, a9) => ite(or(not(isZero(length(a8))), and(not(lt(recordRequired<"stamp">("stamp")(a9), getOrElse(a6, 0))), not(lt(sub(recordRequired<"permits">("permits")(a7), recordRequired<"taken">("taken")(a7)), recordRequired<"need">("need")(a9))))), append(a8, cons(a9, nil())), a8))))), drop(fold(recordRequired<"waiters">("waiters")(a7), take(recordRequired<"waiters">("waiters")(a7), 0), (a8, a9) => ite(or(not(isZero(length(a8))), and(not(lt(recordRequired<"stamp">("stamp")(a9), getOrElse(a6, 0))), not(lt(sub(recordRequired<"permits">("permits")(a7), recordRequired<"taken">("taken")(a7)), recordRequired<"need">("need")(a9))))), append(a8, cons(a9, nil())), a8)), 1)))))), (a7) => optionCase(a7, () => Effect.succeed(none()), (a8) => Effect.flatMap(Deferred.succeed(recordRequired<"hint">("hint")(a8), undefined), (a9) => Effect.succeed(some(add(recordRequired<"stamp">("stamp")(a8), 1)))))),
    step: (a7) => {
      a6 = a7
    },
  }), () => undefined)
}), { startImmediately: false, uninterruptible: true }), (a6) => Effect.succeed(undefined)) : Effect.succeed(undefined)), (a6) => Effect.succeed(tupleAt<"0">("0")(a5))))))))), (a2) => Effect.flatMap(Ref.get(recordRequired<"backing">("backing")(a1)), (a3) => Effect.flatMap(Ref.get(recordRequired<"semaphore">("semaphore")(a1)), (a4) => Effect.succeed(tuple(a2, a3, recordRequired<"permits">("permits")(a4), recordRequired<"taken">("taken")(a4), length(recordRequired<"waiters">("waiters")(a4)), recordRequired<"next">("next")(a4))))))))
