// GENERATED by tools/Tools/TsGen.lean from the Lean environment — do not edit.
// Regenerate: scripts/generate-ts-eff.sh (the drift gate is scripts/check-ts-eff.sh, in the sweep).
//
// One JSON writer per family: the bytes OCaml5.Eff.Goldens.V.json writes and ocaml/eff/eff_json.ml prints. A constructor is ["name", field, …], a structure {field: value}, an option the value or null,
// a cons-list ["cons", head, tail] down to ["nil"]. Same bytes from three languages.
//
// The Eff program IR and its typing (src/Effect4/Program/{Eff,Native,Typing}.lean,
// Machine/Supervision.lean, Machine/Scope.lean, Machine/Stores.lean, Machine/Key.lean): constructor
// and field names verbatim, constructors in declaration order. Two carrier rules, stated here and
// nowhere else: a family whose constructors are exactly `nil` and `cons head tail` is
// ReadonlyArray<head>; a family whose constructors are all nullary is a union of string literals.
// Nat is number, Option is `| null`, List is ReadonlyArray.

import type { Ty, Lit, Term, CauseTerm, MaskMode, ForkOptions, ObserverMode, FinalizerStrategy, FnName, NativeOp, Eff, Stmt, ActionTerm, RowKind, RowShape, ServiceName, ServiceTypeCode, ServiceKey, Row, EffTy } from "./eff.gen.ts"

export type Json = string | number | boolean | null | ReadonlyArray<Json> | { readonly [key: string]: Json }

const consList = <A>(items: ReadonlyArray<A>, each: (a: A) => Json): Json =>
  items.reduceRight<Json>((tail, item) => ["cons", each(item), tail], ["nil"])

export const tyJson = (v: Ty): Json => {
  switch (v._tag) {
    case "never": return ["never"]
    case "unit": return ["unit"]
    case "nat": return ["nat"]
    case "int": return ["int"]
    case "string": return ["string"]
    case "bool": return ["bool"]
    case "handle": return ["handle", v.target]
    case "option": return ["option", tyJson(v.inner)]
    case "list": return ["list", tyJson(v.inner)]
    case "prod": return ["prod", tyJson(v.left), tyJson(v.right)]
    case "except": return ["except", tyJson(v.error), tyJson(v.value)]
    case "exitOf": return ["exitOf", tyJson(v.value), tyJson(v.error)]
    case "causeOf": return ["causeOf", tyJson(v.error)]
    case "fiberOf": return ["fiberOf", tyJson(v.value), tyJson(v.error)]
    case "union": return ["union", tyJson(v.left), tyJson(v.right)]
  }
}

export const litJson = (v: Lit): Json => {
  switch (v._tag) {
    case "unit": return ["unit"]
    case "nat": return ["nat", v.value]
    case "bool": return ["bool", v.value]
    case "str": return ["str", v.value]
  }
}

export const termJson = (v: Term): Json => {
  switch (v._tag) {
    case "var": return ["var", v.index]
    case "lit": return ["lit", litJson(v.value)]
    case "app": return ["app", v.atom, termsJson(v.args)]
  }
}

export const termsJson = (v: ReadonlyArray<Term>): Json => consList(v, (y) => termJson(y))

export const causeTermJson = (v: CauseTerm): Json => {
  switch (v._tag) {
    case "fail": return ["fail", termJson(v.error)]
    case "die": return ["die", termJson(v.defect)]
    case "interrupt": return ["interrupt", (v.interruptor === null ? null : termJson(v.interruptor))]
    case "both": return ["both", causeTermJson(v.left), causeTermJson(v.right)]
  }
}

export const maskModeJson = (v: MaskMode): Json => [v]

export const forkOptionsJson = (v: ForkOptions): Json => ({
  startImmediately: v.startImmediately,
  daemon: v.daemon,
  maskMode: maskModeJson(v.maskMode),
})

export const observerModeJson = (v: ObserverMode): Json => [v]

export const finalizerStrategyJson = (v: FinalizerStrategy): Json => [v]

export const fnNameJson = (v: FnName): Json => [v]

export const nativeOpJson = (v: NativeOp): Json => {
  switch (v._tag) {
    case "refMake": return ["refMake"]
    case "refGet": return ["refGet"]
    case "refSet": return ["refSet"]
    case "refGetAndSet": return ["refGetAndSet"]
    case "refSetAndGet": return ["refSetAndGet"]
    case "refUpdate": return ["refUpdate", fnNameJson(v.f)]
    case "refGetAndUpdate": return ["refGetAndUpdate", fnNameJson(v.f)]
    case "refUpdateAndGet": return ["refUpdateAndGet", fnNameJson(v.f)]
    case "refUpdateSome": return ["refUpdateSome", fnNameJson(v.f)]
    case "refGetAndUpdateSome": return ["refGetAndUpdateSome", fnNameJson(v.f)]
    case "refUpdateSomeAndGet": return ["refUpdateSomeAndGet", fnNameJson(v.f)]
    case "refModify": return ["refModify", fnNameJson(v.f)]
    case "refModifySome": return ["refModifySome", fnNameJson(v.f)]
    case "deferredMake": return ["deferredMake"]
    case "deferredIsDone": return ["deferredIsDone"]
    case "deferredPoll": return ["deferredPoll"]
    case "deferredSucceed": return ["deferredSucceed"]
    case "deferredFail": return ["deferredFail"]
    case "deferredAwait": return ["deferredAwait"]
    case "scopeMake": return ["scopeMake", finalizerStrategyJson(v.strategy)]
  }
}

export const effJson = (v: Eff): Json => {
  switch (v._tag) {
    case "succeed": return ["succeed", termJson(v.value)]
    case "fail": return ["fail", termJson(v.error)]
    case "failCause": return ["failCause", causeTermJson(v.cause)]
    case "yieldError": return ["yieldError", termJson(v.error)]
    case "sync": return ["sync", termJson(v.thunk)]
    case "suspend": return ["suspend", effJson(v.body)]
    case "perform": return ["perform", nativeOpJson(v.op), termJson(v.request)]
    case "bind": return ["bind", effJson(v.first), effJson(v.rest)]
    case "gen": return ["gen", stmtsJson(v.body)]
    case "catchCause": return ["catchCause", effJson(v.body), effJson(v.handler)]
    case "matchCause": return ["matchCause", effJson(v.body), effJson(v.onValue), effJson(v.onCause)]
    case "onExit": return ["onExit", effJson(v.body), effJson(v.finalizer)]
    case "exit": return ["exit", effJson(v.body)]
    case "uninterruptible": return ["uninterruptible", effJson(v.body)]
    case "interruptible": return ["interruptible", effJson(v.body)]
    case "branch": return ["branch", termJson(v.test), effJson(v.thenB), effJson(v.elseB)]
    case "whileLoop": return ["whileLoop", termJson(v.initial), termJson(v.test), termJson(v.step), effJson(v.body)]
    case "yieldNow": return ["yieldNow", v.priority]
    case "callback": return ["callback", nativeOpJson(v.register), termJson(v.request)]
    case "awaitFiber": return ["awaitFiber", termJson(v.fiber), observerModeJson(v.mode)]
    case "withFiber": return ["withFiber", actionTermJson(v.action)]
    case "scoped": return ["scoped", effJson(v.body)]
    case "acquireRelease": return ["acquireRelease", effJson(v.acquire), effJson(v.release)]
    case "choose": return ["choose", v.site, effJson(v.left), effJson(v.right)]
  }
}

export const stmtJson = (v: Stmt): Json => {
  switch (v._tag) {
    case "bindYield": return ["bindYield", effJson(v.effect)]
    case "yieldDiscard": return ["yieldDiscard", effJson(v.effect)]
    case "ret": return ["ret", termJson(v.value)]
    case "ifElse": return ["ifElse", termJson(v.test), stmtsJson(v.thenB), stmtsJson(v.elseB)]
    case "whileTrue": return ["whileTrue", stmtsJson(v.body)]
    case "breakLoop": return ["breakLoop"]
  }
}

export const stmtsJson = (v: ReadonlyArray<Stmt>): Json => consList(v, (y) => stmtJson(y))

export const effsJson = (v: ReadonlyArray<Eff>): Json => consList(v, (y) => effJson(y))

export const actionTermJson = (v: ActionTerm): Json => {
  switch (v._tag) {
    case "fork": return ["fork", effJson(v.program), forkOptionsJson(v.options)]
    case "forkIn": return ["forkIn", effJson(v.program), forkOptionsJson(v.options), termJson(v.scope)]
    case "forkScoped": return ["forkScoped", effJson(v.program), forkOptionsJson(v.options)]
    case "runIn": return ["runIn", termJson(v.target), termJson(v.scope)]
    case "interrupt": return ["interrupt", termJson(v.target)]
    case "interruptScoped": return ["interruptScoped", termJson(v.target)]
    case "interruptAll": return ["interruptAll", termJson(v.targets), (v.interruptor === null ? null : termJson(v.interruptor))]
    case "awaitAll": return ["awaitAll", termJson(v.targets)]
    case "awaitAllFailFast": return ["awaitAllFailFast", termJson(v.targets)]
    case "snapshotChildren": return ["snapshotChildren"]
    case "awaitNewChildren": return ["awaitNewChildren", termJson(v.snapshot)]
    case "raceAll": return ["raceAll", effsJson(v.entrants)]
    case "setContext": return ["setContext", termJson(v.context)]
    case "getContext": return ["getContext"]
    case "getId": return ["getId"]
    case "closeScope": return ["closeScope", termJson(v.scope), termJson(v.exit)]
  }
}

export const rowKindJson = (v: RowKind): Json => [v]

export const rowShapeJson = (v: RowShape): Json => [v]

export const serviceNameJson = (v: ServiceName): Json => ({
  value: v.value,
})

export const serviceTypeCodeJson = (v: ServiceTypeCode): Json => ({
  value: v.value,
})

export const serviceKeyJson = (v: ServiceKey): Json => ({
  name: serviceNameJson(v.name),
  service: serviceTypeCodeJson(v.service),
})

export const rowJson = (v: Row): Json => ({
  name: v.name,
  spelling: v.spelling,
  shape: rowShapeJson(v.shape),
  trailing: v.trailing.map((y) => y),
  kind: rowKindJson(v.kind),
  request: tyJson(v.request),
  answer: tyJson(v.answer),
  error: tyJson(v.error),
  requires: v.requires.map((y) => serviceKeyJson(y)),
  cite: v.cite,
})

export const effTyJson = (v: EffTy): Json => ({
  answer: tyJson(v.answer),
  error: tyJson(v.error),
  requires: v.requires.map((y) => serviceKeyJson(y)),
})

/** The program as the exact bytes Lean writes (no whitespace, no trailing newline). */
export const toJson = (e: Eff): string => JSON.stringify(effJson(e))
