import Test.Counterexamples.Machine.Semantics.M6Capstone
import Test.Counterexamples.Machine.Semantics.ValueMembership
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.bad_reachable
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.bad_exit_not_typed
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.bad_has_bad_exit
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.bad_not_typed
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.current_m6_capstone_false
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.badTape_rejected
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.timerTape_answerFree
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.timed_reachable
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.loaded_code
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.typed_loaded_at
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.typed_loaded
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.loaded_typed
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.loaded_sleep_code
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.loaded_sleep_typed
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.loaded_sleep80_code
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.loaded_sleep80_typed
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.load_code_live
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.reviewed_loaded_at
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.old_bad_queue
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.bad_finished
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.finished_untyped
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.halted_bad_exit_rejected
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.step_finish_false
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.proposed_step_finish_false
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.bad_generated_command_rejected
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.bad_finish_rejected
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.early_resume_rejected
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.bad_observe_rejected
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.join_delivery_typed
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.await_delivery_typed
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.dangling_launch_rejected
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.dangling_enroll_rejected
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.registration_tail_green
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.stackReply_empty_declared
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.registration_mismatch_rejected
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.registration_typed_state_rejected
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.registration_matching_green
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.afterInterrupt_nat_stack_rejected
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.raceCancel_nat_stack_rejected
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.closeParAwait_nat_stack_rejected
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1.afterInterrupt_unit_stack_green
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.OldObserve.loaded_code
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.OldObserve.valid
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.OldObserve.typed
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.OldObserve.internal_below
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.OldObserve.no_requests
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.OldObserve.command_payload
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.OldObserve.queue
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.OldObserve.result_queue
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.OldObserve.emitted_refused
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.OldObserve.result_queue_refused
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.OldObserve.proposed_step_observe_false
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.EarlyStep.drive_of_steps_on
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.EarlyStep.early_runsOnly_five
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.EarlyStep.mEnd_bad_exit
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.EarlyStep.mEnd_not_typed
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.EarlyStep.early_queueOk
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.EarlyStep.load_and_five_inconsistent
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.EarlyStep.load_and_steps_inconsistent
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.EarlyStep.loaded_at80
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.EarlyStep.old_steps_false
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.EarlyStep.early_queue_rejected
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.EarlyDecision.mFired_bad_exit
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.EarlyDecision.mFired_not_typed
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.EarlyDecision.dT_ok
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.EarlyDecision.mT_typed
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.EarlyDecision.load_and_fire_inconsistent
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.EarlyDecision.loaded_at80
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.EarlyDecision.old_fire_false
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.EarlyDecision.early_dispatcher_rejected
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.valid
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.no_requests
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.scheduler
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.observers
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.registration
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.saved_typed
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.typed
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.queue
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.result_fiber
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.result_commands
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.result_current
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.result_stack
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.result_exit_none
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.result_not_typed
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.step_deliver_false
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.typed_queued
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.result_valid
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.result_no_requests
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.result_scheduler
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.result_observers
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.result_registration
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.result_typed
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.result_queue
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.deliver_preserves_this_state
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.completed_commands
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.completed_fiber
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.completed_position
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1TerminalAmendment.published_saved_typed
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.oldSaved_of_saved
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.member_cases
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.valid
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.no_requests
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.scheduler
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.observers
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.registration
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.callback_typed
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.typed
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.old_typed
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.queue
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.result_queue
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.result_halted
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.root_unchanged
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.root_not_terminal
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.output_not_typed
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.step_deliver_false
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.result_fibers
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.result_member_cases
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.result_valid
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.result_no_requests
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.result_scheduler
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.result_observers
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.result_registration
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.result_typed
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.result_queue_typed
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.deliver_preserves_this_state
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.halted_loop_retains_any_queue
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.raw_input_queue
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.raw_result_commands
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.raw_output_untyped
#print axioms Test.Counterexamples.Machine.Semantics.M6Capstone.H1HaltAmendment.unguarded_step_false
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.Reviewed.TypedProg.pure_inv
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.Reviewed.TypedProg.store_inv
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.Reviewed.TypedProg.guard_inv
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.Reviewed.unguard_payload_inv
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.Reviewed.finishFinalizer_payload_inv
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.live_iff_handlesLive
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.wString_one
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.wNat_one
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.wBoolCell_zero
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.wNatCell_zero
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.string_not_sub_nat
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.bool_not_sub_nat
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.fiber1_refused
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.fiber1_accepted
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.handlesLive_one
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.shape_without_fit
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.converse_false
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.g1_old
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.g1_refused
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.g1_control
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.g2_old
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.g2_refused
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.g2_control
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.g3_old
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.g3_refused
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.g3_control
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.g4_old
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.g4_refused
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.g4_control
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.g5_old
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.g5_refused
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.g5_control
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.g6_old
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.g6_refused
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.g6_control
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.sub_nat_union
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.sub_union_nat
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.sub_ref_equiv
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.cell0_keys
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.natCell_old
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.natCell_old_refused
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.strongValue_not_closed_under_sub
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.fitsEq_not_closed_under_sub
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.natCell_equiv_spelling
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.ReviewedLoad.refProg_checks
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.ReviewedLoad.refTy_closed
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.ReviewedLoad.loaded_root
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.ReviewedLoad.refProg_untypable
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.ReviewedLoad.typedState_load_false
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.refProg_typedF
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.getProg_after
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.getProg_typedF
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.typedStateF_load
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.typedStateF_load_ref
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.typedStateF_load_get
#print axioms Test.Counterexamples.Machine.Semantics.ValueMembership.search_heap_extends
#print axioms Effect4.Program.Typed.pending_below
#print axioms Effect4.Program.Typed.QueueOk.fresh
#print axioms Effect4.Program.Typed.reifyExitVal_fits
#print axioms Effect4.Program.Typed.observerDeliveredExit_fits
#print axioms Effect4.Program.Typed.observer_exitValue_typed
#print axioms Effect4.Program.Typed.observerCommand_resume_typed
#print axioms Effect4.Program.Typed.requestOfR_load_none
#print axioms Effect4.Program.Typed.schedulerState_load
#print axioms Effect4.Program.Typed.registrationState_load
#print axioms Effect4.Program.Typed.observerState_load
#print axioms Effect4.Program.Typed.savedPosition_of_saved
#print axioms Effect4.Program.Typed.stepKeeps_of_stepPreserves
#print axioms Effect4.Program.Typed.driveState_typed_of_stepPreserves
