(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400116`, seed 400116, 21 operations.
   Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400116 () =
  let v0 = Fibers_fixture.fork 1 in
  let _v1 = Fibers_fixture.cleanups () in
  let _v2 = Fibers_fixture.cleanups () in
  let _v3 = Fibers_fixture.join v0 in
  let _v4 = Fibers_fixture.started () in
  let v5 = Fibers_fixture.fork_detach 5 in
  let _v6 = Fibers_fixture.fork 4 in
  let _v7 = Fibers_fixture.cleanups () in
  let _v8 = Store_fixtures.scope_make () in
  let _v9 = Fibers_fixture.await_error v0 in
  let _v10 = Fibers_fixture.started () in
  let _v11 = Fibers_fixture.await_value v0 in
  let _v12 = Store_fixtures.scope_make () in
  let _v13 = Fibers_fixture.await_error v0 in
  let _v14 = Store_fixtures.layer_build 1 in
  let v15 = Store_fixtures.def_make () in
  let _v16 = Store_fixtures.def_is_done v15 in
  let _v17 = Store_fixtures.ref_make 4 in
  let _v18 = Fibers_fixture.join v5 in
  let v19 = Fibers_fixture.fork_detach 2 in
  let v20 = Fibers_fixture.await_value v19 in
  v20

let programs : (string * (unit -> value)) list = [ ("p400116", corpus_p400116) ]
