(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400124`, seed 400124, 41 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400124 () =
  let v0 = Fibers_fixture.fork 0 in
  ignore (Fibers_fixture.interrupt v0);
  let _v1 = Fibers_fixture.started () in
  let _v2 = Store_fixtures.def_make () in
  let _v3 = Fibers_fixture.await_value v0 in
  let v4 = Fibers_fixture.fork_detach 2 in
  let _v5 = Fibers_fixture.started () in
  let _v6 = Extra_fixture.interrupt_all [ v4 ] in
  let v7 = Store_fixtures.layer_build 0 in
  ignore (Extra_fixture.yield ());
  let _v8 = Store_fixtures.layer_build 3 in
  let _v9 = Store_fixtures.layer_close () in
  let v10 = Store_fixtures.ref_make 8 in
  let _v11 = Fibers_fixture.started () in
  let v12 = Store_fixtures.def_make () in
  let _v13 = Fibers_fixture.join v4 in
  let _v14 = Store_fixtures.def_poll v12 in
  let v15 = Fibers_fixture.fork 1 in
  let _v16 = Fibers_fixture.started () in
  let _v17 = Fibers_fixture.await_error v0 in
  let _v18 = Store_fixtures.ref_modify v10 9 in
  let _v19 = Store_fixtures.ref_modify v10 10 in
  ignore (Store_fixtures.ref_set v10 6);
  let v20 = Store_fixtures.ref_make 8 in
  let _v21 = Fibers_fixture.started () in
  let _v22 = Fibers_fixture.join v0 in
  let _v23 = Store_fixtures.layer_scope_of v7 in
  let _v24 = Store_fixtures.def_make () in
  ignore (Fibers_fixture.interrupt v15);
  let _v25 = Fibers_fixture.started () in
  let _v26 = Store_fixtures.ref_make 4 in
  ignore (Fibers_fixture.interrupt v0);
  let _v27 = Store_fixtures.scope_make () in
  let _v28 = Store_fixtures.ref_get_and_set v20 1 in
  let _v29 = Store_fixtures.layer_scope_of v7 in
  let _v30 = Extra_fixture.interrupt_all [ v0; v4; v15 ] in
  let _v31 = Extra_fixture.interrupt_all [ v4 ] in
  let _v32 = Fibers_fixture.await_error v15 in
  let _v33 = Fibers_fixture.await_value v15 in
  let _v34 = Fibers_fixture.started () in
  let v35 = Fibers_fixture.await_value v15 in
  v35

let programs : (string * (unit -> value)) list = [ ("p400124", corpus_p400124) ]
