import OCaml5.Ml.Reflect
import OCaml5.Avatar.Part

/-!
# OCaml5.Avatar.ForkFlow

**What it is.** The descriptions behind the generated block of `ocaml/avatar/deep_forkflow.ml`:
the fiber profile's alphabet (seat F2). Its Lean carriers are archived, so it has no derived twin.

**Depends on.** `OCaml5.Ml.Reflect`, `OCaml5.Avatar.Part`.

**Properties.**
* **The block is byte-identical to the one the avatar file carries** — *tested*
  (`ocaml/avatar/render-deep.sh`), executed.
-/

namespace OCaml5.Avatar

open OCaml5.Ml

/-! ## `src/Effect4/Machine/ForkFlow.lean` → `ocaml/avatar/deep_forkflow.ml` (seat F2)

The fiber profile's alphabet: `FiberOp` (twelve rows), the request carriers and the refusal
alphabet. Everything else in `ForkFlow.lean` is the compile of that profile over the Flow IR
(`RegionFlow`, `Code`, `Config`, `OpSpec`), which the avatar has no carriers for: it refuses by
name. `Val` here is `Effects.Trace.Val` (`str`/`nat`/`bool`/`pair`/`unit`/`none`/`some`), which
the wire `value` spells one for one; `BlockId` and `FiberId` are `int`. -/

namespace ForkFlow

def subst : Subst :=
  [("FiberId", Ty.int), ("BlockId", Ty.int), ("Val", Ty.named "value"),
   ("Res", Ty.named "exitv"), ("FiberOp", Ty.named "fiber_op"),
   ("RootRequest", Ty.named "root_request"), ("ForkRequest", Ty.named "fork_request"),
   ("ForkRefusal", Ty.named "fork_refusal")]

/-- `FiberOp` (`ForkFlow.lean:122`), twelve rows in profile order, prefix `Fo`. -/
def fiberOp : InductiveDesc where
  leanName := "FiberOp"; site := "ForkFlow.lean:122"; ctorPrefix := "Fo"; subst := subst
  ctors := [{ leanName := "fork" }, { leanName := "forkScoped" }, { leanName := "join" },
            { leanName := "await" }, { leanName := "interrupt" }, { leanName := "interruptAll" },
            { leanName := "childrenSnapshot" }, { leanName := "awaitChildren" }, { leanName := "raceAll" },
            { leanName := "uninterruptibleIn" }, { leanName := "interruptibleIn" }, { leanName := "yieldNow" }]
def rootRequest : StructDesc where
  leanName := "RootRequest"; site := "ForkFlow.lean:382"; subst := subst
  fields := [{ leanName := "root", leanTy := .nm "BlockId" }, { leanName := "args", leanTy := .lst (.nm "Val") }]
def forkRequest : StructDesc where
  leanName := "ForkRequest"; site := "ForkFlow.lean:401"; subst := subst
  fields := [{ leanName := "root", leanTy := .nm "BlockId" }, { leanName := "args", leanTy := .lst (.nm "Val") },
             { leanName := "daemon", leanTy := .bool }, { leanName := "region", leanTy := .opt .nat }]
/-- `ForkRefusal` (`ForkFlow.lean:449`), prefix `Fr`. -/
def forkRefusal : InductiveDesc where
  leanName := "ForkRefusal"; site := "ForkFlow.lean:449"; ctorPrefix := "Fr"; subst := subst
  ctors := [{ leanName := "requestMalformed", args := [⟨"request", .nm "Val", false⟩] },
            { leanName := "rootUndeclared", args := [⟨"root", .nm "BlockId", false⟩] },
            { leanName := "rootUnknown", args := [⟨"root", .nm "BlockId", false⟩] },
            { leanName := "rootArity", args := [⟨"root", .nm "BlockId", false⟩, ⟨"declared", .nat, false⟩, ⟨"supplied", .nat, false⟩] },
            { leanName := "handleMalformed", args := [⟨"request", .nm "Val", false⟩] },
            { leanName := "scopedNamesRegion", args := [⟨"root", .nm "BlockId", false⟩] }]

def generated : List Decl :=
  [.comment ("Generated by OCaml5.Ml (`Render.lean`, seat W1). Do not edit; edit the"
      ++ " descriptions (`Ml.Deep.ForkFlow`, seat F2).\n   One declaration per `Effect4/Deep/ForkFlow.lean`"
      ++ " carrier of the profile's alphabet, same order."),
   fiberOp.header, renameDecl "fiber_op" fiberOp.decl,
   rootRequest.header, renameDecl "root_request" rootRequest.decl,
   forkRequest.header, renameDecl "fork_request" forkRequest.decl,
   forkRefusal.header, renameDecl "fork_refusal" forkRefusal.decl]


/-- `deep_forkflow.ml` as a part of the avatar. Its Lean carriers are archived, so nothing is under
the projection guard. -/
def part : Part :=
  { name := "forkflow", file := "deep_forkflow.ml", guarded := [], generated := generated }

end ForkFlow

end OCaml5.Avatar
