import Conform.Spec.Reflect
import Conform.Core.Policy
import Tools.GeneratedStamp

/-! Generate ordinary Lean specifications from elaborated declarations. The configuration
supplies the application roots and support namespace. The emitted file needs no reflection.
Generated propositions and proofs come from the same checked terms, with full telescopes.
-/
namespace Conform.Cli.EmitSpecs
open Lean Meta Elab Term

structure Config where
  imports : Array Name
  roots : Array Name
  supportNamespace : Name

def readConfig (j : Json) : Policy.Reader Config := do
  let get ← Policy.object j ["imports", "roots", "supportNamespace"]
  return { imports := ← Policy.field get "imports" fun j => Policy.array j Policy.name,
           roots := ← Policy.field get "roots" fun j => Policy.array j Policy.name,
           supportNamespace := ← Policy.field get "supportNamespace" Policy.name }

def support : Array Name :=
  #[``Conform.Spec.Option.spec_reflect, ``Conform.Spec.Spec.some, ``Conform.Spec.Spec.none,
    ``Conform.Spec.Spec.map_Option, ``Conform.Spec.Spec.bind_Option, ``Conform.Spec.Option.of_triple]

def renamed (cfg : Config) (n : Name) : Name :=
  if (`Conform.Spec).isPrefixOf n then n.replacePrefix `Conform.Spec cfg.supportNamespace else n

def renameExpr (cfg : Config) (e : Expr) : Expr :=
  e.replace fun
    | .const n us => some (.const (renamed cfg n) us)
    | _ => none

def indent (s : String) : String := "\n".intercalate ((s.splitOn "\n").map ("  " ++ ·))

def declaration (cfg : Config) (name : Name) (spec : Bool) : MetaM String := do
  let .thmInfo info ← getConstInfo name | throwError "{name}: expected a theorem"
  let extra := (← collectAxioms name).filter fun n => ![``propext, ``Quot.sound].contains n
  unless extra.isEmpty do throwError "{name}: disallowed axioms {extra}"
  let options := (← getOptions).setBool `pp.universes true |>.setBool `pp.explicit true
    |>.setBool `pp.proofs true |>.setBool `pp.fullNames true |>.setBool `pp.notation false
    |>.set `pp.maxSteps (10000000 : Nat)
  withOptions (fun _ => options) do
    let type := (← ppExpr (renameExpr cfg info.type)).pretty
    let value := (← ppExpr (renameExpr cfg info.value)).pretty
    let universes := if info.levelParams.isEmpty then "" else
      ".{" ++ ", ".intercalate (info.levelParams.map Name.toString) ++ "}"
    return s!"{if spec then "@[spec] " else ""}theorem {renamed cfg name}{universes} :\n{indent type} :=\n{indent value}\n"

def generate (cfg : Config) : TermElabM String := do
  let mut leaves : Array Name := #[]
  for root in cfg.roots do
    let some equations ← getEqnsFor? root | throwError "{root}: no equation lemmas"
    let sources ← equations.mapM fun n => return (← getConstInfo n).type
    for name in ← Conform.Spec.optionLeaves sources do
      unless leaves.contains name do leaves := leaves.push name
  let mut reflected : Array Name := #[]
  for name in leaves.qsort Name.quickLt do
    match ← Conform.Spec.declareReflect name with
    | .ok target | .error (.exists_ target) => reflected := reflected.push target
    | .error refusal => throwError refusal.render
  -- Register renamed support in the tool environment before delaboration. Otherwise the
  -- printer cannot recover implicit binders of the new names and emits ambiguous applications.
  for name in support do
    let .thmInfo info ← getConstInfo name | throwError "{name}: expected theorem"
    let target := renamed cfg name
    unless target == name do
      addDecl (.thmDecl {
        name := target
        levelParams := info.levelParams
        type := renameExpr cfg info.type
        value := renameExpr cfg info.value })
  let mut parts := #[]
  for name in support do
    parts := parts.push (← declaration cfg name (name != ``Conform.Spec.Option.spec_reflect &&
      name != ``Conform.Spec.Option.of_triple))
  for name in reflected do parts := parts.push (← declaration cfg name true)
  return "\n".intercalate parts.toList

/-- Run in Lean's ordinary elaborator so lazy equation generation has the complete imported
extension state. A constant-only `importModules` environment does not provide that state. -/
syntax (name := emitSpecs) "emit_specs " str str : command

@[command_elab emitSpecs] def elabEmitSpecs : Command.CommandElab
  | `(emit_specs $config:str $output:str) => do
    let configFile := config.getString
    let cfg ← Conform.Policy.load configFile readConfig
    let body ← Command.liftTermElabM (generate cfg)
    let stamp ← Tools.GeneratedStamp.line "tools/Conform/Cli/EmitSpecs.lean"
      ((cfg.imports.push `Conform.Cli.EmitSpecs).toList.map Name.toString) [configFile]
    let imports := "\n".intercalate (cfg.imports.toList.map fun n => s!"import {n}")
    let header := s!"-- GENERATED by Conform.Cli.EmitSpecs; do not edit.\n-- {stamp}\n{imports}\nimport Std.Tactic.Do\n\nset_option linter.unusedVariables false\n\n"
    let path : System.FilePath := output.getString
    if let some parent := path.parent then IO.FS.createDirAll parent
    IO.FS.writeFile path (header ++ body)
  | _ => throwUnsupportedSyntax

end Conform.Cli.EmitSpecs

/-- The command runs in an ordinary Lean file, using the current Lake search path. -/
def main (args : List String) : IO UInt32 := do
  let [configFile, output] := args | IO.eprintln "usage: EmitSpecs.lean CONFIG OUTPUT"; return 2
  let cfg ← Conform.Policy.load configFile Conform.Cli.EmitSpecs.readConfig
  let imports := "\n".intercalate (cfg.imports.toList.map fun n => s!"import {n}")
  IO.FS.withTempFile fun handle path => do
    handle.putStr s!"{imports}\nimport Conform.Cli.EmitSpecs\nemit_specs {repr configFile} {repr output}\n"
    handle.flush
    let result ← IO.Process.output { cmd := "lean", args := #["-M4096", path.toString] }
    IO.print result.stdout
    IO.eprint result.stderr
    return result.exitCode
