(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400167`, seed 400167, 18 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400167 () =
  let v0 = Fibers_fixture.fork 3 in
  let v1 = Store_fixtures.def_make () in
  let _v2 = Fibers_fixture.started () in
  let _v3 = Extra_fixture.interrupt_all [ v0 ] in
  let _v4 = Store_fixtures.def_await_error v1 in
  let v5 = Store_fixtures.scope_make () in
  let _v6 = Store_fixtures.ref_make 5 in
  let _v7 = Fibers_fixture.started () in
  let _v8 = Fibers_fixture.await_error v0 in
  let _v9 = Fibers_fixture.started () in
  let _v10 = Fibers_fixture.fork 0 in
  let _v11 = Store_fixtures.def_make () in
  let _v12 = Store_fixtures.def_make () in
  let _v13 = Store_fixtures.layer_build 1 in
  let _v14 = Store_fixtures.scope_add v5 3 in
  let _v15 = Store_fixtures.layer_build 0 in
  let _v16 = Fibers_fixture.join v0 in
  let v17 = Fibers_fixture.join v0 in
  v17

let programs : (string * (unit -> value)) list = [ ("p400167", corpus_p400167) ]
