(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400159`, seed 400159, 34 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400159 () =
  let v0 = Fibers_fixture.fork 1 in
  let _v1 = Fibers_fixture.started () in
  let v2 = Store_fixtures.def_make () in
  let _v3 = Fibers_fixture.started () in
  let _v4 = Fibers_fixture.await_error v0 in
  let v5 = Store_fixtures.ref_make 6 in
  let _v6 = Fibers_fixture.started () in
  ignore (Store_fixtures.ref_set v5 9);
  let _v7 = Store_fixtures.ref_modify v5 8 in
  let _v8 = Fibers_fixture.started () in
  let _v9 = Store_fixtures.def_make () in
  let v10 = Store_fixtures.scope_make () in
  ignore (Extra_fixture.yield ());
  let _v11 = Store_fixtures.def_is_done v2 in
  let _v12 = Fibers_fixture.await_error v0 in
  let v13 = Fibers_fixture.fork 0 in
  let _v14 = Store_fixtures.ref_make 10 in
  let _v15 = Store_fixtures.def_make () in
  let v16 = Store_fixtures.scope_make () in
  let v17 = Store_fixtures.layer_build 0 in
  let _v18 = Store_fixtures.scope_add v16 4 in
  let _v19 = Store_fixtures.layer_scope_of v17 in
  let _v20 = Fibers_fixture.await_value v13 in
  let _v21 = Store_fixtures.scope_add v10 4 in
  let _v22 = Store_fixtures.layer_build 0 in
  let _v23 = Store_fixtures.layer_provide_count 3 in
  ignore (Fibers_fixture.interrupt v0);
  let _v24 = Fibers_fixture.join v0 in
  let _v25 = Store_fixtures.ref_make 9 in
  let _v26 = Fibers_fixture.await_value v13 in
  let v27 = Fibers_fixture.fork_detach 1 in
  let _v28 = Store_fixtures.scope_add v10 3 in
  let _v29 = Fibers_fixture.join v27 in
  let v30 = Fibers_fixture.await_value v0 in
  v30

let programs : (string * (unit -> value)) list = [ ("p400159", corpus_p400159) ]
