import Effect4.Laws.Program.Typed.Commands.Bookkeeping

/-! Seat D3: `#print axioms` for every theorem of `src/Effect4/Laws/Program/Typed/Commands/Bookkeeping.lean` and the ledger lines it
closes (at the head). Run: `LEAN_NUM_THREADS=2 lake env lean docs/research/2026-10-01-landing/seat-D3/AxiomsBookkeeping.lean`. -/

#print axioms Effect4.Program.Typed.rfiber?_id
#print axioms Effect4.Program.Typed.rfiber?_mem
#print axioms Effect4.Program.Typed.rfiber?_of_mem
#print axioms Effect4.Program.Typed.rfiber?_update
#print axioms Effect4.Program.Typed.rfiber?_update_self
#print axioms Effect4.Program.Typed.rfiber?_update_other
#print axioms Effect4.Program.Typed.mem_rupdate
#print axioms Effect4.Program.Typed.mem_rupdate_of_ne
#print axioms Effect4.Program.Typed.mem_rupdate_self
#print axioms Effect4.Program.Typed.rupdate_ids
#print axioms Effect4.Program.Typed.internalKeys_fibers
#print axioms Effect4.Program.Typed.fiberKeys_internal
#print axioms Effect4.Program.Typed.internalKeys_rupdate
#print axioms Effect4.Program.Typed.internalKeys_rupdate_old
#print axioms Effect4.Program.Typed.MachineTyped.wide
#print axioms Effect4.Program.Typed.MachineTyped.fiber
#print axioms Effect4.Program.Typed.machineTyped_of
#print axioms Effect4.Program.Typed.PendingWeaker.refl
#print axioms Effect4.Program.Typed.ObsView.refl
#print axioms Effect4.Program.Typed.ObsView.trans
#print axioms Effect4.Program.Typed.ObsView.ofLookup
#print axioms Effect4.Program.Typed.countdownAt_view
#print axioms Effect4.Program.Typed.storedObserverOk_view
#print axioms Effect4.Program.Typed.observerCommandOk_view
#print axioms Effect4.Program.Typed.enrollRaceOk_view
#print axioms Effect4.Program.Typed.queueOk_transport
#print axioms Effect4.Program.Typed.configTyped_tail
#print axioms Effect4.Program.Typed.ctlView_lookup
#print axioms Effect4.Program.Typed.ctlView_lookup_back
#print axioms Effect4.Program.Typed.activeAt_view
#print axioms Effect4.Program.Typed.commandAuthority_view
#print axioms Effect4.Program.Typed.stackReply_congr
#print axioms Effect4.Program.Typed.commandDelivery_view
#print axioms Effect4.Program.Typed.authView_lookup
#print axioms Effect4.Program.Typed.commandAuthority_auth
#print axioms Effect4.Program.Typed.stackReply_view
#print axioms Effect4.Program.Typed.commandDelivery_stack
#print axioms Effect4.Program.Typed.requestOfR_congr
#print axioms Effect4.Program.Typed.requestOfR_of_parked
#print axioms Effect4.Program.Typed.requestOfR_of_not_parked
#print axioms Effect4.Program.Typed.fiberTyped_transport
#print axioms Effect4.Program.Typed.rfiber?_same
#print axioms Effect4.Program.Typed.obsView_rupdate
#print axioms Effect4.Program.Typed.ctlView_rupdate
#print axioms Effect4.Program.Typed.machineWide_rupdate
#print axioms Effect4.Program.Typed.runFiberOk_congr
#print axioms Effect4.Program.Typed.QuietEdit.keys
#print axioms Effect4.Program.Typed.configTyped_modify_quiet
#print axioms Effect4.Program.Typed.servicesFit_mono
#print axioms Effect4.Program.Typed.fiberColumnsBelow_world
#print axioms Effect4.Program.Typed.racePayload_world
#print axioms Effect4.Program.Typed.countdownAt_world
#print axioms Effect4.Program.Typed.storedObserverOk_world
#print axioms Effect4.Program.Typed.observerCommandOk_world
#print axioms Effect4.Program.Typed.enrollRaceOk_world
#print axioms Effect4.Program.Typed.stackReply_world
#print axioms Effect4.Program.Typed.commandDelivery_world
#print axioms Effect4.Program.Typed.resumeOk_world
#print axioms Effect4.Program.Typed.rcmdOk_world
#print axioms Effect4.Program.Typed.queueOk_world
#print axioms Effect4.Program.Typed.readCode_world
#print axioms Effect4.Program.Typed.runFiberOk_world
#print axioms Effect4.Program.Typed.fiberTyped_world
#print axioms Effect4.Program.Typed.quiet_children
#print axioms Effect4.Program.Typed.quiet_observe
#print axioms Effect4.Program.Typed.mem_append_observer
#print axioms Effect4.Program.Typed.trackChild_preserves
#print axioms Effect4.Program.Typed.queueOk_cons
#print axioms Effect4.Program.Typed.readCode_cons
#print axioms Effect4.Program.Typed.configTyped_cons_resume
#print axioms Effect4.Program.Typed.configTyped_congr
#print axioms Effect4.Program.Typed.authView_rupdate
#print axioms Effect4.Program.Typed.stackView_rupdate
#print axioms Effect4.Program.Typed.configTyped_emit
#print axioms Effect4.Program.Typed.configTyped_rupdate_gen
#print axioms Effect4.Program.Typed.configTyped_rupdate
#print axioms Effect4.Program.Typed.leHost_restate
#print axioms Effect4.Program.Typed.completionStrong_mono
#print axioms Effect4.Program.Typed.captureTyped_mono
#print axioms Effect4.Program.Typed.finNameOk_world
#print axioms Effect4.Program.Typed.scopeStateOk_world
#print axioms Effect4.Program.Typed.storesOk_world
#print axioms Effect4.Program.Typed.wf_restate
#print axioms Effect4.Program.Typed.machineWide_restate
#print axioms Effect4.Program.Typed.configTyped_restate
#print axioms Effect4.Program.Typed.mem_insert_tasks
#print axioms Effect4.Program.Typed.bucketKeys_insert
#print axioms Effect4.Program.Typed.configTyped_postTask
#print axioms Effect4.Program.Typed.postTask_request
#print axioms Effect4.Program.Typed.postTask_isSome
#print axioms Effect4.Program.Typed.owedOk_postTask
#print axioms Effect4.Program.Typed.drainOwed_request
#print axioms Effect4.Program.Typed.configTyped_drainOwed
#print axioms Effect4.Program.Typed.denoteCompletion_typed
#print axioms Effect4.Program.Typed.internalKeys_dueless
#print axioms Effect4.Program.Typed.drainDue_preserves
#print axioms Effect4.Program.Typed.FiberTyped.position
#print axioms Effect4.Program.Typed.MachineWide.declared
#print axioms Effect4.Program.Typed.interruptCause_interrupts
#print axioms Effect4.Program.Typed.exitOk_interrupts
#print axioms Effect4.Program.Typed.interruptRecord_shape
#print axioms Effect4.Program.Typed.rfiber?_update_keep
#print axioms Effect4.Program.Typed.commandAuthority_idle
#print axioms Effect4.Program.Typed.fiberTyped_reframe
#print axioms Effect4.Program.Typed.headOk_evaluate
#print axioms Effect4.Program.Typed.configTyped_cons_evaluate
#print axioms Effect4.Program.Typed.configTyped_interruptRecord
#print axioms Effect4.Program.Typed.scopeStateOk_of
#print axioms Effect4.Program.Typed.scopeStateOk_entries
#print axioms Effect4.Program.Typed.scopeStateOk_closed
#print axioms Effect4.Program.Typed.mem_tableInsert
#print axioms Effect4.Program.Typed.entries_addUnsafe
#print axioms Effect4.Program.Typed.scopeStoreOk_setEntry
#print axioms Effect4.Program.Typed.scopeStoreOk_addUnsafe
#print axioms Effect4.Program.Typed.scopeStoreOk_removeFinalizer
#print axioms Effect4.Program.Typed.internalKeys_scopes
#print axioms Effect4.Program.Typed.internalKeys_scopes'
#print axioms Effect4.Program.Typed.addFinalizer_open_eq
#print axioms Effect4.Program.Typed.rmodify_state
#print axioms Effect4.Program.Typed.scopeLinkFiber_open
#print axioms Effect4.Program.Typed.link_preserves
#print axioms Effect4.Program.Typed.quiet_untrack
#print axioms Effect4.Program.Typed.dropFinalizer_live
#print axioms Effect4.Program.Typed.subN_unknown
#print axioms Effect4.Program.Typed.exitOk_subN
#print axioms Effect4.Program.Typed.failureFits_cause
#print axioms Effect4.Program.Typed.failureFits_of_cause
#print axioms Effect4.Program.Typed.exitOk_failure_append
#print axioms Effect4.Program.Typed.exitOk_causeReasons
#print axioms Effect4.Program.Typed.rrace?_id
#print axioms Effect4.Program.Typed.rrace?_updateRace
#print axioms Effect4.Program.Typed.racePayload_complete
#print axioms Effect4.Program.Typed.racePayload_unique
#print axioms Effect4.Program.Typed.rrace?_updateRace_cases
#print axioms Effect4.Program.Typed.rrace?_of_mem
#print axioms Effect4.Program.Typed.internalKeys_updateRace
#print axioms Effect4.Program.Typed.sameFibers_updateRace
#print axioms Effect4.Program.Typed.storedObserverOk_updateRace
#print axioms Effect4.Program.Typed.observerCommandOk_updateRace
#print axioms Effect4.Program.Typed.enrollRaceOk_updateRace
#print axioms Effect4.Program.Typed.configTyped_updateRace
#print axioms Effect4.Program.Typed.seq_typed_clean
#print axioms Effect4.Program.Typed.raceSettle_typed
#print axioms Effect4.Program.Typed.raceKey_internal
#print axioms Effect4.Program.Typed.racePayload_settled
#print axioms Effect4.Program.Typed.raceComplete_live
#print axioms Effect4.Program.Typed.observe_raceCallback
#print axioms Effect4.Program.Typed.M6Ledger.step_trackChild.checked
#print axioms Effect4.Program.Typed.M6Ledger.step_drainDue.checked
#print axioms Effect4.Program.Typed.M6Ledger.step_link.checked
