#!/usr/bin/env bash
# Host gate: every generated module is byte-identical to Lean's, the four host
# gates pass, and the traced runs agree with the goldens under every mask, at a
# large op budget and at a forced yield after every op. Writes receipts.
#
# The script is three functions and a family table. It used to be nine copies of
# the same five lines with a `mktemp` per family, a `trap` per family that
# respelled a growing list and dropped entries from it -- so every run leaked
# temp files, and one variable was even `mktemp`ed twice in a row -- and a
# closing message that named seven of the ten families it ran (survey finding
# H18). There is one temp directory and one trap now, and the message is built
# from the table.
#
# The table is still spelled here rather than read from `Generate.lean`; making
# a family one row that the generator, this gate and the tsconfig all read is
# survey finding H35, wave 4 of the refactor plan.
#
# ## Stamp (rule 9)
#
# This is the sweep's most expensive gate -- a minute of node -- and everything
# it reads is nameable. On the Lean side: `harness/trace/Generate.lean`, which
# regenerates the ten committed modules, and the Lake traces of what it imports.
# On the host side: every TypeScript file and the tsconfig under
# `harness/trace/`, since the runner typechecks the file set and the tails drive
# the runs; every golden and the mask table under `generated/traces/`, which the
# runs are compared with; the effect4-tools runners; and the pinned
# installation's identity -- the three package manifests at their absolute
# path, `host-pin.json` with the SHA-256 of the whole rc.112 tree, and the node
# version, which the receipts record.
#
# `--update` rewrites the committed modules from Lean, so it is never stamped.
set -euo pipefail
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
. "$repo_root/scripts/lib/portable.sh"
. "$repo_root/scripts/lib/stamp.sh"
tools="${EFFECT4_TOOLS:-$repo_root/../effect4-tools}"
here="$repo_root/harness/trace"
traces="$repo_root/generated/traces"
masks="$traces/masks.tsv"
update=0; stamped=1
for argument in "$@"; do
  case "$argument" in
    --update) update=1; stamped=0 ;;
    --force) export EFFECT4_FORCE=1 ;;
    *) echo "unknown argument $argument" >&2; exit 2 ;;
  esac
done
cd "$repo_root"
lake build Effect4 >/dev/null
if [ "$stamped" -eq 1 ]; then
  inputs=(
    "$repo_root/scripts/check-trace-host.sh"
    "$repo_root/scripts/lib/portable.sh"
    "$repo_root/scripts/lib/stamp.sh"
    "$here/Generate.lean"
    "$here/tsconfig.json"
    "$traces"
    "$repo_root/lakefile.toml"
    "$repo_root/lake-manifest.json"
    "$repo_root/lean-toolchain"
  )
  for module in "$here"/*.ts; do inputs+=("$module"); done
  while IFS= read -r input; do inputs+=("$input"); done < <(
    stamp_lean_traces "$here/Generate.lean"
    stamp_tools_inputs trace.mjs check.mjs copy.mjs
    stamp_host_inputs
  )
  key="$(stamp_key "${inputs[@]}")"
  if stamp_hit trace-host "$key"; then
    stamp_report trace-host "$key"
    exit 0
  fi
fi
tmp="$(mktemp -d "${TMPDIR:-/tmp}/effect4-trace-host.XXXXXX")"
trap 'rm -rf -- "$tmp"' EXIT

# --- generated modules --------------------------------------------------------
# regenerate <Generate.lean command> <committed file, relative to the repo root>
regenerate() {
  local command="$1" file="$2" produced="$tmp/${2##*/}"
  lean_run "$here/Generate.lean" "$command" > "$produced"
  if [ "$update" -eq 1 ]; then cp "$produced" "$repo_root/$file"; fi
  cmp -s "$produced" "$repo_root/$file" || {
    echo "FAIL $file drifted from Lean generation" >&2
    diff "$produced" "$repo_root/$file" | head -20 >&2
    exit 1
  }
  echo "PASS $file regenerated byte-identically"
}

# --- one host run -------------------------------------------------------------
# trace_run <label|-> <program> <golden> <receipt|-> <tail|-> [VAR=VALUE ...]
# `-` means: no label prefix on the printed rows, no receipt, the default tail.
trace_run() {
  local label="$1" program="$2" golden="$3" receipt="$4" tail="$5"; shift 5
  local -a args=( "$tools/packages/harness/trace.mjs" "$here" --golden "$golden" --masks "$masks" )
  [ "$tail" = "-" ] || args+=( --tail "$tail" )
  if [ "$receipt" != "-" ]; then mkdir -p "$(dirname "$receipt")"; args+=( --receipt "$receipt" ); fi
  if [ "$label" = "-" ]; then
    env EFFECT4_PROGRAM="$program" "$@" node "${args[@]}"
  else
    env EFFECT4_PROGRAM="$program" "$@" node "${args[@]}" | sed "s/^trace/trace($label)/"
  fi
}

# --- one family ---------------------------------------------------------------
# host_family <label|-> <tail|-> <receipt dir> <program_from> <yield3> -- <golden>...
#
# `program_from` says how `EFFECT4_PROGRAM` is read out of the golden's file
# name: `whole` is the name itself, `prefix` is the part before the first dot
# (several goldens share one flow), `suffix` drops a trailing `.empty` (the
# straight-line goldens are named `<program>.empty.tsv`). The receipt is always
# `<receipt dir>/<golden base name>.json`.
host_family() {
  local label="$1" tail="$2" receipts="$3" program_from="$4" yield3="$5"; shift 6  # the 6th is `--`
  local golden base program yield_label
  mkdir -p "$receipts"
  for golden in "$@"; do
    [ -e "$golden" ] || { echo "FAIL no goldens matched for family ${label}" >&2; exit 1; }
    base="$(basename "$golden" .tsv)"
    case "$program_from" in
      whole)  program="$base" ;;
      prefix) program="${base%%.*}" ;;
      suffix) program="${base%.empty}" ;;
      *) echo "FAIL unknown program_from $program_from" >&2; exit 1 ;;
    esac
    trace_run "$label" "$program" "$golden" "$receipts/$base.json" "$tail"
    [ "$yield3" = "yes" ] || continue
    # Yield as often as the run loop allows. rc.112 counts the op before its
    # yield check and the yield wrapper itself costs two ops, so 1 and 2 never
    # progress; 3 is the floor. The service-level rows must not change.
    if [ "$label" = "-" ]; then yield_label="yield-every-op"; else yield_label="$label,yield-every-op"; fi
    trace_run "$yield_label" "$program" "$golden" - "$tail" \
      EFFECT4_MAX_OPS=3 EFFECT4_EXPECT_YIELDS=1
  done
}

# --- the modules --------------------------------------------------------------
regenerate fixture harness/trace/fixture.ts
# The atoms module is generated from the same `effect_atoms` rows as the Lean
# functions and the flow embedding's table, so no atom exists in one face only
# (row E4-TARGET-CE-025).
regenerate atoms harness/trace/atoms.ts
regenerate flow-fixture harness/trace/flow-fixture.ts
regenerate structured-fixture harness/trace/structured-fixture.ts
regenerate scope-fixture harness/trace/scope-fixture.ts
regenerate layer-fixture harness/trace/layer-fixture.ts
regenerate fiber-fixture harness/trace/fiber-fixture.ts
regenerate job-fixture harness/trace/job-fixture.ts
regenerate deferred-fixture harness/trace/deferred-fixture.ts
regenerate ref-fixture harness/trace/ref-fixture.ts
node "$tools/packages/harness/check.mjs" "$here"

# --- the straight-line form ---------------------------------------------------
host_family - - "$here/receipts" suffix yes -- "$traces"/*.empty.tsv

# --- the dispatch and structured forms against the Flow-runner goldens --------
# A resource-boundary golden carries `budget <yield setting> <n>` rows: the op
# budget counts primitives and the yield wrapper is itself primitives, so the
# frontier lands on the same row at both settings only with one budget each.
budget_row() { awk -F'\t' -v want="$2" '$1=="budget" && $2==want {print $3}' "$1"; }
mkdir -p "$here/receipts/flow" "$here/receipts/structured"
for golden in "$traces"/flow/*.tsv; do
  base="$(basename "$golden" .tsv)"; program="${base%%.*}"
  default_budget="$(budget_row "$golden" default)"; yield3_budget="$(budget_row "$golden" yield3)"
  trace_run dispatch "$program" "$golden" "$here/receipts/flow/$base.json" flow-tail.ts \
    EFFECT4_BUDGET="${default_budget:-100000}"
  trace_run dispatch,yield-every-op "$program" "$golden" - flow-tail.ts \
    EFFECT4_MAX_OPS=3 EFFECT4_EXPECT_YIELDS=1 EFFECT4_BUDGET="${yield3_budget:-100000}"
  # The structured form of the same program against the same golden, under the
  # same budgets: both forms spend the same primitives up to the frontier. It is
  # run at both yield settings, exactly as the dispatch form is; it used to run
  # only at the default one, with no comment saying so, while
  # docs/LOWERING-COVERAGE.md claimed the two forms shared their evidence
  # (survey finding H39).
  trace_run structured "$program" "$golden" "$here/receipts/structured/$base.json" structured-tail.ts \
    EFFECT4_BUDGET="${default_budget:-100000}"
  trace_run structured,yield-every-op "$program" "$golden" - structured-tail.ts \
    EFFECT4_MAX_OPS=3 EFFECT4_EXPECT_YIELDS=1 EFFECT4_BUDGET="${yield3_budget:-100000}"
done

# --- the remaining families ---------------------------------------------------
host_family scope     scope-tail.ts     "$here/receipts/scope"          whole yes -- "$traces"/scope/*.tsv
host_family layer     layer-tail.ts     "$here/receipts/layer"          whole yes -- "$traces"/layer/*.tsv
host_family interrupt interrupt-tail.ts "$here/receipts/flow/interrupt" whole yes -- "$traces"/flow/interrupt/*.tsv
# There is no yield-every-op run for the fibers, and the refusal is that
# packet's finding. The tape drives `TapeScheduler.shouldYield`; at rc.112's own
# floor of 3 the run loop yields on its own, a deferred child starts with no
# `decide` row to account for it, and the sequential projection's `false` stops
# being a fact about the run. counterexample: E4-SEM-CE-011
host_family fiber     fiber-tail.ts     "$here/receipts/fiber"          whole no  -- "$traces"/fiber/*.tsv
# The job runner (the first real program): its module and its tail over a real
# file-backed queue. `EFFECT4_PROGRAM` is the *golden* name, not the program
# name -- four goldens share the `jobRunner` body and differ in the queue seed
# the tail writes for them -- so this family reads the whole base name.
host_family job       job-tail.ts       "$here/receipts/job"            whole yes -- "$traces"/job/*.tsv
host_family deferred  deferred-tail.ts  "$here/receipts/deferred"       whole yes -- "$traces"/deferred/*.tsv
host_family ref       ref-tail.ts       "$here/receipts/ref"            whole yes -- "$traces"/ref/*.tsv

summary="host traces agree with every golden under every mask, in the straight-line, dispatch, structured, scope, layer, interrupt, fiber, job, deferred and ref forms"
if [ "$stamped" -eq 1 ]; then stamp_write trace-host "$key" "$summary"; fi
echo "PASS $summary"
