#!/usr/bin/env bash
# Host gate: the generated module is byte-identical to Lean's, passes the four
# host gates, and its traced runs agree with the goldens under every mask, at a
# large op budget and at a forced yield after every op. Writes receipts.
set -euo pipefail
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tools="${EFFECT4_TOOLS:-$repo_root/../effect4-tools}"
here="$repo_root/harness/trace"
cd "$repo_root"
lake build Effect4 >/dev/null
generated="$(mktemp)"; trap 'rm -f "$generated"' EXIT
lake env lean --run "$here/Generate.lean" fixture | grep -v '^warning: manifest out of date' > "$generated"
if [ "${1:-}" = "--update" ]; then cp "$generated" "$here/fixture.ts"; fi
cmp -s "$generated" "$here/fixture.ts" || { echo "FAIL harness/trace/fixture.ts drifted from Lean generation" >&2; diff "$generated" "$here/fixture.ts" | head -20 >&2; exit 1; }
echo "PASS harness/trace/fixture.ts regenerated byte-identically"
node "$tools/packages/harness/check.mjs" "$here"
mkdir -p "$here/receipts"
for golden in "$repo_root"/generated/traces/*.empty.tsv; do
  program="$(basename "$golden" .empty.tsv)"
  EFFECT4_PROGRAM="$program" node "$tools/packages/harness/trace.mjs" "$here" \
    --golden "$golden" --masks "$repo_root/generated/traces/masks.tsv" \
    --receipt "$here/receipts/$program.empty.json"
  # Yield as often as the run loop allows. rc.112 counts the op before its yield
  # check and the yield wrapper itself costs two ops, so 1 and 2 never progress;
  # 3 is the floor. The service-level rows must not change.
  EFFECT4_PROGRAM="$program" EFFECT4_MAX_OPS=3 EFFECT4_EXPECT_YIELDS=1 node "$tools/packages/harness/trace.mjs" "$here" \
    --golden "$golden" --masks "$repo_root/generated/traces/masks.tsv" | sed 's/^trace/trace(yield-every-op)/'
done
# --- the dispatch form: the flow-lowered module against the Flow-runner goldens ---
flow_generated="$(mktemp)"; trap 'rm -f "$generated" "$flow_generated"' EXIT
lake env lean --run "$here/Generate.lean" flow-fixture | grep -v '^warning: manifest out of date' > "$flow_generated"
if [ "${1:-}" = "--update" ]; then cp "$flow_generated" "$here/flow-fixture.ts"; fi
cmp -s "$flow_generated" "$here/flow-fixture.ts" || { echo "FAIL harness/trace/flow-fixture.ts drifted from Lean generation" >&2; diff "$flow_generated" "$here/flow-fixture.ts" | head -20 >&2; exit 1; }
echo "PASS harness/trace/flow-fixture.ts regenerated byte-identically"
structured_generated="$(mktemp)"; trap 'rm -f "$generated" "$flow_generated" "$structured_generated"' EXIT
lake env lean --run "$here/Generate.lean" structured-fixture | grep -v '^warning: manifest out of date' > "$structured_generated"
if [ "${1:-}" = "--update" ]; then cp "$structured_generated" "$here/structured-fixture.ts"; fi
cmp -s "$structured_generated" "$here/structured-fixture.ts" || { echo "FAIL harness/trace/structured-fixture.ts drifted from Lean generation" >&2; diff "$structured_generated" "$here/structured-fixture.ts" | head -20 >&2; exit 1; }
echo "PASS harness/trace/structured-fixture.ts regenerated byte-identically"
mkdir -p "$here/receipts/flow" "$here/receipts/structured"
# A resource-boundary golden carries `budget <yield setting> <n>` rows: the op
# budget counts primitives and the yield wrapper is itself primitives, so the
# frontier lands on the same row at both settings only with one budget each.
budget_row() { awk -F'\t' -v want="$2" '$1=="budget" && $2==want {print $3}' "$1"; }
for golden in "$repo_root"/generated/traces/flow/*.tsv; do
  base="$(basename "$golden" .tsv)"; program="${base%%.*}"
  default_budget="$(budget_row "$golden" default)"; yield3_budget="$(budget_row "$golden" yield3)"
  EFFECT4_PROGRAM="$program" EFFECT4_BUDGET="${default_budget:-100000}" \
    node "$tools/packages/harness/trace.mjs" "$here" \
    --golden "$golden" --masks "$repo_root/generated/traces/masks.tsv" --tail flow-tail.ts \
    --receipt "$here/receipts/flow/$base.json" | sed 's/^trace/trace(dispatch)/'
  EFFECT4_PROGRAM="$program" EFFECT4_MAX_OPS=3 EFFECT4_EXPECT_YIELDS=1 \
    EFFECT4_BUDGET="${yield3_budget:-100000}" \
    node "$tools/packages/harness/trace.mjs" "$here" \
    --golden "$golden" --masks "$repo_root/generated/traces/masks.tsv" --tail flow-tail.ts | sed 's/^trace/trace(dispatch,yield-every-op)/'
  # the structured form of the same program against the same golden, under the
  # same budget: both forms spend the same primitives up to the frontier
  EFFECT4_PROGRAM="$program" EFFECT4_BUDGET="${default_budget:-100000}" \
    node "$tools/packages/harness/trace.mjs" "$here" \
    --golden "$golden" --masks "$repo_root/generated/traces/masks.tsv" --tail structured-tail.ts \
    --receipt "$here/receipts/structured/$base.json" | sed 's/^trace/trace(structured)/'
done
# --- the Scopes family: its own module and tail over rc.112's Scope ---
scope_generated="$(mktemp)"; trap 'rm -f "$generated" "$flow_generated" "$structured_generated" "$scope_generated"' EXIT
lake env lean --run "$here/Generate.lean" scope-fixture | grep -v '^warning: manifest out of date' > "$scope_generated"
if [ "${1:-}" = "--update" ]; then cp "$scope_generated" "$here/scope-fixture.ts"; fi
cmp -s "$scope_generated" "$here/scope-fixture.ts" || { echo "FAIL harness/trace/scope-fixture.ts drifted from Lean generation" >&2; diff "$scope_generated" "$here/scope-fixture.ts" | head -20 >&2; exit 1; }
echo "PASS harness/trace/scope-fixture.ts regenerated byte-identically"
mkdir -p "$here/receipts/scope"
for golden in "$repo_root"/generated/traces/scope/*.tsv; do
  program="$(basename "$golden" .tsv)"
  EFFECT4_PROGRAM="$program" node "$tools/packages/harness/trace.mjs" "$here" \
    --golden "$golden" --masks "$repo_root/generated/traces/masks.tsv" --tail scope-tail.ts \
    --receipt "$here/receipts/scope/$program.json" | sed 's/^trace/trace(scope)/'
  EFFECT4_PROGRAM="$program" EFFECT4_MAX_OPS=3 EFFECT4_EXPECT_YIELDS=1 node "$tools/packages/harness/trace.mjs" "$here" \
    --golden "$golden" --masks "$repo_root/generated/traces/masks.tsv" --tail scope-tail.ts | sed 's/^trace/trace(scope,yield-every-op)/'
done
# --- interruption as decisions (M2): the interrupt tail over the same module ---
mkdir -p "$here/receipts/flow/interrupt"
for golden in "$repo_root"/generated/traces/flow/interrupt/*.tsv; do
  program="$(basename "$golden" .tsv)"
  EFFECT4_PROGRAM="$program" node "$tools/packages/harness/trace.mjs" "$here" \
    --golden "$golden" --masks "$repo_root/generated/traces/masks.tsv" --tail interrupt-tail.ts \
    --receipt "$here/receipts/flow/interrupt/$program.json" | sed 's/^trace/trace(interrupt)/'
  EFFECT4_PROGRAM="$program" EFFECT4_MAX_OPS=3 EFFECT4_EXPECT_YIELDS=1 \
    node "$tools/packages/harness/trace.mjs" "$here" \
    --golden "$golden" --masks "$repo_root/generated/traces/masks.tsv" --tail interrupt-tail.ts \
    | sed 's/^trace/trace(interrupt,yield-every-op)/'
done
# --- the Fibers family: two fibers over rc.112, interleaved by the tape ---
fiber_generated="$(mktemp)"; trap 'rm -f "$generated" "$flow_generated" "$structured_generated" "$scope_generated" "$fiber_generated"' EXIT
lake env lean --run "$here/Generate.lean" fiber-fixture | grep -v '^warning: manifest out of date' > "$fiber_generated"
if [ "${1:-}" = "--update" ]; then cp "$fiber_generated" "$here/fiber-fixture.ts"; fi
cmp -s "$fiber_generated" "$here/fiber-fixture.ts" || { echo "FAIL harness/trace/fiber-fixture.ts drifted from Lean generation" >&2; diff "$fiber_generated" "$here/fiber-fixture.ts" | head -20 >&2; exit 1; }
echo "PASS harness/trace/fiber-fixture.ts regenerated byte-identically"
mkdir -p "$here/receipts/fiber"
# There is no yield-every-op run here, and the refusal is the packet's finding.
# The tape drives `TapeScheduler.shouldYield`; at rc.112's own floor of 3 the
# run loop yields on its own, a deferred child starts with no `decide` row to
# account for it, and the sequential projection's `false` stops being a fact
# about the run. counterexample: E4-SEM-CE-011
for golden in "$repo_root"/generated/traces/fiber/*.tsv; do
  program="$(basename "$golden" .tsv)"
  EFFECT4_PROGRAM="$program" node "$tools/packages/harness/trace.mjs" "$here" \
    --golden "$golden" --masks "$repo_root/generated/traces/masks.tsv" --tail fiber-tail.ts \
    --receipt "$here/receipts/fiber/$program.json" | sed 's/^trace/trace(fiber)/'
done
echo "PASS host traces agree with every golden under every mask (straight-line, dispatch, structured, scope, interrupt and fiber forms)"
