#!/usr/bin/env bash
# Host gate: the generated module is byte-identical to Lean's, passes the four
# host gates, and its traced runs agree with the goldens under every mask, at a
# large op budget and at a forced yield after every op. Writes receipts.
set -euo pipefail
repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tools="${EFFECT4_TOOLS:-$repo_root/../effect4-tools}"
here="$repo_root/harness/trace"
cd "$repo_root"
lake build Effect4 >/dev/null
generated="$(mktemp)"; trap 'rm -f "$generated"' EXIT
lake env lean --run "$here/Generate.lean" fixture | grep -v '^warning: manifest out of date' > "$generated"
if [ "${1:-}" = "--update" ]; then cp "$generated" "$here/fixture.ts"; fi
cmp -s "$generated" "$here/fixture.ts" || { echo "FAIL harness/trace/fixture.ts drifted from Lean generation" >&2; diff "$generated" "$here/fixture.ts" | head -20 >&2; exit 1; }
echo "PASS harness/trace/fixture.ts regenerated byte-identically"
node "$tools/packages/harness/check.mjs" "$here"
mkdir -p "$here/receipts"
for golden in "$repo_root"/generated/traces/*.empty.tsv; do
  program="$(basename "$golden" .empty.tsv)"
  EFFECT4_PROGRAM="$program" node "$tools/packages/harness/trace.mjs" "$here" \
    --golden "$golden" --masks "$repo_root/generated/traces/masks.tsv" \
    --receipt "$here/receipts/$program.empty.json"
  # Yield as often as the run loop allows. rc.112 counts the op before its yield
  # check and the yield wrapper itself costs two ops, so 1 and 2 never progress;
  # 3 is the floor. The service-level rows must not change.
  EFFECT4_PROGRAM="$program" EFFECT4_MAX_OPS=3 EFFECT4_EXPECT_YIELDS=1 node "$tools/packages/harness/trace.mjs" "$here" \
    --golden "$golden" --masks "$repo_root/generated/traces/masks.tsv" | sed 's/^trace/trace(yield-every-op)/'
done
# --- the dispatch form: the flow-lowered module against the Flow-runner goldens ---
flow_generated="$(mktemp)"; trap 'rm -f "$generated" "$flow_generated"' EXIT
lake env lean --run "$here/Generate.lean" flow-fixture | grep -v '^warning: manifest out of date' > "$flow_generated"
if [ "${1:-}" = "--update" ]; then cp "$flow_generated" "$here/flow-fixture.ts"; fi
cmp -s "$flow_generated" "$here/flow-fixture.ts" || { echo "FAIL harness/trace/flow-fixture.ts drifted from Lean generation" >&2; diff "$flow_generated" "$here/flow-fixture.ts" | head -20 >&2; exit 1; }
echo "PASS harness/trace/flow-fixture.ts regenerated byte-identically"
mkdir -p "$here/receipts/flow"
for golden in "$repo_root"/generated/traces/flow/*.tsv; do
  base="$(basename "$golden" .tsv)"; program="${base%%.*}"
  EFFECT4_PROGRAM="$program" node "$tools/packages/harness/trace.mjs" "$here" \
    --golden "$golden" --masks "$repo_root/generated/traces/masks.tsv" --tail flow-tail.ts \
    --receipt "$here/receipts/flow/$base.json" | sed 's/^trace/trace(dispatch)/'
  EFFECT4_PROGRAM="$program" EFFECT4_MAX_OPS=3 EFFECT4_EXPECT_YIELDS=1 node "$tools/packages/harness/trace.mjs" "$here" \
    --golden "$golden" --masks "$repo_root/generated/traces/masks.tsv" --tail flow-tail.ts | sed 's/^trace/trace(dispatch,yield-every-op)/'
done
echo "PASS host traces agree with every golden under every mask (straight-line and dispatch forms)"
