#!/usr/bin/env python3
"""Generate the engine program mirror from selected source data and actual engine declarations.

Properties: no independent family or ordinal list; exact named payload checks; known
historical append shortages are reported as unavailable execution. This does not regenerate
or certify the frozen engine. Deterministic products are written only after validation.
"""
import argparse
import json
from pathlib import Path
import subprocess
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent/'lib'))
import generated_inputs as inputs
from program_structure import selected_view

ROOT = Path(__file__).resolve().parents[1]
SOURCE = 'scripts/generate-engine-structure.py'
FILES = ['scripts/lib/program_structure.py', 'ocaml/eff/program-structure.json',
         'ocaml/engine/api_engine.ml']

def emit(descriptor, engine):
    common, boundaries = selected_view(descriptor, engine)
    # Retain the source's mutual groups. One giant recursive group merges independent
    # record-label scopes (e.g. ServiceKey.name and Row.name) and fails OCaml warning 30.
    groups = {family['name']: index for index, block in enumerate(descriptor['blocks'])
              for family in block}
    definitions = []
    previous = None
    for family, declaration, _ in common:
        group = groups[family['name']]
        definitions.append(('  and ' if group == previous else '  type ') +
                           declaration.head + ' = ' + declaration.body)
        previous = group
    signature = 'module type PROGRAM_TYPES = sig\n' + '\n'.join(definitions) + '\nend\n'
    source_rows = []
    engine_rows = []
    for family, _, names in common:
        if family['structure']: continue
        label = family['label']
        source_rows.append(f'  ({json.dumps(label)}, Eff_types.ctor_names_{label})')
        engine_rows.append(f'  ({json.dumps(label)}, [' + '; '.join(map(json.dumps, names)) + '])')
    text = signature + '\nlet source_ctor_names = [\n' + ';\n'.join(source_rows) + '\n]\n'
    text += '\nlet engine_ctor_names = [\n' + ';\n'.join(engine_rows) + '\n]\n'
    report = {'format':'effect4-engine-structure-v1',
              'claim':'selected source shape checked against frozen engine declarations; no execution cutover',
              'families':[family['name'] for family,_,_ in common], 'unavailable':boundaries}
    return text, json.dumps(report, indent=2) + '\n'

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--descriptor', type=Path, default=ROOT/'ocaml/eff/program-structure.json')
    parser.add_argument('--engine', type=Path, default=ROOT/'ocaml/engine/api_engine.ml')
    parser.add_argument('--out', type=Path, default=ROOT/'ocaml/engine')
    args = parser.parse_args()
    code, report = emit(json.loads(args.descriptor.read_text()), args.engine.read_text())
    revision = subprocess.check_output(['git','rev-parse','--short','HEAD'], cwd=ROOT, text=True).strip()
    version = (ROOT/'lean-toolchain').read_text().strip().split(':v')[-1]
    digest = inputs.digest(SOURCE, (), tuple(FILES))
    stamp = f'cut-from: rev={revision} toolchain={version} inputs={digest}'
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out/'e4_program_layout.ml').write_text('(* ' + stamp + ' *)\n' +
        '(* GENERATED by scripts/generate-engine-structure.py; do not edit. *)\n' + code)
    (args.out/'e4_program_layout.json').write_text(report)
    (args.out/'e4_program_layout.json.cut-from').write_text(stamp+'\n')
    print('engine structure: generated selected mirror and explicit historical boundaries')

if __name__ == '__main__':
    try: main()
    except (ValueError, KeyError, OSError) as error:
        raise SystemExit('FAIL engine structure: ' + str(error))
