import Effect4.Laws.Auto.Obligations
import Effect4.Laws.Program.EvaluateR
import Effect4.Laws.Program.Typed.TypedStateDecl
import Effect4.Laws.Program.Typed.PositionGate

/-!
The reference machine's typed-state skeleton. Lean derives the declarations during
elaboration; the source table is the only hand-maintained input. The position gate covers
all four census roots, including interpreter hooks; the skeleton covers stored state and
command residue. Refused source rows remain explicit debt, not proved invariant clauses.
-/
namespace Effect4.Program.Typed

/-- Where a position's expected type comes from, as data the predicates read. -/
inductive Expect
  | root
  | fiber (id : Effect4.FiberId)
  | hook (name : String)


#position_gate Effect4.Program.Sched.RState Effect4.Program.Sched.RCmd
  Effect4.Program.Sched.RInterp Effect4.Program.Sched.RIter

/-- info: typed state: 17 predicates, 12 carrier predicates, 2 refusals -/
#guard_msgs in
#typed_state Effect4.Program.Sched.RState Effect4.Program.Sched.RCmd
  using Effect4.Program.Typed.sources columns Effect4.Machine.Stores

/-! Pending snapshot for the semantic carrier change. The explicit theorem header
is unchanged; its Expect parameter now ranges over three constructors. Keep the
existing searched proof unchanged until the fresh Phase B census. Generated frame
statements are regenerated by #frame_rules, never hand-maintained here. -/
namespace M2ExpectWanted

def saved_from_clauses {W : Type} (P : Preds W) (w : W) (e : Expect)
    (x : Effect4.Program.Sched.RSaved)
    (_current : P.program w e x.current) (_stack : P.StackOk w e x.stack)
    (_interrupted : P.InterruptOnly w e x.interruptedCause) :
    ProofGraph.Obligation (RSavedOk P w e x) := ⟨⟩

end M2ExpectWanted

/-- The named bank assembles a saved-frame invariant from its three clauses. -/
theorem saved_from_clauses {W : Type} (P : Preds W) (w : W) (e : Expect)
    (x : Effect4.Program.Sched.RSaved)
    (current : P.program w e x.current) (stack : P.StackOk w e x.stack)
    (interrupted : P.InterruptOnly w e x.interruptedCause) : RSavedOk P w e x := by
  aesop (rule_sets := [Effect4.TypedState])

end Effect4.Program.Typed

#typed_state_obligations Effect4.Program.Typed.M2ExpectWanted ceiling 1 using aesop (rule_sets := [Effect4.TypedState])
