import Effect4.Laws.Machine.Handles
import Effect4.Laws.Program.Progress
import Effect4.Laws.Program.Typed
import Effect4.Laws.Program.Typed.State
import Effect4.Laws.Effects.Protocol
import Effect4.Laws.Auto.Obligations

/-!
Phase B World statement skeleton. Proof obligations remain explicit below.
Authority: kickoff §2.2 (the amended order), §4 (Completion.ofRefGet only
reads the heap typing table); decisions rows 44–45; deep-dive §3.

The existing existence world is the base record, so its six handle-existence
arms are reused. The new fields are ghost tables in Laws. Cell compatibility
preserves each prior keywise typing judgment; it does not assert either world
is valid. Consequently reflexivity is stated on every World, including invalid
ones. Coverage and typing of fresh cells are separate allocation conclusions.

This slice provides column typing only. Nested HandlesFit belongs to M3; no
coarse Val.hasTy check is claimed to establish handle existence or nested type
agreement. Due entries do not enter PromiseTable and are never typed via Γ.
ParkHandshake and the due/park contract remain separate M4 obligations.

The indexed column quantifiers are generated by #typed_state in Typed.State.
HeapTable and PromiseTable below are aliases of those exact per-field clauses;
Preds stores only HeapCell/PromiseCell leaves. Due work keeps its separate grouped
PromiseTable predicate in the generated bundle and does not enter this cell table.
No due completion is typed using the resumed fiber's final Γ type.

External handle shape admission uses the actual allocation spellings. Stores.le
only orders their lengths. Accordingly this draft does not claim ValueOk or
CompletionOk is monotone for arbitrary worlds: M3's result weakening must also
carry external-table Extends, or a legal-step spelling-agreement premise.

The three store-extension statements use actual syncOpStep equations as premises;
there is no duplicate operational semantics here. Fork's extension is the ghost
id/table update. The accepted downstream Typed/ForkSource obligation connects
the actual allocated child and source body; reachable typing and the complete
fiber protocol remain M3.
-/

set_option autoImplicit false

namespace Effect4.Program.Typed

open Effect4 Effect4.Machine

abbrev FiberTable := FiberId → Option EffTy
abbrev PromiseTableTy := DeferredKey → Option (Ty × Ty)
abbrev HeapTableTy := RefKey → Option Ty

structure World extends Effect4.Machine.World where
  Γ : FiberTable
  «Π» : PromiseTableTy
  Ρ : HeapTableTy

/-- Existing keys retain their declarations; unused keys are unconstrained. -/
def TableExtends {K A : Type} (old newer : K → Option A) : Prop :=
  ∀ key value, old key = some value → newer key = some value

/-- Ghost-table update. Its extension law requires the key to be fresh. -/
def tableInsert {K A : Type} [DecidableEq K]
    (table : K → Option A) (key : K) (value : A) : K → Option A :=
  fun query => if query = key then some value else table query

/-- Shape admission at the actual external allocation table, not handle typing. -/
def ValueOk (w : World) (ty : Ty) (value : Val) : Prop :=
  Val.hasTy value ty w.state.externals.allocated = true

/-- Completion typing has no heap-existence premise. The reference arm reads Ρ
and requires its value type to fit the promise's answer column. It cannot fail
with a typed error; the promise error column imposes no additional restriction. -/
def CompletionOk (w : World) (types : Ty × Ty) :
    Completion Val Err Defect FiberId Ann → Prop
  | .ofExit (.success value) => ValueOk w types.1 value
  | .ofExit (.failure cause) =>
    causeAdmits (fun value ty => Val.hasTy value ty w.state.externals.allocated)
      types.2 cause = true
  | .ofRefGet cell => ∃ ty, w.Ρ cell = some ty ∧ ty.sub types.1 = true

/-- The generated heap-column leaf: actual field payload in, table lookup read
here. Coverage is separate; an undeclared key satisfies this conditional leaf. -/
def HeapCell (w : World) (key : RefKey) (value : Val) : Prop :=
  ∀ ty, w.Ρ key = some ty → ValueOk w ty value

/-- The generated promise-column leaf has the actual DeferredCell carrier.
Waiters and due work have no type inferred from their target fiber. -/
def PromiseCell (w : World) (key : DeferredKey) (cell : DeferredCell) : Prop :=
  ∀ types, w.«Π» key = some types →
    ∀ completion, cell.completion = some completion → CompletionOk w types completion

/-- The generated heap field clause, instantiated with this world's leaf. -/
abbrev HeapTable (w : World) : Prop :=
  Columns.Stores_refs HeapCell w w.state.refs

/-- The generated deferred-cell field clause; due work is a different column. -/
abbrev PromiseTable (w : World) : Prop :=
  Columns.DeferredStore_cells PromiseCell w w.state.deferreds.cells

/-- Coverage is explicit even for pending promise cells, and is independent of
the conditional leaf's shape. It is not hidden in the column generator. -/
def HeapCoverage (w : World) : Prop :=
  ∀ i value, w.state.refs[i]? = some value → ∃ ty, w.Ρ ⟨i⟩ = some ty

def PromiseCoverage (w : World) : Prop :=
  ∀ i cell, w.state.deferreds.cells[i]? = some cell → ∃ types, w.«Π» ⟨i⟩ = some types

/-- Keywise stored-cell judgments for the order, separate from generator leaves.
Liveness is handled by the existing existence judgment and coverage. -/
def HeapTypedAt (w : World) (key : RefKey) (ty : Ty) : Prop :=
  w.Ρ key = some ty ∧
    ∀ value, refPeek w.state.refs key = some value → ValueOk w ty value

def PromiseTypedAt (w : World) (key : DeferredKey) (types : Ty × Ty) : Prop :=
  w.«Π» key = some types ∧
    ∀ cell, w.state.deferreds.cellAt key = some cell →
      ∀ completion, cell.completion = some completion → CompletionOk w types completion

/-- Preservation implications give a preorder on arbitrary, possibly invalid worlds. -/
def CellCompatible (w newer : World) : Prop :=
  (∀ key ty, HeapTypedAt w key ty → HeapTypedAt newer key ty) ∧
  (∀ key types, PromiseTypedAt w key types → PromiseTypedAt newer key types)

def World.le (w newer : World) : Prop :=
  Effect4.Machine.World.le w.toWorld newer.toWorld ∧
  TableExtends w.Γ newer.Γ ∧ TableExtends w.«Π» newer.«Π» ∧
  TableExtends w.Ρ newer.Ρ ∧ CellCompatible w newer

/-- Ghost updates used by the four allocation contracts. -/
def World.addFiber (w : World) (id : FiberId) (ty : EffTy) : World :=
  { w with ids := w.ids ++ [id], Γ := tableInsert w.Γ id ty }

def World.addRef (w : World) (state : Stores) (key : RefKey) (ty : Ty) : World :=
  { w with state := state, Ρ := tableInsert w.Ρ key ty }

def World.addPromise (w : World) (state : Stores) (key : DeferredKey)
    (types : Ty × Ty) : World :=
  { w with state := state, «Π» := tableInsert w.«Π» key types }

namespace WorldWanted

variable {K A : Type}

def table_refl (table : K → Option A) : ProofGraph.Obligation
    (TableExtends table table) := ⟨⟩
#proof_wanted table_refl

def table_trans (a b c : K → Option A) : ProofGraph.Obligation
    (TableExtends a b → TableExtends b c → TableExtends a c) := ⟨⟩
#proof_wanted table_trans

def insert_extends [DecidableEq K] (table : K → Option A) (key : K) (value : A)
    (_fresh : table key = none) : ProofGraph.Obligation
    (TableExtends table (tableInsert table key value)) := ⟨⟩
#proof_wanted insert_extends

def insert_here [DecidableEq K] (table : K → Option A) (key : K) (value : A) :
    ProofGraph.Obligation (tableInsert table key value key = some value) := ⟨⟩
#proof_wanted insert_here

def insert_other [DecidableEq K] (table : K → Option A) (key other : K) (value : A)
    (_different : other ≠ key) : ProofGraph.Obligation
    (tableInsert table key value other = table other) := ⟨⟩
#proof_wanted insert_other

def order_refl (w : World) : ProofGraph.Obligation (w.le w) := ⟨⟩
#proof_wanted order_refl

def order_trans (a b c : World) : ProofGraph.Obligation
    (a.le b → b.le c → a.le c) := ⟨⟩
#proof_wanted order_trans

/-- Freeze the exact connection to the existing protocol's order interface. -/
def protocol_order : ProofGraph.Obligation
    (∃ order : Effect4.Laws.Effects.WorldOrder World, order.le = World.le) := ⟨⟩
#proof_wanted protocol_order

def heap_typed_at_mono (w newer : World) (key : RefKey) (ty : Ty) : ProofGraph.Obligation
    (w.le newer → HeapTypedAt w key ty → HeapTypedAt newer key ty) := ⟨⟩
#proof_wanted heap_typed_at_mono

def promise_typed_at_mono (w newer : World) (key : DeferredKey) (types : Ty × Ty) :
    ProofGraph.Obligation
    (w.le newer → PromiseTypedAt w key types → PromiseTypedAt newer key types) := ⟨⟩
#proof_wanted promise_typed_at_mono

def ref_completion_inv (w : World) (cell : RefKey) (types : Ty × Ty) :
    ProofGraph.Obligation
    (CompletionOk w types (.ofRefGet cell) ↔
      ∃ ty, w.Ρ cell = some ty ∧ ty.sub types.1 = true) := ⟨⟩

/-- The columns plus coverage recover exactly the keywise judgments used by
the order. This is the seam between generated leaves and handler premises. -/
def heap_coverage_iff (w : World) : ProofGraph.Obligation
    ((HeapTable w ∧ HeapCoverage w) ↔
      ∀ key value, refPeek w.state.refs key = some value →
        ∃ ty, HeapTypedAt w key ty) := ⟨⟩
#proof_wanted heap_coverage_iff

def promise_coverage_iff (w : World) : ProofGraph.Obligation
    ((PromiseTable w ∧ PromiseCoverage w) ↔
      ∀ key cell, w.state.deferreds.cellAt key = some cell →
        ∃ types, PromiseTypedAt w key types) := ⟨⟩
#proof_wanted promise_coverage_iff

/-- The old all-nat column is exactly the polymorphic column when every live
heap key is declared nat. Entries beyond the heap do not affect the equivalence. -/
def heapNat_iff (w : World)
    (_types : ∀ cell value, refPeek w.state.refs cell = some value →
      w.Ρ cell = some .nat) : ProofGraph.Obligation
    (HeapTable w ↔ Effect4.Program.Stores.HeapNat w.state) := ⟨⟩
#proof_wanted heapNat_iff

/-- Freshness is logical table freshness, not merely absence from an id list. -/
def fork_extension (w : World) (id : FiberId) (ty : EffTy)
    (_fresh : w.Γ id = none) : ProofGraph.Obligation
    (w.le (w.addFiber id ty) ∧
      (w.addFiber id ty).Γ id = some ty ∧
      (HeapTable w → HeapTable (w.addFiber id ty)) ∧
      (PromiseTable w → PromiseTable (w.addFiber id ty)) ∧
      (HeapCoverage w → HeapCoverage (w.addFiber id ty)) ∧
      (PromiseCoverage w → PromiseCoverage (w.addFiber id ty))) := ⟨⟩
#proof_wanted fork_extension

def refMake_extension (w : World) (value : Val) (ty : Ty) (state : Stores) (key : RefKey)
    (_step : syncOpStep (.refMake value) w.state = some (state, Val.cell key))
    (_fresh : w.Ρ key = none) (_value : ValueOk w ty value) : ProofGraph.Obligation
    (w.le (w.addRef state key ty) ∧ HeapTypedAt (w.addRef state key ty) key ty ∧
      (HeapTable w → HeapTable (w.addRef state key ty)) ∧
      (PromiseTable w → PromiseTable (w.addRef state key ty)) ∧
      (HeapCoverage w → HeapCoverage (w.addRef state key ty)) ∧
      (PromiseCoverage w → PromiseCoverage (w.addRef state key ty))) := ⟨⟩
#proof_wanted refMake_extension

def deferredMake_extension (w : World) (types : Ty × Ty) (state : Stores)
    (key : DeferredKey)
    (_step : syncOpStep .deferredMake w.state = some (state, Val.promise key))
    (_fresh : w.«Π» key = none) : ProofGraph.Obligation
    (w.le (w.addPromise state key types) ∧
      PromiseTypedAt (w.addPromise state key types) key types ∧
      (HeapTable w → HeapTable (w.addPromise state key types)) ∧
      (PromiseTable w → PromiseTable (w.addPromise state key types)) ∧
      (HeapCoverage w → HeapCoverage (w.addPromise state key types)) ∧
      (PromiseCoverage w → PromiseCoverage (w.addPromise state key types))) := ⟨⟩
#proof_wanted deferredMake_extension

/-- Memo allocation uses the same deferred allocator, with the layer's own type.
The returned value is the layer scope; the new promise key is the allocator's key. -/
def memoBuild_extension (w : World) (types : Ty × Ty) (state : Stores)
    (layer : LayerId) (memoMap : MemoMapId) (answer : Val)
    (_step : syncOpStep (.memoBuild layer memoMap) w.state = some (state, answer))
    (_fresh : w.«Π» w.state.deferreds.make.1 = none) : ProofGraph.Obligation
    (let key := w.state.deferreds.make.1
     w.le (w.addPromise state key types) ∧
      PromiseTypedAt (w.addPromise state key types) key types ∧
      (HeapTable w → HeapTable (w.addPromise state key types)) ∧
      (PromiseTable w → PromiseTable (w.addPromise state key types)) ∧
      (HeapCoverage w → HeapCoverage (w.addPromise state key types)) ∧
      (PromiseCoverage w → PromiseCoverage (w.addPromise state key types))) := ⟨⟩
#proof_wanted memoBuild_extension

/-- Retained universal falsifier: allocation growth alone cannot weaken HeapNat. -/
def heapNotMonotone : ProofGraph.Obligation
    (¬ (∀ state newer : Stores, state.le newer →
      Effect4.Program.Stores.HeapNat state → Effect4.Program.Stores.HeapNat newer)) := ⟨⟩
#proof_wanted heapNotMonotone

end WorldWanted

/-- Closed control data, used only to refute weakening by allocation growth. -/
def worldGood : World :=
  { ids := [], state := { Stores.empty with refs := [.nat 0] }
    Γ := fun _ => none, «Π» := fun _ => none
    Ρ := fun key => if key.index = 0 then some .nat else none }

def worldBad : World :=
  { worldGood with state := { worldGood.state with refs := [.bool false] } }

namespace WorldControlWanted

def stores_ordered : ProofGraph.Obligation (worldGood.state.le worldBad.state) := ⟨⟩
#proof_wanted stores_ordered

def heap_good : ProofGraph.Obligation (HeapTable worldGood) := ⟨⟩
#proof_wanted heap_good

def heap_bad : ProofGraph.Obligation (¬ HeapTable worldBad) := ⟨⟩
#proof_wanted heap_bad

def world_order_refuses : ProofGraph.Obligation (¬ worldGood.le worldBad) := ⟨⟩
#proof_wanted world_order_refuses

/-- An invalid world still relates to itself; validity is not an order premise. -/
def invalid_refl : ProofGraph.Obligation (worldBad.le worldBad) := ⟨⟩
#proof_wanted invalid_refl

end WorldControlWanted

-- Phase B: census built dependencies first, then elaborate this statement snapshot.
-- Remove only the wanted markers search actually closes; the live slice gate uses
-- exactly those frozen statements. Expected declaration count: 24 total (19 + 5).
-- #typed_state_obligations Effect4.Program.Typed.WorldWanted ceiling 19 using aesop
-- #typed_state_obligations Effect4.Program.Typed.WorldControlWanted ceiling 5 using aesop

end Effect4.Program.Typed

#typed_state_obligations Effect4.Program.Typed.WorldControlWanted ceiling 5 using aesop (rule_sets := [Effect4.Stores, Effect4.TypedState])
#typed_state_obligations Effect4.Program.Typed.WorldWanted ceiling 19 using aesop (rule_sets := [Effect4.Stores, Effect4.TypedState])
