(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400007`, seed 400007, 14 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400007 () =
  let v0 = Fibers_fixture.fork_detach 2 in
  let _v1 = Fibers_fixture.cleanups () in
  let _v2 = Fibers_fixture.started () in
  let _v3 = Fibers_fixture.cleanups () in
  let _v4 = Fibers_fixture.started () in
  let _v5 = Fibers_fixture.await_value v0 in
  ignore (Fibers_fixture.interrupt v0);
  let v6 = Fibers_fixture.fork 1 in
  let _v7 = Fibers_fixture.started () in
  let _v8 = Fibers_fixture.cleanups () in
  let _v9 = Extra_fixture.await_all [ v6 ] in
  let _v10 = Fibers_fixture.started () in
  let _v11 = Store_fixtures.ref_make 4 in
  let v12 = Fibers_fixture.join v0 in
  v12

let programs : (string * (unit -> value)) list = [ ("p400007", corpus_p400007) ]
