import Effect4.Api.HostProtocol
import Effect4.Program.Profile
import Lean.Data.Json
import Tools.GeneratedStamp

/-! Byte projection of the first-order HostProtocol. Outside the audited runtime graph.
The schema describes transport structure; Envelope validates row/request/completion meaning. -/
open Lean Effect4.Api.HostProtocol
namespace Tools.HostProtocol

def stateName : State → String
  | .idle => "idle" | .awaitingAsync => "awaitingAsync" | .parked => "parked" | .terminated => "terminated"
def tagName : Tag → String
  | .submit => "submit" | .answer => "answer" | .advanceClock => "advanceClock"
  | .cancel => "cancel" | .schedule => "schedule"
def typeName : FieldType → String
  | .natural => "natural" | .boolean => "boolean" | .text => "text" | .json => "json"
def fieldSchema : FieldType → Json
  | .natural => Json.mkObj [("type", "integer"), ("minimum", toJson (0 : Nat)), ("maximum", toJson Effect4.Program.rc112.natBound)]
  | .boolean => Json.mkObj [("type", "boolean")]
  | .text => Json.mkObj [("type", "string"), ("maxLength", toJson (4096 : Nat))]
  | .json => Json.mkObj []

def datum : Json := Json.mkObj [
  ("version", toJson hostProtocol.version), ("initial", .str (stateName hostProtocol.initial)),
  ("states", toJson (hostProtocol.states.map stateName)),
  ("transitions", toJson (hostProtocol.transitions.map fun e =>
    toJson [stateName e.source, tagName e.label, stateName e.target])),
  ("records", toJson (hostProtocol.records.map fun shape => Json.mkObj [
    ("kind", .str shape.kind), ("fields", Json.mkObj (shape.fields.map fun (n, t) => (n, .str (typeName t))))]))]

def recordSchema (shape : RecordShape) : Json := Json.mkObj [
  ("type", "object"), ("additionalProperties", .bool false),
  ("required", toJson (["kind", "version", "session"] ++ shape.fields.map Prod.fst)),
  ("properties", Json.mkObj ([("kind", Json.mkObj [("const", .str shape.kind)]),
    ("version", Json.mkObj [("const", toJson hostProtocol.version)]),
    ("session", fieldSchema .text)] ++ shape.fields.map fun (n, t) => (n, fieldSchema t)))]

def schema : Json := Json.mkObj [
  ("$schema", "https://json-schema.org/draft/2020-12/schema"),
  ("title", "Effect4 keyed host decision record v2"),
  ("description", "One decision record; row payload meaning is checked by Envelope. Receipt and application are distinct."),
  ("oneOf", toJson (hostProtocol.records.map recordSchema))]

end Tools.HostProtocol

def main (args : List String) : IO UInt32 := do
  match args with
  | [directory] =>
    let dir : System.FilePath := directory
    IO.FS.createDirAll dir
    let stamp ← Tools.GeneratedStamp.line "tools/Tools/HostProtocol.lean"
    IO.FS.writeFile (dir / "protocol.gen.ts")
      ("// " ++ stamp ++ "\n// Generated by tools/Tools/HostProtocol.lean; do not edit.\nexport const hostProtocol = " ++
       Tools.HostProtocol.datum.pretty ++ " as const\n" ++
       "export type ProtocolState = typeof hostProtocol.states[number]\n" ++
       "export type ProtocolTag = typeof hostProtocol.transitions[number][1]\n")
    IO.FS.writeFile (dir / "tape.schema.json") (Tools.HostProtocol.schema.pretty ++ "\n")
    Tools.GeneratedStamp.sidecar (dir / "tape.schema.json") stamp
    pure 0
  | _ => IO.eprintln "usage: HostProtocol OUTPUT_DIRECTORY"; pure 2
