(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400219`, seed 400219, 22 operations.
   Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400219 () =
  let v0 = Fibers_fixture.fork 0 in
  let _v1 = Fibers_fixture.cleanups () in
  ignore (Fibers_fixture.interrupt v0);
  let v2 = Fibers_fixture.fork 2 in
  let v3 = Fibers_fixture.fork 5 in
  let v4 = Store_fixtures.scope_make () in
  let _v5 = Fibers_fixture.await_value v0 in
  ignore (Store_fixtures.scope_remove v4 4);
  let v6 = Store_fixtures.ref_make 7 in
  let _v7 = Fibers_fixture.cleanups () in
  let _v8 = Fibers_fixture.cleanups () in
  let _v9 = Store_fixtures.scope_make () in
  let _v10 = Fibers_fixture.cleanups () in
  let _v11 = Fibers_fixture.cleanups () in
  ignore (Store_fixtures.ref_update v6 4);
  let _v12 = Fibers_fixture.cleanups () in
  let _v13 = Fibers_fixture.started () in
  let _v14 = Fibers_fixture.cleanups () in
  ignore (Fibers_fixture.interrupt v3);
  let _v15 = Fibers_fixture.await_value v3 in
  ignore (Extra_fixture.yield ());
  let v16 = Fibers_fixture.join v2 in
  v16

let programs : (string * (unit -> value)) list = [ ("p400219", corpus_p400219) ]
