(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400106`, seed 400106, 23 operations.
   Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400106 () =
  let v0 = Fibers_fixture.fork 2 in
  let _v1 = Fibers_fixture.cleanups () in
  let _v2 = Fibers_fixture.started () in
  let _v3 = Fibers_fixture.join v0 in
  let _v4 = Fibers_fixture.await_error v0 in
  let v5 = Fibers_fixture.fork 0 in
  ignore (Fibers_fixture.interrupt v0);
  let _v6 = Fibers_fixture.join v5 in
  let _v7 = Fibers_fixture.started () in
  let _v8 = Store_fixtures.scope_make () in
  let _v9 = Fibers_fixture.cleanups () in
  let v10 = Fibers_fixture.fork 1 in
  let _v11 = Fibers_fixture.cleanups () in
  let _v12 = Fibers_fixture.await_value v10 in
  let _v13 = Fibers_fixture.started () in
  let _v14 = Store_fixtures.def_make () in
  let _v15 = Store_fixtures.ref_make 9 in
  let _v16 = Extra_fixture.interrupt_all [ v5 ] in
  let _v17 = Fibers_fixture.fork 2 in
  let v18 = Fibers_fixture.fork 0 in
  let _v19 = Fibers_fixture.cleanups () in
  let _v20 = Fibers_fixture.await_value v5 in
  let v21 = Fibers_fixture.join v18 in
  v21

let programs : (string * (unit -> value)) list = [ ("p400106", corpus_p400106) ]
