#!/usr/bin/env bash
# The avatar as a wasm_of_ocaml executable: the fourth-host spike.
#
#   wsl -e bash /mnt/c/Users/kokok/Dev/lean4-effect4/ocaml/wasm/tools/build-wasm.sh [mode]
#
# `mode` is the wasm_of_ocaml effect mode: `cps` (default; runs on this machine's node 22),
# `jspi` (needs node >= 25) or `native` (WasmFX; needs a node canary). See README §4.
#
# Nothing under `ocaml/avatar/` is read-write: the avatar's sources are COPIED to an
# out-of-tree build directory (`$E4_WASM_BUILD`, default `~/Dev/e4-wasm`, the precedent of
# `ocaml/link/README.md` §Layout's `~/Dev/e4-link`) and the copy is what is rewritten. The
# pinned `effect4` switch is never entered by this script; the `effect4-wasm` switch
# (OCaml 5.1.1, wasm_of_ocaml 6.4.1, js_of_ocaml 6.4.1, dune 3.24.2, binaryen 120) is.
#
# Every rewrite of the copy is one row of README §5 "what changed for wasm".
set -uo pipefail
here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo=$(CDPATH= cd -- "$here/../.." && pwd)          # <repo>/ocaml
avatar="$repo/avatar"
mode=${1:-cps}
B=${E4_WASM_BUILD:-$HOME/Dev/e4-wasm}/avatar-$mode

echo "=== build-wasm.sh mode=$mode  src=$avatar  build=$B ==="
[ -d "$avatar" ] || { echo "no avatar at $avatar" >&2; exit 1; }

rm -rf "$B"; mkdir -p "$B"

# (1) The sources the library and the two executables name. `dune`'s `(modules ...)` list is
#     the authority; `jsprobe.ml` and `fuzz_register.ml` are outside the build and are NOT
#     copied (jsprobe needs its own jsoo runtime file and `-no-check-prims`).
for m in deep_fibers deep_stores deep_context deep_layer deep_forkflow avatar_trace \
         deep_census deep_clauses deep_witnesses fibers_fixture store_fixtures \
         extra_fixture corpus_dsl corpus_run avatar_main avatar_witnesses; do
  cp "$avatar/$m.ml" "$B/" || { echo "missing $m.ml" >&2; exit 1; }
done
# `corpus_data.ml` is not copied: it is dune's, generated from `corpus/programs.txt` by the
# rule below, exactly as in the avatar.
mkdir -p "$B/corpus"
cp "$avatar/corpus/programs.txt" "$B/corpus/"
cp "$avatar/effect4-avatar.opam" "$B/"

# (2) `dune-project`. The avatar declares `(lang dune 3.0)`; dune's wasm mode is 3.17+, so
#     the copy declares 3.17. Nothing else in the avatar's dune file depends on the version.
cat > "$B/dune-project" <<'EOF'
(lang dune 3.17)
; COPY of ocaml/avatar/dune-project with `(lang dune 3.0)` -> `(lang dune 3.17)`:
; dune's `(modes wasm)` and `(wasm_of_ocaml ...)` fields are 3.17+. Generated by
; ocaml/wasm/tools/build-wasm.sh -- do not edit; edit the script.
(name effect4-avatar)
(generate_opam_files false)
EOF

# (3) `dune`. The library stanza is copied verbatim (same modules, same flags); the
#     executables' `(modes byte exe js)` becomes `(modes wasm)` and the `js_of_ocaml` flags
#     stanza becomes `wasm_of_ocaml` with the effect mode.
cat > "$B/dune" <<EOF
; GENERATED by ocaml/wasm/tools/build-wasm.sh from ocaml/avatar/dune. Do not edit.
; Differences from the avatar's file, each a row of ocaml/wasm/README.md §5:
;   (a) the corpus rule is identical;
;   (b) the library stanza is identical;
;   (c) (modes byte exe js) -> (modes wasm);
;   (d) (js_of_ocaml (flags (--enable effects --target-env=nodejs)))
;       -> (wasm_of_ocaml (flags (--effects=$mode))).

(rule
 (target corpus_data.ml)
 (deps corpus/programs.txt)
 (action
  (with-stdout-to
   %{target}
   (progn
    (echo "(* Generated by dune from corpus/programs.txt. Do not edit. *)\n")
    (echo "let text = {corpus|")
    (cat corpus/programs.txt)
    (echo "|corpus}\n")))))

(library
 (name effect4_avatar)
 (public_name effect4-avatar)
 (wrapped false)
 (modules
  deep_fibers deep_stores deep_context deep_layer deep_forkflow avatar_trace deep_census deep_clauses deep_witnesses
  fibers_fixture store_fixtures extra_fixture corpus_dsl corpus_data corpus_run)
 (flags (:standard -w -a)))

(executables
 (names avatar_main avatar_witnesses)
 (modules avatar_main avatar_witnesses)
 (libraries effect4_avatar)
 (modes wasm)
 (wasm_of_ocaml (flags (--effects=$mode)))
 (flags (:standard -w -a)))
EOF

# (4) Build.
echo "--- dune build --root . ---"
t0=$(date +%s.%N)
( eval "$(opam env --switch=effect4-wasm --set-switch)" && cd "$B" && dune build --root . 2>&1 )
rc=$?
t1=$(date +%s.%N)
printf 'dune build exit=%d  wall=%.1fs\n' "$rc" "$(echo "$t1 - $t0" | bc)"
[ $rc -eq 0 ] || exit $rc

echo "--- outputs ---"
find "$B/_build/default" -maxdepth 1 \( -name 'avatar_*' -o -name '*.assets' \) -printf '%y\t%10s\t%f\n' | sort -k3
for a in "$B"/_build/default/*.assets; do
  [ -d "$a" ] || continue
  printf 'assets %s: %s bytes over %s files\n' "$(basename "$a")" \
    "$(du -sb "$a" | cut -f1)" "$(ls -1 "$a" | wc -l)"
done
echo "=== build-wasm.sh done (mode=$mode) ==="
