import Effect4.Concurrency.Supervision

/-!
All theorem names frozen by the supervision packet. This report is intentionally
red until implementation. Its later output, not this list, supplies kernel
receipts. Allowed ceiling: `propext` and `Quot.sound` only.
-/

#print axioms Effect4.Supervision.MaskMode.select_interruptible
#print axioms Effect4.Supervision.MaskMode.select_uninterruptible
#print axioms Effect4.Supervision.MaskMode.select_inherit
#print axioms Effect4.Supervision.MaskMode.cases_receipt
#print axioms Effect4.Supervision.ObserverMode.cases_receipt
#print axioms Effect4.Supervision.ScopeMode.cases_receipt
#print axioms Effect4.Supervision.Globals.install_eq
#print axioms Effect4.Supervision.Globals.valid_iff
#print axioms Effect4.Supervision.Globals.ownsChildren_iff
#print axioms Effect4.Supervision.Fiber.valid_iff
#print axioms Effect4.Supervision.Fiber.valid?_iff
#print axioms Effect4.Supervision.Fiber.toFiberState_eq
#print axioms Effect4.Supervision.Fiber.published_iff
#print axioms Effect4.Supervision.Fiber.published_eq
#print axioms Effect4.Supervision.Fiber.addChild_eq
#print axioms Effect4.Supervision.Fiber.removeChild_eq
#print axioms Effect4.Supervision.Fiber.addChild_nodup
#print axioms Effect4.Supervision.Fiber.removeChild_membership
#print axioms Effect4.Supervision.observation_await
#print axioms Effect4.Supervision.observation_join
#print axioms Effect4.Supervision.observation_value_ne_effect
#print axioms Effect4.Supervision.Fiber.observe_invalid
#print axioms Effect4.Supervision.Fiber.observe_done
#print axioms Effect4.Supervision.Fiber.observe_live
#print axioms Effect4.Supervision.Fiber.observe_duplicate
#print axioms Effect4.Supervision.Fiber.cancel_eq
#print axioms Effect4.Supervision.Fiber.cancel_membership
#print axioms Effect4.Supervision.Fiber.publish_eq
#print axioms Effect4.Supervision.Fiber.publish_valid
#print axioms Effect4.Supervision.interruptCause_eq
#print axioms Effect4.Supervision.Fiber.recordInterrupt_done
#print axioms Effect4.Supervision.Fiber.recordInterrupt_live
#print axioms Effect4.Supervision.Fiber.recordInterrupt_core
#print axioms Effect4.Supervision.initialFiber_eq
#print axioms Effect4.Supervision.initialFiber_valid
#print axioms Effect4.Supervision.commitFork_eq
#print axioms Effect4.Supervision.forkUnsafe_duplicate
#print axioms Effect4.Supervision.forkUnsafe_deferred
#print axioms Effect4.Supervision.forkUnsafe_wrong_deferred
#print axioms Effect4.Supervision.forkUnsafe_wrong_immediate
#print axioms Effect4.Supervision.forkUnsafe_wrong_identity
#print axioms Effect4.Supervision.forkUnsafe_wrong_parent
#print axioms Effect4.Supervision.forkUnsafe_invalid_child
#print axioms Effect4.Supervision.forkUnsafe_invalid_parent
#print axioms Effect4.Supervision.forkUnsafe_invalid_globals
#print axioms Effect4.Supervision.forkUnsafe_invalid_ownership
#print axioms Effect4.Supervision.forkUnsafe_invalid_child_ownership
#print axioms Effect4.Supervision.forkUnsafe_immediate
#print axioms Effect4.Supervision.forkUnsafe_fresh
#print axioms Effect4.Supervision.forkUnsafe_allocated_nodup
#print axioms Effect4.Supervision.forkUnsafe_child_valid
#print axioms Effect4.Supervision.forkUnsafe_parent_children_nodup
#print axioms Effect4.Supervision.forkChild_eq
#print axioms Effect4.Supervision.forkDetach_eq
#print axioms Effect4.Supervision.commitFork_done_untracked
#print axioms Effect4.Supervision.commitFork_daemon_untracked
#print axioms Effect4.Supervision.Globals.allocate_eq
#print axioms Effect4.Supervision.Globals.extends_iff
#print axioms Effect4.Supervision.Globals.extends?_iff
#print axioms Effect4.Supervision.Globals.ownsChildren?_iff
#print axioms Effect4.Supervision.WaitState.begin_eq
#print axioms Effect4.Supervision.WaitState.pending_eq
#print axioms Effect4.Supervision.WaitState.ready_iff
#print axioms Effect4.Supervision.WaitState.ready_publications
#print axioms Effect4.Supervision.WaitState.observe_pending
#print axioms Effect4.Supervision.WaitState.observe_unknown
#print axioms Effect4.Supervision.WaitState.observe_pending_membership
#print axioms Effect4.Supervision.waitStep_iff
#print axioms Effect4.Supervision.waitRuns_iff
#print axioms Effect4.Supervision.ReplayResult.state_done
#print axioms Effect4.Supervision.ReplayResult.state_frontier
#print axioms Effect4.Supervision.ReplayResult.state_refused
#print axioms Effect4.Supervision.waitReplay_ready
#print axioms Effect4.Supervision.waitReplay_frontier
#print axioms Effect4.Supervision.waitReplay_cons_ok
#print axioms Effect4.Supervision.waitReplay_cons_error
#print axioms Effect4.Supervision.wait_fixedTape_deterministic
#print axioms Effect4.Supervision.waitReplay_done_ready
#print axioms Effect4.Supervision.waitReplay_frame
#print axioms Effect4.Supervision.wait_two_publications
#print axioms Effect4.Supervision.beginParentExit_eq
#print axioms Effect4.Supervision.parentExitView_waiting
#print axioms Effect4.Supervision.parentExitView_ready
#print axioms Effect4.Supervision.parentExitView_not_published_while_waiting
#print axioms Effect4.Supervision.parentExitView_publication_requires_children
#print axioms Effect4.Supervision.newChildren_eq
#print axioms Effect4.Supervision.newChildren_membership
#print axioms Effect4.Supervision.awaitAllChildren_eq
#print axioms Effect4.Supervision.interruptAllRequests_eq
#print axioms Effect4.Supervision.interruptAllWait_eq
#print axioms Effect4.Supervision.bindScope_invalid
#print axioms Effect4.Supervision.bindScope_done
#print axioms Effect4.Supervision.bindScope_closed
#print axioms Effect4.Supervision.bindScope_duplicate_key
#print axioms Effect4.Supervision.bindScope_open
#print axioms Effect4.Supervision.forkScopedBinding_eq
#print axioms Effect4.Supervision.scopeFinalizerInterruptor_eq
#print axioms Effect4.Supervision.scopeFinalizer_self_guard
#print axioms Effect4.Supervision.scopeObserver_eq
#print axioms Effect4.Supervision.scopeObserver_key_membership
#print axioms Effect4.Supervision.raceForkOptions_eq
#print axioms Effect4.Supervision.raceCleanupMask_eq
#print axioms Effect4.Supervision.RaceAllState.initial_eq
#print axioms Effect4.Supervision.raceAllAdmit_eq
#print axioms Effect4.Supervision.RaceAllState.result_eq
#print axioms Effect4.Supervision.raceComplete_unknown
#print axioms Effect4.Supervision.raceComplete_after_accepted
#print axioms Effect4.Supervision.raceComplete_success
#print axioms Effect4.Supervision.raceComplete_failure_last
#print axioms Effect4.Supervision.raceComplete_failure_pending
#print axioms Effect4.Supervision.raceStep_begin_blocked
#print axioms Effect4.Supervision.raceStep_begin_empty
#print axioms Effect4.Supervision.raceStep_begin
#print axioms Effect4.Supervision.raceStep_finish_missing
#print axioms Effect4.Supervision.raceStep_finish_duplicate
#print axioms Effect4.Supervision.raceStep_finish_live
#print axioms Effect4.Supervision.raceStep_finish_done
#print axioms Effect4.Supervision.raceStep_complete
#print axioms Effect4.Supervision.raceStep_complete_unknown
#print axioms Effect4.Supervision.raceStep_beginCleanup
#print axioms Effect4.Supervision.raceStep_beginCleanup_blocked
#print axioms Effect4.Supervision.raceStep_requestNext
#print axioms Effect4.Supervision.raceStep_requestNext_blocked
#print axioms Effect4.Supervision.raceStep_iff
#print axioms Effect4.Supervision.raceRuns_iff
#print axioms Effect4.Supervision.raceReplay_ready
#print axioms Effect4.Supervision.raceReplay_frontier
#print axioms Effect4.Supervision.raceReplay_cons_ok
#print axioms Effect4.Supervision.raceReplay_cons_error
#print axioms Effect4.Supervision.race_fixedTape_deterministic
#print axioms Effect4.Supervision.race_first_accepted_stable
#print axioms Effect4.Supervision.race_result_requires_start_finished
#print axioms Effect4.Supervision.race_cleanup_result_requires_publications
#print axioms Effect4.Supervision.race_empty_frontier
#print axioms Effect4.Supervision.race_single_success
#print axioms Effect4.Supervision.race_two_failures
