#!/usr/bin/env python3
"""Generate `e4d_families_data.ml`: the five service families and their `OpSpec` rows.

The rows are read out of the committed `harness/trace/*fixture*.ts` modules, which
`scripts/check-trace-host.sh` regenerates from `harness/trace/Generate.lean` and refuses if
they have drifted -- so the daemon's `families` answer is the Lean family table, reached
through the one artefact both faces already agree on, and not a second copy of it.

  fiber     FibersRows        harness/trace/fibers-fixture.stub.ts
  ref       RefsRows          harness/trace/ref-fixture.ts
  deferred  DeferredsRows     harness/trace/deferred-fixture.ts
  scope     ScopesRows        harness/trace/scope-fixture.ts
  layer     LayersRows        harness/trace/layer-fixture.ts

`extra` and `corpus` are not families: `extra` is the avatar's own set of programs for the
`WithFiberAction` arms no committed golden reaches, and `corpus` is the adversarial corpus,
whose steps range over all five alphabets at once. Both are reported by the daemon under
their own heading, not as a family.

The fixtures left main with the Flow route (75002d7); the copies read here are the archived
ones, vendored under `server/generated/harness-trace/` by `tools/vendor-archived-inputs.sh`.

Usage: gen_families.py <harness/trace dir> > e4d_families_data.ml
       gen_families.py <fixture file>... > e4d_families_data.ml   (as `server/dune` calls it)
"""
import os
import re
import sys

# A family is one or more `*Rows` objects. `ref` is two: `Refs` is the total face and
# `ERefs` the fallible one, which is where `tryTake` lives -- and the avatar's `ref` family
# runs `takeUnderflow`, so a `ref` answer that listed only `RefsRows` would be missing an
# operation the daemon can actually perform.
FAMILIES = [
    ("fiber", [("FibersRows", "fibers-fixture.stub.ts")]),
    ("ref", [("RefsRows", "ref-fixture.ts"), ("ERefsRows", "ref-fixture.ts")]),
    ("deferred", [("DeferredsRows", "deferred-fixture.ts")]),
    ("scope", [("ScopesRows", "scope-fixture.ts")]),
    ("layer", [("LayersRows", "layer-fixture.ts")]),
]

ENTRY = re.compile(r'"([A-Za-z0-9_]+)"\s*:\s*\{\s*params\s*:\s*(\d+)\s*,\s*answer\s*:\s*"([^"]*)"')


def ocaml_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def object_after(text, marker):
    start = text.find(marker)
    if start < 0:
        raise SystemExit("no %s in the fixture" % marker)
    open_brace = text.index("{", start)
    depth = 0
    for i in range(open_brace, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[open_brace:i + 1]
    raise SystemExit("unbalanced braces after %s" % marker)


def locate(arguments):
    """filename -> path: a directory holding the fixtures, or the fixture files themselves."""
    if len(arguments) == 1 and os.path.isdir(arguments[0]):
        return lambda filename: os.path.join(arguments[0], filename)
    by_name = {os.path.basename(path): path for path in arguments}

    def find(filename):
        if filename not in by_name:
            raise SystemExit("gen_families.py: no %s among the arguments" % filename)
        return by_name[filename]
    return find


def main():
    find = locate(sys.argv[1:])
    print("(* GENERATED by ocaml/server/tools/gen_families.py (server/dune). Do not edit. *)")
    print("(* Sources: the harness/trace fixtures of the archived Flow route (archive/flow-route,")
    print("   606918e), vendored under server/generated/harness-trace/. *)")
    print()
    print("(* family -> [(operation, parameter count, answer type)] *)")
    print("let families : (string * (string * int * string) list) list = [")
    for family, parts in FAMILIES:
        seen = []
        for marker, filename in parts:
            with open(find(filename)) as handle:
                text = handle.read()
            for name, params, answer in ENTRY.findall(object_after(text, "export const " + marker)):
                if name not in [n for n, _, _ in seen]:
                    seen.append((name, params, answer))
        print("  (%s, [" % ocaml_string(family))
        for name, params, answer in seen:
            print("    (%s, %s, %s);" % (ocaml_string(name), params, ocaml_string(answer)))
        print("  ]);")
    print("]")
    print()
    print("let sources : (string * string) list = [")
    for family, parts in FAMILIES:
        print("  (%s, %s);"
              % (ocaml_string(family),
                 ocaml_string(", ".join("harness/trace/%s :: %s" % (f, m) for m, f in parts))))
    print("]")


if __name__ == "__main__":
    main()
