#!/usr/bin/env python3
"""Generate `e4d_pins.ml`: the rc.112 pin, the per-file digests, the build note.

`avatar_main.ml` stamps every `input` row with one digest over all its sources at once. The
daemon stamps each file with its own SHA-256, so a `pins` answer says which file changed --
which matters when seat W1 is editing the avatar under the daemon's feet.

The avatar digests are taken from the sources actually compiled (dune's copies under
`_build/default/avatar/`), not from the working tree.

The pin itself is not invented: it is the `pin effects <sha>` row of the mask table, the
same row `avatar/build-avatar.sh` reads out of a golden. The mask table itself is the
archived `generated/traces/masks.tsv`, vendored under `server/generated/traces/` (see
`tools/vendor-archived-inputs.sh`).

Usage (as `server/dune` invokes it):

  gen_pins.py --ocaml <version> --node <version> [--jsoo <version>] --masks <masks.tsv>
              --avatar <avatar module .ml>... --corpus <programs.txt>
              --server <server source>... --tools <generator>...
              --inputs <vendored input>... --lean <src/Effect4/Machine/*.lean>...
              > e4d_pins.ml

Every file is labelled by its group's fixed repo-relative prefix and its basename (for the
vendored inputs, its parent directory too), so the labels do not depend on the directory
dune ran the generator from. The generator digest is one hash over the `--server` and
`--tools` files, the way `build-avatar.sh` stamps the avatar's `generator` row.
"""
import argparse
import hashlib
import os


def ocaml_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def digest(path):
    with open(path, "rb") as handle:
        return hashlib.sha256(handle.read()).hexdigest()


def labelled(prefix, paths):
    return sorted((prefix + os.path.basename(p), p) for p in paths)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--ocaml", required=True)
    parser.add_argument("--node", required=True)
    parser.add_argument("--jsoo", default="5.7.1")
    parser.add_argument("--masks", required=True)
    parser.add_argument("--corpus", required=True)
    parser.add_argument("--avatar", nargs="*", default=[])
    parser.add_argument("--server", nargs="*", default=[])
    parser.add_argument("--tools", nargs="*", default=[])
    parser.add_argument("--inputs", nargs="*", default=[])
    parser.add_argument("--lean", nargs="*", default=[])
    args = parser.parse_args()

    pin = ""
    with open(args.masks) as handle:
        for line in handle:
            cells = line.rstrip("\n").split("\t")
            if len(cells) >= 3 and cells[0] == "pin" and cells[1] == "effects":
                pin = cells[2]

    server_files = (labelled("ocaml/server/", args.server)
                    + labelled("ocaml/server/tools/", args.tools))
    vendored = sorted(
        ("ocaml/server/generated/%s/%s"
         % (os.path.basename(os.path.dirname(os.path.abspath(p))), os.path.basename(p)), p)
        for p in args.inputs)

    inputs = (labelled("ocaml/avatar/", args.avatar)
              + [("ocaml/avatar/corpus/programs.txt", args.corpus)]
              + server_files
              + vendored
              + labelled("src/Effect4/Machine/", args.lean))

    combined = hashlib.sha256()
    for _label, path in server_files:
        with open(path, "rb") as handle:
            combined.update(handle.read())

    print("(* GENERATED by ocaml/server/tools/gen_pins.py (server/dune). Do not edit. *)")
    print()
    print("let pin = %s" % ocaml_string(pin))
    print("let generator_sha = %s" % ocaml_string(combined.hexdigest()))
    print("let build_note = %s" % ocaml_string(
        "ocaml %s; js_of_ocaml %s --enable effects; node %s; dune"
        % (args.ocaml, args.jsoo, args.node)))
    print()
    print("let inputs : (string * string) list = [")
    for label, path in inputs:
        print("  (%s, %s);" % (ocaml_string(label), ocaml_string(digest(path))))
    print("]")


if __name__ == "__main__":
    main()
