// Generated by js_of_ocaml
//# buildInfo:effects=true, kind=cmo, use-js-string=true, version=5.7.1

//# unitInfo: Provides: P2_nested_forward
//# unitInfo: Requires: Stdlib, Stdlib__Effect
(function
  (globalThis){
   "use strict";
   var
    runtime = globalThis.jsoo_runtime,
    caml_callback = runtime.caml_callback,
    caml_maybe_attach_backtrace = runtime.caml_maybe_attach_backtrace,
    caml_pop_trap = runtime.caml_pop_trap;
   function caml_cps_call3(f, a0, a1, a2){
    return runtime.caml_stack_check_depth()
            ? (f.l
                >= 0
                ? f.l
                : f.l = f.length)
              == 3
              ? f(a0, a1, a2)
              : runtime.caml_call_gen(f, [a0, a1, a2])
            : runtime.caml_trampoline_return(f, [a0, a1, a2]);
   }
   function caml_cps_call4(f, a0, a1, a2, a3){
    return runtime.caml_stack_check_depth()
            ? (f.l
                >= 0
                ? f.l
                : f.l = f.length)
              == 4
              ? f(a0, a1, a2, a3)
              : runtime.caml_call_gen(f, [a0, a1, a2, a3])
            : runtime.caml_trampoline_return(f, [a0, a1, a2, a3]);
   }
   var
    global_data = runtime.caml_get_global_data(),
    Stdlib_Effect = global_data.Stdlib__Effect,
    Stdlib = global_data.Stdlib,
    _a_ = [248, "P2_nested_forward.E", runtime.caml_fresh_oo_id(0)];
   function _b_(_q_, cont){
    return runtime.caml_perform_effect
            ([0, _a_, 41], 0, function(_r_){return cont(1 + _r_ | 0);});
   }
   function _c_(_m_, cont){
    return caml_cps_call4
            (Stdlib_Effect[3][4],
             _b_,
             0,
             [0,
              function(_p_, cont){return cont(_p_);},
              function(_o_, cont){
               var raise = caml_pop_trap();
               return raise(caml_maybe_attach_backtrace(_o_, 1));
              },
              function(_n_, cont){return cont(0);}],
             cont);
   }
   var
    _d_ =
      caml_callback
       (Stdlib_Effect[3][4],
        [_c_,
         0,
         [0,
          function(_l_, cont){return cont(_l_ * 2 | 0);},
          function(_k_, cont){
           var raise = caml_pop_trap();
           return raise(caml_maybe_attach_backtrace(_k_, 1));
          },
          function(_f_, cont){
           var _g_ = _f_[1] === _a_ ? 1 : 0;
           if(_g_)
            var
             _h_ = _f_[2],
             _i_ =
               [0,
                function(_j_, cont){
                 return caml_cps_call3(Stdlib_Effect[3][1], _j_, _h_, cont);
                }];
           else
            var _i_ = _g_;
           return cont(_i_);
          }]]),
    _e_ = caml_callback(Stdlib[33], [_d_]);
   caml_callback(Stdlib[42], [_e_]);
   caml_callback(Stdlib[47], [0]);
   var P2_nested_forward = [0, _a_, _b_, _c_];
   runtime.caml_register_global(3, P2_nested_forward, "P2_nested_forward");
   return;
  }
  (globalThis));
