(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400180`, seed 400180, 37 operations.
   Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400180 () =
  let v0 = Fibers_fixture.fork 0 in
  let _v1 = Fibers_fixture.cleanups () in
  let v2 = Store_fixtures.def_make () in
  ignore (Fibers_fixture.interrupt v0);
  let _v3 = Fibers_fixture.started () in
  ignore (Fibers_fixture.interrupt v0);
  let _v4 = Extra_fixture.interrupt_all [ v0 ] in
  let _v5 = Fibers_fixture.started () in
  let v6 = Fibers_fixture.fork 2 in
  ignore (Fibers_fixture.interrupt v0);
  let _v7 = Fibers_fixture.started () in
  let _v8 = Fibers_fixture.await_value v0 in
  let _v9 = Fibers_fixture.await_value v0 in
  let _v10 = Fibers_fixture.await_value v6 in
  ignore (Fibers_fixture.interrupt v6);
  let _v11 = Fibers_fixture.join v0 in
  let _v12 = Store_fixtures.def_await_value v2 in
  ignore (Fibers_fixture.interrupt v0);
  let _v13 = Store_fixtures.def_await_value v2 in
  let _v14 = Fibers_fixture.started () in
  let _v15 = Fibers_fixture.await_error v0 in
  let _v16 = Fibers_fixture.fork 0 in
  let _v17 = Fibers_fixture.await_value v0 in
  let _v18 = Fibers_fixture.await_value v6 in
  let _v19 = Fibers_fixture.cleanups () in
  let _v20 = Store_fixtures.def_is_done v2 in
  let _v21 = Store_fixtures.def_succeed v2 3 in
  let _v22 = Fibers_fixture.started () in
  let _v23 = Store_fixtures.layer_build 2 in
  let _v24 = Fibers_fixture.fork 1 in
  let _v25 = Store_fixtures.layer_provide_count 3 in
  let v26 = Store_fixtures.scope_make () in
  let _v27 = Store_fixtures.scope_add v26 2 in
  let _v28 = Fibers_fixture.cleanups () in
  let _v29 = Store_fixtures.def_make () in
  let _v30 = Store_fixtures.scope_close v26 in
  let v31 = Fibers_fixture.cleanups () in
  v31

let programs : (string * (unit -> value)) list = [ ("p400180", corpus_p400180) ]
