(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400005`, seed 400005, 36 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400005 () =
  let v0 = Fibers_fixture.fork 3 in
  let _v1 = Fibers_fixture.join v0 in
  let _v2 = Fibers_fixture.cleanups () in
  let _v3 = Fibers_fixture.started () in
  let _v4 = Fibers_fixture.started () in
  let _v5 = Fibers_fixture.started () in
  let _v6 = Fibers_fixture.join v0 in
  let _v7 = Fibers_fixture.started () in
  let _v8 = Fibers_fixture.started () in
  let v9 = Fibers_fixture.fork_detach 0 in
  let _v10 = Fibers_fixture.await_error v0 in
  let _v11 = Fibers_fixture.started () in
  let _v12 = Fibers_fixture.started () in
  let _v13 = Extra_fixture.interrupt_all [ v0 ] in
  let _v14 = Fibers_fixture.await_value v0 in
  let _v15 = Fibers_fixture.started () in
  let v16 = Store_fixtures.ref_make 6 in
  let _v17 = Store_fixtures.ref_get v16 in
  let v18 = Store_fixtures.ref_make 9 in
  let _v19 = Fibers_fixture.await_error v0 in
  let _v20 = Fibers_fixture.join v0 in
  ignore (Store_fixtures.ref_set v18 9);
  let v21 = Store_fixtures.def_make () in
  let _v22 = Store_fixtures.def_succeed v21 5 in
  let _v23 = Fibers_fixture.await_error v0 in
  let _v24 = Store_fixtures.def_succeed v21 6 in
  ignore (Fibers_fixture.interrupt v9);
  let _v25 = Fibers_fixture.await_value v0 in
  let v26 = Fibers_fixture.fork 4 in
  let _v27 = Store_fixtures.def_make () in
  let _v28 = Fibers_fixture.await_value v9 in
  let _v29 = Fibers_fixture.cleanups () in
  let _v30 = Store_fixtures.def_succeed v21 4 in
  let _v31 = Fibers_fixture.started () in
  let _v32 = Store_fixtures.def_fail v21 10 in
  let v33 = Fibers_fixture.join v26 in
  v33

let programs : (string * (unit -> value)) list = [ ("p400005", corpus_p400005) ]
