/**
 * Generated by Effect4 (Effect v4 profile).
 *
 * Host: typescript 7.0.2
 * Runtime: node 22 --experimental-strip-types
 * Language service: @effect/tsgo@0.38.0
 * Library: effect@4.0.0-rc.112
 *
 * Do not edit.
 */
import { Context, Effect, Result } from "effect"
import { succ, orZero } from "./atoms.ts"

/** Service `Cell`: one method per operation of the Lean family. */
export class Cell extends Context.Service<Cell, {
  readonly get: Effect.Effect<number>
  readonly put: (n: number) => Effect.Effect<void>
}>()("Cell") {}

/** Operation rows of `Cell`, for the trace harness. */
export const CellRows = { "get": { params: 0, answer: "number" }, "put": { params: 1, answer: "void" } }

/** Lowered from `incr` over `Cell`. */
export const incr = (n: number) =>
  Effect.gen(function* () {
    const cell = yield* Cell
    const x = yield* cell.get
    yield* cell.put(succ(x))
    const y = yield* cell.get
    return y
  })

/** Lowered from `twice` over `Cell`. */
export const twice = (n: number) =>
  Effect.gen(function* () {
    const cell = yield* Cell
    yield* cell.put(n)
    yield* cell.put(succ(n))
    const y = yield* cell.get
    return y
  })

/** Service `ECell`: one method per operation of the Lean family. */
export class ECell extends Context.Service<ECell, {
  readonly tryGet: Effect.Effect<Result.Result<number, string>>
  readonly put: (n: number) => Effect.Effect<void>
}>()("ECell") {}

/** Operation rows of `ECell`, for the trace harness. */
export const ECellRows = { "tryGet": { params: 0, answer: "Result.Result<number, string>" }, "put": { params: 1, answer: "void" } }

/** Lowered from `recover` over `ECell`. */
export const recover = (n: number) =>
  Effect.gen(function* () {
    const eCell = yield* ECell
    const r = yield* eCell.tryGet
    yield* eCell.put(n)
    return orZero(r)
  })

/** Service `FCell`: one method per operation of the Lean family. */
export class FCell extends Context.Service<FCell, {
  readonly get: Effect.Effect<number, string>
  readonly put: (n: number) => Effect.Effect<void>
}>()("FCell") {}

/** Operation rows of `FCell`, for the trace harness. */
export const FCellRows = { "get": { params: 0, answer: "number" }, "put": { params: 1, answer: "void" } }

/** Lowered from `fallible` over `FCell`. */
export const fallible = (n: number) =>
  Effect.gen(function* () {
    const fCell = yield* FCell
    yield* fCell.put(n)
    const x = yield* fCell.get
    return x
  })
