/**
 * Generated by Effect4 (Effect v4 profile).
 *
 * Host: typescript 7.0.2
 * Runtime: node 22 --experimental-strip-types
 * Language service: @effect/tsgo@0.38.0
 * Library: effect@4.0.0-rc.112
 *
 * Do not edit.
 */
import { Context, Effect } from "effect"
import type { Scope } from "effect"

/** Service `Scopes`: one method per operation of the Lean family. */
export class Scopes extends Context.Service<Scopes, {
  readonly make: Effect.Effect<Scope.Closeable>
  readonly addFinalizer: (scope: Scope.Closeable, key: number) => Effect.Effect<boolean>
  readonly remove: (scope: Scope.Closeable, key: number) => Effect.Effect<void>
  readonly close: (scope: Scope.Closeable) => Effect.Effect<ReadonlyArray<number>>
}>()("Scopes") {}

/** Operation rows of `Scopes`, for the trace harness. */
export const ScopesRows = { "make": { params: 0, answer: "Scope.Closeable" }, "addFinalizer": { params: 2, answer: "boolean" }, "remove": { params: 2, answer: "void" }, "close": { params: 1, answer: "ReadonlyArray<number>" } }

/** Lowered from `scopeLifo` over `Scopes`. */
export const scopeLifo = (n: number) =>
  Effect.gen(function* () {
    const scopes = yield* Scopes
    const s = yield* scopes.make
    yield* scopes.addFinalizer(s, 1)
    yield* scopes.addFinalizer(s, 2)
    yield* scopes.addFinalizer(s, 3)
    const r = yield* scopes.close(s)
    return r
  })

/** Lowered from `scopeAddAfterClosed` over `Scopes`. */
export const scopeAddAfterClosed = (n: number) =>
  Effect.gen(function* () {
    const scopes = yield* Scopes
    const s = yield* scopes.make
    yield* scopes.addFinalizer(s, 1)
    yield* scopes.close(s)
    const a = yield* scopes.addFinalizer(s, 2)
    return a
  })

/** Lowered from `scopeRemove` over `Scopes`. */
export const scopeRemove = (n: number) =>
  Effect.gen(function* () {
    const scopes = yield* Scopes
    const s = yield* scopes.make
    yield* scopes.addFinalizer(s, 1)
    yield* scopes.addFinalizer(s, 2)
    yield* scopes.remove(s, 1)
    const r = yield* scopes.close(s)
    return r
  })

/** Lowered from `scopeCloseTwice` over `Scopes`. */
export const scopeCloseTwice = (n: number) =>
  Effect.gen(function* () {
    const scopes = yield* Scopes
    const s = yield* scopes.make
    yield* scopes.addFinalizer(s, 1)
    yield* scopes.addFinalizer(s, 2)
    yield* scopes.close(s)
    const r = yield* scopes.close(s)
    return r
  })
