(* Generated by OCaml5.Render (spike P5). Do not edit. *)
type ('a, 'b) stack
type ('a, 'b) continuation
type last_fiber

type u =
  | I of int
  | U
  | F of (u -> u)
  | Ef of u Effect.t
  | Xn of exn
  | Nn
  | Sm of u
  | Kt of (u, u) continuation
  | Sk of (u, u) stack
  | Lf of last_fiber

external perform : 'a Effect.t -> 'a = "%perform"
external resume : ('a, 'b) stack -> ('c -> 'a) -> 'c -> 'b = "%resume"
external runstack : ('a, 'b) stack -> ('c -> 'a) -> 'c -> 'b = "%runstack"
external reperform :
  'a Effect.t -> ('a, 'b) continuation -> last_fiber -> 'b = "%reperform"
external alloc_stack :
  ('a -> 'b) -> (exn -> 'b) ->
  ('c Effect.t -> ('c, 'b) continuation -> last_fiber -> 'b) -> ('a, 'b) stack
  = "caml_alloc_stack"
external take_cont_noexc : ('a, 'b) continuation -> ('a, 'b) stack
  = "caml_continuation_use_noexc" [@@noalloc]
external update_handler :
  ('a, 'b) continuation -> ('b -> 'c) -> (exn -> 'c) ->
  ('d Effect.t -> ('d, 'b) continuation -> last_fiber -> 'c) -> ('a, 'c) stack
  = "caml_continuation_use_and_update_handler_noexc" [@@noalloc]
external drop_continuation : ('a, 'b) continuation -> unit = "caml_drop_continuation"

let stuck () = print_string "!stuck\n"; exit 2
let as_int = function I n -> n | _ -> stuck ()
let as_fun = function F f -> f | _ -> stuck ()
let as_eff = function Ef e -> e | _ -> stuck ()
let as_exn = function Xn e -> e | _ -> stuck ()
let as_k = function Kt k -> k | _ -> stuck ()
let as_stk = function Sk s -> s | _ -> stuck ()
let as_lf = function Lf l -> l | _ -> stuck ()
let seq_exn (_ : u) (e : exn) = e
let cell : u ref = ref U
let emit s = print_string s; print_newline (); U

type _ Effect.t += E2 : u -> u Effect.t

let eff_id (e : u Effect.t) = match e with
  | E2 _ -> 2
  | _ -> 0
let exn_id (e : exn) = match e with
  | Effect.Unhandled _ -> 0
  | Effect.Continuation_already_resumed -> 1
  | _ -> 0
let rec render_u = function
  | I n -> string_of_int n
  | U -> "()"
  | F _ -> "<fun>"
  | Ef e -> "eff" ^ string_of_int (eff_id e)
  | Xn e -> "exn" ^ string_of_int (exn_id e)
  | Nn -> "none"
  | Sm v -> "some(" ^ render_u v ^ ")"
  | Kt _ -> "cont"
  | Sk _ -> "stack"
  | Lf _ -> "lastfiber"
let _ = render_u

let () = ignore (((let v0 = (let v0 = (let t0a = (F (fun v0 -> ((emit "retc"); (I 0)))) in let t0b = (F (fun v0 -> ((emit "exnc"); (I 1)))) in let t0c = (F (fun v0 -> (F (fun v1 -> (F (fun v2 -> (match v0 with | Ef (E2 v3) -> ((emit "handled"); ((cell := v1; U); ((emit "parked"); (I 2)))) | v3 -> (let t4a = v0 in let t4b = v1 in let t4c = v2 in reperform (as_eff t4a) (as_k t4b) (as_lf t4c))))))))) in Sk (alloc_stack (as_fun t0a) (fun q0x -> as_fun t0b (Xn q0x)) (fun q0e q0k q0l -> as_fun (as_fun (as_fun t0c (Ef q0e)) (Kt q0k)) (Lf q0l)))) in (let t1a = v0 in let t1b = (F (fun v1 -> ((emit "perform"); (perform (as_eff (Ef (E2 U))))))) in let t1c = U in runstack (as_stk t1a) (as_fun t1b) t1c)) in (let t1a = v0 in emit ("status" ^ "\t" ^ render_u t1a))); (let v0 = (try ((emit "drop"); ((drop_continuation (as_k (!cell)); U); (I 0))) with x0 -> let v0 = Xn x0 in ((emit "caught"); (I 9))) in (let t1a = v0 in emit ("after" ^ "\t" ^ render_u t1a)))))
