import Effect4.Laws.Program.Typed.Membership
#print axioms Effect4.Program.Typed.fitsExit_success_iff
#print axioms Effect4.Program.Typed.fitsExit_failure_iff
#print axioms Effect4.Program.Typed.fitsExit_success
#print axioms Effect4.Program.Typed.fitsExit_of_clean
#print axioms Effect4.Program.Typed.cleanExit_of_never_fits
#print axioms Effect4.Program.Typed.fitsExit_failure_of_error
#print axioms Effect4.Program.Typed.causeFits_map
#print axioms Effect4.Program.Typed.flatFits_fits
#print axioms Effect4.Program.Typed.causeFits_admits
#print axioms Effect4.Program.Typed.fits_hasTy
#print axioms Effect4.Program.Typed.live_of_keys_nil
#print axioms Effect4.Program.Typed.live_list
#print axioms Effect4.Program.Typed.live_ctor
#print axioms Effect4.Program.Typed.live_ctor_one
#print axioms Effect4.Program.Typed.keys_of_cause
#print axioms Effect4.Program.Typed.live_fiber
#print axioms Effect4.Program.Typed.live_cell
#print axioms Effect4.Program.Typed.live_promise
#print axioms Effect4.Program.Typed.live_handle
#print axioms Effect4.Program.Typed.fits_live
#print axioms Effect4.Program.Typed.isSome_extends
#print axioms Effect4.Program.Typed.live_map
#print axioms Effect4.Program.Typed.fiberDeclared_map
#print axioms Effect4.Program.Typed.refDeclared_map
#print axioms Effect4.Program.Typed.promiseDeclared_map
#print axioms Effect4.Program.Typed.handleFits_map
#print axioms Effect4.Program.Typed.flatFits_map
#print axioms Effect4.Program.Typed.servicesFit_map
#print axioms Effect4.Program.Typed.fits_map
#print axioms Effect4.Program.Typed.fits_mono
#print axioms Effect4.Program.Typed.fits_sub
#print axioms Effect4.Program.Typed.fitsExit_mono
#print axioms Effect4.Program.Typed.fitsExit_sub
#print axioms Effect4.Program.Typed.fits_pair
#print axioms Effect4.Program.Typed.fits_fst
#print axioms Effect4.Program.Typed.await_fits
#print axioms Effect4.Program.Typed.fits_list_iff
#print axioms Effect4.Program.Typed.Fits.alg
#print axioms Effect4.Program.Typed.Fits.hom
#print axioms Effect4.Program.Typed.Fits.eq_cata
