(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400000`, seed 400000, 37 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400000 () =
  let v0 = Fibers_fixture.fork 4 in
  let _v1 = Fibers_fixture.join v0 in
  let v2 = Fibers_fixture.fork 0 in
  let _v3 = Fibers_fixture.started () in
  let _v4 = Store_fixtures.def_make () in
  ignore (Fibers_fixture.interrupt v2);
  let _v5 = Fibers_fixture.started () in
  ignore (Fibers_fixture.interrupt v0);
  let _v6 = Fibers_fixture.started () in
  ignore (Fibers_fixture.interrupt v2);
  let _v7 = Fibers_fixture.started () in
  let _v8 = Store_fixtures.def_make () in
  ignore (Extra_fixture.yield ());
  let v9 = Store_fixtures.ref_make 2 in
  let v10 = Fibers_fixture.fork 4 in
  let _v11 = Fibers_fixture.started () in
  let _v12 = Store_fixtures.ref_get_and_set v9 6 in
  ignore (Fibers_fixture.interrupt v2);
  let _v13 = Fibers_fixture.cleanups () in
  let _v14 = Fibers_fixture.await_value v2 in
  let _v15 = Fibers_fixture.fork 4 in
  let _v16 = Fibers_fixture.started () in
  let _v17 = Store_fixtures.ref_make 1 in
  let _v18 = Fibers_fixture.join v10 in
  let _v19 = Store_fixtures.scope_make () in
  let _v20 = Store_fixtures.def_make () in
  let _v21 = Fibers_fixture.fork 4 in
  let v22 = Fibers_fixture.fork 2 in
  let _v23 = Fibers_fixture.await_value v22 in
  let _v24 = Fibers_fixture.fork 6 in
  let _v25 = Fibers_fixture.join v0 in
  let _v26 = Store_fixtures.ref_get_and_set v9 2 in
  ignore (Store_fixtures.ref_set v9 9);
  ignore (Store_fixtures.ref_update v9 7);
  let _v27 = Fibers_fixture.join v2 in
  let _v28 = Store_fixtures.ref_make 3 in
  let v29 = Fibers_fixture.await_value v10 in
  v29

let programs : (string * (unit -> value)) list = [ ("p400000", corpus_p400000) ]
