(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400202`, seed 400202, 11 operations.
   Do not edit; regenerate with `workshop/OCaml5/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400202 () =
  let v0 = Fibers_fixture.fork 3 in
  let _v1 = Fibers_fixture.cleanups () in
  let v2 = Store_fixtures.ref_make 10 in
  let _v3 = Store_fixtures.def_make () in
  let _v4 = Fibers_fixture.await_error v0 in
  let _v5 = Store_fixtures.def_make () in
  let v6 = Fibers_fixture.fork 4 in
  let _v7 = Fibers_fixture.await_value v6 in
  let _v8 = Store_fixtures.ref_modify v2 9 in
  let _v9 = Fibers_fixture.started () in
  let v10 = Fibers_fixture.await_value v0 in
  v10

let programs : (string * (unit -> value)) list = [ ("p400202", corpus_p400202) ]
