#!/usr/bin/env bash
# Seat W1: render one avatar module's carriers from `OCaml5.Ml.Deep.*` and diff them against
# the block the avatar file carries. The diff is against the real file, not a copy, so the
# claim decays the moment either side changes -- which is the point (P5 §11).
#
#   render-deep.sh stores      # deep_stores.ml
#
# With `--write`, the rendered block replaces the one in the file.
set -euo pipefail
here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo=$(CDPATH= cd -- "$here/../../.." && pwd)
out=${W1_BUILD:-/private/tmp/claude-501/-Users-pooks-Dev-lean4-effect4/d87ba830-2e63-4750-815f-2679b36f870a/scratchpad/w1}
mkdir -p "$out"
which=${1:-stores}
write=${2:-}

( cd "$repo" && lake env lean --run workshop/OCaml5/avatar/render-deep.lean "$which" ) \
  > "$out/$which.gen.ml"

file="$here/deep_$which.ml"
begin='(* Generated by OCaml5.Ml (`Render.lean`, seat W1)'
end='(* ===== END GENERATED ====='
python3 - "$file" "$out/$which.gen.ml" "${write:-}" <<'PY'
import sys
target, gen, write = sys.argv[1], sys.argv[2], sys.argv[3]
text = open(target).read()
start = text.index("(* Generated by OCaml5.Ml (`Render.lean`, seat W1)")
stop = text.index("(* ===== END GENERATED =====")
have = text[start:stop]
want = open(gen).read()
if have.rstrip() == want.rstrip():
    print(f"{target}: carriers IDENTICAL to OCaml5.Ml.Deep")
elif write == "--write":
    open(target, "w").write(text[:start] + want.rstrip() + "\n\n" + text[stop:])
    print(f"{target}: carriers REWRITTEN from OCaml5.Ml.Deep")
else:
    import difflib
    print(f"{target}: carriers DIFFER")
    for line in difflib.unified_diff(have.splitlines(), want.splitlines(),
                                     "avatar", "generated", lineterm=""):
        print("    " + line)
    raise SystemExit(1)
PY
