export const main: Effect.Effect<readonly [boolean, ReadonlyArray<number>], never, never> = Effect.flatMap(Ref.make(recordValue<{ readonly open: boolean; readonly waiters: ReadonlyArray<{ readonly hint: Deferred.Deferred<void, never>; readonly id: Deferred.Deferred<void, never> }> }>([10, [20], [[4, [[5, [3, "open"], [5, [1, false], [10, [5], []]]], [5, [3, "waiters"], [5, [1, false], [10, [8], [[10, [20], [[4, [[5, [3, "hint"], [5, [1, false], [10, [17], [[10, [1], []], [10, [], []]]]]], [5, [3, "id"], [5, [1, false], [10, [17], [[10, [1], []], [10, [], []]]]]]]]]]]]]]]]]], { open: false, waiters: nil() })), (a0) => Effect.flatMap(Ref.make(take(cons(0, nil()), 0)), (a1) => Effect.flatMap(Effect.forkChild(Effect.flatMap(Effect.flatMap(Effect.uninterruptibleMask((a2) => Effect.succeed(a2)), (a2) => Effect.uninterruptible(Effect.flatMap(Deferred.make<void, never>(), (a3) => Effect.flatMap(Deferred.make<void, never>(), (a4) => Effect.flatMap(Ref.modify(a0, (a5) => ite(recordRequired<"open">("open")(a5), pair(true, a5), pair(false, recordSet<"waiters">("waiters")(a5)(append(fold(recordRequired<"waiters">("waiters")(a5), take(recordRequired<"waiters">("waiters")(a5), 0), (a6, a7) => ite(sameHandle(recordRequired<"id">("id")(a7), a3), a6, append(a6, cons(a7, nil())))), cons(recordValue<{ readonly hint: Deferred.Deferred<void, never>; readonly id: Deferred.Deferred<void, never> }>([10, [20], [[4, [[5, [3, "id"], [5, [1, false], [10, [17], [[10, [1], []], [10, [], []]]]]], [5, [3, "hint"], [5, [1, false], [10, [17], [[10, [1], []], [10, [], []]]]]]]]]], { id: a3, hint: a4 }), nil())))))), (a5) => Effect.suspend(() => a5 ? Effect.succeed(undefined) : Effect.onExit(pipe(Deferred.await(a4), a2), (a6) => Effect.suspend(() => causeIsInterrupt(a6) ? Ref.modify(a0, (a7) => pair(undefined, recordSet<"waiters">("waiters")(a7)(fold(recordRequired<"waiters">("waiters")(a7), take(recordRequired<"waiters">("waiters")(a7), 0), (a8, a9) => ite(sameHandle(recordRequired<"id">("id")(a9), a3), a8, append(a8, cons(a9, nil()))))))) : Effect.succeed(undefined))))))))), (a2) => Ref.update(a1, (a3) => append(a3, cons(1, nil())))), { startImmediately: true, uninterruptible: "inherit" }), (a2) => Effect.flatMap(Effect.yieldNowWith(0), (a3) => Effect.flatMap(Fiber.interrupt(a2), (a4) => Effect.flatMap(Effect.uninterruptible(Effect.flatMap(Ref.modify(a0, (a5) => ite(recordRequired<"open">("open")(a5), pair(tuple(false, take(recordRequired<"waiters">("waiters")(a5), 0)), a5), pair(tuple(true, recordRequired<"waiters">("waiters")(a5)), recordSet<"open">("open")(recordSet<"waiters">("waiters")(a5)(take(recordRequired<"waiters">("waiters")(a5), 0)))(true)))), (a5) => Effect.flatMap(Effect.suspend(() => {
  let a6 = 0
  return Effect.map(Effect.whileLoop({
    while: () => lt(a6, length(tupleAt<"1">("1")(a5))),
    body: () => optionCase(get(tupleAt<"1">("1")(a5), a6), () => Effect.succeed(undefined), (a7) => Effect.flatMap(Effect.forkDetach(Deferred.succeed(recordRequired<"hint">("hint")(a7), undefined), { startImmediately: false, uninterruptible: true }), (a8) => Effect.succeed(undefined))),
    step: (a7) => {
      a6 = succ(a6)
    },
  }), () => a6)
}), (a6) => Effect.succeed(tupleAt<"0">("0")(a5))))), (a5) => Effect.flatMap(Ref.update(a1, (a6) => append(a6, cons(3, nil()))), (a6) => Effect.flatMap(Ref.get(a1), (a7) => Effect.succeed(tuple(a5, a7))))))))))
