(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400216`, seed 400216, 37 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400216 () =
  let v0 = Fibers_fixture.fork 5 in
  let _v1 = Fibers_fixture.started () in
  let v2 = Store_fixtures.ref_make 5 in
  let v3 = Fibers_fixture.fork_detach 2 in
  let _v4 = Fibers_fixture.join v3 in
  let _v5 = Fibers_fixture.cleanups () in
  let _v6 = Fibers_fixture.cleanups () in
  ignore (Store_fixtures.ref_set v2 2);
  let _v7 = Fibers_fixture.cleanups () in
  let _v8 = Fibers_fixture.cleanups () in
  let v9 = Store_fixtures.ref_make 1 in
  let _v10 = Fibers_fixture.cleanups () in
  let _v11 = Fibers_fixture.join v0 in
  let _v12 = Fibers_fixture.cleanups () in
  ignore (Extra_fixture.yield ());
  let _v13 = Store_fixtures.def_make () in
  let _v14 = Store_fixtures.def_make () in
  let _v15 = Store_fixtures.layer_build 0 in
  let _v16 = Store_fixtures.layer_close () in
  let _v17 = Store_fixtures.def_make () in
  let _v18 = Fibers_fixture.await_value v3 in
  let _v19 = Fibers_fixture.join v3 in
  let _v20 = Fibers_fixture.cleanups () in
  ignore (Fibers_fixture.interrupt v3);
  let _v21 = Store_fixtures.ref_get v9 in
  let v22 = Fibers_fixture.fork_detach 6 in
  let _v23 = Store_fixtures.scope_make () in
  let _v24 = Store_fixtures.ref_modify v2 1 in
  let _v25 = Store_fixtures.ref_get_and_set v9 1 in
  ignore (Fibers_fixture.interrupt v22);
  ignore (Store_fixtures.ref_set v2 3);
  let _v26 = Store_fixtures.scope_make () in
  let _v27 = Store_fixtures.layer_build 1 in
  let _v28 = Fibers_fixture.join v0 in
  let _v29 = Store_fixtures.ref_make 9 in
  let _v30 = Store_fixtures.layer_close () in
  let v31 = Fibers_fixture.join v0 in
  v31

let programs : (string * (unit -> value)) list = [ ("p400216", corpus_p400216) ]
