(* Generated by OCaml5.Fuzz (spike P5, round four). Program `p400039`, seed 400039, 22 operations.
   Do not edit; regenerate with `ocaml/tools/fuzz.sh corpus`. *)

open Deep_fibers

let corpus_p400039 () =
  let v0 = Fibers_fixture.fork 3 in
  let _v1 = Fibers_fixture.cleanups () in
  let _v2 = Fibers_fixture.started () in
  let v3 = Store_fixtures.ref_make 5 in
  let _v4 = Fibers_fixture.started () in
  let v5 = Fibers_fixture.fork 0 in
  ignore (Store_fixtures.ref_set v3 0);
  let _v6 = Fibers_fixture.await_value v0 in
  let _v7 = Store_fixtures.ref_get_and_set v3 8 in
  let _v8 = Store_fixtures.ref_get v3 in
  let _v9 = Fibers_fixture.cleanups () in
  let _v10 = Fibers_fixture.await_value v5 in
  let _v11 = Fibers_fixture.cleanups () in
  let _v12 = Fibers_fixture.started () in
  let _v13 = Fibers_fixture.cleanups () in
  let _v14 = Store_fixtures.ref_get v3 in
  let v15 = Fibers_fixture.fork 0 in
  let _v16 = Fibers_fixture.cleanups () in
  ignore (Store_fixtures.ref_update v3 10);
  let _v17 = Fibers_fixture.await_value v0 in
  let _v18 = Fibers_fixture.started () in
  let v19 = Fibers_fixture.join v15 in
  v19

let programs : (string * (unit -> value)) list = [ ("p400039", corpus_p400039) ]
