import Effect4.Api
import TypeScript.Render

/-!
Finite target controls for Concept 5's print/read boundary and R5/R8 service identity
(DI-24/DI-76). Ordinary programs pass through `Api.emitModule`, so their declared types
come from the core checker. The custom unknown-carrier case uses its explicitly named
signature and `checkTypedProgram`. Consumers: `scripts/check-service-identity.py`, the
target compiler and the pinned Effect runtime. The deliberately false annotations are
negative controls only. This is finite host evidence, not a general lowering theorem.

Run: lake env lean -DwarningAsError=true -M4096 --run tools/TestSupport/ServiceIdentity.lean <out>
-/

namespace TestSupport.ServiceIdentity

open Effect4 Effect4.Program

def firstKey : ServiceKey := ⟨⟨4⟩, ⟨4⟩⟩
def secondKey : ServiceKey := ⟨⟨5⟩, ⟨4⟩⟩
def unknownKey : ServiceKey := ⟨⟨6⟩, ⟨99⟩⟩

def both : NativeEff := .bind (.service firstKey) (.service secondKey)
def wrongProvision : NativeEff := .provideService firstKey (.lit (.nat 7)) (.service secondKey)
def correct : NativeEff :=
  .provideService firstKey (.lit (.nat 7))
    (.provideService secondKey (.lit (.nat 9)) both)
def sameKey : NativeEff :=
  .provideService firstKey (.lit (.nat 7)) (.bind (.service firstKey) (.service firstKey))
def scopedLookup : NativeEff :=
  .scoped (.bind (.service nativeScopeKey) (.succeed (.lit (.nat 42))))

/-- The ordinary fixture route retains the actual public API's checked declarations. -/
def checked (name : String) (program : NativeEff) : IO (List TypeScript.ConstDecl) :=
  match Effect4.Api.emitModule name program with
  | .ok emission => pure emission.declarations
  | .error why => throw (IO.userError s!"{name}: {reprStr why}")

/-- A separate explicit signature admits an unknown carrier without erasing its identity. -/
def customUnknown : IO (List TypeScript.ConstDecl) := do
  let sig := { nativeSignature with serviceTy := fun key =>
    (if key = unknownKey then some .unknown else nativeServiceTy key) }
  let program : NativeEff := .service unknownKey
  let some typing := checkTypedProgram sig program
    | throw (IO.userError "customUnknown: checker refused")
  match printModule sig "customUnknown" typing.ty program with
  | .ok declarations => pure declarations
  | .error why => throw (IO.userError s!"customUnknown: {reprStr why}")

def render (declarations : List TypeScript.ConstDecl) : String :=
  "// GENERATED by tools/TestSupport/ServiceIdentity.lean; finite test fixture.\n" ++
  "import { Context, Effect, Scope } from \"effect\"\n\n" ++
  String.intercalate "\n" (declarations.map (TypeScript.Render.constDecl TypeScript.house0))

/-- Only a negative fixture changes the annotation of a checked emitted program. -/
def falseAnnotation (requirement : TypeScript.TypeRef)
    (declarations : List TypeScript.ConstDecl) : List TypeScript.ConstDecl :=
  declarations.map fun declaration =>
    { declaration with type := some (.name ["Effect", "Effect"]
      [.name ["number"] [], .name ["never"] [], requirement]) }

def emit (out : System.FilePath) : IO Unit := do
  IO.FS.createDirAll out
  let fixtures : List (String × NativeEff) :=
    [ ("first", .service firstKey)
    , ("both", both)
    , ("wrongProvision", wrongProvision)
    , ("correct", correct)
    , ("sameKey", sameKey)
    , ("scopeService", .service nativeScopeKey)
    , ("scopedLookup", scopedLookup) ]
  let ordinary ← fixtures.mapM fun (name, program) => checked name program
  let declarations := ordinary.flatten ++ (← customUnknown)
  IO.FS.writeFile (out / "positive.ts") (render declarations)
  -- Erasing only declaration annotations asks tsgo to infer from the emitted expressions.
  IO.FS.writeFile (out / "inferred.ts")
    (render (declarations.map fun declaration => { declaration with type := none }))
  IO.FS.writeFile (out / "false-closed.ts")
    (render (falseAnnotation (.name ["never"] []) (← checked "falseClosed" wrongProvision)))
  IO.FS.writeFile (out / "wrong-brand.ts")
    (render (falseAnnotation (.literal "k5_4") (← checked "wrongBrand" (.service firstKey))))

end TestSupport.ServiceIdentity

def main (args : List String) : IO Unit := do
  let [out] := args | throw (IO.userError "usage: ServiceIdentity <out>")
  TestSupport.ServiceIdentity.emit out
